/**
 * Real replies from Photon's structured search, for the street check in
 * `addressVerify.test.ts`.
 *
 * Captured on 2026-09-24 from https://photon.komoot.io/structured with
 * `street` and `city` as in `sent`, `countrycode=AU`, `layer=street` and
 * `limit=15`, one request every 1.3 s. Only each feature's `extent` has been
 * dropped. `value` is the address as typed into the form that the request
 * stands for.
 *
 * Note what comes back for a street Photon cannot find in the suburb: other
 * streets there (`noSuchStreet`), the nearest spelling (`walcotTypo`,
 * `walcottRoad`), or streets in a place of the same name in another state
 * (`walcottInglewood`, all Queensland).
 *
 * Address data © OpenStreetMap contributors, ODbL.
 */
import type { AddressValue } from './addressVerify'

export type StreetCheckFixture = {
  value: AddressValue
  sent: { street: string; city: string }
  json: unknown
}

export const STRUCTURED = {
  walcottStreet: {
    value: {
      addressLine: '12 Walcott Street',
      suburb: 'Mount Lawley',
      state: 'WA',
      postcode: '6050',
    },
    sent: { street: 'Walcott Street', city: 'Mount Lawley' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 321108371,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8766691, -31.9382523] },
        },
      ],
    },
  },
  walcottStMtLawley: {
    value: {
      addressLine: '12 Walcott St',
      suburb: 'Mt Lawley',
      state: 'WA',
      postcode: '6050',
    },
    sent: { street: 'Walcott St', city: 'Mt Lawley' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 321108371,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8766691, -31.9382523] },
        },
      ],
    },
  },
  walcotTypo: {
    value: {
      addressLine: '12 Walcot Street',
      suburb: 'Mount Lawley',
      state: 'WA',
      postcode: '6050',
    },
    sent: { street: 'Walcot Street', city: 'Mount Lawley' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 321108371,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8766691, -31.9382523] },
        },
      ],
    },
  },
  walcottRoad: {
    value: {
      addressLine: '12 Walcott Road',
      suburb: 'Mount Lawley',
      state: 'WA',
      postcode: '6050',
    },
    sent: { street: 'Walcott Road', city: 'Mount Lawley' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 321108371,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8766691, -31.9382523] },
        },
      ],
    },
  },
  noSuchStreet: {
    value: {
      addressLine: '12 Zyxwv Street',
      suburb: 'Mount Lawley',
      state: 'WA',
      postcode: '6050',
    },
    sent: { street: 'Zyxwv Street', city: 'Mount Lawley' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172838773,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Vale Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8672397, -31.9294901] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 411113513,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Bradford Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8653788, -31.9199067] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 83070201,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Vincent Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8706839, -31.936523] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 712195580,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.866853, -31.9299412] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 173948998,
            osm_key: 'highway',
            osm_value: 'service',
            type: 'street',
            name: 'Woodsome Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8694782, -31.9184995] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 569385733,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'William Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8667655, -31.9310024] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 157203545,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Hutt Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8686508, -31.9334678] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 669653053,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Carrington Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8822893, -31.9300314] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 844837390,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Clotilde Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8770063, -31.9354359] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 24052783,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Clarence Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8720343, -31.9373701] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1348293846,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Harold Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8757143, -31.9400491] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 28556205,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Monmouth Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8640049, -31.9289772] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 24059607,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Ebsworth Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8804, -31.9379116] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 667103142,
            osm_key: 'highway',
            osm_value: 'unclassified',
            type: 'street',
            name: 'Stancliffe Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8734688, -31.9180774] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 55356798,
            osm_key: 'highway',
            osm_value: 'unclassified',
            type: 'street',
            name: 'Woodsome Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8702132, -31.9192127] },
        },
      ],
    },
  },
  beaufortFannieBay: {
    value: {
      addressLine: '12 Beaufort Street',
      suburb: 'Fannie Bay',
      state: 'NT',
      postcode: '0820',
    },
    sent: { street: 'Beaufort Street', city: 'Fannie Bay' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 22929263,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Beaumont Street',
            district: 'Rose Bay',
            city: 'Sydney',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2029',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.2753317, -33.8746473] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 962763466,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Beaufort Place',
            city: 'Deception Bay',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4508',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [153.0260174, -27.1910499] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1047850688,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Philip Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8374234, -12.4241442] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 4644543,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Little Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8398524, -12.431118] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 154072306,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Scott Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8370913, -12.4290695] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 4644628,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Playford Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8443817, -12.4272409] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 282221163,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Allen Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8371234, -12.4264433] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1461484073,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Elizabeth Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8358841, -12.424327] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 174187292,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Brown Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8421562, -12.426432] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 4647849,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Seale Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8387614, -12.4368226] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 547944138,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'McKinlay Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8387783, -12.4333482] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 547944133,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Gregory Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8394884, -12.4322025] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 4644564,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Goldsmith Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8404497, -12.4275714] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 684491507,
            osm_key: 'highway',
            osm_value: 'unclassified',
            type: 'street',
            name: 'Conacher Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8378489, -12.4362567] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 4644525,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Charlotte Street',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8398418, -12.4351958] },
        },
      ],
    },
  },
  walcottInglewood: {
    value: {
      addressLine: '12 Walcott Street',
      suburb: 'Inglewood',
      state: 'WA',
      postcode: '6052',
    },
    sent: { street: 'Walcott Street', city: 'Inglewood' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1100998470,
            osm_key: 'highway',
            osm_value: 'trunk',
            type: 'street',
            name: 'Albert Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.081854, -28.4145609] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172449640,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Nicholas Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0772821, -28.4196885] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1089631871,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Tomkins Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0904946, -28.4176566] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172216735,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Brook Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0833031, -28.4170576] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 59264365,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Macintyre Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0902477, -28.4123714] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 185434615,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Great Road Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.080178, -28.4124963] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 185746760,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'McIntyre Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0746182, -28.4186776] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 59264359,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Piper Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0946115, -28.416422] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172216739,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Princess Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0786738, -28.4143134] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 182986000,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Lloyd Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0749507, -28.4172015] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 59264364,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Tomkins Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0900567, -28.4200299] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172216738,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Elizabeth Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0813294, -28.4140033] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172216733,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Regent Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0788655, -28.4180719] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 185743865,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'King Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0787318, -28.4196847] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 27132650,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'George Street',
            district: 'Inglewood',
            city: 'Inglewood',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4387',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.0810646, -28.4135964] },
        },
      ],
    },
  },
  mudstoneTreeby: {
    value: {
      addressLine: 'Lot 50 Mudstone Road',
      suburb: 'Treeby',
      state: 'WA',
      postcode: '6164',
    },
    sent: { street: 'Mudstone Road', city: 'Treeby' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 663106257,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Mudstone Road',
            locality: 'Calleya',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8781409, -32.1196756] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 662335913,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Sunstone Boulevard',
            locality: 'Calleya',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8734036, -32.1186751] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 100402571,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Marine Road',
            district: 'Tenby Point',
            city: 'Tenby Point',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3984',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [145.4778082, -38.408279] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1539591070,
            osm_key: 'highway',
            osm_value: 'cycleway',
            type: 'street',
            name: 'Armadale Road PSP',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8700051, -32.1280066] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 830263266,
            osm_key: 'highway',
            osm_value: 'trunk',
            type: 'street',
            name: 'Armadale Road',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8968724, -32.1361409] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1002873867,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Jandakot Road',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8871706, -32.1184613] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1193376157,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Warton Road',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.9051225, -32.1249596] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1033112332,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Armadale Road',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8706169, -32.1285094] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 22781144,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Fraser Road',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8889044, -32.1164452] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 175380424,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Skotsch Road',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.893615, -32.1252588] },
        },
      ],
    },
  },
  eastPtRd: {
    value: {
      addressLine: '12 East Pt Rd',
      suburb: 'Fannie Bay',
      state: 'NT',
      postcode: '0820',
    },
    sent: { street: 'East Pt Rd', city: 'Fannie Bay' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 4648676,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'East Point Road',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8370121, -12.4303967] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 22717436,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Pt Henry 3',
            city: 'Bremer Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6338',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [119.3748883, -34.4810994] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 671248361,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Pt Malcolm camping',
            district: 'Israelite Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6452',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [123.7462363, -33.7759634] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 393305087,
            osm_key: 'highway',
            osm_value: 'footway',
            type: 'street',
            name: 'Pt Smythe',
            district: 'Venus Bay',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3956',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [145.7401959, -38.6468228] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 22717441,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Pt Henry 4',
            city: 'Bremer Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6338',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [119.3808022, -34.4785768] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 586968410,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Pt. Malcolm 4WD Only',
            district: 'Israelite Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6452',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [123.7572403, -33.7976414] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 22717431,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Pt Henry 2',
            city: 'Bremer Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6338',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [119.371471, -34.4776717] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 22717400,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: 'Pt Henry 1',
            city: 'Bremer Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6338',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [119.3696156, -34.4758904] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 142166327,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Pt Gordon Road',
            city: 'Bremer Bay',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6338',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [119.3883044, -34.4554409] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 464857534,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Nimingarra Rd (P)',
            locality: 'Nimingarra Mine (closed)',
            city: 'Marble Bar',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6760',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [120.0353353, -20.393271] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 220103841,
            osm_key: 'highway',
            osm_value: 'path',
            type: 'street',
            name: 'Sock Puppet East',
            district: 'Redland Bay',
            city: 'Brisbane',
            state: 'Queensland',
            country: 'Australia',
            postcode: '4165',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [153.2773586, -27.6454823] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1441591874,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'East Street',
            district: 'Warners Bay',
            city: 'Newcastle',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2282',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [151.6565517, -32.9725148] },
        },
      ],
    },
  },
  thirdAve: {
    value: {
      addressLine: '12 3rd Ave',
      suburb: 'Mount Lawley',
      state: 'WA',
      postcode: '6050',
    },
    sent: { street: '3rd Ave', city: 'Mount Lawley' },
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 169060404,
            osm_key: 'highway',
            osm_value: 'path',
            type: 'street',
            name: '3rd Parallel Track',
            district: 'Mount Beauty',
            city: 'Mount Beauty',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3699',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [147.1881664, -36.7440238] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1100785213,
            osm_key: 'highway',
            osm_value: 'service',
            type: 'street',
            name: '3rd Street',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5418225, -33.4505926] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1108468409,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: '3rd Avenue',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5496923, -33.4583066] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 762433046,
            osm_key: 'highway',
            osm_value: 'service',
            type: 'street',
            name: '3rd Avenue',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5528404, -33.43782] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1106071475,
            osm_key: 'highway',
            osm_value: 'service',
            type: 'street',
            name: '33rd Avenue',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5470859, -33.4549892] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1108468398,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: '23rd Street',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5494075, -33.4578934] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1100785199,
            osm_key: 'highway',
            osm_value: 'service',
            type: 'street',
            name: '23rd Street',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5473154, -33.4499298] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1106071496,
            osm_key: 'highway',
            osm_value: 'track',
            type: 'street',
            name: '23rd Avenue',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5474687, -33.4564803] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1100780028,
            osm_key: 'highway',
            osm_value: 'service',
            type: 'street',
            name: '23rd Avenue',
            district: 'Mount Panorama',
            city: 'Bathurst',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2795',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [149.5482493, -33.4498763] },
        },
      ],
    },
  },
} satisfies Record<string, StreetCheckFixture>
