/**
 * Real Photon replies, for the tests in `addressLookup.test.ts`.
 *
 * Captured on 2026-09-24 from https://photon.komoot.io/api/ with the URL
 * `photonUrl(typed, biasState)` builds, except `smithStUnitUnfiltered` (the
 * whole text sent bare, with no bbox or layers, which is how Trinidad and
 * Ontario got in) and `refused` (Photon's 400 for an empty query). Only each
 * feature's `extent` has been dropped.
 *
 * Address data © OpenStreetMap contributors, ODbL.
 */

export type PhotonFixture = {
  typed: string
  biasState?: string
  json: unknown
}

export const PHOTON = {
  walcottStreet: {
    typed: '12 Walcott Street Mount Lawley',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 321108372,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8766206, -31.9383132] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 9708233616,
            osm_key: 'healthcare',
            osm_value: 'optometrist',
            type: 'house',
            name: 'Spectacles of Mount Lawley',
            street: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'WA',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.87173, -31.9336826] },
        },
      ],
    },
  },
  walcottStMtLawley: {
    typed: '12 Walcott St Mt Lawley',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 146355581,
            osm_key: 'amenity',
            osm_value: 'hospital',
            type: 'house',
            name: 'St John of God Mt Lawley Hospital',
            street: 'Thirlmere Road',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8848151, -31.9366453] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 9708233616,
            osm_key: 'healthcare',
            osm_value: 'optometrist',
            type: 'house',
            name: 'Spectacles of Mount Lawley',
            street: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'WA',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.87173, -31.9336826] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 321108371,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Walcott Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8766691, -31.9382523] },
        },
      ],
    },
  },
  mudstoneRoad: {
    typed: '10 Mudstone Rd Treeby',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 484157184,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Mudstone Road',
            locality: 'Calleya',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8767968, -32.1192004] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 8373802281,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Clementine Boulevard after Mudstone Road',
            street: 'Clementine Boulevard',
            locality: 'Calleya',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8784978, -32.1191006] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 8373802276,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Armadale Rd before Ghostgum Av',
            street: 'Armadale Road PSP',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8744586, -32.1302765] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 12883224273,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Armadale Rd Before Liddelow Rd',
            street: 'Armadale Road PSP',
            district: 'Treeby',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6164',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8860072, -32.1337208] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 12955225795,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Challenger Rd After Tranby St',
            street: 'Challenger Road',
            locality: 'Madora Bay',
            district: 'Madora Bay',
            city: 'Mandurah',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6210',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7501047, -32.4762673] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 12955452960,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Challenger Rd Before Tranby St',
            street: 'Challenger Road',
            locality: 'Madora Bay',
            district: 'Madora Bay',
            city: 'Mandurah',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6210',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7500155, -32.476275] },
        },
      ],
    },
  },
  romeoRoad: {
    typed: '15 Romeo Road Alkimos',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1152335362,
            osm_key: 'highway',
            osm_value: 'secondary',
            type: 'street',
            name: 'Romeo Road',
            district: 'Alkimos',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6038',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7065709, -31.6238819] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1302027812,
            osm_key: 'highway',
            osm_value: 'cycleway',
            type: 'street',
            name: 'Romeo Road Shared Path',
            district: 'Alkimos',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6038',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.6912658, -31.6190892] },
        },
      ],
    },
  },
  smithStUnit: {
    typed: '3/12 Smith St Perth',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 10875160000,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'South St Before Smith St',
            street: 'South Street',
            district: 'White Gum Valley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6162',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7775845, -32.0632359] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 165801545,
            osm_key: 'amenity',
            osm_value: 'place_of_worship',
            type: 'house',
            housenumber: '31',
            name: 'Serbian Orthodox Church of St. Sava',
            street: 'Smith Street',
            district: 'Highgate',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6003',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8706693, -31.9415634] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 664426734,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'Perth',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6000',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8697457, -31.9436661] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1348287060,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'Highgate',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6003',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8707364, -31.9420847] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1348081884,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'Dianella',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6059',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8872712, -31.8946436] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 667188380,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Smith Street',
            district: 'Morley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6062',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8920958, -31.8905342] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 5514226,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Smith Street',
            district: 'Claremont',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6010',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.789127, -31.9804351] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 30594427,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Smith Street',
            district: 'Mosman Park',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6012',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7657569, -32.0079081] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 25782623,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Smith Street',
            district: 'Karrinyup',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6018',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7818363, -31.8776489] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 172956270,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Smith Street',
            district: 'Beechboro',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6063',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.9457929, -31.8662915] },
        },
      ],
    },
  },
  whitewoodRoadLot: {
    typed: 'Lot 50 Whitewood Road Howard Springs',
    biasState: 'NT',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 572191909,
            osm_key: 'highway',
            osm_value: 'unclassified',
            type: 'street',
            name: 'Whitewood Road',
            district: 'Howard Springs',
            city: 'Palmerston',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0192916, -12.4921729] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1264824147,
            osm_key: 'amenity',
            osm_value: 'fire_station',
            type: 'house',
            housenumber: '325',
            name: 'Howard Springs Volunteer Fire Brigade',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'NT',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0463224, -12.4953177] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 75608940,
            osm_key: 'tourism',
            osm_value: 'caravan_site',
            type: 'house',
            housenumber: '170',
            name: 'BIG4 Howard Springs Holiday Park',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'NT',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0331934, -12.497624] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 3767372791,
            osm_key: 'shop',
            osm_value: 'convenience',
            type: 'house',
            housenumber: '290',
            name: 'IGA Howard Springs',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0439184, -12.496768] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 5055207621,
            osm_key: 'amenity',
            osm_value: 'restaurant',
            type: 'house',
            name: 'Howard Springs Tavern',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.043459, -12.4967032] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 11597839249,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Howard Springs Primary School (583)',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0455152, -12.4963424] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 763261522,
            osm_key: 'building',
            osm_value: 'kindergarten',
            type: 'house',
            name: 'Howard Springs Pre-School',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0443302, -12.4959706] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 11597839066,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Howard Springs Primary School (587)',
            street: 'Whitewood Road',
            district: 'Howard Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0835',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [131.0459917, -12.4962062] },
        },
      ],
    },
  },
  eastPointRoad: {
    typed: '12 East Pt Rd Fannie Bay',
    biasState: 'NT',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 11597839016,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'East Point Rd (079)',
            street: 'East Point Road',
            district: 'Fannie Bay',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0820',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.837062, -12.430741] },
        },
      ],
    },
  },
  marineParade: {
    typed: '88 Marine Pde Cottesloe',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 5313527287,
            osm_key: 'amenity',
            osm_value: 'fast_food',
            type: 'house',
            housenumber: '118',
            name: 'Cottesloe general store',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'WA',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7521715, -31.9935928] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 339627647,
            osm_key: 'amenity',
            osm_value: 'pub',
            type: 'house',
            housenumber: '104',
            name: 'Cottesloe Beach Hotel',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'WA',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7521821, -31.9946995] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1276335584,
            osm_key: 'building',
            osm_value: 'yes',
            type: 'house',
            housenumber: '87',
            name: 'Cottesloe Surf Life Saving Club',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'WA',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7515466, -31.9973185] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1276335701,
            osm_key: 'tourism',
            osm_value: 'hotel',
            type: 'house',
            housenumber: '104',
            name: 'Cottesloe Beach Hotel',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'WA',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7522963, -31.9947045] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 892165563,
            osm_key: 'club',
            osm_value: 'surf_life_saving',
            type: 'house',
            name: 'North Cottesloe Surf Life Saving Club',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7525532, -31.9889879] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 1504407656,
            osm_key: 'amenity',
            osm_value: 'drinking_water',
            type: 'house',
            name: 'Cottesloe Beach',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7514342, -31.9956599] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 8292427532,
            osm_key: 'amenity',
            osm_value: 'clock',
            type: 'house',
            name: 'Cottesloe Sundial',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.75119, -31.9982407] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 617928599,
            osm_key: 'tourism',
            osm_value: 'attraction',
            type: 'house',
            name: 'Cottesloe Pylon',
            street: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7502611, -31.9951509] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 8005757,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Little Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7532068, -31.9861476] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 441623975,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Marine Parade',
            district: 'Cottesloe',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6011',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7532754, -31.9872382] },
        },
      ],
    },
  },
  toddStreet: {
    typed: 'Todd Street Alice Springs',
    biasState: 'NT',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 225563507,
            osm_key: 'highway',
            osm_value: 'residential',
            type: 'street',
            name: 'Todd Street',
            city: 'Alice Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0870',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [133.8818059, -23.7017204] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 4370884353,
            osm_key: 'amenity',
            osm_value: 'library',
            type: 'house',
            housenumber: '93',
            name: 'Alice Springs Library',
            street: 'Todd Street',
            city: 'Alice Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0870',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [133.883013, -23.7014386] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'R',
            osm_id: 3461714,
            osm_key: 'amenity',
            osm_value: 'townhall',
            type: 'house',
            housenumber: '93',
            name: 'Alice Springs Town Council',
            street: 'Todd Street',
            city: 'Alice Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0870',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [133.8823034, -23.7018257] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 4314011490,
            osm_key: 'shop',
            osm_value: 'travel_agency',
            type: 'house',
            housenumber: '76',
            name: 'Greyhound Australia, Alice Springs Travel Centre',
            street: 'Todd Street',
            city: 'Alice Springs',
            state: 'NT',
            country: 'Australia',
            postcode: '0870',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [133.8816876, -23.7016272] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 2024713697,
            osm_key: 'amenity',
            osm_value: 'cinema',
            type: 'house',
            name: 'Alice Springs Cinema',
            street: 'Todd Street',
            city: 'Alice Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0870',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [133.8840457, -23.6977343] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 313590523,
            osm_key: 'shop',
            osm_value: 'convenience',
            type: 'house',
            name: 'Alice 24',
            street: 'Todd Street',
            city: 'Alice Springs',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0870',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [133.8813054, -23.7034551] },
        },
      ],
    },
  },
  scarboroughBeachRoad: {
    typed: '25 Scarborough Beach Rd Mt Hawthorn',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 12805585402,
            osm_key: 'shop',
            osm_value: 'shoes',
            type: 'house',
            name: 'Tredways Shoes Mt Hawthorn',
            street: 'Scarborough Beach Road',
            district: 'Mount Hawthorn',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6016',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8386352, -31.9214345] },
        },
      ],
    },
  },
  beaufortStreet: {
    typed: '15 Beaufort St Perth',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 12872545388,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Coode St After Beaufort St',
            street: 'Coode Street',
            district: 'Bayswater',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6053',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.9003822, -31.9090859] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 376696594,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Beaufort Street',
            district: 'Mount Lawley',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6050',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8768356, -31.9289729] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 685997298,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Beaufort Street',
            district: 'Perth',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6000',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8624756, -31.9498184] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1358095634,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Beaufort Street',
            district: 'Inglewood',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6052',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8902826, -31.9179605] },
        },
      ],
    },
  },
  partlyTyped: {
    typed: '25 Scarb',
    biasState: 'WA',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1430780986,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Scarborough Beach Road',
            district: 'Mount Hawthorn',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6016',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8452911, -31.9236966] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 655208800,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Scarborough Beach Road',
            district: 'Osborne Park',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6017',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8267288, -31.9141895] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 580608671,
            osm_key: 'highway',
            osm_value: 'primary',
            type: 'street',
            name: 'Scarborough Beach Road',
            district: 'Doubleview',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6018',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.7770648, -31.8939786] },
        },
      ],
    },
  },
  smithSt: {
    typed: '12 Smith St',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1292983275,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'Collingwood',
            city: 'Melbourne',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3066',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [144.9828272, -37.8073668] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1292983279,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'East Melbourne',
            city: 'Melbourne',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3002',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [144.9825195, -37.8090831] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 1268858490,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'Fitzroy',
            city: 'Melbourne',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3065',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [144.9829625, -37.8065461] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 211397557,
            osm_key: 'highway',
            osm_value: 'tertiary',
            type: 'street',
            name: 'Smith Street',
            district: 'Clifton Hill',
            city: 'Melbourne',
            state: 'Victoria',
            country: 'Australia',
            postcode: '3068',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [144.9855963, -37.7912527] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 314176992,
            osm_key: 'amenity',
            osm_value: 'place_of_worship',
            type: 'house',
            housenumber: '90',
            name: "St Mary's Cathedral",
            street: 'Smith Street',
            district: 'Darwin City',
            city: 'Darwin',
            state: 'Northern Territory',
            country: 'Australia',
            postcode: '0800',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [130.8382674, -12.4590586] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'R',
            osm_id: 3272301,
            osm_key: 'amenity',
            osm_value: 'school',
            type: 'house',
            name: "Smith's Hill High School",
            street: 'Church Street',
            district: 'Wollongong',
            city: 'Wollongong',
            state: 'New South Wales',
            country: 'Australia',
            postcode: '2500',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [150.8956224, -34.4187638] },
        },
      ],
    },
  },
  nothing: {
    typed: 'zzqxj',
    biasState: 'WA',
    json: { type: 'FeatureCollection', features: [] },
  },
  smithStUnitUnfiltered: {
    typed: '3/12 Smith St Perth',
    json: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 165801545,
            osm_key: 'amenity',
            osm_value: 'place_of_worship',
            type: 'house',
            housenumber: '31',
            name: 'Serbian Orthodox Church of St. Sava',
            street: 'Smith Street',
            district: 'Highgate',
            city: 'Perth',
            state: 'Western Australia',
            country: 'Australia',
            postcode: '6003',
            countrycode: 'AU',
          },
          geometry: { type: 'Point', coordinates: [115.8706693, -31.9415634] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 1318203429,
            osm_key: 'place',
            osm_value: 'house',
            type: 'house',
            housenumber: '12',
            street: 'SMITH ST',
            district: 'Arouca',
            city: 'ROUCA',
            state: 'Tunapuna-Piarco',
            country: 'Trinidad and Tobago',
            postcode: '350509',
            countrycode: 'TT',
          },
          geometry: { type: 'Point', coordinates: [-61.334405, 10.628105] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 1318236404,
            osm_key: 'place',
            osm_value: 'house',
            type: 'house',
            housenumber: '12',
            street: 'SMITH ST',
            district: 'Arouca',
            city: 'ROUCA',
            state: 'Tunapuna-Piarco',
            country: 'Trinidad and Tobago',
            postcode: '350509',
            countrycode: 'TT',
          },
          geometry: { type: 'Point', coordinates: [-61.33444, 10.628058] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 10935405066,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: 'Opp 12 Norman Smith St',
            street: 'Norman Smith Street',
            district: 'Rangatira Park',
            city: 'Taupō',
            county: 'Taupō District',
            state: 'Waikato',
            country: 'New Zealand / Aotearoa',
            postcode: '3377',
            countrycode: 'NZ',
          },
          geometry: { type: 'Point', coordinates: [176.0677151, -38.6807594] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 10935405065,
            osm_key: 'highway',
            osm_value: 'bus_stop',
            type: 'house',
            name: '12 Norman Smith St',
            street: 'Norman Smith Street',
            district: 'Rangatira Park',
            city: 'Taupō',
            county: 'Taupō District',
            state: 'Waikato',
            country: 'New Zealand / Aotearoa',
            postcode: '3377',
            countrycode: 'NZ',
          },
          geometry: { type: 'Point', coordinates: [176.0676138, -38.6806944] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 1891957387,
            osm_key: 'place',
            osm_value: 'house',
            type: 'house',
            housenumber: '12',
            street: 'Smith Street',
            city: 'St. Catharines',
            county: 'Niagara',
            state: 'Ontario',
            country: 'Canada',
            postcode: 'L2P 3J5',
            countrycode: 'CA',
          },
          geometry: { type: 'Point', coordinates: [-79.2179806, 43.1668992] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'N',
            osm_id: 14024875277,
            osm_key: 'shop',
            osm_value: 'funeral_directors',
            type: 'house',
            housenumber: '4',
            name: 'John Smith & Son',
            street: 'Abbey Terrace',
            city: 'Auchterarder',
            county: 'Perth and Kinross',
            state: 'Alba / Scotland',
            country: 'United Kingdom',
            postcode: 'PH3 1DF',
            countrycode: 'GB',
          },
          geometry: { type: 'Point', coordinates: [-3.699819, 56.2980835] },
        },
        {
          type: 'Feature',
          properties: {
            osm_type: 'W',
            osm_id: 178847103,
            osm_key: 'place',
            osm_value: 'house_number',
            type: 'house',
            housenumber: '12',
            street: 'Perth Street',
            city: 'St. Catharines',
            county: 'Niagara',
            state: 'Ontario',
            country: 'Canada',
            postcode: 'L2P 3C8',
            countrycode: 'CA',
          },
          geometry: {
            type: 'Point',
            coordinates: [-79.21565562670447, 43.16285776590286],
          },
        },
      ],
    },
  },
  refused: {
    typed: '',
    json: {
      message:
        'q parameter is required when no include categories are specified',
    },
  },
} satisfies Record<string, PhotonFixture>
