//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',

      /**
       * Off because every instance it reports in this codebase is a false
       * positive, and acting on them would be a behaviour change:
       *
       *   - `authComponent.getAuthUser()` is typed as non-nullable but returns
       *     null for an unauthenticated caller, so the `if (!user) throw
       *     UNAUTHENTICATED` guards in convex/lib/access.ts and
       *     convex/memberships.ts read as "always falsy" while actually being
       *     the authentication gate.
       *   - `Object.entries(patch).filter(([, v]) => v !== undefined)` — the
       *     idiom that stops an omitted optional arg from being written into a
       *     document as undefined — reads as "types have no overlap" because
       *     Object.entries widens the value type.
       *
       * A rule whose every report must be ignored trains you to ignore the
       * rule. Re-enable if Convex's types stop over-promising.
       */
      '@typescript-eslint/no-unnecessary-condition': 'off',
    },
  },
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      // Generated by `convex dev`; the .js files there are not in any tsconfig
      // project, so the type-aware parser cannot read them.
      'convex/_generated/**',
      'src/routeTree.gen.ts',
    ],
  },
]
