/**
 * Every suburb and locality in the Australian Capital Territory (ACT) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Belconnen 2617 2615
Braddon 2612
Kambah 2902
Phillip 2606
Kingston 2604
City 2601
Queanbeyan 2620
Gungahlin 2912
Greenway 2900
Griffith 2603
Ngunnawal 2913
Karabar 2620
Googong 2620
Queanbeyan East 2620
Bruce 2617
Dickson 2602
Lyneham 2602
Wanniassa 2903
Watson 2602
Narrabundah 2604
Harrison 2914
Crestwood 2620
Fyshwick 2609
Gordon 2906
Turner 2612
Kaleen 2617
Campbell 2612
Franklin 2913
Taylor 2913
O'Connor 2602
Holt 2615
Macgregor 2615
Denman Prospect 2611
Casey 2913
Dunlop 2615
Coombs 2611
Nicholls 2913
Ainslie 2602
Monash 2904
Curtin 2605
Bonner 2914
Deakin 2600
Palmerston 2913
Amaroo 2914
Weston 2611
Calwell 2905
Wright 2611
Evatt 2617
Chisholm 2905
Florey 2615
Queanbeyan West 2620
Crace 2911
Conder 2906
Banks 2906
Downer 2602
Mawson 2607
Lyons 2606
Moncrieff 2914
Barton 2600
Farrer 2607
Isabella Plains 2905
Red Hill 2603
Yarralumla 2600
Reid 2612
Macquarie 2614
Bonython 2905
Forde 2914
Garran 2605
Cook 2614
Latham 2615
Hackett 2602
Page 2614
Rivett 2611
Hawker 2614
Scullin 2614
Theodore 2905
Fisher 2611
Mitchell 2911
Whitlam 2611
Higgins 2615
Hughes 2605
Forrest 2603
Duffy 2611
Chifley 2606
Melba 2615
Charnwood 2615
Giralang 2617
Flynn 2615
Pearce 2607
Holder 2611
Waramanga 2611
Richardson 2905
Gowrie 2904
Throsby 2914
Chapman 2611
Weetangera 2614
Fadden 2904
Lawson 2617
McKellar 2617
Aranda 2614
Spence 2615
Isaacs 2607
Gilmore 2905
Torrens 2607
Strathnairn 2615
Sutton 2620
Gundaroo 2620
Stirling 2611
Fraser 2615
Wamboin 2620
Oxley 2903
Hume 2620
Tralee 2620
Carwoola 2620
Symonston 2609
O'Malley 2606
Macarthur 2904
Burra 2620
Royalla 2620
Canberra Airport 2609
Michelago 2620
Greenleigh 2620
Acton 2601
Oaks Estate 2620
Parkes 2600
Beard 2620
Jacka 2914
Macnamara 2615
Wallaroo 2618
Springrange 2618
Hall 2618
Jerrabomberra 2600
Uriarra Village 2611
The Ridgeway 2620
Urila 2620
Tinderry 2620
Pialligo 2609
Tharwa 2620
Majura 2609
Paddys River 2620
Williamsdale 2620
Brindabella 2611
The Angle 2620
Clear Range 2620
Uriarra 2611
Tuggeranong 2900
Stromlo 2611
Kowen 2620
Booth 2620
Coree 2611
Kenny 2911
Environa 2620
Molonglo Valley 2617
Yarrow 2620
Tennent 2620
Weston Creek 2611
Canberra Central 2601
Russell 2600
Capital Hill 2600
Cotter River 2611
Rendezvous Creek 2620`
