/**
 * Every suburb and locality in New South Wales (NSW) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Sydney 2000
Port Macquarie 2444
Dubbo 2830
Blacktown 2148
Parramatta 2150
Orange 2800
Bankstown 2200
Castle Hill 2154
Liverpool 2170
Randwick 2031
Hurstville 2220
Coffs Harbour 2450
Ryde 2112
Surry Hills 2010
Mosman 2088
Wollongong 2500
Maroubra 2035
Chatswood 2067
Marrickville 2204
Auburn 2144
Penrith 2750
Armidale 2350
Dee Why 2099
Epping 2121
Baulkham Hills 2153
Campsie 2194
Goulburn 2580
Merrylands 2160
Cronulla 2230
Ashfield 2131
Hornsby 2077
Mascot 2020
Manly 2095
Waterloo 2017
Strathfield 2135
Broken Hill 2880
Forster 2428
Carlingford 2118
Kogarah 2217
Burwood 2134
Miranda 2228
Lidcombe 2141
Pyrmont 2009
Darlinghurst 2010
Campbelltown 2560
Griffith 2680
Bondi Junction 2022
Redfern 2016
Newtown 2042
North Sydney 2060
Taree 2430
Macquarie Park 2113
Seven Hills 2147
Coogee 2034
Alexandria 2015
Guildford 2161
Greenacre 2190
Quakers Hill 2763
Kellyville 2155
Cabramatta 2166
Rockdale 2216
Bondi Beach 2026
Caringbah 2229
Leichhardt 2040
Westmead 2145
Zetland 2017
Eastwood 2122
Fairfield 2165
Umina Beach 2257
Haymarket 2000
St Marys 2760
Glebe 2037
Punchbowl 2196 2460
Glenmore Park 2745
Ballina 2478
Rosebery 2018
Dulwich Hill 2203
Ultimo 2007
Bexley 2207
Granville 2142
Neutral Bay 2089
Greystanes 2145
Potts Point 2011
Cessnock 2325
Paddington 2021
Banora Point 2486
Drummoyne 2047
Lakemba 2195
St Ives 2075
Wentworth Point 2127
Yagoona 2199
Lavington 2641
Ingleburn 2565
Lane Cove 2066
Kingsford 2032
Gladesville 2111
Tweed Heads 2485
Revesby 2212
Cremorne 2090
St Leonards 2065
Sutherland 2232
Mount Druitt 2770
Botany 2019
Wahroonga 2076
Earlwood 2206
Bondi 2026
Wentworthville 2145
Charlestown 2290
Oran Park 2570
Engadine 2233
Terrigal 2260
Toongabbie 2146
Muswellbrook 2333
Lane Cove North 2066
Wagga Wagga 2650
Schofields 2762
Kensington 2033
Kingswood 2747 2340 2550
Rhodes 2138
North Kellyville 2155
Camperdown 2050
Homebush 2140
Rouse Hill 2155
Austral 2179
North Parramatta 2151
Parkes 2870
Bowral 2576
Mudgee 2850
Belmore 2192
Goonellabah 2480
Cherrybrook 2126
Riverwood 2210
West Ryde 2114
Wallsend 2287
East Maitland 2323
Woy Woy 2256
Padstow 2211
Erskineville 2043
Penshurst 2222
Byron Bay 2481
Raymond Terrace 2324
Balmain 2041
St Clair 2759 2330
Young 2594
Inverell 2360
Peakhurst 2210
Homebush West 2140
Grafton 2460
Nelson Bay 2315
Casula 2170
Wolli Creek 2205
Nowra 2541
Chippendale 2008
Kirrawee 2232
Smithfield 2164
Rose Bay 2029
Katoomba 2780
Marsden Park 2765
Box Hill 2765
Cowra 2794
Marsfield 2122
Tweed Heads South 2486
Rutherford 2320
Mortdale 2223
Arncliffe 2205
Mona Vale 2103
Gunnedah 2380
Casino 2470
North Ryde 2113
Concord 2137
Sans Souci 2219
Sylvania 2224
West Pennant Hills 2125
Merewether 2291
Newcastle 2300
Cranebrook 2749
Minto 2566
Artarmon 2064
Carlton 2218
Kingsgrove 2208
Bateau Bay 2261
Moree 2400
Prestons 2170
Northmead 2152
Albion Park 2527
Bellevue Hill 2023
Kingscliff 2487
Bathurst 2795
Turramurra 2074
Woonona 2517
Pymble 2073
Mayfield 2304 2580 2540 2787
Rooty Hill 2766
Macquarie Fields 2564
Thurgoona 2640
Narrabeen 2101
Roselands 2196
Brighton-Le-Sands 2216
Wyoming 2250
Chester Hill 2162
Panania 2213
Ermington 2115
Moama 2731
Lindfield 2070
Five Dock 2046
The Ponds 2769
Annandale 2038
Yamba 2464
Petersham 2049
Tuncurry 2428
Canterbury 2193
Caringbah South 2229
Woollahra 2025
Gosford 2250
Rozelle 2039
Brookvale 2100
Elizabeth Bay 2011
Dapto 2530
Moorebank 2170
Ulladulla 2539
Frenchs Forest 2086
Moss Vale 2577
Forbes 2871
Gordon 2072
Kiama 2533
Deniliquin 2710
Condell Park 2200
Leppington 2179
Edmondson Park 2174
New Lambton 2305
Kincumber 2251
Leeton 2705
Matraville 2036
Figtree 2525
Doonside 2767
The Entrance 2261
Kelso 2795
Crows Nest 2065
Wetherill Park 2164
North Bondi 2026
Croydon Park 2133
Narrabri 2390
Nambucca Heads 2448
Freshwater 2096
Thornton 2322
Riverstone 2765
Warners Bay 2282
Chipping Norton 2170
Killara 2071
Roseville 2069
Lennox Head 2478
Glenwood 2768
Wollstonecraft 2065
Newport 2106
Long Jetty 2261
Medowie 2318
Bossley Park 2176
Queanbeyan 2620
Croydon 2132
South Penrith 2750
Balgowlah 2093
Vaucluse 2030
Murwillumbah 2484
Sanctuary Point 2540
Woolloomooloo 2011
Avalon Beach 2107
Summer Hill 2130 2421
Oatley 2223
Beverly Hills 2209
Winston Hills 2153
Waitara 2077
Double Bay 2028
Wiley Park 2195
Warriewood 2102
Albury 2640
Erina 2250
Stanmore 2048
Belmont 2280
Gymea 2227
Ettalong Beach 2257
Springwood 2777
Menai 2234
South West Rocks 2431
Cammeray 2062
Cooma 2630
Leumeah 2560
Belrose 2085
Corowa 2646
Cootamundra 2590
Fairy Meadow 2519
Gorokan 2263
Canley Vale 2166
Warwick Farm 2170
Green Valley 2168
Gregory Hills 2557
North Rocks 2151
Cameron Park 2285
Hunters Hill 2110
Beecroft 2119
Corrimal 2518
North Richmond 2754
Bella Vista 2153
Thornleigh 2120
Cooranbong 2265
Emu Plains 2750
North Tamworth 2340
Toronto 2283
Harrington Park 2567
Jordan Springs 2747
Collaroy 2097
Mount Annan 2567
Meadowbank 2114
Fairfield West 2165
Berkeley Vale 2261
Canley Heights 2166
Cardiff 2285
South Tamworth 2340
Glen Innes 2370
Bomaderry 2541
Glenfield 2167
Richmond 2753
Merimbula 2548
Wentworth Falls 2782
Tumut 2720
Hamlyn Terrace 2259
Karabar 2620
Mittagong 2575
Rydalmere 2116
Lilyfield 2040
Woolgoolga 2456
Shell Cove 2529
Norwest 2153
Spring Farm 2570
Bass Hill 2197
Kirribilli 2061
Salamander Bay 2317
Bronte 2024
Blackheath 2785
Adamstown 2289
Yass 2582
Jamisontown 2750
Wauchope 2446
Googong 2620
Unanderra 2526
Lurnea 2170
South Grafton 2460
North Albury 2640
Pendle Hill 2145
Edgeworth 2285
Kooringal 2650
Bradbury 2560
Oak Flats 2529
Dural 2158
Jerrabomberra 2619
Albion Park Rail 2527
Sussex Inlet 2540
Queanbeyan East 2620
Allawah 2218
Leura 2780
West Tamworth 2340
Narara 2250
Warilla 2528
Toormina 2452
Jindabyne 2627
Pottsville 2489
Cromer 2099
Scone 2337
Alstonville 2477
East Ballina 2478
Berkeley 2506
Green Point 2251 2428
Bonnyrigg 2177
Mount Pritchard 2170
Darling Point 2027
Manly Vale 2093
Tweed Heads West 2485
East Albury 2640
Singleton 2330
Morisset 2264
Willoughby 2068
South Windsor 2756
Asquith 2077
Denham Court 2565
Wyong 2259
Fairlight 2094
Hillsdale 2036
Tahmoor 2573
Horsley 2530
Forestville 2087
Pennant Hills 2120
Kellyville Ridge 2155
Lismore 2480
Eastlakes 2018
Hinchinbrook 2168
Temora 2666
Swansea 2281
Lithgow 2790
Berala 2141
Stanhope Gardens 2768
Kings Langley 2147
Kurri Kurri 2327
Blaxland 2774
Naremburn 2065
Killarney Vale 2261
Bega 2550
Jannali 2226
Georges Hall 2198
Elderslie 2570 2335
Greenwich 2065
Colyton 2760
Edensor Park 2176
Old Bar 2430
Villawood 2163
Lalor Park 2147
Port Kembla 2505
East Gosford 2250
Toukley 2263
Hamilton South 2303
Telopea 2117
Abbotsford 2046
Hamilton 2303
Hillvue 2340
Rosemeadow 2560
Werrington 2747
Tenterfield 2372
Merrylands West 2160
Strathfield South 2136
Harris Park 2150
Moruya 2537
Vincentia 2540
Marayong 2148
East Tamworth 2340
Mount Colah 2079
South Wentworthville 2145
Thirroul 2515
St Peters 2044
Maryland 2287
Forest Lodge 2037
Crestwood 2620
Girraween 2145
Wamberal 2260
Narrandera 2700
Wingham 2429
Plumpton 2761
Tallawong 2762
Corlette 2315
Narromine 2821
Fairfield Heights 2165
Cambridge Park 2747
Avoca Beach 2251
Wattle Grove 2173
Blakehurst 2221
Woolooware 2230
Lake Cathie 2445
Northbridge 2063
Warrawong 2502
Ocean Shores 2483
Fletcher 2287
Breakfast Point 2137
Sydney Olympic Park 2127
Lambton 2299
Narraweena 2099
Wellington 2820
Bulli 2516
Allambie Heights 2100
Seaforth 2092
Picton 2571
West Hoxton 2171
Cobar 2835
North Nowra 2541
Flinders 2529
Lewisham 2049
Haberfield 2045
Elermore Vale 2287
Heathcote 2233
Rushcutters Bay 2011
East Lismore 2480
Hurlstone Park 2193
Lake Albert 2650
Tea Gardens 2324
Culburra Beach 2540
South Hurstville 2221
Narwee 2209
Barrack Heights 2528
Anna Bay 2316
Gledswood Hills 2557
Lake Munmorah 2259
Waverley 2024
West Gosford 2250
Beaumont Hills 2155
Narooma 2546
South Coogee 2034
Helensburgh 2508
Shoalhaven Heads 2535
Harrington 2427
Illawong 2234
Thirlmere 2572
Little Bay 2036
Waratah 2298
Cooks Hill 2300
Monterey 2217
Kanahooka 2530
Melonba 2765
Mulwala 2647
Bligh Park 2756
South Granville 2142
Eden 2551
North Gosford 2250
Coonabarabran 2357
Clovelly 2031
Londonderry 2753
Belmont North 2280
Batemans Bay 2536
Junee 2663
Beacon Hill 2100
Concord West 2138
Silverwater 2128 2264
Sefton 2162
West Kempsey 2440
Millers Point 2000
Balgownie 2519
North Strathfield 2137
Evans Head 2473
Rosehill 2142
Mullumbimby 2482
Aberglasslyn 2320
Gerringong 2534
Edgecliff 2027
Lane Cove West 2066
Shoal Bay 2315
Glenfield Park 2650
Picnic Point 2213
Winmalee 2777
Blue Haven 2262
Oberon 2787
Sawtell 2452
Glenhaven 2156
Camden 2570
West Wollongong 2500
Eastgardens 2036
Gymea Bay 2227
Ropes Crossing 2760
Ambarvale 2560
Stockton 2295
Eleebana 2282
Woongarrah 2259
North Narrabeen 2101
Kariong 2250
Gables 2765
Dundas Valley 2117
Normanhurst 2076
Condobolin 2877
Narellan Vale 2567
Oatlands 2117
Bungendore 2621
Cabramatta West 2166
Hazelbrook 2779
Walcha 2354
Boambee East 2452
Quirindi 2343
Enmore 2042 2350
Tocumwal 2714
Regents Park 2143
Lisarow 2250
Newcastle West 2302
Valentine 2280
Shortland 2307
Chisholm 2322
Middleton Grange 2171
St Helens Park 2560
Bardia 2565
Russell Lea 2046
Narellan 2567
Cobbitty 2570
Erskine Park 2759
Bayview 2104
Dundas 2117
Lake Illawarra 2528
Gloucester 2422
Whalan 2770
Tuggerah 2259
Tumbi Umbi 2261
Hornsby Heights 2077
Blayney 2799
Newington 2127
Lugarno 2210
Beresfield 2322
Gillieston Heights 2321
Kotara 2289
Bombala 2632
Singleton Heights 2330
Minchinbury 2770
Bellingen 2454
Milsons Point 2061
Kanwal 2259
Crookwell 2583
Urunga 2455
Queenscliff 2096
Wilton 2571
Maitland 2320
Prospect 2148
South Nowra 2541
Fairfield East 2165
Belfield 2191
Tuross Head 2537
Suffolk Park 2481
West Wyalong 2671
Bonnyrigg Heights 2177
Pemulwuy 2145
West Albury 2640
Redhead 2290
Calala 2340
Darlington 2008 2330
Oakhurst 2761
Bellambi 2518
Woodcroft 2767
Adamstown Heights 2289
Bangor 2234
Coonamble 2829
Glenbrook 2773
Gilgandra 2827
Milperra 2214
St Georges Basin 2540
Budgewoi 2262
North Willoughby 2068
Oyster Bay 2225
Tura Beach 2548
Metford 2323
Ourimbah 2258
Hawks Nest 2324
St Johns Park 2176
Grenfell 2810
Silverdale 2752
Raby 2566
The Rocks 2000 2795
Worrigee 2540
Norfolk Island 2899
Mollymook Beach 2539
West Ballina 2478
Cecil Hills 2171
Finley 2713
Eagle Vale 2558
Currans Hill 2567
Bargo 2574
McMahons Point 2060
Point Clare 2250
Bonnells Bay 2264
Ruse 2560
Kiama Downs 2533
Kings Park 2148
Lake Haven 2263
Fern Bay 2295
Berowra Heights 2082
Mount Hutton 2290
North Rothbury 2335
Kenthurst 2156
Guildford West 2161
Berry 2535
Malua Bay 2536
Oxley Park 2760
Shellharbour 2529
Bexley North 2207
Caves Beach 2281
Colebee 2761
Bundanoon 2578
North St Marys 2760
Howlong 2643
Hebersham 2770
Ashmont 2650
Chinderah 2487
Fingal Bay 2315
Glendenning 2761
Batehaven 2536
Claremont Meadows 2747
Jesmond 2299
North Turramurra 2074
Queanbeyan West 2620
Windang 2528
Lake Heights 2502
Waverton 2060
Mount Warrigal 2528
St Andrews 2566
Mount Austin 2650
Speers Point 2284
Bogangar 2488
Catherine Field 2557
Laurieton 2443
Springfield 2250 2630
Maclean 2463
Wickham 2293
Broulee 2537
San Remo 2262
Lethbridge Park 2770
West Pymble 2073
Carramar 2163
Macksville 2447
Casuarina 2487
Grantham Farm 2765
Wyee 2259
East Corrimal 2518
Constitution Hill 2145
Berowra 2081
Wadalba 2259
Dover Heights 2030
Weston 2326
Faulconbridge 2776
Gwandalan 2259
Bermagui 2546
Calderwood 2527
Lawson 2783
Centennial Park 2021
Gateshead 2290
Tanilba Bay 2319
Iluka 2466
North Wollongong 2500
Hay 2711
Gulgong 2852
Glenroy 2640 2653
Watanobbi 2259
Brunswick Heads 2483
Davistown 2251
Greta 2334
Camden South 2570
Ashtonfield 2323
Towradgi 2518
West Bathurst 2795
Oxley Vale 2340
Burradoo 2576
Uralla 2358
Wangi Wangi 2267
Saratoga 2251
Windsor 2756
Pitt Town 2756
Turvey Park 2650
Malabar 2036
East Hills 2213
Holsworthy 2173
Mayfield West 2304
Boorowa 2586
Glendale 2285
Thrumster 2444
Karuah 2324
Forresters Beach 2260
Enfield 2136
Murrumbateman 2582
Tolland 2650
Birchgrove 2041
Broadmeadow 2292
Padstow Heights 2211
Windale 2306
Wee Waa 2388
Collaroy Plateau 2097
Point Frederick 2250
Tempe 2044
Lemon Tree Passage 2319
Surf Beach 2536
Taren Point 2229
Loftus 2232
Buff Point 2262
Sapphire Beach 2450
Kyogle 2474
Wakeley 2176
Canowindra 2804
North Epping 2121
Keiraville 2500
Bilambil Heights 2486
Coolamon 2701
North Lambton 2299
North Boambee Valley 2450
South Kempsey 2440
The Hill 2300
Putney 2112
Elanora Heights 2101
Westleigh 2120
Bonny Hills 2445
Barden Ridge 2234
Chiswick 2046
Tenambit 2323
Blackbutt 2529
Kurrajong 2758
Glenorie 2157
Halekulani 2262
Busby 2168
Wilberforce 2756
Copacabana 2251
Bidwill 2770
Nyngan 2825
Wollongbar 2477
Greenfield Park 2176
Korora 2450
Milton 2538
Heddon Greta 2321
Gwynneville 2500
Mardi 2259
Cordeaux Heights 2526
Killarney Heights 2087
Tamworth 2340
Farmborough Heights 2526
Moore Creek 2340
Tullimbar 2527
Cremorne Point 2090
Palm Beach 2108
Charmhaven 2263
Dalmeny 2546
Pokolbin 2320
Canton Beach 2263
Bourke 2840
Manilla 2346
North Curl Curl 2099
Chain Valley Bay 2259
Prairiewood 2176
Dungog 2420
Glen Alpine 2560
South Lismore 2480
Portland 2847
Merriwa 2329
Harden 2587
Catalina 2536
South Albury 2640
Carrington 2294 2324
Pagewood 2035
Queens Park 2022
Ramsgate Beach 2217
Tregear 2770
Airds 2560
Como 2226
Molong 2866
Callala Bay 2540
Denistone 2114
Burraneer 2230
Noraville 2263
Braidwood 2622
Terranora 2486
Barham 2732
Windradyne 2795
Bellbird 2325
Hammondville 2170
Islington 2296
Chifley 2036
Hunterview 2330
Hoxton Park 2171
Westdale 2340 2653
Koonawarra 2530
Miller 2168
Guyra 2365
Soldiers Point 2317
Galston 2159
Ashcroft 2168
Teralba 2284
Werrington County 2747
Dolls Point 2219
Boolaroo 2284
North Haven 2443
Emu Heights 2750
Ashbury 2193
Walgett 2832
Springdale Heights 2641
Hassall Grove 2761
Bangalow 2479
Mannering Park 2259
Mortlake 2137
Long Beach 2536
Crescent Head 2440
Norah Head 2263
Melrose Park 2114
Cartwright 2168
Caddens 2747
Tathra 2550
Warrawee 2074
Huskisson 2540
Whitebridge 2290
Blackett 2770
Terrey Hills 2084
West Wallsend 2286
Gobbagombalin 2650
Bonville 2450
Summerland Point 2259
Clarence Town 2321
Kahibah 2290
Waratah West 2298
Austinmer 2515
Abbotsbury 2176
Coniston 2500
Hillston 2675
Blackalls Park 2283
Lightning Ridge 2834
Banksmeadow 2019
Mays Hill 2145
Horsley Park 2175
Old Toongabbie 2146
East Lindfield 2070
Macquarie Hills 2285
Cumbalum 2478
Jindera 2642
Cardiff South 2285
Mangerton 2500
Tomakin 2537
Sandy Beach 2456
Gundagai 2722
Tumbarumba 2653
Holbrook 2644
Hill Top 2575 2628
Bilgola Plateau 2107
Bourkelands 2650
Aberdare 2325
Banksia 2216
Mollymook 2539
Appin 2560
North Manly 2100
Morpeth 2321
Lansvale 2166
The Rock 2655
Lochinvar 2321
Sunshine Bay 2536
Woodberry 2322
Estella 2650
Branxton 2335
Burrill Lake 2539
Shalvey 2770
Yennora 2161
Aberdeen 2336
Eglinton 2795
Oakville 2765
The Oaks 2570
Lake Cargelligo 2672
North Balgowlah 2093
Kurnell 2231
Glossodia 2756
Kareela 2232
Yowie Bay 2228
Nirimba Fields 2763
Kootingal 2352
Claymore 2559
Taminda 2340
Bolwarra Heights 2320
Acacia Gardens 2763
Denman 2328
Lismore Heights 2480
Orchard Hills 2748
Telarah 2320
The Entrance North 2261
Wentworth 2648
Blackwall 2256
Hastings Point 2489
Emerald Beach 2456
North Avoca 2260
Turrella 2205
Abermain 2326
Gol Gol 2738
Niagara Park 2250
Castlecrag 2068
Beverley Park 2217
South Murwillumbah 2484
Balgowlah Heights 2093
Narrawallee 2539
Barraba 2347
Sylvania Waters 2224
Sadleir 2168
Hobartville 2753
Nimbin 2480
Boggabri 2382
Forest Hill 2651
Tatton 2650
Balmain East 2041
Robertson 2577
Berrigan 2712
Birmingham Gardens 2287
Bulahdelah 2423
Warialda 2402
Birrong 2143
Kemps Creek 2178
Werrington Downs 2747
Cabarita 2137
Mount Riverview 2774
Cliftleigh 2321
Connells Point 2221
Coolah 2843
Empire Bay 2257
South Turramurra 2074
Dean Park 2761
Werris Creek 2341
Bingara 2404
Horningsea Park 2171
Marks Point 2280
Bundeena 2230
Berridale 2628
Vineyard 2765
Coleambally 2707
Point Piper 2027
Wallerawang 2845
New Lambton Heights 2305
Arrawarra 2456
Smiths Lake 2428
Callala Beach 2540
Tarrawanna 2518
Bowenfels 2790
Mulgoa 2745
Grays Point 2232
Bardwell Valley 2207
Wheeler Heights 2097
Carnes Hill 2171
Shellharbour City Centre 2529
Blacksmiths 2281
Rathmines 2283
Booker Bay 2257
Warabrook 2304
Glenning Valley 2261
Heckenberg 2168
Jewells 2280
Smeaton Grange 2567
Hurstville Grove 2220
Lilli Pilli 2536 2229
Marulan 2579
Mount Victoria 2786
Warren 2824
Castle Cove 2069
Moonee Beach 2450
East Wagga Wagga 2650
Kurraba Point 2089
Tighes Hill 2297
Riverview 2066
St Ives Chase 2075
Yenda 2681
Mount Kuring-Gai 2080
Woodford 2778
Diamond Beach 2430
East Killara 2071
Dora Creek 2264
Dudley 2290
Somersby 2250
Bensville 2251
Maryville 2293
Tamarama 2026
Rankin Park 2287
Kandos 2848
Lockhart 2656
Alfords Point 2234
Georgetown 2298
McGraths Hill 2756
Mungindi 2406
Valla Beach 2448
Trangie 2823
Yarrawarrah 2233
Bardwell Park 2207
Kew 2439
Woronora 2232
Greenwell Point 2540
Macmasters Beach 2251
Curl Curl 2096
Freemans Reach 2756
Dharruk 2770
Leonay 2750
Coraki 2471
Warrimoo 2774
Beaconsfield 2015
Peakhurst Heights 2210
Cringila 2502
Cundletown 2430
Batlow 2730
Jamberoo 2533
Wallacia 2745
Dorrigo 2453
Eschol Park 2558
North Arm Cove 2324
Woodbine 2560
Kogarah Bay 2217
Luddenham 2745
Surfside 2536
Henty 2658
Bolton Point 2283
Gulmarrad 2463
Coal Point 2283
Toowoon Bay 2261
Ramsgate 2217
Davidson 2085
Skennars Head 2478
Kearns 2558
Balranald 2715
The Junction 2291
East Kurrajong 2758
East Ryde 2113
Emerton 2770
Buxton 2571
Willmot 2770
Shelly Beach 2261
South Bathurst 2795
Oakdale 2570
Culcairn 2660
Primbee 2502
Raworth 2321
Elizabeth Hills 2171
Warnervale 2259
Mayfield East 2304
Sutton 2620
Corindi Beach 2456
Stream Hill 2526
Old Guildford 2161
Newcastle East 2300
Bawley Point 2539
Tarro 2322
Fennell Bay 2283
Peak Hill 2869
Denistone East 2112
Woronora Heights 2233
Blue Bay 2261
Bungarribee 2767
Liberty Grove 2138
Dunbogan 2443
Rossmore 2557
Llanarth 2795
Baradine 2396
Kempsey 2440
East Branxton 2335
Hanwood 2680
Kincumber South 2251
Dunedoo 2844
Gilead 2560
Lawrence 2460
Frederickton 2440
Woodstock 2793 2538 2360
Colo Vale 2575
Largs 2320
Wareemba 2046
Bullaburra 2784
Moruya Heads 2537
Grasmere 2570
Lloyd 2650
Chittaway Bay 2261
Bonnet Bay 2226
Llandilo 2747
Buronga 2739
Wyongah 2259
Cheltenham 2119
Pambula 2549
Heatherbrae 2324
Jerilderie 2716
Gundaroo 2620
Coomba Park 2428
Murrurundi 2338
Blair Athol 2560
South Bowenfels 2790
Tingira Heights 2290
Kangaroo Valley 2577
Manyana 2539
Rylstone 2849
Barnsley 2278
Avondale 2530
Basin View 2540
Berrima 2577
East Jindabyne 2627
Pindimar 2324
Longueville 2066
Ganmain 2702
Darlington Point 2706
Lake Conjola 2539
Gerroa 2534
Scotts Head 2447
Tallwoods Village 2430
Thredbo 2625
West Nowra 2541
Castlereagh 2749
Millfield 2325
Booragul 2284
Adelong 2729
Girards Hill 2480
Currarong 2540
Brewarrina 2839
Lavender Bay 2060
Yoogali 2680
Bar Beach 2300
Nabiac 2312
Floraville 2280
Tascott 2250
Bywong 2621
Cambridge Gardens 2747
Kendall 2439
Wongawilli 2530
Boambee 2450
North Wahroonga 2076
King Creek 2446
Boomerang Beach 2428
Table Top 2640
Lorn 2320
Menangle 2568
Potts Hill 2143
Millthorpe 2798
Black Head 2430
Daceyville 2032
Wamboin 2620
Boorooma 2650
Revesby Heights 2212
Ellalong 2325
Red Head 2430
Exeter 2579
Sydenham 2044
Camden Park 2570
Sandringham 2219
Daleys Point 2257
Argenton 2284
Parklea 2768
Lakewood 2443
Salt Ash 2318
East Kempsey 2440
Junction Hill 2460
Garden Suburb 2289
Tomago 2322
South Durras 2536
Pearl Beach 2256
Binnaway 2395
Worrowing Heights 2540
Huntleys Cove 2111
Stanwell Park 2508
Boat Harbour 2316 2480
Farley 2320
Mathoura 2710
Catherine Hill Bay 2281
Renwick 2575
Russell Vale 2517
Bobs Farm 2316
Stroud 2425
Arcadia Vale 2283
Tuggerawong 2259
Warragamba 2752
Kilaben Bay 2283
Townsend 2463
Clemton Park 2206
Belmont South 2280
Bowen Mountain 2753
Maraylya 2765
Springvale 2650
Bowraville 2449
Bringelly 2556
Berkshire Park 2765
Woombah 2469
Clontarf 2093
Geurie 2818
Nemingha 2340
Canada Bay 2046
Kurrajong Heights 2758
Broadwater 2472 2549
Lake Tabourie 2539
Mount Saint Thomas 2500
Coomealla 2717
North Batemans Bay 2536
North Lismore 2480
Tomerong 2540
Holroyd 2142
Jilliby 2259
West Haven 2443
Eastern Creek 2766
Wilcannia 2836
Williamtown 2318
Coledale 2515
Hume 2620
Willoughby East 2068
Bolwarra 2320
Bemboka 2550
Mount Keira 2500
Moonbi 2353
Chatswood West 2067
Ariah Park 2665
Cudmirrah 2540
Buttaba 2283
Wyee Point 2259
Cardiff Heights 2285
Fernhill 2519
Wooli 2462
Morisset Park 2264
Woodburn 2472 2538
Roseville Chase 2069
Ulmarra 2462
Tinonee 2430
Tralee 2620
Gunning 2581
Grose Vale 2753
Robin Hill 2795
South Gundagai 2722
Cobargo 2550
Euston 2737
Yellow Rock 2777 2527
Carwoola 2620
Carss Park 2221
Ingleside 2101
Mount Ousley 2519
Tallong 2579
Waterview Heights 2460
Valley Heights 2777
Binalong 2584
Collarenebri 2833
Paterson 2421
Valla 2448
Wyalong 2671
Wardell 2477
Killcare Heights 2257
Tottenham 2873
Woodpark 2164
Holmesville 2286
Killcare 2257
Mount Vernon 2178
Arcadia 2159
Seaham 2324
Berrara 2540
Uranquinty 2652
Curlewis 2381
Raglan 2795
Denhams Beach 2536
Ewingsdale 2481
Wallaga Lake 2546
Old Erowal Bay 2540
Douglas Park 2569
Yerrinbool 2575
Bundarra 2359
Pambula Beach 2549
St Huberts Island 2257
Voyager Point 2172
Arndell Park 2148
Nords Wharf 2281
Paxton 2325
Stuarts Point 2441
Braemar 2575
Boggabilla 2409
Mallabula 2319
Walla Walla 2659
Agnes Banks 2753
Candelo 2550
Lakelands 2282
Mossy Point 2537
Mulgrave 2756
Nana Glen 2450
Mount Pleasant 2519
Murrays Beach 2281
Rodd Point 2046
Carey Bay 2283
Eugowra 2806
Hamilton North 2292
Mendooran 2842
Kianga 2546
Pelaw Main 2327
Kurmond 2757
Manildra 2865
Menindee 2879
Myocum 2481
North Narooma 2546
Taralga 2580
Tabulam 2469
Bow Bowing 2566
Fishing Point 2283
Gulargambone 2828
Merewether Heights 2291
Annangrove 2156
Tennyson Point 2111
Dawes Point 2000
Ungarie 2669
Haywards Bay 2530
Kalaru 2550
Yarravel 2440
Watsons Bay 2030
Wolumla 2550
Tingha 2369
Mandurama 2792
Erowal Bay 2540
Medlow Bath 2780
Middle Cove 2068
Lansdowne 2430 2163
Kotara South 2289
Gormans Hill 2795
Clunes 2480
Barmedman 2668
Trundle 2875
Abercrombie 2795
Balcolyn 2264
Hamilton East 2303
Church Point 2105
Coutts Crossing 2460
Burwood Heights 2136
Hamilton Valley 2641
Cattai 2756
Barrack Point 2528
Dunoon 2480
Barellan 2665
Swan Bay 2324 2471
Bodalla 2545
Bilbul 2680
Scotland Island 2105
South Golden Beach 2483
Ebenezer 2756
Ardlethan 2665
Falls Creek 2540
One Mile 2316
Macquarie Links 2565
Safety Beach 2456
Brightwaters 2264
Wallabi Point 2430
Glenreagh 2450
Yanco 2703
Bowning 2582
Kyeemagh 2216
Ashford 2361
Koolewong 2256
Matcham 2250
New Berrima 2577
Emmaville 2371
Louth Park 2320
Minnamurra 2533
Wattle Ponds 2330
Wombarra 2515
Bungonia 2580
Nulkaba 2325
Brooklyn 2083
Nowra Hill 2540
Nundle 2340
Cudgen 2487
Woodrising 2284
North Wagga Wagga 2650
Lake Wyangan 2680
Orangeville 2570
Welby 2575
Bilpin 2758
Lower Portland 2756
Rosedale 2536
Koorawatha 2807
Windellama 2580
Cambewarra Village 2540
Wingello 2579
Cecil Park 2178
Pilliga 2388
Razorback 2571
Barangaroo 2000
Woolwich 2110
Kiama Heights 2533
Lovedale 2325
Menangle Park 2563
Clareville 2107
Taylors Beach 2316
Mount Kembla 2526
Carcoar 2791
Port Hacking 2229
Tarcutta 2652
North Macksville 2447
Chittaway Point 2261
Raleigh 2454
Beechwood 2446
Captains Flat 2623
Bradfield 2556
Vacy 2421
Woollamia 2540
Failford 2430
Fingal Head 2487
Kyle Bay 2221
Wongarbon 2831
Sandgate 2304
Greenhills Beach 2230
Fullerton Cove 2318
Laguna 2325
Wallabadah 2343
Burra 2620 2653
Eveleigh 2015
Deepwater 2371
Bendemeer 2355
Burringbar 2483
Montefiores 2820
Urana 2645
Collingullie 2650
Willow Vale 2575 2534
Bray Park 2484
Mogo 2536 2850
Mount Lewis 2190
Middle Dural 2158
Clifton Grove 2800
Clyde 2142
Dareton 2717
Dunmore 2529
Pelican 2281
Wollombi 2325
Kearsley 2325
Ivanhoe 2878
Werombi 2570
Invergowrie 2350
Highfields 2289
South Maitland 2320
Uki 2484
Bonalbo 2469
Regentville 2745
Adaminaby 2629
Manning Point 2430
Upper Orara 2450
Broke 2330
Caerleon 2850
Clarenza 2460
Grong Grong 2652
Coramba 2450
Dondingalong 2440
Magenta 2261
Wallalong 2320
Hat Head 2440
Mirrabooka 2264
Little Hartley 2790
Boydtown 2551
Royalla 2620
Nimmitabel 2631
Tarago 2580
Laggan 2583
Cudal 2864
Khancoban 2642
Willow Tree 2339
Windsor Downs 2756
Krambach 2429
Moulamein 2733
Northwood 2066
Orient Point 2540
Whitton 2705
Comboyne 2429
Boree Creek 2652
Geneva 2474
Lapstone 2773
Littleton 2790
Arakoon 2431
Coolongolook 2423
Hallidays Point 2430
Tharbogang 2680
Bexhill 2480
Sancrox 2446
Collombatti 2440
Talbingo 2720
Blueys Beach 2428
Dolphin Point 2539
Millingandi 2549
Holgate 2250
Lyndhurst 2797 2350
Repton 2454
Fountaindale 2258
Hargraves 2850
Oaklands 2646
Tullamore 2874
Bellbird Heights 2325
Delungra 2403
Woodenbong 2476
Cargo 2800
Killingworth 2278
Gilgai 2360
Kulnura 2250
Gumly Gumly 2652
Bombira 2850
Yippin Creek 2446
Bellata 2397
Nelligen 2536
Tambar Springs 2381
Marmong Point 2284
North Casino 2470
Currabubula 2342
Patonga 2256
Wirlinga 2640
Kioloa 2539
Nymagee 2831
McDougalls Hill 2330
Werri Beach 2534
Federal 2480
Hinton 2321
Michelago 2620
Bigga 2583
Brogo 2550
Richmond Hill 2480
Stokers Siding 2484
Caniaba 2480
Darawank 2428
Denistone West 2114
Gooloogong 2805
Mangrove Mountain 2250
Vale Of Clwydd 2790
Kurrajong Hills 2758
Kings Point 2539
Rainbow Flat 2430
Spencer 2775
Wallagoot 2550
Mumbil 2820
Cassilis 2329
Whale Beach 2107
Brownsville 2530
Fishermans Paradise 2539
Maloneys Beach 2536
Maroota 2756
Moonbah 2627
Yarramundi 2753
Berrambool 2548
Coopernook 2426
Greenhill 2440
Stockinbingal 2725
Kitchener 2325
Fassifern 2283
Balaclava 2575
Delegate 2633
Smithtown 2440
Booral 2425
Pretty Beach 2257 2539
Mirador 2548
Nunderi 2484
Bendalong 2539
Ellis Lane 2570
Neath 2326
Aldavilla 2440
Daruka 2340
Gerogery 2642
Greenleigh 2620
McLeans Ridges 2480
Mount Hunter 2570
Berowra Waters 2082
Grose Wold 2753
Morts Estate 2790
Balmoral 2283
Ravenswood 2824
Bangalee 2541
Charlotte Bay 2428
Tyalgum 2484
Doyalson North 2262
Stuart Town 2820
Tapitallee 2540
Linden 2778
Maianbar 2230
Wyndham 2550
Duri 2344
Upper Lansdowne 2430
Cumnock 2867
Hay South 2711
Phillip Bay 2036
Run-O-Waters 2580
Windermere Park 2264
Bredbo 2626
South Guyra 2365
Minmi 2287
Mitchells Island 2430
Pallamallawa 2399
Telegraph Point 2441
Blaxlands Ridge 2758
Canyonleigh 2577
Murringo 2586
Spring Hill 2800 2500
Bennetts Green 2290
Dolans Bay 2229
Mulbring 2323
O'Connell 2795
Windeyer 2850
Badagarang 2540
Kentlyn 2560
Windella 2320
Moorland 2443
Perthville 2795
Goolgowi 2652
Yarrabin 2850
Red Rock 2456
Seelands 2460
Mylestom 2454
Tintenbar 2478
Awaba 2283
Horseshoe Bend 2320
Cooks Gap 2850
Cowan 2081
Duns Creek 2321
Jerrys Plains 2330
Conjola Park 2539
South Pambula 2549
Matong 2652
New Brighton 2483
Wisemans Ferry 2775
Loomberah 2340
Oaks Estate 2620
Wherrol Flat 2429
Attunga 2345
Nelson 2765 2550
Swansea Heads 2281
Tomingley 2869
Marrar 2652
Kundabung 2441
White Cliffs 2836
Minnie Water 2462
Mullaway 2456
East Gresford 2311
Hillsborough 2290 2320
Quorrobolong 2325
South Arm 2449 2460
Yanderra 2574
Beard 2620
South Maroota 2756
Arrawarra Headland 2456
Main Arm 2482
Urbenville 2475
Cabarita Beach 2488
Hallsville 2340
Binda 2583
Carroll 2340
Sutton Forest 2577
Burrawang 2577
Forest Reefs 2798
Angus 2765
Crackenback 2627
Pheasants Nest 2574
Brooms Head 2463
Yerong Creek 2642
Broken Head 2481
Euabalong 2877
Neville 2799
Sunshine 2264
Wedderburn 2560
White Rock 2795
Burren Junction 2386
Hillgrove 2350 2650
Hyams Beach 2540
Eumungerie 2822
Nymboida 2460
Tucabia 2462
Wyangala 2808
Crosslands 2446
Dalgety 2628
Majors Creek 2622
Wallendbeen 2588
Lower Macdonald 2775
Tullibigeal 2669
Balmoral Village 2571
Collector 2581
Stanford Merthyr 2327
Bucca 2450
Modanville 2480
Marrangaroo 2790
Rockley 2795
Canbelego 2835
Croudace Bay 2280
Elizabeth Beach 2428
Lidsdale 2790
Oxford Falls 2100
Rocky River 2358 2372
Yattalunga 2251
Gwabegar 2356
Palmers Island 2463
Yeoval 2868
Hyland Park 2448
Newrybar 2479
Bellbrook 2440
Lowanna 2450
Mount George 2424
Karangi 2450
Ladysmith 2652
Phegans Bay 2256
Upper Horton 2347
Spring Ridge 2343
Weethalle 2669
Curlwaa 2648
Moore Park 2021
Tennyson 2754
Larnook 2480
Mullumbimby Creek 2482
Lower Boro 2580
Central Tilba 2546
Collie 2827
Hartley 2790
Mangoplah 2652
Woolomin 2340
Wyong Creek 2259
Bar Point 2083
Black Mountain 2365
Dangar Island 2083
Gumma 2447
Quaama 2550
Tacoma 2259
Dalton 2581
Mitchell 2795
Ebor 2453
Newee Creek 2447
Numeralla 2630
Putty 2330
Yarrawonga 2850
Sandy Point 2172
Canobolas 2800
Gladstone 2440
Rye Park 2586
Berry Park 2321
Drake 2469
South Gundurimba 2480
Yass River 2582
Bankstown Aerodrome 2200
Barrington 2422
Oallen 2622
The Channon 2480
Towamba 2550
Wilsons Creek 2482
Doyalson 2262
Pillar Valley 2462
Tregeagle 2480
Woy Woy Bay 2256
Brandy Hill 2324
Copmanhurst 2460
Loftville 2480
Harwood 2465
Hexham 2322
Rosewood 2652 2446
Warral 2340
Waterfall 2233
Kangaroo Point 2224
La Perouse 2036
Lower Belford 2335
Beelbangera 2680
Grattai 2850
Lambs Valley 2335 2370
Meroo Meadow 2540
Wallaroo 2618
Erina Heights 2260
Martinsville 2265
Quandialla 2721
Araluen 2622
Black Hill 2322
Coorabell 2479
Ashby 2463
Gravesend 2401
Horsfield Bay 2256
Johns River 2443
Brocklehurst 2830
Cams Wharf 2281
Hardys Bay 2257
Tumbulgum 2490
Wagstaffe 2257
Carinda 2831
Goodooga 2838
Terara 2540
Ilford 2850
Myola 2540
North Bourke 2840
Mooney Mooney 2083
Greendale 2745 2550
Mullion Creek 2800
Murrami 2705
North Shore 2444
Billinudgel 2483
Elands 2429
Kangy Angy 2258
Mount Rankin 2795
Garah 2405
Wandandian 2540
Currawarna 2650
Duffys Forest 2084
Kirkham 2570
Middle Arm 2580
Theresa Park 2570
Burrumbuttock 2642
Lanitza 2460
Rosebank 2480
Chilcotts Grass 2480
Mandalong 2264
Morundah 2700
Wattamondara 2794
Woodville 2321
Old Junee 2652
Wakool 2710
Whittingham 2330
Newbridge 2795
Sawyers Gully 2326
Wattle Flat 2795
Borenore 2800
Lochiel 2549
Ashley 2400
East Seaham 2324
Springrange 2618
Wee Jasper 2582
Baan Baa 2390
Jaspers Brush 2535
Brookdale 2656
Chullora 2190
Oakey Park 2790
Tintinhull 2352
Caragabal 2810
Bundabah 2324
Glen Oak 2320
Grabben Gullen 2583
Martins Creek 2420
Megalong Valley 2785
Smiths Creek 2484 2474 2460
Taree South 2430
Goonengerry 2482
Kalkite 2627
Bogan Gate 2876
Bungwahl 2423
Tyndale 2460
Wooloweyah 2464
Bilambil 2486
Coolagolite 2550
Eungai Creek 2441
Gunderman 2775
Manton 2582
Yarrawonga Park 2264
Crangan Bay 2259
Limeburners Creek 2324 2444
Stanwell Tops 2508
Wootton 2423
Sackville North 2756
Duranbah 2487
Gresford 2311
Lakesland 2572
Mystery Bay 2546
Spring Grove 2470
Clandulla 2848
Galong 2585
Saumarez Ponds 2350
Bimbi 2810
Dyers Crossing 2429
Warialda Rail 2402
East Wardell 2477
Wombat 2587
Congarinni North 2447
Gowrie 2330 2340
Pimlico 2478
Sofala 2795
Wyrallah 2480
Fairy Hill 2470
Glenridding 2330
Murray Downs 2734
Pleasure Point 2172
Wombeyan Caves 2580
Parkville 2337
Camberwell 2330
Dungowan 2340
Henley 2111
Pampoolah 2430
Rand 2642
Somerton 2340
Spring Flat 2850
Swanhaven 2540
Thalgarrah 2350
Greenethorpe 2809
Meadow Flat 2795
Stanbridge 2705
Tallimba 2669
Fernmount 2454
Hermitage Flat 2790
Huntley 2530 2800
St Albans 2775
Tooraweenah 2817
Wingen 2337
Yarrowitch 2354
Belimbla Park 2570
Merungle Hill 2705
Wollar 2850
Angourie 2464
Bulga 2330
Coolac 2727
Oura 2650
Quambone 2831
Wonboyn 2551
Lord Howe Island 2898
Mount Panorama 2795
Mount Wilson 2786
Jugiong 2726
Lue 2850
Yarramalong 2259
Penrose 2579
Riverside 2444
Rock Valley 2480
Verges Creek 2440
Euchareena 2866
Girilambone 2831
Koraleigh 2735
Yorklea 2470
Bentley 2480
Gleniffer 2454
High Range 2575
Jiggi 2480
Tooleybuc 2736
Gregadoo 2650
Hawkesbury Heights 2777
Nangus 2722
Termeil 2539
Boxers Creek 2580
Elland 2460
Nerong 2423
Oxley Island 2430
Way Way 2447
Buckajo 2550
Caroona 2343
Hill End 2850
Potato Point 2545
Redbank 2446
Mallanganee 2469
Belmore River 2440
Benandarah 2536
Congo 2537
Otford 2508
Quialigo 2580
Brayton 2579
Glendon Brook 2330
Gundary 2580
Mount Vincent 2323
Cudgera Creek 2484
Dunbible 2484
Eraring 2264
Jervis Bay 2540
Lake Innes 2446
Ashby Heights 2463
Binjura 2630
Bribbaree 2594
Ettamogah 2640
Hall 2618
Rushforth 2460
Black Springs 2787
Bombowlee 2720
Jeir 2582
Wildes Meadow 2577
Lake Bathurst 2580
Premer 2381
Elong Elong 2831
Kembla Grange 2526
Lucknow 2800
Verona 2550
Cedar Party 2429
Durras North 2536
East Coraki 2471
Shanes Park 2747
Stubbo 2852
Terramungamine 2830
Byabarra 2446
Corndale 2480
Cunjurong Point 2539
Monaltrie 2480
Congarinni 2447
Firefly 2429
Kingsvale 2587
Nashdale 2800
Wrights Beach 2540
Alstonvale 2477
Breeza 2381
Humula 2652
Koonorigan 2480
Tarraganda 2550
Coopers Shoot 2479
Kooragang 2304
Torrington 2371
Capertee 2846
Eureka 2480
Gundy 2337
Hermidale 2831
Colo Heights 2756
Ellangowan 2470
Kinchela 2440
Millers Forest 2324
Nethercote 2549
The Slopes 2754
Condong 2484
Cullen Bullen 2790
Englorie Park 2560
Burrell Creek 2429
Crabbes Creek 2483
Darbys Falls 2793
Minto Heights 2566
Mount Fairy 2580
Woodlands 2575 2536
Anglers Reach 2629
Eurunderee 2850
Monteagle 2594
Bookham 2582
Tallawang 2852
Bomen 2650
Doonbah 2473
Ilarwill 2463
Louth 2840
South Littleton 2790
Tarana 2787
New Italy 2472
Red Range 2370
Sandy Hollow 2333
Splitters Creek 2640
Carrathool 2711
Dalwood 2477 2335
Liston 2372
Rydal 2790
Woodford Island 2463
Brownlow Hill 2570
Moorong 2650
Woomargama 2644
Balldale 2646
Legume 2476
Linley Point 2066
Little Wobby 2256
Tarbuck Bay 2428
The Lagoon 2795
Trunkey Creek 2795
Stroud Road 2415
Upper Burringbar 2483
Wards River 2422
Bannaby 2580
Eltham 2480
Eungai Rail 2441
Halfway Creek 2460
Nericon 2680
Nobbys Creek 2484
Quipolly 2343
Limpinwood 2484
Wantabadgery 2650
Glencoe 2365
Piggabeen 2486
Ulong 2450
Bucketty 2250
Burraga 2795
Missabotti 2449
Parkesbourne 2580
Rankins Springs 2669
Ulamambri 2357
Yetman 2410
Abernethy 2325
Bald Hills 2549
Clothiers Creek 2484
Glen Davis 2846
Nevertire 2826
Springside 2800
Turill 2850
Bethungra 2590
Bunyah 2429
Hampton 2790
Meerschaum Vale 2477
Minimbah 2312
Running Stream 2850
Woolbrook 2354
Buchanan 2323
Bunnan 2337
Mount White 2250
Pumpenbil 2484
Thora 2454
Winton 2344
Boomi 2405
Cawdor 2570
Fitzroy Falls 2577
Lidster 2800
Middle Brook 2337
Nelsons Plains 2324
Binya 2665
Lorne 2439
North Star 2408
Oakhampton 2320
Polo Flat 2630
Tatham 2471
Ulan 2850
Yetholme 2795
Blairmount 2559
Glenugie 2460
Great Mackerel Beach 2108
Halls Creek 2346
Scarborough 2515
Stratford 2422
Tirrannaville 2580
Currawang 2580
Dirty Creek 2456
Hillville 2430
Kalang 2454
Moonan Flat 2337
Congewai 2325
Dundurrabin 2453
Killabakh 2429
Lindendale 2480
Tumblong 2729
Clybucca 2440
Fifield 2875
Wanaaring 2840
Blandford 2338
Brierfield 2454
Burrangong 2594
Coolangatta 2535
Goolma 2852
Kanimbla 2790
Mount Burrell 2484
Myall Park 2681
Peel 2795
Albert 2873
Barry 2799 2340
Bibbenluke 2632
Budgee Budgee 2850
Clarence 2790
Niangala 2354
North Dorrigo 2453
Sunset Strip 2879
Tibooburra 2880
Baw Baw 2580
Deer Vale 2453
Leadville 2844
Merriwagga 2652
Metz 2350
Temagog 2440
Blackville 2343
Curban 2827
Enngonia 2840
Glenthorne 2430
Muscle Creek 2333
Wollomombi 2350
Coolatai 2402
Frogmore 2586
Glenquarry 2576
Hernani 2453
McKellars Park 2790
Peats Ridge 2250
Chillingham 2484
Couridjah 2571
Eungella 2484
Ferodale 2318
Maitland Vale 2320
Marlee 2429
McCullys Gap 2333
Tanja 2550
Barrengarry 2577
Braunstone 2460
Dooralong 2259
Gungal 2333
Maules Creek 2382
Yatte Yattah 2539
Yowrie 2550
Bithramere 2340
Bugaldie 2357
Jacks Creek 2390
Paddys River 2577 2620 2653
Pooncarie 2648
San Isidore 2650
Wallarah 2259
Argents Hill 2449
Ballimore 2830
Blackmans Point 2444
Brushgrove 2460
Cawongla 2474
Duramana 2795
Georges Plains 2795
Redbournberry 2330
Teven 2478
Bilgola Beach 2107
Bingie 2537
Herons Creek 2439
Marchmont 2582
Belbora 2422
Bendick Murrell 2803
Numulgi 2480
Wybong 2333
Alison 2420 2259
Badgerys Creek 2555
Moorbel 2804
Murrays Run 2325
Seahampton 2286
Segenhoe 2337
Tullera 2480
Tyagarah 2481
Wells Crossing 2460
Blighty 2713
Byrock 2831
Cooperabung 2441
Euroka 2440
Hannam Vale 2443
Piambong 2850
Upper Corindi 2456
Brocklesby 2642
Crystal Creek 2484
Gilmore 2720
Greenwich Park 2580
Guerilla Bay 2536
Mountain View 2460
Talarm 2447
Warrell Creek 2447
Willawarrin 2440
Billimari 2804
Borambola 2650
Broughton Vale 2535
Coolabah 2831
Sedgefield 2330
Sherwood 2440 2450 2474
Allworth 2425
Carool 2486
Cumberland Reach 2756
Dundee 2370
Grogan 2666
Koolkhan 2460
Mongarlowe 2622
Mullaley 2379
Sackville 2756
Beckom 2665
Eagleton 2324
Golspie 2580
Mount Olive 2330 2787
Ben Lomond 2365
Blue Knob 2480
Morton 2538
Fernvale 2484
Krawarree 2622
Piallamore 2340
Watagan 2325
Conjola 2539
Dangarsleigh 2350
Edgeroi 2390
Fiddletown 2159
Fishermans Reach 2441
Illabo 2590
Kains Flat 2850
Kapooka 2661
McKees Hill 2480
Milbrulong 2656
Southgate 2460
Cambewarra 2540
Central Mangrove 2250
Merrygoen 2831
Mortons Creek 2446
Reids Flat 2586
Yarrahapinni 2441
Chatsworth 2469
Knockrow 2479
Nowendoc 2354
Possum Creek 2479
Springdale 2666
St Fillans 2850
Terania Creek 2480
Walbundrie 2642
Burcher 2671
Cartwrights Hill 2650
Dargan 2786
Kangaloon 2576
Mole River 2372
Upper Main Arm 2482
Brungle 2722
Galore 2650
Georgica 2480
Good Hope 2582
Tuntable Creek 2480
Berrilee 2159
Bohena Creek 2390
Clarendon 2756
Ganbenang 2790
Gurley 2398
Kingsdale 2580
Kunghur 2484
Menah 2850
Reidsdale 2622
The Pocket 2483
Combaning 2666
Far Meadow 2535
Hoskinstown 2621
Tarlo 2580
Upper Crystal Creek 2484
Gelston Park 2650
Maryvale 2820
Maude 2711
Perisher Valley 2624
Willbriggie 2680
Yallah 2530
Bootawa 2430
Empire Vale 2478
Girvan 2425
Glen Martin 2321
Taylors Flat 2586
Camden Head 2443
Corbie Hill 2705
Toothdale 2550
Tuckombil 2477
Aberfoyle 2350
Bendolba 2420
Charbon 2848
Coomba Bay 2428
Kayuga 2333
Kelvin 2380
Long Point 2564 2330
Megan 2453
Nerriga 2622
Rocky Point 2259
Bridgman 2330
Brooklet 2479
Fernleigh 2479
Shannon Brook 2470
Tacoma South 2259
Tarriaro 2390
Aylmerton 2575
Back Creek 2671 2484 2372 2422 2390
Bango 2582
Bunyan 2630
Ellenborough 2446
Kremnos 2460
Leeville 2470
Shannon Vale 2370
Stratheden 2470
Sunny Corner 2795
Yarra 2580
Akolele 2546
Cathcart 2632
Charleys Forest 2622
Foxground 2534
Narrawa 2583
North Tumbulgum 2490
Paynes Crossing 2325
Possum Brush 2430
The Branch 2425
Coalcliff 2508
Downside 2650
Dungay 2484
Kielvale 2484
Mount View 2325
Pomona 2648
Putta Bucca 2850
Rowena 2387
Hilldale 2420
Isabella 2795
Little Forest 2538
Mayrung 2710
Merah North 2388
Morven 2660 2370
Pleasant Hills 2658
The Gap 2650 2472
Uralba 2477
Yathella 2650
Avonside 2628
Canoelands 2157
Craven 2422
Torryburn 2421 2358
Upper Kangaroo River 2577
Bocoble 2850
Pyramul 2850
Ramornie 2460
Whian Whian 2480
Alectown 2870
Botobolar 2850
Coasters Retreat 2108
Howes Valley 2330
Mount Arthur 2820
Wiangaree 2474
Barraganyatti 2441
Big Springs 2650
Brimbin 2430
Brookfield 2420
Bungowannah 2640
Glen Alice 2849
Moobi 2337
Mundongo 2720
Nanima 2582
Rappville 2469
Wisemans Creek 2795
Bendoura 2622
Dunolly 2330
Eatonsville 2460
Melinga 2430
Milvale 2594
Mount Warning 2484
Purlewaugh 2357
South Ballina 2478
Thuddungra 2594
Utungun 2447
Balala 2358
Biniguy 2399
Black Range 2550
Cobbora 2844
Jerangle 2630
Koreelah 2476
Milroy 2380 2850
Mooball 2483
Ryhope 2283
Towrang 2580
Wallarobba 2420
Wayo 2580
Arding 2358
Armatree 2828
Bonshaw 2361
Brucedale 2650
Bucca Wauka 2429
Durran Durra 2622
Eviron 2484
Jeremadra 2536
Mount Thorley 2330
Pottery Estate 2790
South Wolumla 2550
Turondale 2795
Bannister 2580
Burroway 2821
Cobaki 2486
Dairymans Plains 2630
Greenlands 2330 2631
Gum Flat 2360
Kimbriki 2429
Lewis Ponds 2800
Nashua 2479
Rous 2477
Stony Chute 2480
Sun Valley 2777
Wakefield 2278
Bective 2340
Bobin 2429
Burragate 2550
Euberta 2650
Freemans Waterhole 2323
James Creek 2463
Keith Hall 2478
Kentucky 2354
Kungala 2460
Mount David 2795
Mullion 2582
Rock Forest 2795
Butterwick 2321
Cooyal 2850
Ewingar 2469
Greigs Flat 2549
Lake George 2581
Monkerai 2415
Myrtleville 2580
Piallaway 2342
Benerembah 2680
Brisbane Grove 2580
Cabramurra 2629
Cope 2852
Joadja 2575
Summer Hill Creek 2800
Wandella 2550
Windera 2800
Lovett Bay 2105
Parma 2540
Rileys Hill 2472
Shannons Flat 2630
Sodwalls 2790
Adjungbilly 2727
Barkers Vale 2474
Bostobrick 2453
Frazers Creek 2446
Gingkin 2787
Glanmire 2795
Kiah 2551
Murrumburrah 2587
Nullamanna 2360
Rous Mill 2477
Urliup 2484
Barragga Bay 2546
Belford 2335
Bergalia 2537
Bevendale 2581
Billywillinga 2795
Bogee 2849
Cumborah 2832
Harefield 2650
Kellys Plains 2350
Kings Plains 2799 2360
Koorainghat 2430
Mount Hope 2877
Muttama 2722
Stony Creek 2550 2850
Tantawangalo 2550
Forbesdale 2422
Kundle Kundle 2430
Oakwood 2360
Stanhope 2335
Yarranbella 2447
Bishops Bridge 2326
Bombay 2622
Boolambayte 2423
Bumbaldry 2794
Carrick 2580
Gin Gin 2823
Meringo 2537
Mogendoura 2537
Turrawan 2390
Angledale 2550
Beaumont 2577
Bedgerabong 2871
Bell 2786
Bolivia 2372
Bombo 2533
Boomanoomana 2712
Byangum 2484
Conargo 2710
Elsmore 2360
Emerald Hill 2380
Great Marlow 2460
Kikoira 2669
Lacmalac 2720
Minore 2830
Mitchells Flat 2330
Mullengandra 2644
Boorabee Park 2480
Burrundulla 2850
Coopers Gully 2550
Dartbrook 2336
Deep Creek 2440 2469 2460
Green Pigeon 2474
Hanging Rock 2340
Harolds Cross 2622
Huonbrook 2482
Killawarra 2429
Markwell 2423
Neurea 2820
Palmers Channel 2463
Ardglen 2338
Avoca 2577
Bungawalbin 2469
Castle Doyle 2350
Cowper 2460
Emu Swamp 2800
Oberne Creek 2650
Wellingrove 2370
Bandon Grove 2420
Beryl 2852
Farrants Hill 2484
Tanglewood 2488
Westbrook 2330
Booligal 2711
Buckaroo 2850
Croobyar 2539
Curramore 2533
Dorroughby 2480
Grassy Head 2441
Kingfisher Shores 2259
Ogunbil 2340
Reserve Creek 2484
Roslyn 2580
Seal Rocks 2423
Braemar Bay 2628
Brunkerville 2323
Buckra Bendinni 2449
Clergate 2800
Cottage Point 2084
Cunningar 2587
Huntingwood 2148
Lade Vale 2581
Maison Dieu 2330
Old Adaminaby 2629
Reedy Creek 2330
The Ridgeway 2620
Balladoran 2822
Bellmount Forest 2581
Berremangra 2582
Coffee Camp 2480
Creewah 2631
Hobbys Yards 2795
Kangaroo Creek 2460
Marom Creek 2480
Tuena 2583
Tygalgah 2484
Bullawa Creek 2390
Cedar Point 2474
Doon Doon 2484
Fernbrook 2453
Frog Rock 2850
Godfreys Creek 2586
Little Billabong 2644
Luskintyre 2321
Napoleon Reef 2795
Old Bonalbo 2469
Picketts Valley 2251
Wendoree Park 2250
Barwang 2594
Bellawongarah 2535
Bowman 2422
Cookamidgera 2870
Crowdy Head 2427
Curraweela 2580
Llangothlin 2365
Round Mountain 2484
Tomboye 2622
Twelve Mile 2850
Blaxlands Creek 2460
Breadalbane 2581
Calga 2250
Doubtful Creek 2470
Evans Plains 2795
Fosterton 2420
Fullerton 2583
Kiacatoo 2877
Martindale 2328
Mimosa 2666
Mount Mitchell 2365
Pembrooke 2446
Tyalgum Creek 2484
Upper Dartbrook 2336
Brewongle 2795
Bullarah 2400
Euabalong West 2877
Fernbank Creek 2444
Galambine 2850
Girral 2669
Kinvara 2478
Lynwood 2477
Triangle Flat 2795
Upsalls Creek 2439
Warrawidgee 2680
Cedar Brush Creek 2259
Edith 2787
Gidginbung 2666
Gillenbah 2700
Medway 2577
North Woodburn 2471
Upper Taylors Arm 2447
Bora Ridge 2471
Bournda 2548
Browns Creek 2799
Bungaba 2852
Darkwood 2454
Mount Tomah 2758
Pearces Creek 2477
Watsons Creek 2355
Bukkulla 2360
Bundook 2422
Caffreys Flat 2424
Carcalgong 2850
Hickeys Creek 2440
Millbank 2440
Reno 2722
Rollands Plains 2441
Rugby 2583
Salisbury 2420
Sheedys Gully 2790
Tamban 2441
Tullymorgan 2463
Wirrinya 2871
Woodview 2470
Berry Jerry 2701
Boro 2622
Eurongilly 2663
Goolmangar 2480
Hebden 2330
Jerrawa 2582
Jerseyville 2431
Logans Crossing 2439
Moparrabah 2440
Numbugga 2550
Rouchel 2336
The Marra 2831
Tucki Tucki 2480
Wang Wauk 2423
Alleena 2671
Blakebrook 2480
Collendina 2646
Coreen 2646
Elvina Bay 2105
Essington 2787
Glen William 2321
Gocup 2720
Kyeamba 2650
Lower Creek 2440
Mondrook 2430
Naradhan 2669
Sleepy Hollow 2483
Taylors Arm 2447
Waukivory 2422
Wuuluman 2820
Daysdale 2646
Gollan 2820
Graman 2360
Gurrundah 2581
Jenolan 2790
Kameruka 2550
Maimuru 2594
Marshall Mount 2530
Milbrodale 2330
Pitt Town Bottoms 2756
Bectric 2665
Bellimbopinni 2440
Binna Burra 2479
Bungarby 2630
Colo 2756 2795
Crudine 2795
Elrington 2325
Kundibakh 2429
Lower Southgate 2460
Main Creek 2420
Moto 2426
Sebastopol 2666
Wallangra 2360
Wamban 2537
Woodside 2372
Blakney Creek 2581
Cheero Point 2083
Dorrigo Mountain 2453
Drake Village 2469
Garoo 2340
Hartley Vale 2790
Lillian Rock 2480
Manar 2622
North Yalgogrin 2671
North Yeoval 2868
Primrose Valley 2621
Sandigo 2700
Tongarra 2527
Turners Flat 2440
Upper Macdonald 2775
Upper Manilla 2346
Bakers Creek 2422 2447 2359
Bielsdown Hills 2453
Booerie Creek 2480
Erudgere 2850
Ingebirah 2627
Jeremy 2795
Keerrong 2480
Middle Pocket 2483
Mountain Lagoon 2758
Spring Creek 2800
Tonderburine 2817
Upper Rouchel 2336
Whiteman Creek 2460
Wiarborough 2580
Clear Creek 2795
Eunanoreenya 2650
Giants Creek 2328
Goodnight 2736
Guyong 2798
Kembla Heights 2526
Leconfield 2335
Limbri 2352
Methul 2701
Mount Elliot 2250
Myrtle Creek 2469
Reddestone 2370
Sandy Flat 2372
Skinners Shoot 2481
Tilba Tilba 2546
Tyringham 2453
Upper Colo 2756
Urila 2620
West Coraki 2471
Apsley 2820
Biddon 2827
Billys Creek 2453
Bunnaloo 2731
Crowther 2803
Cudgegong 2850
Dulguigan 2484
East Lynne 2536
Garthowen 2345
Junee Reefs 2666
Marlow 2775
Mount Seaview 2446
New Park 2474
Stonehenge 2370
The Whiteman 2460
Yarrowyck 2358
Caloola 2795
Hazelgrove 2787
Horse Station Creek 2474
Huntleys Point 2111
Kamarah 2665
Limekilns 2795
Mirrool 2665
Stannum 2371
Turlinjah 2537
Brays Creek 2484
Bream Beach 2540
Bullio 2575
Castle Rock 2333
Crooked Corner 2583
Mount Russell 2360
Murrah 2546
Rannock 2701
Tinderry 2620
Widgelli 2680
Wirrimah 2803
Allgomera 2441
Anambah 2320
Bodangora 2820
Broughton Village 2534
Burra Creek 2722
Collins Creek 2474
Copeland 2422
Deua River Valley 2537
Eden Creek 2474
Ettrick 2474
Fishermans Bay 2316
Fordwich 2330
Goobarragandra 2720
Ophir 2800
Peelwood 2583
Rowlands Creek 2484
Ruthven 2480
Timbumburi 2340
Upper Duroby 2486
Austral Eden 2440
Jackadgery 2460
Kenebri 2396
Taloumbi 2463
Walleroobie 2665
Wapengo 2550
Wooyung 2483
Budgong 2577
Dum Dum 2484
Dumaresq 2350
Glen Allen 2631
Greenridge 2471
Kynnumboon 2484
Leycester 2480
Mount Frome 2850
Oyster Cove 2318
Webbs Creek 2775
Alpine 2575
Belgravia 2800
Carrs Creek 2460
Laughtondale 2775
Long Flat 2446
Lost River 2583
Pomeroy 2580
Wandsworth 2365
Wog Wog 2622
Backmede 2470
Book Book 2650
Bungalora 2486
Byrrill Creek 2484
Caparra 2429
Fawcetts Plain 2474
Goolhi 2379
Kangiara 2582
Leets Vale 2775
Maragle 2653
Maxwell 2650
Mulloon 2622
Mummel 2580
Mungay Creek 2440
Rose Valley 2534 2630
Stewarts River 2443
Swan Creek 2462
Tharwa 2620
Upper Rollands Plains 2441
Waterview 2460
Weemelah 2406
Broadway 2581
Chatsbury 2580
Cookardinia 2650
Croppa Creek 2411
Dyraaba 2470
Ellerslie 2648 2729
Gogeldrie 2705
Hopkins Creek 2484
Kentucky South 2354
Mongogarie 2470
Numinbah 2484
Osborne 2656
Savernake 2646
Warragoon 2710
Warrah Ridge 2343
Wheeny Creek 2758
Wirrimbi 2447
Bellangry 2446
Burraboi 2732
Busbys Flat 2469
Curlew Waters 2672
Dobies Bight 2470
Glenbawn 2337
Kunama 2730
Kyalite 2715
Moonan Brook 2337
Neilrex 2831
Nullo Mountain 2849
Obley 2868
Sandy Creek 2835 2338
Spring Terrace 2798
Tallwood 2798
Talmalmo 2640
Trenayr 2460
Trungley Hall 2666
Tuckurimba 2480
Vittoria 2799
Walang 2795
Warri 2622
Camellia 2142
Courabyra 2653
Goonumbla 2870
Grevillia 2474
Mullamuddy 2850
Peak View 2630
Porters Retreat 2787
Spring Plains 2388
Woodhill 2535
Wyanbene 2622
Beggan Beggan 2587
Buddabadah 2825
Depot Beach 2536
Fosters Valley 2795
Gilgooma 2829
Glenmore 2570
Kikiamah 2594
Memagong 2594
Mount Irvine 2786
Pulletop 2650
Rossi 2621
Suntop 2820
Tipperary 2429
Warrah Creek 2339
Whoota 2428
Yarragundry 2650
Big Hill 2579
Calliope 2462
Cavan 2582
Coralville 2443
Dignams Creek 2546
Faulkland 2422
Glenellen 2642
Jerrara 2533
Logie Brae 2713
Mangoola 2328
Morangarell 2666
Mourquong 2739
Mummulgum 2469
Numbaa 2540
Pine Ridge 2343
Rushes Creek 2346
Tabbil Creek 2420
Tomewin 2484
Tootool 2655
Wheeo 2583
Willala 2382
Womboota 2731
Wondalga 2729
Bowna 2644
Eurobodalla 2545
Glengarrie 2486
Homeleigh 2474
Mount Marsden 2849
Narraburra 2666
Pyree 2540
Quandary 2665
Richmond Lowlands 2753
Rowan 2650
Shallow Bay 2428
Two Mile Flat 2852
Wattamolla 2535 2232
Weetaliba 2395
Auburn Vale 2360
Berambing 2758
Bimbimbie 2536
Bobadah 2877
Brombin 2446
Coolgardie 2478
Cooplacurripa 2424
Dirnaseer 2666
Garland 2797
Howards Grass 2480
Jingellic 2642
Lynchs Creek 2474
Newton Boyd 2370
Nubba 2587
Trentham Cliffs 2738
Werai 2577
Yarrowford 2370
Atholwood 2361
Baldry 2867
Colinroobie 2700
Hogarth Range 2469
Jones Island 2430
Naughtons Gap 2470
Pappinbarra 2446
Rocky Glen 2357
Rocky Hall 2550
Stannifer 2369
Uarbry 2329
Upper Wilsons Creek 2482
Whiporie 2469
Wittitrin 2440
Wongwibinda 2350
Yessabah 2440
Burrinjuck 2582
Cogra Bay 2083
Cornwallis 2756
Curra Creek 2820
East Kangaloon 2576
Garema 2871
Grahamstown 2729
Hydes Creek 2454
Kars Springs 2337
Mooral Creek 2429
North Arm 2484
Tambaroora 2850
Terragon 2484
Twelve Mile Creek 2324
Upper Copmanhurst 2460
Urangeline 2656
Alfredtown 2650
Anembo 2621
Biala 2581
Birriwa 2844
Chambigne 2460
Coongbar 2469
Cootralantra 2628
Countegany 2630
Croom 2527
Darkes Forest 2508
Ghoolendaadi 2380
Hopefield 2646
Kanoona 2550
Keinbah 2320
Munni 2420
Murrulebale 2652
Piora 2470
Sandy Hill 2372
Talofa 2481
Warroo 2871
West Bungawalbin 2471
West Wiangaree 2474
Boambolo 2582
Breelong 2827
Colinton 2626
Forest Grove 2795
Glendon 2330
Lake Cowal 2671
Langley Vale 2426
Little Plain 2360
Loxford 2326
Mebul 2852
Mogilla 2550
Mororo 2469
Mozart 2787
Murrumbucca 2630
Palm Grove 2258
Rothbury 2320
Toolijooa 2534
Valery 2454
Bobs Creek 2439
Bundella 2343
Dollys Flat 2429
Gunningbland 2876
Home Rule 2850
Kickabil 2830
Mandemar 2575
March 2800
Norway 2787
Palmdale 2258
Spicers Creek 2820
Upper Horseshoe Creek 2474
Wadeville 2474
Wondabyne 2256
Yarrie Lake 2388
Baldersleigh 2365
Balickera 2324
Bearbong 2827
Ben Bullen 2790
Boeill Creek 2739
Cedar Creek 2325 2484
Cuttabri 2388
Forbes Creek 2621
Kingstown 2358
Mannus 2653
Mogareeka 2550
Mount Lambie 2790
Nerrigundah 2545
Paytens Bridge 2871
Pejar 2583
Repentance Creek 2480
Roseberg 2793
The Bight 2429
Tilpa 2840
Tooma 2642
Varroville 2566
Warburn 2680
Aarons Pass 2850
Bland 2721
Corinella 2871
Dandry 2357
Eccleston 2311
Frogs Hollow 2550
Gongolgon 2839
Gowan 2795
Gum Scrub 2441
Laffing Waters 2795
Lower Pappinbarra 2446
Lowesdale 2646
Mandagery 2870
Manobalai 2333
Myrtle Mountain 2550
Nowley 2386
Pipeclay 2446
Purfleet 2430
Shadforth 2800
Waverly 2337
Woodsreef 2347
Allandale 2320
Baerami 2333
Crawford River 2423
Duckenfield 2321
Errowanbang 2791
Euroley 2700
Kindee 2446
Lankeys Creek 2644
Mogriguy 2830
Ootha 2875
Pucawan 2666
Toogong 2864
Waitui 2443
Wallamore 2340
Walmer 2820
Wanganella 2710
Williamsdale 2620
Allynbrook 2311
Bald Ridge 2795
Batar Creek 2439
Dyrring 2330
Eremerang 2877
Eucumbene 2628
Gobarralong 2727
Knorrit Flat 2424
Lower Mangrove 2250
Mayfield North 2304
Osterley 2324
Owens Gap 2337
Roughit 2330
Speewa 2735
Stewarts Brook 2337
Topi Topi 2423
Warraderry 2810
Wimbledon 2795
Yarrawa 2328
Booyong 2480
Chakola 2630
Corobimilla 2700
Corunna 2546
Garra 2866
Gurranang 2460
Jemalong 2871
Reefton 2666
Rocky Creek 2390 2371
Sugarloaf 2420
Terry Hie Hie 2400
Tugrabakh 2422
Walcha Road 2354
Willsons Downfall 2372
Abercrombie River 2795
Boorolong 2350
Bowan Park 2864
Braefield 2339
Bureen 2328
Carabost 2650
Clifton 2515
Clovass 2480
Come By Chance 2832
Coombell 2470
Corney Town 2790
Currowan 2536
Cuttagee 2546
Eulah Creek 2390
Fairholme 2871
Glen Elgin 2370
Jellat Jellat 2550
Pangee 2825
Pelton 2325
Pine Lodge 2714
Rawdon Island 2446
Richmond Vale 2323
Salisbury Plains 2358
Tilbuster 2350
Toongi 2830
Wambangalang 2830
Willigobung 2653
Alma Park 2659
Blue Vale 2380
Bruinbun 2795
Carrai 2440
Coldstream 2462
Coxs Creek 2849
Dandaloo 2823
Falconer 2365
Marthaguy 2824
McLeods Shoot 2479
Munyabla 2658
Nooroo 2415
Retreat 2355
Rookhurst 2422
Tullakool 2732
Yarras 2446 2795
Bean Creek 2469
Bolaro 2629
Bolong 2540
Durren Durren 2259
Marys Mount 2380
Mayers Flat 2423
Mount Murray 2577
Oakhampton Heights 2320
Palmers Oaky 2795
Piney Range 2810
Saumarez 2350
Tenandra 2824
The Angle 2620
Wardrop Valley 2484
Wollogorang 2581
Angledool 2834
Bewong 2540
Big Jacks Creek 2339
Burnt Bridge 2440
Burrapine 2447
Central Macdonald 2775
Good Forest 2790
Green Gully 2850
Kerrs Creek 2800
Kybeyan 2631
Mallowa 2400
Milsons Passage 2083
Panuara 2800
Phoenix Park 2321
Pretty Pine 2710
Rainbow Reach 2440
Ravensdale 2259
Tabbita 2652
Tichborne 2870
Tuross 2630
Upper Tooloom 2475
Wallanbah 2422
Wambrook 2630
Warkworth 2330
Weabonga 2340
Wyan 2469
Yannergee 2343
Yelgun 2483
Apple Tree Flat 2850
Birganbigil 2710
Brooklana 2450
Canonba 2825
Diggers Camp 2462
Dripstone 2820
Duckmaloi 2787
Edenville 2474
Girralong 2449
Gradys Creek 2474
Larbert 2622
Mundamia 2540
Pitnacree 2323
Sandon 2463
Tewinga 2449
The Pinnacles 2460
Woodlawn 2480
Zara 2484
Ando 2631
Arkell 2795
Berthong 2594
Boomey 2866
Bournewood 2868
Dumaresq Island 2430
Mount Rivers 2311
Mulla Creek 2352
Namoi River 2346
Paling Yards 2580 2795
Parraweena 2339
Red Hill 2347 2824 2720
Roseberry Creek 2474
Shannondale 2460
Skillion Flat 2440
Summer Island 2440
Tara 2665
Tomalla 2337
Underbank 2420
Alumy Creek 2460
Bidgeemia 2642
Bohnock 2430
Boree 2800
Broughton 2535
Buccarumbi 2460
Chichester 2420
Coaldale 2460
Comobella 2820
Dungarubba 2480
Hollisdale 2446
Jerrong 2580
Mindaribba 2320
Mountain Top 2480
Palmvale 2484
Pinkett 2370
Upper Fine Flower 2460
Wean 2382
Winifred 2631
Camboon 2849
Dry Plain 2630
Kooba 2680
Lindifferon 2710
Lostock 2311
Middle Falbrook 2330
Midginbil 2484
Moorwatha 2640
Old Grevillia 2474
Rawsonville 2830
Rock Flat 2630
Stanborough 2360
Tubbul 2594
Warranulla 2423
Weilmoringle 2839
Benolong 2818
Black Creek 2439 2729
Bulgary 2650
Burnt Yards 2792
Cangai 2460
Carrowbrook 2330
Cattle Creek 2339
Clydesdale 2330
Croki 2430
Goorangoola 2330
Hovells Creek 2794
Lerida 2581
Mila 2632
Monak 2738
Pinny Beach 2281
Rennie 2646
Rosebrook 2320
Ryan 2658
Toorooka 2440
Wandera 2360
Back Forest 2535
Bakers Swamp 2820
Blackmans Flat 2790
Bylong 2849
Cabbage Tree Island 2430 2477
Clear Range 2620
Codrington 2471
Cowabbie 2652
Derriwong 2877
Dinoga 2404
Dombarton 2530
Duck Creek 2469
Gumble 2865
Hereford Hall 2622
Horseshoe Creek 2474
Little Jilliby 2259
Matheson 2370
Mirannie 2330
Myall Creek 2403
Mylneford 2460
Pullabooka 2810
Rangari 2380
Riverlea 2850
Rocky Plain 2628
Saddleback Mountain 2533
Stockyard Creek 2460
Tumut Plains 2720
Tuncester 2480
Tunglebung 2469
Wantiool 2663
Wards Mistake 2350
Warragai Creek 2460
Ballengarra 2441
Ballyroe 2795
Bogan 2826
Bundemar 2823
Campvale 2318
Chatham Valley 2787
Gunbar 2711
Jembaicumbene 2622
Lowther 2790
Meroo 2850
Nombi 2379
Oswald 2321
Pola Creek 2440
Stockrington 2322
Triamble 2850
Wrathall 2642
Yaouk 2629
Arthurville 2820
Ballalaba 2622
Billeroy 2829
Bundewallah 2535
Carrabolla 2311
Dhulura 2650
Furracabad 2370
Gidley 2340
Jeogla 2350
Loadstone 2474
Mulyandry 2871
Nattai 2570
Olinda 2849
Southampton 2460
Sweetmans Creek 2325
Theresa Creek 2469
Tindarey 2835
Upper Eden Creek 2474
Weismantels 2415
Anabranch South 2648
Avisford 2850
Berrico 2422
Brogers Creek 2535
Bulla Creek 2594
Crawney 2338
Devils Hole 2550
Donnellyville 2447
Ellerston 2337
Eurimbla 2867
Five Ways 2873
Goorianawa 2396
Jerrawangala 2540
Monga 2622
Mooneba 2440
Ooma 2871
Reedy Swamp 2550
Strathcedar 2429
Upper Turon 2795
Wyneden 2474
Bagotville 2477
Cobark 2422
Cobbadah 2347
Commissioners Creek 2484
Copeton 2360
Cundle Flat 2424
Doyles Creek 2330
Dunkeld 2795
Fernside 2480
Fitzgeralds Mount 2799
Flat Tops 2420
Fortis Creek 2460
Goodwood Island 2469
Innes View 2429
Jews Lagoon 2397
Killongbutta 2795
Kippaxs 2429
Lavadia 2462
Locksley 2795
Longreach 2540
Lords Hill 2632
Moombooldool 2665
Mowbray Park 2571
Muli Muli 2476
Numbla Vale 2628
Orange Grove 2380
Ponto 2818
Tulloona 2400
Bald Blair 2365
Banyabba 2460
Blue Mountains National Park 2787
Bruie Plains 2875
Chowan Creek 2484
Combara 2829
Corrowong 2633
Dabee 2849
Darlow 2729
Fernances Crossing 2325
Gilmandyke 2795
Gosforth 2320
Harparary 2390
Huntingdon 2446
Kilgra 2474
Kippenduff 2469
Larras Lee 2866
Len Waters Estate 2171
Linburn 2850
Mallan 2734
McMahons Reef 2587
Mooney Mooney Creek 2250
Murga 2864
Myrtle Park 2713
Nullica 2551
Rob Roy 2360
Timor 2338
Upper Growee 2849
Wallanthery 2675
Warrah 2339
Yaven Creek 2729
Bingleburra 2311
Bourbah 2828
Carlaminda 2630
Coila 2537
Cow Flat 2795
Darbalara 2722
Erin Vale 2663
Ghinni Ghinni 2430
Goombargana 2646
Jacky Bulbin Flat 2463
Jimenbuen 2628
Kiora 2537
Mangrove Creek 2250
Mollyan 2842
Morans Crossing 2550
Mundarlo 2729
Munderoo 2653
Ournie 2640
Oxley 2711 2824
Palmwoods 2482
Pindaroi 2361
Upper Pappinbarra 2446
Wambool 2795
Willina 2423
Berrigal 2390
Bulldog 2469
Cambra 2420
Camira 2469
Cherry Tree Hill 2360
Collingwood 2850
Coolringdon 2630
Dairy Arm 2325
Gadara 2720
Ghinni Ghi 2474
Glennies Creek 2330
Invergordon 2422
Keybarbin 2469
Lenaghan 2322
Magometon 2829
Montecollum 2482
Morning Bay 2105
Mount Knowles 2850
Neringla 2622
Niemur 2733
Patchs Beach 2478
Shark Creek 2463
Upper Coopers Creek 2482
Wandook 2710
Watton 2795
Webbers Creek 2421
Welaregang 2642
Willi Willi 2440
Bangheet 2404
Banoon 2347
Berringer Lake 2539
Birdwood 2446
Bom Bom 2460
Boorook 2372
Bowman Farm 2422
Burrandana 2650
Canadian Lead 2850
Couradda 2390
Cullendore 2372
Cumbo 2850
Dark Corner 2795
Doctor George Mountain 2550
Donald Creek 2350
Duncans Creek 2340
Fishers Hill 2421
Gibberagee 2469
Gineroi 2404
Gowang 2357
Growee 2849
Hampden Hall 2440
Kangaroobie 2800
Karaak Flat 2429
Marlo Merrican 2441
Mount Harris 2824
Mountain Creek 2644
Number One 2424
Queens Pinch 2850
Ravensworth 2330
Richlands 2580
Tallowwood Ridge 2453
The Risk 2474
Toms Creek 2446
Wantagong 2644
Wingadee 2829
Yallaroi 2408
Booroorban 2710
Budawang 2622
Cobaki Lakes 2486
Cooks Myalls 2870
Dalswinton 2328
Glenelg 2810
Halton 2311
Harpers Hill 2321
Higher Macdonald 2775
Khatambuhl 2429
Miandetta 2825
Moorilda 2795
Mount Adrah 2729
Mullengudgery 2825
Pericoe 2550
Pinnacle Swamp 2849
Rockley Mount 2795
Sapphire 2360
Shooters Hill 2787
Smiggin Holes 2624
Stroud Hill 2420
Tarban 2372
Tibbuc 2422
Urangeline East 2656
Woodhouselee 2580
Woolooma 2337
Yarrabandai 2875
Afterlee 2474
Bombowlee Creek 2720
Buttai 2323
Byng 2800
Caldwell 2710
Calimo 2710
Collerina 2839
Comara 2440
Cullerin 2581
Gulf Creek 2347
Howell 2360
Hyndmans Creek 2446
Keera 2404
Kookabookra 2370
Lagoon Grass 2480
Lewinsbrook 2311
Limerick 2583
Marshdale 2420
Maybole 2365
Merotherie 2852
Middle Flat 2630
Mookerawa 2820
Noona 2835
Oolong 2581
Pallal 2404
Rossglen 2439
Seven Oaks 2440
Warrumbungle 2828
Yalbraith 2580
Bagnoo 2446
Bara 2850
Belltrees 2337
Bindera 2422
Boona Mount 2877
Brodies Plains 2360
Bushells Ridge 2259
Cobar Park 2790
Craigie 2632
Dilkoon 2460
Drildool 2386
Dry Creek 2337
Forest Glen 2157
Halloran 2259
Irvington 2470
Jingera 2622
Little Jacks Creek 2339
Maffra 2630
Mairjimmy 2716
Merricumbene 2622
Merrill 2581
Mount Darragh 2632
New Mexico 2346
Ringwood 2646
Silverton 2880
Tenterden 2365
Thumb Creek 2447
Tomki 2470
Toonumbar 2474
Wyangle 2720
Yerranderie 2787
Boorganna 2429
Brockley 2365
Browns Mountain 2540
Brushy Creek 2365
Burrier 2540
Central Colo 2756
Crooble 2400
Deauville 2443
Honeybugle 2825
Lemon Tree 2259
Lower Acacia Creek 2476
Lower Lewis Ponds 2800
Mellool 2734
Melville 2320
Morago 2710
New Buildings 2550
New Valley 2365
Puddledock 2350
Richards 2765
Round Swamp 2846
Spicketts Creek 2454
Swan Vale 2370
Teridgerie 2829
Tooloon 2829
Tubbamurra 2365
Urawilkie 2829
Wanganui 2482
Widden 2328
Wilbetree 2850
Wolgan Valley 2790
Wollun 2354
Wymah 2640
Yellow Pinch 2548
Babinda 2825
Backwater 2365
Bocobra 2865
Brooman 2538
Buckendoon 2472
Conimbia 2829
Coree 2710
Cougal 2474
Cubba 2835
Cullenbone 2850
Daroobalgie 2870
Diehard 2370
Dog Rocks 2795
Fernances 2775
Fine Flower 2460
Fords Bridge 2840
Freemantle 2795
Kings Forest 2487
Kirkconnell 2795
Knights Hill 2577
Kunghur Creek 2484
Long Plain 2360 2629
Louisa Creek 2469
Millie 2397
Moolarben 2850
Pyangle 2849
Tantonan 2731
Thule 2732
Timbarra 2372
Upper Myall 2423
Woolgarlo 2582
Berry Mountain 2535
Bickley Vale 2570
Boolcarroll 2388
Budden 2849
Bumbalong 2626
Cryon 2832
Findon Creek 2474
Greengrove 2250
Grosses Plain 2627
Landervale 2652
Levenstrath 2460
Lindesay 2347
Manchester Square 2577
McCarrs Creek 2105
Minjary 2720
Nelungaloo 2876
Scheyville 2756
Silent Grove 2372
Steeple Flat 2631
Wiagdon 2795
Yarragrin 2842
Brundee 2540
Bulliac 2422
Cells River 2424
Cooneys Creek 2726
Erigolia 2669
Gilletts Ridge 2462
Greg Greg 2642
Greta Main 2325
Hollydeen 2328
Jerrabattgulla 2622
Kelgoola 2849
Kilgin 2472
Micalo Island 2464
Middle Brother 2443
Monivae 2850
Mookima Wybra 2469
Mount Royal 2330
Mulla 2825
Pinnacle 2810
Roto 2675
Rufus 2648
Stud Park 2710
Tabbimoble 2472
Terrace Creek 2474
Upper Mongogarie 2470
Wellington Vale 2371
Whitlow 2404
Wrights Creek 2775
Yerriyong 2540
Bingeebeebra Creek 2469
Boomi Creek 2476
Bullagreen 2824
Creel Bay 2627
Dhuragoon 2733
Farnham 2820
Fern Gully 2330
Gonn 2732
Gungalman 2829
Gunning Gap 2876
Illaroo 2540
Lower Bottle Creek 2469
Maitland Bar 2850
Marinna 2663
Mogood 2538
Mutawintji 2880
Orton Park 2795
Packsaddle 2880
Runnyford 2536
Sallys Flat 2850
Talawanta 2839
Taradale 2653
Totnes Valley 2850
Upper Bylong 2849
Windermere 2321
Wirragulla 2420
Wongo Creek 2346
Yantabulla 2840
Arumpo 2715
Balfours Peak 2403
Barigan 2850
Bathampton 2795
Belanglo 2577
Boonoo Boonoo 2372
Bottle Creek 2469
Goonoo Goonoo 2340
Hayes Gap 2850
Indi 2642
Jinden 2622
Kia Ora 2422
Kingsland 2370
Laverstock 2582
Lower Dyraaba 2470
Port Botany 2036
Rivertree 2372
Tannas Mount 2795
Argalong 2720
Baerami Creek 2333
Bamarang 2540
Barretts Creek 2460
Brawboy 2337
Cadgee 2545
Cudgel 2700
Cundumbul 2866
Green Forest 2471
Klori 2346
Milparinka 2880
Mograni 2422
Moppy 2422
Mossgiel 2878
Mount Tenandra 2828
Mumblebone Plain 2824
Rouchel Brook 2336
Tuppal 2714
Ullamalla 2850
Upper Allyn 2311
Washpool 2425
Bindook 2787
Borambil 2343
Bulga Forest 2429
Bullatale 2710
Bulyeroi 2387
Carwell 2849
Dumaresq Valley 2372
Duroby 2486
Farringdon 2622
Goodmans Ford 2575
Green Hills 2365 2730
Gumbalie 2840
Gunderbooka 2840
Kindervale 2622
Little Back Creek 2474
Mihi 2358
Murrawombie 2825
One Tree 2711
Rangers Valley 2370
Rhine Falls 2630
Rosemeath 2632
Sassafras 2622
Scotts Flat 2330
The Hatch 2444
Titaatee Creek 2422
Twin Rivers 2410
Yarraman 2343
Arkstone 2795
Barringella 2540
Belowra 2545
Bowling Alley Point 2340
Breakfast Creek 2849
Calamia 2460
Cathundral 2823
Charlton 2795
Cunninyeuk 2734
Ginghi 2849
Kerrigundi 2835
Kowen 2620
Lilydale 2460
Longarm 2347
Moleville Creek 2460
Nyrang Creek 2804
Quanda 2828
Redlands 2646
Rockton 2632
Trewilga 2869
Twenty Forests 2795
Wollumboola 2540
Worlds End 2850
Abington 2350
Acacia Creek 2476
Brobenah 2705
Brookong 2656
Brungle Creek 2722
Camerons Creek 2359
Carrington Falls 2577
Colly Blue 2343
Dilpurra 2734
Falbrook 2330
Iron Pot Creek 2474
Jaunter 2787
Judds Creek 2795
Monia Gap 2675
Mount Aquila 2820
Northangera 2622
Roseberry 2474
Stonequarry 2580
Thyra 2731
Wermatong 2720
Wylies Flat 2330
Badja 2630
Baryulgil 2460
Beloka 2628
Bobundara 2630
Booth 2620
Borah Creek 2346
Brogans Creek 2848
Broughams Gate 2880
Charles Sturt University 2678
Charlotte Pass 2624
Chilcotts Creek 2339
Clearfield 2469
Coombadjha 2460
Corang 2622
Ironbark 2347
Little River 2720
Marlowe 2622
Mount Horeb 2729
Narrabarba 2551
Tinpot 2546
Upper Nile 2849
Warrazambil Creek 2474
Appleby 2340
Appletree Flat 2330
Arable 2630
Audley 2232
Bald Nob 2370
Boonal 2409
Briarbrook 2365
Clifden 2460
Comberton 2540
Coneac 2422
Copperhannia 2795
Doctors Gap 2790
Forbes River 2446
Gemalla 2795
Georges Creek 2365
Glenworth Valley 2250
Hartwood 2710
Laurel Hill 2649
Lindesay Creek 2476
Miamley 2873
Moggs Swamp 2370
Mount Collins 2794
Narrangullen 2582
Paddys Flat 2632 2469
Pan Ban 2648
Peacock Creek 2469
Sandy Gully 2729
Scotts Creek 2338
Tahlee 2324
Tooloom 2475
Wallaringa 2420
Weedallion 2594
Yarara 2644
Amaroo 2866
Beemunnel 2824
Boorga 2652
Bowmans Creek 2330
Bretti 2422
Bundagen 2454
Chinnock 2550
Cobramunga 2732
Cockwhy 2539
Coomoo Coomoo 2343
Corangula 2440
Eenaweena 2824
Green Creek 2338
Hartys Plains 2446
Jacksons Flat 2469
Kiar 2259
Kulwin 2835
Macdonalds Creek 2339
Maldon 2571
Middlingbank 2630
Munghorn 2850
Newnes 2790
Noorong 2732
Nyora 2646
Oban 2365
Paringi 2738
Quidong 2632
Singleton Military Area 2331
Terreel 2422
The Meadows 2787
The Pilliga 2388
Thirldene 2347
Woolners Arm 2470
Yarragal 2820
Buckenderra 2630
Callaghans Creek 2422
Coxs Crown 2849
Culmaran Creek 2469
Dairy Flat 2474
Elcombe 2404
Gangat 2422
Glen Fergus 2630
Guthega 2624
Kaputar 2390
Killimicat 2720
Little Topar 2880
Meryla 2577
Myuna Bay 2264
Old Station 2440
Pine Valley 2630
Rixs Creek 2330
Rookwood 2141
Stotts Creek 2487
Waugorah 2711
Belfrayden 2650
Billilingra 2630
Bookookoorara 2372
Combo 2330
Comerong Island 2540
Davis Creek 2336
Dunville Loop 2849
Fargunyah 2656
Guntawang 2852
Hayters Hill 2481
Keepit 2340
Mount Marsh 2469
Murrin Bridge 2672
Murrumbo 2849
Nurenmerenmong 2649
Paupong 2628
Pulganbar 2460
Scotia 2648
Unumgar 2474
Upper Bingara 2404
Waldegrave 2800
Warregah Island 2469
Watersleigh 2540
Wilpinjong 2850
Winegrove 2460
Wylie Creek 2372
Bago 2446
Big Ridge 2330
Black Hollow 2828
Cumbandry 2852
Dewitt 2422
Hacks Ferry 2441
Havilah 2850
Irymple 2835
Kyarran 2460
Lilyvale 2508
Mogo Creek 2775
Narran Lake 2839
Sharps Creek 2729
The Brothers 2630
Tumorrama 2720
Yabbra 2469
Yanga 2711
Ashby Island 2463
Bombah Point 2423
Bundure 2700
Cambalong 2632
Dangelong 2630
Fowlers Gap 2880
French Park 2655
Gunningrah 2632
Joes Box 2469
Lee Creek 2849
Little Pelican 2281
Mellong 2756
Merrigal 2827
Nebea 2829
Obanvale 2330
Old Mill 2369
Perrys Crossing 2775
Pigeonbah 2824
Pine Camp 2648
Rukenvale 2474
Sandilands 2469
Sawpit Creek 2474
Simpkins Creek 2469
Snakes Plain 2824
Stony Crossing 2734
Warumbul 2232
Windowie 2720
Yellow Dam 2371
Argoon 2707
Babyl Creek 2470
Bengalla 2333
Callaghan 2308
Cascade 2453
Coolumbooka 2632
Gouldsville 2330
Hungerford 2840
Limestone 2361
Lionsville 2460
Lower Duck Creek 2469
Lucas Heights 2234
Maddens Plains 2508
Marengo 2453
Melbergen 2669
Millah Murrah 2795
Moonpar 2453
Mount Foster 2824
Nimmo 2628
Sandy Crossing 2460
Sextonville 2470
State Mine Gully 2790
Wallis Lake 2428
Yadboro 2539
Bangadang 2729
Bungabbee 2480
Cross Roads 2850
Debenham 2446
Environa 2620
Garland Valley 2330
Gorge Creek 2469
Gostwyck 2358
Hambledon Hill 2330
Jincumbilly 2631
Lemington 2330
Mayvale 2347
Milkers Flat 2795
Newstead 2360
Palarang 2632
Pine Clump 2824
Pine Grove 2829
Pointer Mountain 2539
Port Stephens 2317
Spring Mountain 2370
Swanbrook 2360
Terrabella 2818
Tombong 2633
Wimborne 2346
Anabranch North 2648
Bassendean 2365
Blue Nobby 2408
Buckenbowra 2536
Carrolls Creek 2372
Cleveland 2530
Coggan 2849
Corrong 2711
Cullivel 2645
Gala Vale 2716
Gilgunnia 2877
Glen Ward 2422
Gurnang 2787
Heifer Station 2460
Kerrabee 2328
Kings Hill 2324
Mallee 2738
Mount Dee 2320
Omadale 2337
Pages Creek 2337
Pages River 2338
Pebbly Beach 2536
Rawdon Vale 2422
Timbillica 2551
Yullundry 2867
Barcoongere 2460
Barratta 2710
Bukalong 2632
Carnham 2460
Carrs Peninsula 2460
Clare 2711
Cooleys Creek 2729
Craven Plateau 2422
Curricabark 2422
Dalmorton 2460
Eighteen Mile 2460
Four Mile Creek 2800
Giro 2422
Goonoo Forest 2830
Gundamulda 2347
Haystack 2469
Jones Bridge 2720
Kerewong 2439
Kiandra 2629
Merriangaah 2632
Moorara 2648
Mount Cooper 2631
Mulguthrie 2877
Tocal 2421
Warrabah 2346
Wetuppa 2734
Yarrow 2620
Aratula 2714
Booti Booti 2428
Carrs Island 2460
Freemans 2259
Frying Pan 2630
Ironmungy 2630
Kennaicle Creek 2449
Lower Peacock 2469
Mabins Well 2716
Macquarie Marshes 2831
Middle Harbour 2087
Moolpa 2734
Moonbria 2710
Pittwater 2105
Rossgole 2336
Six Mile Swamp 2469
St George 2622
Tennent 2620
Tiri 2424
Tooranie 2734
Wilsons Valley 2624
Woronora Dam 2508
Yarrangobilly 2720
Alice 2469
Boco 2631
Bulla 2835
Cadia 2800
Califat 2729
Capeen Creek 2469
Capoompeta 2371
Colongra 2262
Coppabella 2644
Fitzgeralds Valley 2795
Gragin 2403
Hanleys Creek 2420
Hatfield 2715
Jooriland 2787
Koonyum Range 2482
Lake Brewster 2675
Lansdowne Forest 2430
Macquarie Pass 2577
Murulla 2337
Para 2648
Stewarts Mount 2795
The Freshwater 2466
Tichular 2850
Upper Duck Creek 2469
Upper Karuah River 2415
Upper Mangrove 2250
Wereboldera 2720
Wombat Creek 2460
Brinerville 2454
Burragorang Valley 2570
Cataract 2560
Dungeree 2849
Jibbon 2232
Ku-Ring-Gai Chase 2080
Paradise 2360
Pikapene 2469
Sanger 2646
Singletons Mill 2775
Steam Plains 2710
The Glen 2476
Tianjara 2622
Upper Kangaroo Valley 2577
Westwood 2729
Bonnie Vale 2232
Bouddi 2251
Brumby Plains 2476
Bullocks Flat 2627
Bumberry 2870
Edrom 2551
Holts Flat 2631
Kingsgate 2370
Kowmung 2787
Lake Macquarie 2283
Mount Werong 2787
Mungo 2715
Nungatta 2551
Saltwater 2430
Snowball 2622
Snowy Plain 2628
Woody Head 2466
Yengo 2325
Barneys Reef 2852
Barren Grounds 2577
Barrington Tops 2422
Beloon 2787
Blowering 2720
Budderoo 2535
Clouds Creek 2453
Coolumburra 2622
Couragago 2720
Edderton 2333
Four Corners 2716
Goarra 2232
Gooandra 2629
Keri Keri 2711
Kiwarrak 2430
Lower Bago 2730
Mares Run 2422
Mernot 2422
Mondayong 2540
Mount Kingiman 2539
Newbold 2460
Nightcap 2480
Pagans Flat 2469
Red Rocks 2577
Tantangara 2629
The Gulf 2365
Wallingat 2428
Windy 2343
Woko 2422
Yalwal 2540
Barringun 2840
Beecroft Peninsula 2540
Berlang 2622
Botany Bay 2019
Buangla 2540
Cairncross 2446
Chaelundi 2460
Collum Collum 2460
Corrabare 2325
Curragh 2795
Deua 2537
Duval 2350
Glenrock 2337
Grants Beach 2445
Jagumba 2642
Liddell 2333
Moonee 2259
Myalla 2630
Providence Portal 2629
The Basin 2365
The Sandon 2463
Tiona 2428
Tullarwalla 2540
Wallacetown 2650
Wattle Ridge 2575
Wonboyn North 2551
Wybung 2259
Yarratt Forest 2429
Avon 2574
Blue Cow 2624
Bogong Peaks Wilderness 2720
Box Head 2257
Currawong Beach 2108
Diamond Head 2443
Forest Land 2372
Garie 2232
Gearys Flat 2441
Geehi 2642
Gibraltar Range 2370
Glen Nevis 2365
Grawin Opal Fields 2832
Green Cape 2551
Jolly Nose 2445
Kedumba 2787
Lake Burrendong 2820
Lake Hiawatha 2462
Malabugilmah 2460
Marley 2232
Moogem 2370
Moollattoo 2540
Mungo Brush 2423
Murrengenburg 2622
Nadgee 2551
Never Never 2453
Ngarigo 2627
North Brother 2443
North Harbour 2095
Palerang 2622
Quiera 2622
Rendezvous Creek 2620
Ten Mile Hollow 2250
Willurah 2710
Yenabilli 2232`
