/**
 * Every suburb and locality in the Northern Territory (NT) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Darwin City 0800
Stuart Park 0820
Larrakeyah 0820
Nightcliff 0810
Coconut Grove 0810
Gillen 0870
Zuccoli 0832
Leanyer 0812
Parap 0820
Humpty Doo 0836
Karama 0812
Nhulunbuy 0880
Fannie Bay 0820
Tennant Creek 0860
Rapid Creek 0810
Rosebery 0832
Durack 0830
Katherine East 0850
Gray 0830
East Side 0870
Berrimah 0828
Bakewell 0832
Millner 0810
Winnellie 0820
Braitling 0870
The Gap 0870
Woodroffe 0830
Muirhead 0810
Moulden 0830
Howard Springs 0835
Driver 0830
Malak 0812
Araluen 0870
Johnston 0832
Sadadeen 0870
Larapinta 0875
Bellamack 0832
Gunn 0832
Katherine South 0850
Yulara 0872
Tiwi 0810
Wulagi 0812
Anula 0812
Alawa 0810
Bayview 0820
Woolner 0820
Lyons 0810
Virginia 0834
Ludmilla 0820
Katherine 0850
Moil 0810
Wagaman 0810
Desert Springs 0870
Jabiru 0886
Jingili 0810
Nakara 0810
Alice Springs 0870
Wanguri 0810
Marrara 0812
Farrar 0830
Girraween 0836
Dundee Beach 0840
Ciccone 0870
Herbert 0836
Alyangula 0885
Yarrawonga 0830
Cossack 0850
Brinkin 0810
Mount Johns 0874
The Gardens 0820
Ross 0873
Berry Springs 0838
Casuarina 0810
Darwin River 0841
Bees Creek 0822
Wurrumiyanga 0822
Wagait Beach 0822
The Narrows 0820
Borroloola 0854
Marrakai 0822
Southport 0822
Batchelor 0845
Wadeye 0822
Acacia Hills 0822
Palmerston City 0830
Coolalinga 0839
McMinns Lagoon 0822
Gunbalanya 0822
Kilgariff 0873
Tindal 0853
Marlow Lagoon 0830
Pine Creek 0847
Stuart 0870
Adelaide River 0846
East Arm 0822
Yirrkala 0880
Elliott 0862
Galiwinku 0822
Knuckey Lagoon 0828
Livingstone 0822
Pinelands 0829
Dundee Downs 0840
Mataranka 0852
Ilparpa 0873
Noonamah 0837
Eaton 0820
Ramingining 0822
Yuendumu 0872
Pukatja 0872
Lake Bennett 0822
Holtze 0829
Lansdowne 0850
Gapuwiyak 0880
Hermannsburg 0872
Lajamanu 0852
Santa Teresa 0872
Bynoe 0822
Lambells Lagoon 0822
Ali Curung 0872
Barunga 0852
Anmatjere 0872
Edith 0852
Connellan 0873
Amata 0872
Dundee Forest 0840
Tumbling Waters 0822
Umbakumba 0822
Kintore 0872
Eva Valley 0822
Fly Creek 0822
Tivendale 0822
Mimili 0872
Blackmore 0822
Iwantja 0872
Kalkarindji 0852
Lloyd Creek 0822
Arumbera 0873
Lee Point 0810
Timber Creek 0852
Kaltjiti 0872
Kaltukatjara 0872
Papunya 0872
Willowra 0872
Nyirripi 0872
Minjilang 0822
Ampilatwatja 0872
Finke 0872
Weddell 0822
Uralla 0852
Pipalyatjara 0872
Beswick 0852
Rum Jungle 0822
Imanpa 0872
Laramba 0872
Mount Liebig 0872
Canteen Creek 0872
Amoonguna 0873
Titjikala 0872
Yuelamu 0872
Baines 0852
Venn 0852
Robin Falls 0822
Daly Waters 0852
Douglas-Daly 0822
Umuwa 0872
Areyonga 0872
Atitjere 0872
Wallace Rockhole 0872
Emungalan 0850
Ti Tree 0872
Wutunugurra 0872
Daly River 0822
Florina 0852
Flynn 0875
Davenport 0872
Haasts Bluff 0872
Engawala 0872
Wishart 0822
Rakula 0822
Warumungu 0852
Nitmiluk 0852
Stapleton 0822
Hughes 0822
White Gums 0870
Wilora 0872
Middle Point 0822
Burt Plain 0872
Manton 0837
Watarru 0872
Kalka 0872
Tara 0872
Pamayu 0862
Yunyarinyi 0872
Birdum 0852
Charlotte 0822
Finniss Valley 0822
Hugh 0872
Kanpi 0872
Newcastle Waters 0862
Nyapari 0872
Coomalie Creek 0822
Larrimah 0852
McArthur 0852
Wickham 0822
Petermann 0872
Tortilla Flats 0822
East Arnhem 0822
Victoria River 0852
Ghan 0872
Point Stuart 0822
Top Springs 0852
Collett Creek 0822
Elsey 0852
Freds Pass 0822
Creswell 0852
Delamere 0852
Mount Bundey 0822
Tablelands 0862
Archer 0830
Hart 0872
Watinuma 0872
Costello 0872
Fleming 0822
Cox Peninsula 0822
Flying Fox 0852
Murputja 0872
Sandover 0872
Buchanan 0852
Koolpinyah 0822
Gregory 0852
Kakadu 0822
Mount Zeil 0872
Mt Liebig 0872
Anatye 0872
Hale 0872
Manbulloo 0852
Shoal Bay 0830
De Rose Hill 0872
Mandorah 0822
Namatjira 0872
Arnold 0852
Hidden Valley 0822
Margaret River 0822
Milingimbi 0822
Ngaanyatjarra-Giles 0872
East Point 0820
West Arnhem 0822
Camp Creek 0822
Mitchell 0832
Ngukurr 0852
Coonawarra 0820
Limmen 0852
Litchfield Park 0822
Tanami 0872
Tanami East 0852
Wak Wak 0822
Ayers Range South 0872
Beswick Creek 0852
Burrundie 0822
Darwin River Dam 0822
Holmes 0812
Irlpme 0874
Maranunga 0822
Micket Creek 0822
Acacia Larrakia 0837
Anangu Pitjantjatjara Yankunytjatjara 0872
Bradshaw 0852
Calvert 0862
Channel Island 0822
Charles Darwin 0820
Chilla Well 0872
Claravale 0822
Elrundie 0822
Gurindji 0852
Lake Mackay 0872
Milyakburra 0822
Nauiyu 0822
Tieyon 0872
Tjirrkarli 0872
Belyuen 0822
Binjari 0852
Black Jungle 0822
Buffalo Creek 0812
Bulman Weemol 0852
Daly 0822
Gibson Desert South 0872
Glyde Point 0822
Gulung Mardrulk 0852
Gunn Point 0822
Lambina 0872
Murrumujuk 0822
Mutitjulu 0872
Numbulwar 0822
Tipperary 0822
Undoolya 0874
Warruwi 0822`
