/**
 * Every suburb and locality in Queensland (QLD) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Surfers Paradise 4217
Southport 4215
Brisbane City 4000
Maroochydore 4558
Buderim 4556
Caboolture 4510
West End 4101 4810
Labrador 4215
Morayfield 4506
South Brisbane 4101
Robina 4226
Fortitude Valley 4006
Broadbeach 4218
Coorparoo 4151
Palm Beach 4221
Burleigh Heads 4220
Cleveland 4163
Upper Coomera 4209
Pimpama 4209
Russell Island 4184
Redbank Plains 4301
Kallangur 4503
Capalaba 4157
Nerang 4211
Hope Island 4212
Chermside 4032
North Lakes 4509
Nundah 4012
New Farm 4005
Coomera 4209
Helensvale 4212
Emerald 4720
Forest Lake 4078
Maryborough 4650
Kirwan 4817
Deception Bay 4508
Varsity Lakes 4227
Narangba 4504
Kangaroo Point 4169
Toowong 4066
Noosaville 4566
Wynnum 4178
Burpengary 4505
Woolloongabba 4102
Mooloolaba 4557
Eagleby 4207
Indooroopilly 4068
Coolangatta 4225
Coolum Beach 4573
Bowen 4805
Victoria Point 4165
Redland Bay 4165
Thornlands 4164
Mermaid Beach 4218
The Gap 4061 4825
Spring Hill 4000
Redcliffe 4020
Park Ridge 4125
Nambour 4560
Calamvale 4116
Urangan 4655
Carindale 4152
Annerley 4103
Warwick 4370
Ashmore 4214
Morningside 4170
Sunnybank Hills 4109
Burleigh Waters 4220
Dalby 4405
Hamilton 4007
Eight Mile Plains 4113
Ormeau 4208
Clayfield 4011
St Lucia 4067
Gympie 4570
Albany Creek 4035
Carrara 4211
Rochedale South 4123
Bracken Ridge 4017
Newstead 4006
Upper Mount Gravatt 4122
Aspley 4034
Ashgrove 4060
Biggera Waters 4216
Moorooka 4105
Woodridge 4114
Birkdale 4159
Mareeba 4880
Mermaid Waters 4218
Alexandra Hills 4161
Mango Hill 4509
Newtown 4350 4305
Inala 4077
Bongaree 4507
Pacific Pines 4211
Noosa Heads 4567
Greenbank 4124
Miami 4220
Springfield Lakes 4300
Slacks Creek 4127
Carina 4152
Beenleigh 4207
Marsden 4132
Coombabah 4216
Arundel 4214
Mount Gravatt East 4122
Runaway Bay 4216
Mudgeeraba 4213
Springwood 4127
Camp Hill 4152
Kingaroy 4610
Runcorn 4113
Brassall 4305
Wynnum West 4178
Burpengary East 4505
Cairns City 4870
Taringa 4068
Oxenford 4210
Logan Reserve 4133
Bargara 4670
Shailer Park 4128
Everton Park 4053
Tewantin 4565
Kedron 4031
Paddington 4064
Ayr 4807
Manly West 4179
Griffin 4503
Wellington Point 4160
Yarrabilba 4207
Harristown 4350
Kelvin Grove 4059
Moranbah 4744
Bowen Hills 4006
Atherton 4883
Currumbin Waters 4223
Benowa 4217
Greenslopes 4120
Yeppoon 4703
Elanora 4221
Port Douglas 4877
Kingston 4114
Sippy Downs 4556
Gracemere 4702
Main Beach 4217
Kearneys Spring 4350
Edmonton 4869
Scarborough 4020
Windsor 4030
Strathpine 4500
Roma 4455
Paradise Point 4216
Zillmere 4034
Tarragindi 4121
Bli Bli 4560
Bulimba 4171
Crestmead 4132
Mountain Creek 4557
Bardon 4065
Clontarf 4019 4357
Cairns North 4870
Andergrove 4740
Bridgeman Downs 4035
Loganlea 4131
Mitchelton 4053
Murrumba Downs 4503
Tugun 4224
Urraween 4655
Wavell Heights 4012
Warner 4500
Oxley 4075
Cannonvale 4802
Kippa-Ring 4021
Stafford 4053
East Brisbane 4169
Norman Gardens 4701
Caloundra 4551
Brighton 4017
Broadbeach Waters 4218
Mackay 4740
Acacia Ridge 4110
Sunnybank 4109
Raceview 4305
Carseldine 4034
Tamborine Mountain 4272
Trinity Beach 4879
Caboolture South 4510
North Ward 4810
Boondall 4034
Beaudesert 4285
Margate 4019
Yeronga 4104
Chinchilla 4413
Little Mountain 4551
Tingalpa 4173
Loganholme 4129
Redlynch 4870
Kenmore 4069
Palmview 4553
Torquay 4655
Teneriffe 4005
Glenvale 4350
Bellbird Park 4300
Goodna 4300
Macleay Island 4184
Parkinson 4115
Kelso 4815
Rothwell 4022
Wishart 4122
Rangeville 4350
Durack 4077
Underwood 4119
Highfields 4352
Peregian Springs 4573
Berserker 4701
Ascot 4007 4359
Gatton 4343
Golden Beach 4551
Regents Park 4118
Alexandra Headland 4572
Frenchville 4701
Auchenflower 4066
Wilsonton 4350
Townsville City 4810
Coopers Plains 4108
Holland Park 4121
Collingwood Park 4301
Browns Plains 4118
Highgate Hill 4101
Chapel Hill 4069
Mount Louisa 4814
Taigum 4018
Jimboomba 4280
Waterford West 4133
Molendinar 4214
Cornubia 4130
Pelican Waters 4551
Goondiwindi 4390
Rochedale 4123
Bray Park 4500
Ripley 4306
Sherwood 4075
Carina Heights 4152
Norman Park 4170
Cannon Hill 4170
Manunda 4870
Mansfield 4122
Pialba 4655
Lutwyche 4030
Alderley 4051
Lawnton 4501
Banksia Beach 4507
Algester 4115
Bethania 4205
Smithfield 4878
Milton 4064
Manoora 4870
Petrie 4502
Toowoomba City 4350
Brendale 4500
South Mackay 4740
North Mackay 4740
Bundall 4217
Beerwah 4519
Mount Sheridan 4868
Caloundra West 4551
Holland Park West 4121
Salisbury 4107
Hillcrest 4118
Boronia Heights 4124
Albion 4010 4822
Stanthorpe 4380
East Toowoomba 4350
Parkwood 4214
Gordonvale 4865
Middle Ridge 4350
Palmwoods 4555
Keperra 4054
Bentley Park 4869
Ormiston 4160
Southside 4570
Red Hill 4059 4413
Banyo 4014
Northgate 4013
Wakerley 4154
Flagstone 4280
Ferny Hills 4055
South Toowoomba 4350
Kings Beach 4551
Logan Central 4114
Mooroobool 4870
Nirimba 4551
Bundamba 4304
Rockhampton City 4700
Biloela 4715
Merrimac 4226
Palm Cove 4879
West Mackay 4740
Newport 4020
Peregian Beach 4573
Sinnamon Park 4073
Ingham 4850
Fitzgibbon 4018
Aitkenvale 4814
Bald Hills 4036
Burdell 4818
Garbutt 4814
McDowall 4053
Sarina 4737
Centenary Heights 4350
Woree 4868
Chermside West 4032
Westcourt 4870
Daisy Hill 4127
Geebung 4034
Condon 4815
Douglas 4814 4354
Camira 4300
Currimundi 4551
Pallara 4110
Woody Point 4019
Agnes Water 4677
Kuraby 4112
Spring Mountain 4300
Enoggera 4051
Newmarket 4051
Murarrie 4172
Annandale 4814
Stafford Heights 4053
Kewarra Beach 4879
Logan Village 4207
Blackwater 4717
Gladstone Central 4680
Arana Hills 4054
Richlands 4077
Park Avenue 4701
Sandgate 4017
Corinda 4075
West Gladstone 4680
Springfield 4300 4871
Everton Hills 4053
Hawthorne 4171
Doolandella 4077
Clermont 4721
Bahrs Scrub 4207
Clinton 4680
Bundaberg North 4670
Beaconsfield 4740
Mount Warren Park 4207
Marcoola 4564
Bungalow 4870
Reedy Creek 4227
Cooroy 4563
Maudsland 4210
Point Vernon 4655
Nanango 4615
Darra 4076
Tinana 4650
Highland Park 4211
Cranbrook 4814
Waterford 4133
Bellmere 4510
Birtinya 4575
Macgregor 4109
Mount Cotton 4165
Kawungan 4655
Bushland Beach 4818
White Rock 4868 4306
Oakey 4401
Earlville 4870
Mount Pleasant 4740 4521
Parramatta Park 4870
Mount Coolum 4573
St George 4487
Maleny 4552
Karalee 4306
Eatons Hill 4037
Flinders View 4305
Avoca 4670
Dakabin 4503
Wooloowin 4030
Gordon Park 4031
Darling Heights 4350
Ningi 4511
Wurtulla 4575
Glass House Mountains 4518
Ipswich 4305
Tannum Sands 4680
Sunshine Beach 4567
Baringa 4551
Graceville 4075
Beachmere 4510
Warana 4575
Hendra 4011
Manly 4179
Charleville 4470
Rural View 4740
Upper Caboolture 4510
Buddina 4575
Scarness 4655
Sandstone Point 4511
Cloncurry 4824
Yamanto 4305
Worongary 4213
Holmview 4207
Rocklea 4106
Cooktown 4895
Ferny Grove 4055
New Auckland 4680
North Ipswich 4305
Jindalee 4074
Currumbin 4223
Stones Corner 4120
Balmoral 4171
Edge Hill 4870
Parrearra 4575
Whitfield 4870
Tara 4421
Laidley 4341
Longreach 4730
Tanah Merah 4128
Avenell Heights 4670
Kawana 4701
New Beith 4124
Mount Gravatt 4122
Hermit Park 4812
Upper Kedron 4055
Proserpine 4800
Thorneside 4158
South Townsville 4810
Eli Waters 4655
Boyne Island 4680
South Gladstone 4680
Augustine Heights 4300
Moggill 4070
Bellbowrie 4070
Grange 4051
Deagon 4017
Gaythorne 4051
Calliope 4680
Landsborough 4550
Clear Island Waters 4226
Edens Landing 4207
Burnett Heads 4670
South Ripley 4306
Robertson 4109
The Range 4700
Bellara 4507
Idalia 4811
Rasmussen 4815
Meridan Plains 4551
Wilston 4051
Bucasia 4750
Brinsmead 4870
Rosewood 4340
Wulguru 4811
Mount Low 4818
Bundaberg South 4670
Koongal 4701
Mundingburra 4812
Allenstown 4700
Clifton Beach 4879
Doonan 4562
Lowood 4311
Airlie Beach 4802
Wandal 4700
Kepnock 4670
Hemmant 4174
Yorkeys Knob 4878
Bonogin 4213
Heritage Park 4118
North Toowoomba 4350
Branyan 4670
Leichhardt 4305
Sunrise Beach 4567
Cranley 4350
Bilinga 4225
East Mackay 4740
Tin Can Bay 4580
Elimbah 4516
Woombye 4559
Heatley 4814
Murgon 4605
Yandina 4561
Meadowbrook 4131
Booval 4304
Pimlico 4812
Railway Estate 4810
Home Hill 4806
Pittsworth 4356
Moffat Beach 4551
Deeragun 4818
Heathwood 4110
Nudgee 4014
Fairfield 4103
Glenella 4740
River Heads 4655
Svensson Heights 4670
Mount Morgan 4714
Redbank 4301
Cooloola Cove 4580
Emu Park 4710
Bundaberg West 4670
Barcaldine 4725
Dysart 4745
Mount Lofty 4350
Blacks Beach 4740
Karana Downs 4306
Kuranda 4881
Belmont 4153
Bohle Plains 4817
Moore Park Beach 4670
Yatala 4207
Glenwood 4570
Silkstone 4304
Slade Point 4740
Burrum Heads 4659
Tolga 4882
Currajong 4812
Stretton 4116
Virginia 4014
Bundaberg East 4670
Rockville 4350
Wondai 4606
Walkerston 4751
Deebing Heights 4306
Bayview Heights 4868
Cashmere 4500
Woodford 4514
Marian 4753
Riverhills 4074
Tully 4854
Westlake 4074
Miles 4415
Fig Tree Pocket 4069
Gayndah 4625
Tamborine 4270
Westbrook 4350
Woorim 4507
Tallai 4213
Ormeau Hills 4208
Hughenden 4821
Blackall 4472
Lota 4179
Zilzie 4710
Pacific Paradise 4564
Fernvale 4306
Eastern Heights 4305
Wamuran 4512
Harlaxton 4350
Middle Park 4074
Woodgate 4660
Charters Towers City 4820
Forestdale 4118
Burnside 4560
Granville 4650
Point Lookout 4183
Forest Glen 4556
Chelmer 4068
Tallebudgera 4228
Boonah 4310
Drewvale 4116
Chambers Flat 4133
Trinity Park 4879
Drayton 4350
Ellen Grove 4078
Ooralea 4740
Eumundi 4562
Pomona 4568
Parkhurst 4702
Mooloolah Valley 4553
Walloon 4306
Collinsville 4804
Seventeen Mile Rocks 4073
Rainbow Beach 4581
Mudjimba 4564
Toogoom 4655
Gulliver 4812
Twin Waters 4564
Eimeo 4740
Nelly Bay 4819
Holloways Beach 4878
Rosslea 4812
Crows Nest 4355
Hollywell 4216
Kuluin 4558
Yeerongpilly 4105
Herston 4006
Booral 4655
Jacobs Well 4208
Cardwell 4849
Normanton 4890
Wondunna 4655
South Maclean 4280
Dutton Park 4102
Malanda 4885
Clifton 4361
North Booval 4304
Walkervale 4670
Joyner 4500
Innes Park 4670
Seven Hills 4170
Innisfail 4860
Oonoonba 4811
Moura 4718
Minyama 4575
Mossman 4873
Riverview 4303
Brookfield 4069
Kooralbyn 4285
Belgian Gardens 4810
Lammermoor 4703
Mount Ommaney 4074
Kalkie 4670
Norville 4670
Berrinba 4117
Middlemount 4746
Thabeban 4670
Aroona 4551
Jamboree Heights 4074
Thursday Island 4875
Howard 4659
Bundaberg Central 4670
Childers 4660
Glen Eden 4680
Millbank 4670
Rosenthal Heights 4370
Wilsonton Heights 4350
Craignish 4655
Richmond 4822 4740
Bokarina 4575
Dicky Beach 4551
Alligator Creek 4816 4740
Cambooya 4358
Parkside 4825
Gleneagle 4285
Dundowran Beach 4655
Pullenvale 4069
Battery Hill 4551
Dayboro 4521
Samford Valley 4520
Freshwater 4870
East Ipswich 4305
Esk 4312
Paget 4740
Brookwater 4300
Meringandan West 4352
Millmerran 4357
Chuwar 4306
Forrest Beach 4850
Mornington 4825
Lamb Island 4184
Thuringowa Central 4817
Wongaling Beach 4852
Taranganba 4703
Curra 4570
Jubilee Pocket 4802
Mission Beach 4852
Rocky Point 4874 4873
Munruben 4125
Kin Kora 4680
Yungaburra 4884
Kanimbla 4870
Nikenbah 4655
Wacol 4076
Banya 4551
Yaroomba 4573
Mount Perry 4671
Plainland 4341
Ravenshoe 4888
Portsmith 4870
Windaroo 4207
Mitchell 4465
Cedar Vale 4285
Caravonica 4878
Hyde Park 4812
Kilcoy 4515
Alice River 4817
Babinda 4861
Craiglie 4877
Shorncliffe 4017
Gilston 4211
Cunnamulla 4490
Diddillibah 4559
Richmond Hill 4820
Pioneer 4825
Currumbin Valley 4223
Pinkenba 4008
West Rockhampton 4700
Regency Downs 4341
Townview 4825
Kenmore Hills 4069
Monto 4630
Archerfield 4108
Kirkwood 4680
Withcott 4352
Gowrie Junction 4352
Rosemount 4560
Wyreema 4352
Taroom 4420
Gin Gin 4671
Petrie Terrace 4000
Yarrabah 4871
Vincent 4814
Cotswold Hills 4350
Buccan 4207
Sheldon 4157
Jensen 4818
Mapleton 4560
Palm Island 4816
Sunset 4825
East Innisfail 4860
Telina 4680
Willow Vale 4209
Sumner 4074
Yarraman 4614
Cooroibah 4565
Kunda Park 4556
One Mile 4305
Rockyview 4701
Maroochy River 4561
Churchill 4305
Kleinton 4352
Inglewood 4387
Queenton 4820
Toogoolawah 4313
Kingsthorpe 4400
Kalinga 4030
Torrington 4350
Tennyson 4105
Springsure 4722
Texas 4385
D'Aguilar 4514
Kensington Grove 4341
Glenden 4743
Eagle Farm 4009
Allora 4362
Cooran 4569
Soldiers Hill 4825
Nebo 4742
Montville 4560
Delaneys Creek 4514
Bauple 4650
North Maclean 4280
Mackenzie 4156 4702
Mundubbera 4626
Brandon 4808
Oakhurst 4650
Hay Point 4740
Winton 4735
Cedar Grove 4285
Ravenswood 4816
Goomeri 4601
South Mission Beach 4852
Quilpie 4480
Elliott Heads 4670
Gumdale 4154
Pine Mountain 4306
Killarney 4373
Dimbulah 4872
Healy 4825
Coochiemudlo Island 4184
Canungra 4275
Cedar Creek 4207 4520
Marburg 4346
Mount Crosby 4306
Barney Point 4680
Mackay Harbour 4740
Jandowae 4410
Brisbane Airport 4008
Dundowran 4655
Bakers Creek 4740
Carbrook 4130
Tiaro 4650
Balgal Beach 4816
Chandler 4155
Koumala 4738
Eidsvold 4627
Gailes 4300
Millstream 4888
Mirani 4754
Tallebudgera Valley 4228
Dirranbandi 4486
Innisfail Estate 4860
Mundoolun 4285
Coominya 4311
Stapylton 4207
Boyne Valley 4680
South Nanango 4615
Kilkivan 4600
Blackbutt 4314
Coral Cove 4670
Winston 4825
Lake Macdonald 4563
Gaven 4211
Alpha 4724
Cooee Bay 4703
Gooburrum 4670
Barellan Point 4306
Kalbar 4309
Biggenden 4621
Imbil 4570
Nome 4816
Woodend 4305
Aurukun 4892
Burketown 4830
Horseshoe Bay 4819
Goldsborough 4865
Wandoan 4419
Seaforth 4741
Tieri 4709
Capella 4723
Stratford 4870
Monkland 4570
Black River 4818
Chatsworth 4570
Mount Nathan 4211
Highvale 4520
Tivoli 4305
Proston 4613
Peachester 4519
Springbrook 4213
Stuart 4811
Wongawallan 4210
Wonga Beach 4873
Black Mountain 4563
Bunya 4055
Woodhill 4285
Park Ridge South 4125
Anstead 4070
Greenmount 4359 4751
Peak Crossing 4306
Hatton Vale 4341
Helidon 4344
Cannon Valley 4800
Poona 4650
Goombungee 4354
Wulkuraka 4305
Menzies 4825
Mount Garnet 4872
Kurrimine Beach 4871
Samford Village 4520
Springfield Central 4300
Glenlee 4711
Booie 4610
Hope Vale 4895
Avondale 4670
Julia Creek 4823
Tanawha 4556
Thagoona 4306
Alton Downs 4702
Kamerunga 4870
Herberton 4887
Witta 4552
Lower Beechmont 4211
Nobby 4360
Pacific Heights 4703
Willowbank 4306
Coes Creek 4560
Jones Hill 4570
South Kolan 4670
Burbank 4156
Mount Isa City 4825
Bucca 4670
Laidley Heights 4341
Dinmore 4303
Shoal Point 4750
Sadliers Crossing 4305
Sharon 4670
Beechmont 4211
Toorbul 4510
Trunding 4874
Flaxton 4560
Blackstone 4304
Kowanyama 4892
Kurwongbah 4503
Verrierdale 4562
Tinbeerwah 4563
Buxton 4660
Depot Hill 4700
Stockleigh 4280
Wattle Camp 4615
Hidden Valley 4703
Midge Point 4799
St Lawrence 4707
Sun Valley 4680
Ninderry 4561
Dunwich 4183
Shaw 4818
Machans Beach 4878
Maryborough West 4650
Pie Creek 4570
Leyburn 4365
Bamaga 4876
Tambo 4478
Thangool 4716
Mons 4556
Bluewater 4818
Grasstree Beach 4740
South Stradbroke 4216
Glenview 4553
Cabarlah 4352
Bouldercombe 4702
Aramac 4726
Strathdickie 4800
Toolooa 4680
Apple Tree Creek 4660
Camp Mountain 4520
Forest Hill 4342
Mount Peter 4869
Taroomball 4703
Julatten 4871
Bloomsbury 4799
Habana 4740
Minden 4311
Ocean View 4521
Widgee 4570
Hodgson Vale 4352
Castle Hill 4810
Preston 4352 4800
Rowes Bay 4810
Chillagoe 4871
Georgetown 4871
Barmaryee 4703
West Woombye 4559
Cootharaba 4565
Glenore Grove 4342
Condamine 4416
Karumba 4891
Qunaba 4670
Glen Aplin 4381
Kensington 4670
Kureelpa 4560
Lucinda 4850
Kin Kin 4571
Armstrong Beach 4737
Eudlo 4554
Sunshine Acres 4655
Benaraby 4680
Willawong 4110
Conondale 4552
Sapphire Central 4702
Picnic Bay 4819
Grantham 4347
Broughton 4820
Amity 4183
Wallangarra 4383
Rubyvale 4702
Pacific Haven 4659
Shelly Beach 4551
North Isis 4660
Kuttabul 4741
Mysterton 4812
Arcadia 4819
Thargomindah 4492
Belli Park 4562
Veteran 4570
Yandina Creek 4561
Burrum Town 4659
Millaa Millaa 4886
Ashfield 4670
Purga 4306
Nanum 4874
Baralaba 4702
Injune 4454
Bannockburn 4207
Peeramon 4885
Maryvale 4370 4703
Yuleba 4427
Marcus Beach 4573
Pentland 4816
Boulia 4829
Donnybrook 4510
Halifax 4850
The Caves 4702
The Palms 4570
Kuridala 4824
Bunya Mountains 4405
Kenilworth 4574
Clare 4807
Sugarloaf 4380 4800
Aloomba 4871
Yelarbon 4388
Theodore 4719
Harrisville 4307
Julago 4816
Bluff 4702
Augathella 4477
Aeroglen 4870
Abergowrie 4850
Wallumbilla 4428
Badu Island 4875
Eton 4741
West Ipswich 4305
Goovigen 4702
Wowan 4702
Beerburrum 4517
Adare 4343
Farleigh 4741
Nathan 4111
K'gari 4581
Basin Pocket 4305
Millaroo 4807
Mirriwinni 4871
Redridge 4660
Bluewater Park 4818
Wondecla 4887
Carmila 4739
Ilfracombe 4727
Brooklands 4615
Coalfalls 4305
Dugandan 4310
Jericho 4728
Upper Brookfield 4069
Moa Island 4875
Southern Cross 4820
Amberley 4306
Grandchester 4340
Torbanlea 4662
Mission River 4874
Muttaburra 4732
Doomadgee 4830
Guanaba 4210
Kandanga 4570
Wellesley Islands 4892
Speewah 4881
Laguna Quays 4800
Woorabinda 4713
Tamaree 4570
Aldershot 4650
Greenvale 4816
Rangewood 4817
Finch Hatton 4756
Ilbilbie 4738
Blue Mountain Heights 4350
Glenlogan 4280
Dulong 4560
Mutchilba 4872
Rosedale 4674
Haigslea 4306
Belvedere 4860
Barlows Hill 4703
Deepwater 4674
Guthalungra 4805
Irvinebank 4887
Marlborough 4705
North Maleny 4552
Miriam Vale 4677
Moores Pocket 4305
Banana 4702
Rosslyn 4703
Cosgrove 4818
Pallarenda 4810
Mourilyan 4858
Burua 4680
Hideaway Bay 4800
Woolooga 4570
Dallarnil 4621
Boreen Point 4565
Spring Creek 4361 4343 4420
Toll 4820
Amamoor 4570
Cawarral 4702
Cherbourg 4605
Kingsholme 4208
North Arm 4561
Millchester 4820
Sarina Beach 4737
Steiglitz 4207
Boonooroo 4650
Silkwood 4856
Bell 4408
Horseshoe Lagoon 4809
Mulambin 4703
Brightview 4311
Goondi Bend 4860
Beecher 4680
Euthulla 4455
Tully Heads 4854
Moolboolaman 4671
Southbrook 4363
Kinka Beach 4703
Moore 4314
Wangan 4871
Takura 4655
Valdora 4561
Horse Camp 4671
Applethorpe 4378
Woolmar 4515
Cordalba 4660
Mount Mee 4521
Mount St John 4818
Clear Mountain 4500
Giru 4809
Pinjarra Hills 4069
Riverbend 4280
Kiels Mountain 4559
Captain Creek 4677
Surat 4417
Tingoora 4608
East Deep Creek 4570
Koah 4881
Harlin 4314
South Johnstone 4859
Cow Bay 4873
Thallon 4497
The Leap 4740
Wights Mountain 4520
Wooroolin 4608
Araluen 4570
Bloomfield 4895
Glendale 4711
Calen 4798
Yandaran 4673
Blackbutt North 4314
Dalveen 4374
Erakala 4740
Kogan 4406
Cecil Plains 4407
Eerwah Vale 4562
Jarvisfield 4807
Duaringa 4712
Breddan 4820
Jondaryan 4403
Yengarie 4650
Alberton 4207
Belivah 4207
Tinaroo 4872
Bollon 4488
Ebbw Vale 4304
Isisford 4731
Alloway 4670
Lake Eacham 4884
Laidley North 4341
Watsonville 4887
Tinana South 4650
Wallumbilla North 4428
Lakes Creek 4701
Castaways Beach 4567
Trebonne 4850
Noosa North Shore 4565
Woodwark 4802
Memerambi 4610
Witheren 4275
Bohle 4818
Boyland 4275
Goondi Hill 4860
Hampden 4741
Tarzali 4885
Ilkley 4554
Tanby 4703
Weranga 4405
Carole Park 4300
Chevallum 4555
Cracow 4719
Croydon 4871
Murphys Creek 4352
Top Camp 4350
Adavale 4474
Karawatha 4117
Prince Henry Heights 4350
Summerholm 4341
Bajool 4699
Bingil Bay 4852
Happy Valley 4825
Kaimkillenbun 4406
Taabinga 4610
Warra 4411
Aratula 4309
Ballandean 4382
Kairi 4872
Lonesome Creek 4719
Meikleville Hill 4703
Cooya Beach 4873
Dolphin Heads 4740
Campwin Beach 4737
Birdsville 4482
Hunchy 4555
Pormpuraaw 4892
Westwood 4702
Hazeldean 4515
Taromeo 4314
Wallaville 4671
Clagiraba 4211
Port Curtis 4700
Keppel Sands 4702
Meandarra 4422
Gregory River 4800 4660
Mighell 4860
Biarra 4313
Bororen 4678
Cungulla 4816
Draper 4520
Sandy Creek 4515
Scottville 4804
Karragarra Island 4184
Mount Hallen 4312
Biboohra 4880
Bonnie Doon 4873
Reesville 4552
Woongarra 4670
Forsayth 4871
Fredericksfield 4806
Horn 4875
Deeral 4871
Lockhart River 4892
South Innisfail 4860
Yabulu 4818
South Bingera 4670
Maidenwell 4615
Cooyar 4402
Walkamin 4872
Gunalda 4570
Tarong 4615
Moffatdale 4605
Victory Heights 4570
Corbould Park 4551
Airville 4807
Barrine 4872
Morven 4468
Willows 4702
Kumbia 4610
Ball Bay 4741
Closeburn 4520
Hampton 4352
Mothar Mountain 4570
Woodstock 4816
Advancetown 4211
East Nanango 4615
Booyal 4671
Evelyn 4888
Placid Hills 4343
Carters Ridge 4563
Moogerah 4309
Tansey 4601
Cullinane 4860
Mapoon 4874
Pratten 4370
Bemerside 4850
Bungundarra 4703
Delan 4671
Oakenden 4741
Comet 4702
Whiteside 4503
Durong 4610
Kobble Creek 4520
Taylors Beach 4850
Mount Nebo 4520
Miles End 4825
Tallegalla 4340
El Arish 4855
Majors Creek 4816
Mount Samson 4520
Ogmore 4706
Yangan 4371
Mondure 4611
Balberra 4740
Flying Fish Point 4860
Upper Barron 4883
Ravensbourne 4352
Stanmore 4514
Karrabin 4306
Mount Tarampa 4311
South Isis 4660
Kholo 4306
Turkey Beach 4678
Veresdale Scrub 4285
Cluden 4811
Newell 4873
Alva 4807
Mount Ossa 4741
Bidwill 4650
Hendon 4362
Kabra 4702
Ryan 4825
Brooloo 4570
Mourilyan Harbour 4858
Calvert 4340
Godwin Beach 4511
Miallo 4873
The Dawn 4570
Ebenezer 4340
Paluma 4816
Luscombe 4207
Meadowvale 4670
Goomboorian 4570
Etty Bay 4858
Macknade 4850
Goranba 4421
Basalt 4820
Lytton 4178
Rathdowney 4287
The Summit 4377
Benarkin North 4314
Upper Lockyer 4352
Mount Larcom 4695
Traveston 4570
Wolvi 4570
Aubigny 4401
Brigalow 4412
Lockrose 4342
Raglan 4697
Samsonvale 4520
Braemeadows 4850
Meringandan 4352
Roseneath 4811
Welcome Creek 4670
Degilbo 4621
Ironbark 4306
Saunders Beach 4818
Ellesmere 4610
Dulacca 4425
Point Arkwright 4573
Woongoolba 4207
Mandalay 4802
Inverness 4703
Owanyilla 4650
Webb 4860
Walligan 4655
Coen 4892
Federal 4568
Lockyer Waters 4311
Maaroom 4650
Mount Glorious 4520
Farnborough 4703
Mount Julian 4800
Mungar 4650
Three Rivers 4824
Wellcamp 4350
Cinnabar 4600
Gladstone Harbour 4680
Mount Archer 4514 4701
Linthorpe 4356
Pleystowe 4741
Barratta 4809
Osborne 4806
Paddys Green 4880
Jundah 4736
Macalister 4406
Thulimbah 4376
Torrens Creek 4816
McKinlay 4823
Ballogie 4610
Hodgson 4455
Severnlea 4380
Bondoola 4703
Mount Molloy 4871
Winya 4515
Helidon Spa 4344
Sladevale 4370
South East Nanango 4615
Thornborough 4871
Wivenhoe Pocket 4306
Bedourie 4829
Dingo Beach 4800
Pinbarren 4568
Whitsundays 4802
Glastonbury 4570
Upper Tenthill 4343
Rosevale 4340
Amiens 4380
Blackrock 4850
Dululu 4702
Valentine Plains 4715
Hivesville 4612
Millmerran Woods 4357
Mount Alford 4310
St Ruth 4405
The Gums 4406
Yalboroo 4741
Maroondan 4671
Kybong 4570
Mutdapilly 4307
Riordanvale 4800
Mosman Park 4820
Oak Valley 4811
Stanage 4702
Gindie 4702
Pinnacle 4741
Balnagowan 4740
Colosseum 4677
Coolmunda 4387
Coonarr 4670
Cushnie 4608
Image Flat 4560
Prenzlau 4311
Mowbray 4877
Stanwell 4702
Ducklo 4405
Hawkins Creek 4850
Innot Hot Springs 4872
Tingun 4455
Wurdong Heights 4680
Eubenangee 4860
Masig Island 4875
Mount Kelly 4807
Felton 4358
Mount Jukes 4740
Upper Haughton 4809
Victoria Plains 4751
Good Night 4671
Prairie 4821
Coverty 4613
Jambin 4702
Jubilee Heights 4860
Silver Spur 4385
Camooweal 4828
Diamond Valley 4553
Umbiram 4352
Geham 4352
Homebush 4740
Inkerman 4806
Mount Rascal 4350
Ridgewood 4563
Lakeside 4621
Airdmillan 4807
Calavos 4670
Dalbeg 4807
Glamorgan Vale 4306
Seventy Mile 4820
Hervey Range 4817
Kumbarilla 4405
Bald Knob 4552
Baree 4714
Broadwater 4380
Byfield 4703
Toobanna 4850
Walterhall 4714
Arriga 4880
Linville 4314
McDesme 4807
St Helens Beach 4798
Vale View 4352
Kerry 4285
Kulangoor 4560
Mount Maria 4674
Stonehenge 4730 4357
Postmans Ridge 4352
Veresdale 4285
Carruchan 4816
East Greenmount 4359
East Trinity 4871
Emu Vale 4371
Gargett 4741
Mount Isa 4825
Weyba Downs 4562
Glencoe 4352
Rodds Bay 4678
Thornton 4341
Windorah 4481
Bramston Beach 4871
Bungadoo 4671
Callemondah 4680
Clairview 4741
Kianga 4718
Bellenden Ker 4871
Boompa 4621
Haliday Bay 4740
O'Connell 4680
Selwyn 4824
Devereux Creek 4753
Dingo 4702
Rita Island 4807
Rocksberg 4510
Eungella 4757
Mount Beppo 4313
Brookstead 4364
Rifle Range 4311
Somerset Dam 4312
Adelaide Park 4703
Bracewell 4695
Bulgun 4854
Curtis Island 4680
Erub Island 4875
Lannercost 4850
Lower Wonga 4570
Nudgee Beach 4014
Gheerulla 4574
Lowmead 4676
Mount Mellum 4550
Mount Coolon 4804
Yowah 4490
Dixalea 4702
Prospect 4715
Moorina 4506
Dotswood 4820
Glan Devon 4615
Goodger 4610
Yugar 4520
Drillham 4424
Mingela 4816
Winfield 4670
Kooringal 4025
Laidley South 4341
Maxwelton 4822
Mount Mort 4340
Corfield 4733
Lower Mount Walker 4340
Nerimbera 4701
Rockingham 4854
Elbow Valley 4370
Greens Creek 4570
Rossville 4895
Crawford 4610
Jimbour East 4406
Mount Chalmers 4702
Little Mulgrave 4865
Bowenville 4404
Dunmora 4650
Moola 4406
Rolleston 4702
Haden 4353
Ironpot 4701 4610
Mount Tyson 4356
Towers Hill 4820
North Deep Creek 4570
Pirrinuan 4405
Runnymede 4615
Teelah 4314
Waterloo 4673
Woodbury 4703
Daradgee 4860
Diwan 4873
Gundiah 4650
Moodlu 4510
North Talwood 4496
Rubyanna 4670
Running Creek 4287
Gordonbrook 4610
Jennings 4383
McIlwraith 4671
Stony Creek 4514
Coolabunia 4610
Goomburra 4362
Japoonvale 4856
Mount Abundance 4455
Mount Kynoch 4350
Targinnie 4694
Blenheim 4341
Cedar Pocket 4570
Cooranga 4408
Didcot 4621
Mona Park 4807
Tangorin 4821
Charlton 4350
Mulgildie 4630
Yarwun 4694
Deuchar 4362
Forest Creek 4873
Kokotungo 4702
Lake Clarendon 4343
Feluga 4854
Isis Central 4660
Toomulla 4816
Warraber Islet 4875
Balmoral Ridge 4552
Coconuts 4860
East Feluga 4854
Marmor 4702
Mount Forbes 4340
Silky Oak 4854
Canina 4570
Clumber 4309
Highworth 4560
Lakeland 4871
Lower Tenthill 4343
Moonie 4406
Seventeen Seventy 4677
Upper Stone 4850
Horton 4660
Moorland 4670
Wolffdene 4207
Cordelia 4850
Glenmorgan 4423
Morganville 4671
Mount Charlton 4741
Sarina Range 4737
Sheep Station Creek 4515
Boondooma 4613
Booroobin 4552
Euleilah 4674
King Scrub 4521
Ransome 4154
Biddeston 4401
Coppabella 4741
Mount Martin 4754
Anduramba 4355
East Palmerston 4860
Einasleigh 4871
Freestone 4370
Tuan 4650
Warrill View 4307
West Stowe 4680
Barron 4878
Bullyard 4671
East Barron 4883
Jarra Creek 4854
Kynuna 4823
Pink Lily 4702
Te Kowai 4740
Wonglepong 4275
Blackbutt South 4314
Bungil 4455
Orallo 4455
Teddington 4650
Utchee Creek 4871
Buaraba 4311
Carmoo 4852
Gaeta 4671
Pozieres 4352
Villeneuve 4514
Wilkesdale 4608
Croftby 4310
Greenlands 4380
Bungeworgorai 4455
Isla 4719
Mount Kilcoy 4515
Perwillowen 4560
Ambrose 4695
Mount Colliery 4370
Obi Obi 4574
Round Hill 4677
Royston 4515
Woowoonga 4621
Bambaroo 4850
Camp Creek 4871 4385
Injinoo 4876
Moonford 4630
Racecourse 4740
Wooderson 4680
Cawdor 4352
Ellerbeck 4816
Gumlu 4805
Peranga 4352
Toobeah 4498
Wieambilla 4413
Laceys Creek 4521
Noorindoo 4417
Oakwood 4670
Tungamull 4702
Coringa 4621
Maroon 4310
Mundoo 4860
Pin Gin Hill 4860
Armstrong Creek 4520
Bridges 4561
Keriri Island 4875
Roadvale 4310
St Helens 4650 4356
Gregory 4830
Mena Creek 4871
Pine Creek 4670
Acland 4401
Cape Cleveland 4810
Irvingdale 4404
Junabee 4370
Kalpowar 4630
Whyanbeel 4873
Cooloolabin 4560
Iama Island 4875
Burrum River 4659
Hebel 4486
Lake Barrine 4884
Norwell 4208
Bilyana 4854
Crossdale 4312
Munbilla 4309
Ramsay 4358
Topaz 4885
Wellesley 4417
Crystal Brook 4800
Kiamba 4560
Wujal Wujal 4895
Bartle Frere 4861
Paterson 4570
Wrights Creek 4869
Austinville 4213
Clarendon 4311
Miara 4673
Tumoulin 4888
Booubyjan 4601
Inverlaw 4610
Lawgi Dawes 4716
Baffle Creek 4674
Colinton 4314
Hull Heads 4854
Palmyra 4751
Poruma Island 4875
Bromelton 4285
Eukey 4380
Struck Oil 4714
East End 4695
Eromanga 4480
Hannaford 4406
Jaggan 4885
Kennedy 4816
Long Pocket 4850
Mount Marshall 4362
Swanfels 4371
Whetstone 4387
Alpurrurulam 4825
Tirroan 4671
Ellangowan 4361
Helens Hill 4850
Mulgowie 4341
Nerada 4860
Palen Creek 4287
Redbank Creek 4312
Sandy Ridges 4615
Towen Mountain 4560
Wanora 4306
Coowonga 4702
Gogango 4702
Murray Upper 4854
Tannymorel 4372
Kidaman Creek 4574
Kunwarara 4702
Mutarnee 4816
North Stradbroke Island 4183
Ringtail Creek 4565
Wonbah 4671
Anakie Siding 4702
Farnsfield 4660
Neurum 4514
Three Moon 4630
Wallumbilla South 4428
Bollier 4570
Coalstoun Lakes 4621
Miva 4570
Mossman Gorge 4873
Orange Creek 4715
Chewko 4880
Churchable 4311
Cottonvale 4375
Fishery Falls 4871
Flagstone Creek 4344
Grosmont 4419
Kirknie 4806
Monduran 4671
Pilton 4361
Woopen Creek 4871
Eumamurrin 4455
Kelsey Creek 4800
Morgan Park 4370
New Harbourline 4858
Boogan 4871
Dalcouth 4380
Laravale 4285
Sandy Camp 4361
Black Jack 4820
New Moonta 4671
North Gregory 4660
Cloyna 4605
Duingal 4671
Dumbleton 4740
Swanbank 4306
Wongabel 4883
Branch Creek 4625
Dundathu 4650
Euramo 4854
Meldale 4510
North Eton 4741
Toolakea 4818
Wyandra 4489
Coulson 4310
Dajarra 4825
Degarra 4895
Foreshores 4678
Hodgleigh 4610
Hoya 4310
Jackson 4426
Mount Whitestone 4347
Mowbullan 4405
Peacock Siding 4850
Boynewood 4626
Eureka 4660
Homestead 4816
Kilcummin 4721
Reid River 4816
River Ranch 4680
Beebo 4385
Bellthorpe 4514
Camboon 4719
Carrington 4883
Eulo 4491
Nankin 4701
Shoalwater 4702
Upper Daintree 4873
Boolboonda 4671
Cannon Creek 4310 4380
Columboola 4415
Kulpi 4352
Muirlea 4306
Tarome 4309
Theebine 4570
Almaden 4871
Fairy Bower 4700
Hungerford 4493
Ropeley 4343
Tarampa 4311
Tuckerang 4411
Windera 4605
Duchess 4825
Grand Secret 4820
Redwood 4350
Womina 4370
Ballard 4352
Charlestown 4608
Eurong 4581
Hudson 4860
Mundowran 4626
Wengenville 4615
Cambroon 4552
Canoona 4702
Emu Creek 4355
Hawkwood 4626
Mount Pelion 4741
Sundown 4860 4382
Swan Creek 4370
Weengallon 4497
Bancroft 4630
Gunnewin 4455
Kurumbul 4388
Mackenzie River 4705
Moongan 4714
Tuchekoi 4570
Freshwater Point 4737
Glen Allyn 4885
Lower Daintree 4873
New Mapoon 4876
Patrick Estate 4311
Tablelands 4605 4680
Vernor 4306
Atkinsons Dam 4311
Conway 4800
Jerona 4809
Karara 4352
Kinbombi 4601
Owens Creek 4741
Tinnanbar 4650
Wootha 4552
Maria Creeks 4855
Mount Fox 4850
Mount Surround 4809
Sunnyside 4737
Woodmillar 4625
Septimus 4754
Etna Creek 4702
Glanmire 4570
Ma Ma Creek 4347
Pampas 4352
Benarkin 4314
Derri Derra 4626
Goodwood 4660
Milford 4310
Victoria Plantation 4850
White Patch 4507
Bells Bridge 4570
Daintree 4873
Grahams Creek 4650
Green Hill 4865
Moresby 4871
Muckadilla 4461
Ridgelands 4702
Rules Beach 4674
Cassowary 4873
Munro Plains 4854
Port Of Brisbane 4178
Rollingstone 4816
Flametree 4802
Kia Ora 4570
Mount Marrow 4306
Nindaroo 4740
Numinbah Valley 4211
Oak Beach 4877
Pimpimbudgee 4615
Scrubby Mountain 4356
Umagico 4876
Abercorn 4627
Campaspe 4820
Cypress Gardens 4357
Kings Creek 4361
Lamington 4285
McEwens Beach 4740
Quinalow 4403
Cairdbeign 4722
Chelmsford 4606
Coleyville 4307
Fairney View 4306
Gowrie Mountain 4350
Landers Shoot 4555
Lefthand Branch 4343
Maclagan 4352
Moomin 4887
Pickanjinnie 4428
Saibai Island 4875
Wyaralong 4310
Black Snake 4600
Blanchview 4352
Doolbi 4660
Parklands 4560
Shannonvale 4873
Tandur 4570
Allenview 4285
Amby 4462
Carneys Creek 4310
Chahpingah 4610
Eidsvold West 4627
Mer Island 4875
Myrtlevale 4800
Palmer 4892
Yerra 4650
Brooweena 4620
East Russell 4861
Elphinstone 4361 4742
Greenview 4606
Jimna 4515
Ranges Bridge 4405
Rosehill 4370
Curramore 4552
Millmerran Downs 4357
Sexton 4570
St Mary 4650
Talegalla Weir 4650
Berajondo 4674
Coonambula 4626
Coorumba 4860
Garradunga 4860
Groper Creek 4806
Jeebropilly 4340
Pheasant Creek 4702
Silver Valley 4872
Smithlea 4385
Windermere 4670
Alexandra 4740
Cape Tribulation 4873
Jimbour West 4406
Magnolia 4650
Mount Carbine 4871
Shute Harbour 4802
Wetheron 4625
Goodar 4390
Kureen 4885
Langshaw 4570
Mount Molar 4361
Mount Surprise 4871
Binjour 4625
Canaga 4413
Crohamhurst 4519
Diglum 4680
Gumlow 4815
Hopeland 4413
Sandiford 4740
Stamford 4821
Upper Flagstone 4344
Biddaddaba 4275
Daymar 4497
Groomsville 4352
Isis River 4660
Larapinta 4110
Laura 4892
Lower Tully 4854
Yaamba 4704
Bangalee 4703
Felton South 4358
Guluguba 4418
Mount Byron 4312
Mount Murchison 4715
Bulwer 4025
Carstairs 4806
Dows Creek 4754
Hibernia 4723
Island Plantation 4650
Manumbar 4601
Milbong 4310
Mount Urah 4650
Orange Hill 4455
Priestdale 4127
Riverleigh 4626
Silverleaf 4605
Charlwood 4309
Iredale 4344
Milman 4702
Pechey 4352
West Haldon 4359
Alabama Hill 4820
Birkalla 4854
Boolburra 4702
Braemore 4313
Brigooda 4613
Dalysford 4671
Dunkeld 4465
Flinton 4422
Kooroongarra 4357
Kullogum 4660
Laidley Creek West 4341
Lanefield 4340
North Branch 4356 4370
Benair 4610
Dargal Road 4455
Drinan 4671
Dumgree 4715
Durham 4492
Josephville 4285
Netherdale 4756
Tummaville 4352
Barker Creek Flat 4615
Birnam 4285 4352
Bogie 4805
Coquette Point 4860
Cowley 4871
Fletcher 4381
Lagoon Pocket 4570
Mount Sylvia 4343
Ross River 4816
Cowan Cowan 4025
Horse Creek 4714
Massie 4370
Merryburn 4854
Midgenoo 4854
Mount Alma 4680
Antigua 4650
Dundas 4306
Kinchant Dam 4741
Machine Creek 4695
Piturie 4825
Teebar 4620
Bombeeta 4871
Bungunya 4494
Crossroads 4413
Haly Creek 4610
Monsildale 4515
Mullett Creek 4670
Mungallala 4467
Reids Creek 4625
Silver Ridge 4352
Wheatlands 4606
Beelbi Creek 4659
Berat 4362
Crediton 4757
Glenrae 4626
Jackson North 4426
Kanigan 4570
Mica Creek 4825
Shirbourne 4809
Darlington 4285
Elliott 4670
Glen Cairn 4342
Athol 4350
Eidsvold East 4627
Fairyland 4413
Forest Springs 4362
Highland Plains 4454 4401
Ideraway 4625
Limestone Creek 4701
Manyung 4605
Mount Coot-Tha 4066
Moy Pocket 4574
Stoters Hill 4860
Byrnestown 4625
Cape Gloucester 4800
Cressbrook 4313
Foresthome 4850
Kunioon 4615
Mount Walker 4340
Allandale 4310
Beatrice 4886
Coochin 4310
Coolana 4311
Cowley Beach 4871
Leslie Dam 4370
Natural Bridge 4211
Packers Camp 4865
Seisia 4876
Spreadborough 4825
Upper Kandanga 4570
Yarranlea 4356
Yuleba North 4427
Bapaume 4352
Cainbable 4285
Mungungo 4630
Southwood 4406
Storm King 4380
Barambah 4601
Boonara 4601
Bunjurgen 4310
Burncluith 4413
Columbia 4820
Fitzgerald Creek 4860
Mingo 4625
Two Mile 4570
Winwill 4347
Bryden 4312
Dagun 4570
Gootchie 4650
Mooloo 4570
Mount Marlow 4800
Stalworth 4613
Yaraka 4731
Beach Holm 4818
Bells Creek 4551
Bullcamp 4615
Chances Plain 4413
Glen Isla 4800
Nandi 4405
Neerdie 4570
Okeden 4613
Springlands 4804
Thorndale 4380
Brymaroo 4403
Dakenba 4715
Dalwogon 4415
Electra 4670
Illinbah 4275
Mannuem 4610
The Falls 4373
Womalilla 4465
Benholme 4754
Burra Burri 4410
Golden Fleece 4621
Innisplain 4285
Morton Vale 4343
Petford 4871
South Talwood 4496
Talgai 4362
Benobble 4275
Blue Mountain 4737
Dingo Pocket 4854
Killaloe 4877
Martyville 4858
Monogorilby 4626
Nindooinbah 4285
No 4 Branch 4856
Oaky Creek 4285
South Trees 4680
Upper Pilton 4361
Warrubullen 4871
Alice Creek 4610
Anderleigh 4570
Bamboo Creek 4860
Bracalba 4512
Brush Creek 4387
Coolbie 4850
Fordsdale 4343
Foxdale 4800
Lethebrook 4800
Middleton 4735
Minerva 4722
Avoca Vale 4314
Bamboo 4873
Bunburra 4310
Calico Creek 4570
Kolonga 4671
Pinnacles 4815
Teviotville 4309
Thanes Creek 4370
Wilsons Pocket 4570
Ceratodus 4627
Cooroy Mountain 4563
Dumpy Creek 4702
Gainsford 4702
Headington Hill 4361
Irongate 4356
Khosh Bulduk 4723
Mount Tully 4380
Murrigal 4854
Oman Ama 4352
Wamuran Basin 4512
Wattle Grove 4610
Granadilla 4855
Loch Lomond 4370
Lochington 4720
Lockyer 4344
North Tivoli 4305
Pinelands 4355
Turallin 4357
Wuruma Dam 4627
Christmas Creek 4285
Merlwood 4605
Nundubbermere 4380
Upper Daradgee 4860
Amamoor Creek 4570
Arcturus 4702
Back Plains 4361
Breakaway 4825
Darts Creek 4695
Kimberley 4873
Muldu 4401
Carpendale 4344
Cremorne 4740
Danbulla 4872
Diamondy 4410
Djarawong 4854
Ivory Creek 4313
Moorang 4340
Obum Obum 4309
Orion 4722
Upper Glastonbury 4570
Wolfang 4721
Barney View 4287
Clintonvale 4370
Evans Landing 4874
Kincora 4356
Maryland 4377
Milora 4309
Pindi Pindi 4798
Abington 4660
Aramara 4620
Bongeen 4356
Dalrymple Heights 4757
Greymare 4370
Hamilton Plains 4800
Kandanga Creek 4570
Mount Stanley 4314
Munna Creek 4570
Murrays Bridge 4370
No 6 Branch 4859
Rosella 4740
Silverdale 4307
St Kilda 4671
Townson 4341
Wallu 4570
Banks Pocket 4570
Bauhinia 4718
Condamine Plains 4352
Glenorchy 4650
Kalapa 4702
Kapaldo 4630
Morinish 4702
Opalton 4735
Stockyard 4703 4344
Susan River 4655
Blacksoil 4306
Crowley Vale 4342
Dalma 4702
Eskdale 4312
Fairymead 4670
Iveragh 4680
Kinkuna 4670
Pioneers Rest 4650
Rawbelle 4630
Tellebang 4630
Upper Freestone 4370
Valkyrie 4742
Vasa Views 4860
Barmoya 4703
Bony Mountain 4370
Garnant 4702
Mia Mia 4754
Mount Berryman 4341
Takilberan 4671
The Pines 4357
Walter Lever Estate 4856
Wildash 4370
Yuruga 4850
Butchers Creek 4885
Corndale 4610
Ingoldsby 4343
Lotus Creek 4705
McIntosh Creek 4570
Netherby 4650
Palm Grove 4800
Boigu Island 4875
Broxburn 4356
Causeway Lake 4703
Johnstown 4615
Munbura 4740
Ashwell 4340
Hookswood 4415
Lilyvale 4352 4723
Middlebrook 4886
Oxford 4742
Pierces Creek 4355
Rockmount 4344
Springside 4356
The Bluff 4340 4355
Undullah 4285
Upper Yarraman 4614
Ward 4470
Willowvale 4370
Woodlands 4343
Wyalla 4615
Bunya Creek 4655
Coolabine 4574
Cryna 4285
Dittmer 4800
Glen Esk 4312
Glenlyon 4380
Limestone Ridges 4305
Mount Binga 4314
Nahrunda 4570
South Yaamba 4702
Templin 4310
Veradilla 4347
West Point 4819
Beeron 4626
Brookhill 4816
Kalunga 4887
Kentville 4341
Tamrookum 4285
West Prairie 4403
Yandilla 4352
Googa Creek 4314
Gregors Creek 4313
Knapp Creek 4285
Palmtree 4352
Rossvale 4356
Stoneleigh 4356
Wunjunga 4806
Blythdale 4455
Coalbank 4352
Coles Creek 4570
Coochin Creek 4519
Doongul 4620
Germantown 4871
Hamilton Creek 4714
Hillview 4285
Lower Cowley 4871
Mabuiag Island 4875
Mount Debateable 4625
Shell Pocket 4855
Thinoomba 4650
Burnett Creek 4310
Currajah 4871
Djuan 4352
Fassifern Valley 4309
Glen Echo 4570
Inglestone 4422
Mount Tom 4677
Norwin 4356
Pikedale 4380
Rush Creek 4521
Woocoo 4620
Ghinghinda 4420
Scotchy Pocket 4570
Warroo 4387
Anthony 4310
Baking Board 4413
Brandy Creek 4800
Bymount 4455
Callide 4715
Cedarton 4514
Dangore 4610
Duckinwilla 4650
Gigoomgan 4620
Kalkadoon 4825
Kinleymore 4613
Minbun 4886
Philpott 4626
Warkon 4417
Chirnside 4723
Conway Beach 4800
Frazerview 4309
Gladfield 4370
Jinghi 4410
Junction View 4343
Kaban 4888
Limevale 4384
Mount Delaney 4514
Mount French 4310
Parknook 4417
Stonelands 4612
Theresa Creek 4721
Wyberba 4382
Cattle Creek 4626 4407
Chelona 4740
Ferny Glen 4275
Forest Ridge 4357
Fulham 4313
Neranwood 4213
Silverwood 4370
Taunton 4674
Walkers Point 4650
Westvale 4514
Ban Ban 4625
Beaver Rock 4650
Brightly 4741
Canningvale 4370
Diamondvale 4380
Kinnoul 4420
Kowguran 4415
O'Briens Hill 4860
O'Reilly 4275
Plainby 4355
Speedwell 4613
Stewart Creek Valley 4873
Damascus 4671
Goondi 4860
Manapouri 4361
Mp Creek 4606
Rossmoya 4702
Scrubby Creek 4570 4478
Wilson Beach 4800
Ballaroo 4455
Caffey 4343
Crinum 4723
Dalrymple Creek 4850
Dunnrock 4740
Friday Pocket 4855
Hirstglen 4359
Redgate 4605
Ryeford 4361
Andromache 4800
Belyando 4721
Boyneside 4610
Glenbar 4620
Joskeleigh 4702
Tabooba 4285
Thoopara 4800
Wangaratta 4806
Arcadia Valley 4454
Cromarty 4809
Downsfield 4570
Garners Beach 4852
Marys Creek 4570
Midgee 4702
Montrose 4413 4370
Moombra 4312
Mount Bindango 4455
Nine Mile 4702
North Aramara 4620
Rosalie Plains 4401
Alberta 4702
Barringha 4816
Campbells Pocket 4521
Castle Creek 4715
Coal Creek 4312
Cona Creek 4722
Ferney 4650
Kyoomba 4380
Lake Mary 4703
Sandringham 4701
Wallaces Creek 4310
Wyaga 4390
Allan 4370
Captains Mountain 4357
Gilla 4314
Glen Niven 4377
Goomeribong 4601
May Downs 4746
North Johnstone 4885
Warrami 4854
Wattlebank 4704
Woleebee 4419
Wooroonden 4605
Yarrol 4630
Billa Billa 4390
Coomrith 4422
Coorooman 4702
Frenches Creek 4310
Kooralgin 4402
Mungabunda 4718
Nangwee 4407
Oakdale 4605
Bergen 4353
Drillham South 4424
Ellinjaa 4886
Fishermans Pocket 4570
Gilberton 4208 4871
Glenarbon 4385
Mount Wyatt 4804
Mungalli 4886
O'Bil Bil 4626
Strathfield 4742
Teelba 4423
Terrica 4387
Thornville 4352
Wangetti 4877
Westmar 4422
Begonia 4487
Callandoon 4390
College View 4343
Dauan Island 4875
Derrymore 4352
Mount Luke 4352
Mulara 4703
Prince Of Wales 4875
Warnoah 4718
Wutul 4352
Beilba 4454
Blaxland 4405
Borallon 4306
Bringalily 4357
Cobraball 4703
Eurella 4462
Ficks Crossing 4606
Frankfield 4721
Gurulmundi 4415
Kagaru 4285
Lyra 4382
Mingoola 4380
Scrub Creek 4313
Walhallow 4462
Bogandilla 4425
Burgowan 4659
Crownthorpe 4605
Langlo 4470
Midgeree Bar 4852
Mount Hutton 4454
New Chum 4303
Oakview 4600
Passchendaele 4380
Punchs Creek 4357
Yenda 4625
Blackswamp 4413
Cameby 4413
Dirnbir 4625
Fairdale 4606
Gooroolba 4625
Llanarth 4820
Lyons 4124
Mooga 4455
Noccundra 4492
Sarabah 4275
Blantyre 4310
Boynedale 4680
Bukali 4630
Calgoa 4570
Cambridge 4822
Corella 4570
Evergreen 4352
Goolman 4306
Greenswamp 4413
Mount Edwards 4309
Redhill Farms 4671
Retro 4723
Silverleigh 4401
Somme 4382
Taragoola 4680
The Keppels 4700
Waugh Pocket 4871
Wheatvale 4370
Cania 4630
Cunningham 4370
Dykehead 4626
Ellinthorp 4362
Finnie 4350
Ginoondan 4625
Glenaubyn 4424
Mulgrave 4807
Roche Creek 4419
Skyring Reserve 4671
Split Yard Creek 4306
Tarawera 4494
Wilson Valley 4625
Barnard 4702
Cheeseborough 4702
Condamine Farms 4357
Daveson 4855
Foulden 4740
Gilbert River 4871
Iron Range 4892
Kents Lagoon 4309
Lilydale 4344
Long Flat 4570
Moregatta 4886
Mount McEuen 4606
North Bungunya 4494
Promisedland 4660
Rhydding 4718
Tabragalba 4285
Washpool 4306
Watalgan 4670
Bon Accord 4625
Boonarga 4413
Campbell Creek 4625
Damper Creek 4849
Glenaven 4355
Glengallan 4370
Jollys Lookout 4520
Marathon 4821
Mungy 4671
Ruby Creek 4380
Stewarton 4702
The Hermitage 4370
Wyuna 4723
Bella Creek 4570
Canal Creek 4702
Clarke Creek 4705
Colevale 4808
Elaman Creek 4552
Goldfields 4380
Lundavra 4390
McCutcheon 4856
Monal 4630
Mount Britton 4742
Palgrave 4374
Taldora 4823
Tarramba 4702
Valley Of Lagoons 4850
Victoria Hill 4361
Wealwandangie 4722
Wondalli 4390
Aldoga 4694
Cadarga 4413
Cynthia 4627
Formartin 4404
Kilbirnie 4354
Kulgun 4309
Malmoe 4627
Moreton Island 4025
Mount Mulligan 4871
Ottaba 4313
The Head 4373
Watsons Crossing 4385
Wilsons Plains 4307
Woondum 4570
Yuleba South 4427
Boodua 4401
Gairloch 4850
Gordonstone 4702
Maadi 4855
Marshlands 4611
Moraby 4416
Mount Barney 4287
Mount Pluto 4800
Old Talgai 4362
Pinevale 4754
Wycarbah 4702
Canning Creek 4357
Coondoo 4570
Eaton 4860
Gore 4352
Gurgeena 4626
Harrami 4630
Kelvinhaugh 4401
Newlands 4804
Old Cooranga 4626
Oyster Creek 4674
The Glen 4370
Ulogie 4702
Wattle Ridge 4357
Wycombe 4455
Bonshaw 4385
Branchview 4352
Como 4571
Evanslea 4356
Fifteen Mile 4352
Jellinbah 4702
Macfarlane 4478
Merritts Creek 4352
Pelican 4413
Springvale 4405
Tregony 4370
Weir River 4406
Cannindah 4630
Consuelo 4702
Doughboy 4671
Eurombah 4420
Glen Russell 4880
Glenleigh 4630
Jaffa 4855
Narko 4352
Pilerwa 4650
Sandy Pocket 4871
Selene 4630
Undercliffe 4380
Widgee Crossing South 4570
Abbeywood 4613
Abbotsford 4670
Albinia 4722
Bakers Bend 4470
Barlil 4605
Belcong 4723
Broadmere 4420
Fleurbaix 4375
Glenrock 4605
Goolboo 4856
Nukku 4314
Oombabeer 4718
Ringwood 4343
Sunny Nook 4605
Yalangur 4352
Yargullen 4401
Yulabilla 4416
Brovinia 4626
Bushley 4702
Durham Downs 4454
Dutton River 4821
East Haldon 4343
England Creek 4306
Kitoba 4605
Lark Hill 4306
Mount Tabor 4370
Ross Creek 4570
Toolburra 4370
Wills 4829
Wychie 4412
Auburn 4413
Bayrick 4478
Glenmoral 4719
Goowarra 4702
Gowrie Little Plain 4352
Mount Stuart 4811
Prawle 4650
Splinter Creek 4630
St Agnes 4671
Thane 4370
Buckland 4722
Bungaban 4419
Doctor Creek 4352
Gemini Mountains 4721
Jardine 4702
Malarga 4620
Mount Darry 4353
Nebine 4488
Porcupine 4821
Rodgers Creek 4370
Widgeegoara 4490
Windeyer 4478
Woolooman 4310
Beenaam Valley 4570
Budgee 4359
Burleigh 4822
Cement Mills 4352
Glenfern 4515
Grapetree 4352
Lake Manchester 4306
Mount Enniskillen 4472
Pasha 4721
Perseverance 4352
Roundstone 4718
The Mine 4714
Thompson Point 4702
Banks Creek 4306
Elgin Vale 4615
Givelda 4670
Gungaloon 4620
Kragra 4413
Lynam 4818
Malling 4352
Mimosa 4702
Missen Flat 4361
Mudlo 4600
Noorama 4490
Sommariva 4470
Toonpan 4816
Tyrconnel 4467
Wiyarra 4370
Black Duck Creek 4343
Byee 4605
Devon Park 4401
Lake Wivenhoe 4311
Moondooner 4605
Neumgna 4614
Neusa Vale 4570
Tamrookum Creek 4285
Upper Pinelands 4355
Weribone 4417
Widgee Crossing North 4570
Woodbine 4343
Binna Burra 4211
Bundi 4419
Cherry Creek 4314
Cowley Creek 4871
Glebe 4420
Goombi 4413
Leafdale 4606
Mount Steadman 4625
Muniganeen 4352
Myall Park 4415
Radford 4307
Silver Creek 4800
Trotter Creek 4714
Yandarlo 4478
Burton 4742
Caroline Crossing 4477
Chinghee Creek 4285
Collaroy 4707
Forestvale 4465
Goorganga Creek 4800
Melawondi 4570
Mon Repos 4670
The Limits 4625
White Mountain 4352
Woolmer 4352
Bingegang 4702
Calingunee 4390
Cape Hillsborough 4740
Clara Creek 4468
Cressbrook Creek 4355
Danderoo 4370
Darr Creek 4410
East Cooyar 4353
Enoggera Reservoir 4520
Finlayvale 4873
Glenhaughton 4420
Hutton Creek 4454
Kingaham 4515
Maalan 4886
Nandowrie 4722
Nevilton 4361
Oberina 4417
Rockside 4343
Rocky Creek 4357
Springdale 4380
Stockhaven 4625
Upper Cooyar Creek 4402
Wateranga 4621
Western Creek 4357
Bargunyah 4465
Coominglah 4630
Dunmore 4407
Flying Fox 4275
Gindoran 4676
Glenroy 4702
Greycliffe 4715
Humphery 4625
Kawl Kawl 4612
Kents Pocket 4310
Melrose 4613
Minnamoolka 4872
Waraba 4513
Wigton 4612
Womblebank 4465
Aranbanga 4625
Cobbs Hill 4605
Cockatoo 4419
Comoon Loop 4858
Harriet 4625
Highgrove 4352
Humboldt 4702
Marodian 4570
Mungallala South 4467
Nine Mile Creek 4714
Nutgrove 4352
Seventeen Mile 4344
Stockton 4871
Thornton Beach 4873
Tipton 4405
Breadalbane 4800
Coorumbene 4702
Gilldora 4570
Goomally 4702
Grays Gate 4357
Grosvenor 4627
Kairabah 4207
Lake Borumba 4570
Lansdowne 4478
Linden 4490
Morinish South 4702
Mosquito Creek 4387
Pauls Pocket 4800
Southedge 4871
Wallaroo 4702
Whichello 4352
Carbine Creek 4723
Cornwall 4455
Glen Boughton 4871
Gowrie Station 4470
Greenwood 4401
Jones Gully 4355
Lanskey 4825
Lilywood 4513
Maidenhead 4385
Malpas-Trenton 4816
Mountain Camp 4355
Nive 4477
Wooroona 4702
Ban Ban Springs 4625
Boatman 4468
Buaraba South 4311
Byellee 4680
Clifford 4427
Coongoola 4490
Dundarrah 4625
Granite Vale 4815
Gunyarra 4800
Humeburn 4490
Keysland 4612
Kindon 4390
Lawes 4343
Lower Cressbrook 4313
Marmadua 4405
Mona Mona 4881
Mount Walker West 4340
Rewan 4702
Ugar Island 4875
V Gate 4465
Ventnor 4630
Warnung 4605
Wivenhoe Hill 4311
Cutella 4352
Cuttaburra 4490
Greenup 4387
Hazledean 4741
Kurrowah 4352
Laglan 4721
Langlands 4410
Mount Macarthur 4723
Togara 4702
Yimbun 4313
Barramornie 4416
Cheltenham 4627
Coomoo 4702
Gunpowder 4825
Gwambegwine 4420
Lowestoff 4723
Millwood 4357
Mount Irving 4401
Pony Hills 4454
The Dimonds 4650
Upper Wheatvale 4370
Vinegar Hill 4343
Egypt 4344
Fassifern 4309
Lowesby 4702
Malu 4403
Mantuan Downs 4722
Mount Gipps 4285
Rangemore 4352 4806
Bindebango 4488
Boulder Creek 4714
Bybera 4387
Crystal Creek 4816
Epsom 4741
Fork Lagoons 4723
Kilmorey Falls 4465
Kioma 4498
Merryvale 4340
Mount Emlyn 4357
Mount Lindesay 4287
Nangram 4416
Nearum 4671
Oakey Creek 4714
Pelham 4415
St Aubyn 4352
Tuan Forest 4650
Woolgar 4822
Alsace 4702
Belmunda 4740
Cooladdi 4479
Coral Sea 4740
Hail Creek 4742
Morwincha 4309
Mount Sturt 4370
Pikes Creek 4380
Riversleigh 4470
Balcomba 4702
Beelbee 4405
Calcium 4816
Elgin 4721
Gunnawarra 4872
Halliford 4406
Lake Monduran 4671
Motley 4356
Mount Gardiner 4705
Orient 4850
Swans Lagoon 4807
Walmul 4714
Baroondah 4420
Barringun 4490
Kemmis 4742
Lemontree 4357
Leslie 4370
Lynford 4342
Peak Vale 4721
Pile Gully 4625
Port Alma 4699
Stokes 4823
Amosfield 4380
Argyll 4721
Bulli Creek 4357
Cherwell 4660
Mount Howe 4454
Mount Moffatt 4465
No 5 Branch 4856
Riverton 4385
Rywung 4413
Upper Warrego 4477
Waikola 4420
Wainui 4404
Walliebum 4655
Woolshed 4340
Boonooroo Plains 4650
Cardstone 4854
Commissioners Flat 4514
Cooeeimbardi 4313
Coominglah Forest 4630
Deep Creek 4625
Fisher 4825
Florence Bay 4819
Jobs Gate 4490
Koombooloomba 4872
Lavelle 4357
Minnie Downs 4478
Shelburne 4874
Toondahra 4625
Tuen 4490
Yarraden 4892
Caboonbah 4312
Cherry Gully 4370
Clemant 4816
Dromedary 4718
Lake Proserpine 4800
Pine Hills 4416
Quetta 4724
Ranken 4825
Redford 4467
Rungoo 4849
Sujeewong 4413
Yagaburne 4390
Coorada 4420
Lumeah 4478
Molangul 4671
Mount Lawless 4625
Murrumba 4312
Purrawunda 4356
Sabine 4401
Southern Moreton Bay Islands 4208
Spring Bluff 4352
Tandora 4650
Town Common 4810
Upper Dawson 4454
Wura 4714
Barkly 4825
Blairmore 4625
Diamantina Lakes 4735
Leydens Hill 4714
Lyndhurst 4871
Macalister Range 4871
Mount Moriah 4403
Winchester 4721
Woolein 4702
Cameron Corner 4492
Domville 4357
Eaglefield 4742
Fletcher Creek 4714
Greenlake 4701
Inskip 4581
Langley 4630
Limestone 4714
North Maclagan 4352
The Common 4701
Baffle West 4454
Balgowan 4401
Broken River 4757
Caldervale 4478
Durah 4413
Eungella Dam 4757
Great Sandy Strait 4655
Johnsons Hill 4714
Lake Tinaroo 4872
Lakefield 4892
Mentmore 4798
Silverbark Ridge 4124
Wonbah Forest 4671
Barakula 4413
Bundoora 4723
Kings Siding 4401
Murweh 4470
Wagtail Grove 4513
Warenda 4829
Westgrove 4454
Yagoonya 4892
Bauple Forest 4650
Ellis Beach 4879
Farrars Creek 4481
Goorganga Plains 4800
Lawn Hill 4825
Simmie 4454
Suttor 4743
Toolara Forest 4570
Turrawulla 4742
Wenlock 4874
Dalga 4630
Gamboola 4892
Hurricane 4871
Jackson South 4426
Punsand 4876
Saxby 4822
Waverley 4825
West Wellesley Islands 4892
Archer River 4892
Barlyne 4625
Carnarvon Park 4702
Claraville 4871
Conjuboy 4871
Cooroo Lands 4860
Djiru 4852
Eurimbula 4677
Four Ways 4824
Green Island 4871
Mount Rooper 4802
Penwhaupell 4625
Weipa Airport 4874
Wrattens Forest 4601
Basilisk 4871
Blackbull 4871
Boondandilla 4406
Crystalbrook 4871
Desailly 4871
Eight Mile Creek 4807
Eungella Hinterland 4741
Howitt 4890
Kooroomool 4854
Min Min 4829
Savannah 4816
Warburton 4823
Welsby 4507
Arbouin 4892
Bellevue 4892
Blue Hills 4818
Bulloo Downs 4492
Cape Conway 4800
Carrandotta 4825
Coralie 4871
Corymbia 4513
Cotherstone 4723
Dixie 4892
Fitzroy Island 4871
Forty Mile 4872
Garrawalt 4850
Girraween 4382
Grassdale 4405
Groganville 4892
Lamb Range 4870
Maramie 4892
Moreton Bay 4178
Mount Elliot 4816
Ngatjan 4860
Northhead 4871
Palmerston 4860
Rookwood 4871
The Narrows 4695
Wahoon 4625
Wallaman 4850
Walter Hill 4854
Woodleigh 4352
Wrotham 4892
Amaroo 4829
Amber 4871
Barron Gorge 4870
Bolwarra 4871
Dagmar 4873
Flinders Lakes 4285
Fossilbrook 4871
Holroyd River 4892
Lyndside 4892
Mamu 4871
Mount Mackay 4854
Munderra 4872
Nychum 4871
Somerset 4876
Starcke 4895
Sturt 4829
Tanbar 4481
The Percy Group 4707
Wanjuru 4860
Woondul 4357
Wooroonooran 4860
Barwidgi 4872
Carpentaria 4823
Cooloola 4580
Gadgarra 4884
Greenstone 4513
Highbury 4892
Lumholtz 4849
Murray 4814
Nicholson 4830
Noah 4873
Southern Lamington 4211
Strathmore 4871
Tam O'Shanter 4852
Toko 4829
Wharps 4850`
