/**
 * Every suburb and locality in South Australia (SA) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Adelaide 5000
Mount Gambier 5290
Morphett Vale 5162
Mount Barker 5251
Port Lincoln 5606
Murray Bridge 5253
Prospect 5082
Parafield Gardens 5107
Mawson Lakes 5095
Paralowie 5108
Seaton 5023
Norwood 5067
Aldinga Beach 5173
North Adelaide 5006
Campbelltown 5074
Magill 5072
Hallett Cove 5158
Port Augusta 5700
Happy Valley 5159
Salisbury 5108
Golden Grove 5125
Salisbury North 5108
Aberfoyle Park 5159
Ingle Farm 5098
Hope Valley 5090
Woodcroft 5162
Encounter Bay 5211
Victor Harbor 5211
Salisbury East 5109
Strathalbyn 5255
Findon 5023
Glenelg North 5045
Nuriootpa 5355
Athelstone 5076
Naracoorte 5271
Craigmore 5114
Pooraka 5095
Glenelg 5045
West Lakes 5021
Greenwith 5125
Flagstaff Hill 5159
Whyalla Norrie 5608
Rostrevor 5073
Whyalla Stuart 5608
Andrews Farm 5114
Modbury 5092
Somerton Park 5044
Blakeview 5114
Christies Beach 5165
Paradise 5075
Klemzig 5087
Wynn Vale 5127
Henley Beach 5022
Millicent 5280
Wallaroo 5556
Davoren Park 5113
Munno Para West 5115
Plympton 5038
Mitchell Park 5043
Edwardstown 5039
Renmark 5341
Grange 5022
North Haven 5018
Enfield 5085
Angle Vale 5117
Lightsview 5085
Fulham Gardens 5024
Kilburn 5084
Munno Para 5115
Warradale 5046
Modbury Heights 5092
Parkside 5063
Para Hills 5096
Loxton 5333
Tanunda 5352
Windsor Gardens 5087
Salisbury Downs 5108
Oaklands Park 5046
Berri 5343
Brooklyn Park 5032
Highbury 5089
Newton 5074
Christie Downs 5164
Gawler East 5118
Unley 5061
Valley View 5093
Lockleys 5032
Blair Athol 5084
Glengowrie 5044
Mannum 5238
West Beach 5024
Mile End 5031
Ridgehaven 5097
Moonta Bay 5558
South Plympton 5038
Burton 5110
Flinders Park 5025
Modbury North 5092
Broadview 5083
Seaford Rise 5169
McLaren Vale 5171
Torrensville 5031
Sheidow Park 5158
Hectorville 5073
Nairne 5252
Fullarton 5063
Semaphore Park 5019
Seaford 5169
Blackwood 5051
Clare 5453
Port Augusta West 5700
Elizabeth Downs 5113
Port Pirie South 5540
Holden Hill 5088
Port Adelaide 5015
Whyalla 5600
Reynella 5161
Brighton 5048
Brompton 5007
Robe 5276
Marion 5043
Coober Pedy 5723
Glenelg East 5045
Camden Park 5038
Richmond 5033
Ascot Park 5043
Croydon Park 5008
Redwood Park 5097
St Agnes 5097
North Plympton 5037
Bordertown 5268
Risdon Park 5540
Goolwa 5214
Seaford Meadows 5169
Elizabeth East 5112
Kadina 5554
Hackham 5163
Tranmere 5073
Clearview 5085
Waikerie 5330
Port Pirie West 5540
Roxby Downs 5725
Woodville West 5011
Two Wells 5501
Northfield 5085
Port Elliot 5212
Morphettville 5043
Gilles Plains 5086
Largs North 5016
Glenside 5065
Hindmarsh Island 5214
Largs Bay 5016
Ferryden Park 5010
Para Hills West 5096
Elizabeth Vale 5112
Kapunda 5373
Elizabeth North 5113
Barmera 5345
Noarlunga Downs 5168
Hillbank 5112
Royal Park 5014
Willaston 5118
Elizabeth Park 5113
Goodwood 5034
Wingfield 5013
Mansfield Park 5012
Belair 5052
Normanville 5204
Rosewater 5013
Kurralta Park 5037
Old Reynella 5161
Huntfield Heights 5163
Salisbury Heights 5109
Taperoo 5017
West Croydon 5008
Plympton Park 5038
Dernancourt 5075
Kingscote 5223
Park Holme 5043
Marden 5070
Hackham West 5163
Kidman Park 5025
St Marys 5042
Moana 5169
Port Noarlunga 5167
Walkerville 5081
Virginia 5120
Hove 5048
Seacombe Gardens 5047
Evanston Park 5116
Tea Tree Gully 5091
Pennington 5013
Goolwa Beach 5214
Lonsdale 5160
Woodside 5244
Semaphore 5019
Coromandel Valley 5051
Hillcrest 5086
Woodville South 5011
Gawler South 5118
Sellicks Beach 5174
Dover Gardens 5048
Payneham 5070
Elizabeth South 5112
Hayborough 5211
Greenacres 5086
Stirling 5152
Oakden 5086
Bowden 5007
St Clair 5011
Bridgewater 5155
St Peters 5069
Kent Town 5067
Glandore 5037
Henley Beach South 5022
Smithfield Plains 5114
West Lakes Shore 5020
Glenelg South 5045
Tumby Bay 5605
Pasadena 5042
Whyalla Playford 5600
Streaky Bay 5680
Port Noarlunga South 5167
Middleton 5213
Peterborough 5422
Smithfield 5114
Myrtle Bank 5064
Evanston 5116
Fairview Park 5126
Felixstow 5070
Clovelly Park 5042
Sturt 5047
Fulham 5024
Quorn 5433
Glynde 5070
Brahma Lodge 5109
Melrose Park 5039
Hahndorf 5245
Woodville Gardens 5012
Surrey Downs 5126
Thebarton 5031
Aldgate 5154
Littlehampton 5250
McCracken 5211
Lewiston 5501
Angaston 5353
Daw Park 5041
Gulfview Heights 5096
Lobethal 5241
South Brighton 5048
Para Vista 5093
Woodville North 5012
Kingston Se 5275
Burnside 5066
Kensington Gardens 5068
Banksia Park 5091
Underdale 5032
Jamestown 5491
Marleston 5033
Tailem Bend 5260
Ottoway 5013
Walkley Heights 5098
Penola 5277
Williamstown 5351
Balaklava 5461
Clarence Park 5034
Torrens Park 5062
Malvern 5061
O'Halloran Hill 5158
Hawthorndene 5051
Ceduna 5690
Seacliff Park 5049
Wayville 5034
Toorak Gardens 5065
Stirling North 5710
Craigburn Farm 5051
Kensington 5068
Eden Hills 5050
Keith 5267
Kilkenny 5009
Woodville 5011
Willunga 5172
Colonel Light Gardens 5041
Kensington Park 5068
Port Broughton 5522
Freeling 5372
Cumberland Park 5041
Queenstown 5014
Elizabeth Grove 5112
Evanston Gardens 5116
Beverley 5009
Seacliff 5049
Vale Park 5081
Trott Park 5158
Port Willunga 5173
Bellevue Heights 5050
Crystal Brook 5523
Kingswood 5062
Cheltenham 5014
Hyde Park 5061
Goolwa South 5214
North Brighton 5048
Alberton 5014
Novar Gardens 5040
Cowell 5602
Nailsworth 5083
Beaumont 5066
Northgate 5085
Hawthorn 5062
Allenby Gardens 5009
Risdon Park South 5540
Athol Park 5012
Seaview Downs 5049
Burra 5417
Black Forest 5035
Salisbury Plain 5109
Panorama 5041
Lyndoch 5351
Maitland 5573
Stepney 5069
Ardrossan 5571
Meningie 5264
Osborne 5017
Glenunga 5064
Elizabeth 5112
Clarence Gardens 5039
Linden Park 5065
O'Sullivan Beach 5166
Westbourne Park 5041
Onkaparinga Hills 5163
Hewett 5118
Salisbury Park 5109
Albert Park 5014
Goolwa North 5214
Hampstead Gardens 5086
Netley 5037
Port Vincent 5581
Dulwich 5065
Coffin Bay 5607
Gilberton 5081
Marino 5049
Tonsley 5042
Lower Mitcham 5062
Yorketown 5576
Birkenhead 5015
Hazelwood Park 5066
Mitcham 5062
Whyalla Jenkins 5609
Renown Park 5008
Riverton 5412
Reynella East 5161
Payneham South 5070
New Port 5015
Angle Park 5010
Firle 5070
Lameroo 5302
Woodville Park 5011
Port Hughes 5558
Crafers 5152
Meadows 5201
Seaford Heights 5169
Port Macdonnell 5291
Minlaton 5575
Maylands 5069
Carrickalinga 5204
Leabrook 5068
North Beach 5556
Roseworthy 5371
Gawler 5118
Solomontown 5540
Collinswood 5081
Ashford 5035
Balhannah 5242
Ethelton 5015
Millswood 5034
Glen Osmond 5064
St Morris 5068
West Hindmarsh 5007
Beulah Park 5067
Cleve 5640
Beachport 5280
Hindmarsh 5007
Rose Park 5067
Woomera 5720
Forestville 5035
Morgan 5320
Milang 5256
Glenalta 5052
Pinnaroo 5304
Old Noarlunga 5168
Highgate 5063
Bedford Park 5042
Ridleyton 5008
Wattle Park 5066
Renmark West 5341
Mount Compass 5210
Moonta 5558
Cowandilla 5033
Riverlea Park 5120
Evandale 5069
Edithburgh 5583
Everard Park 5035
Keswick 5035
Hendon 5014
Eudunda 5374
Macclesfield 5153
Maslin Beach 5170
Murray Bridge East 5253
Eyre 5121
Auburn 5451
Andamooka 5722
Stansbury 5582
Gladstone 5473
Eastwood 5063
Welland 5007
McLaren Flat 5171
Unley Park 5061
Kimba 5641
Birdwood 5234
Monash 5342
Peterhead 5016
St Georges 5064
Blanchetown 5357
Devon Park 5008
Cummins 5631
Tusmore 5065
Yankalilla 5203
Exeter 5019
Clapham 5062
Waterloo Corner 5110
Mount Pleasant 5235
Laura 5480
Tennyson 5022
Rosslyn Park 5072
Port Wakefield 5550
New Town 5554
Clayton Bay 5256
Croydon 5008
Worrolong 5291
Paringa 5340
Sefton Park 5083
Manningham 5086
Hilton 5033
Port Victoria 5573
Glossop 5344
Trinity Gardens 5068
Darlington 5047
Point Turton 5575
Royston Park 5070
American River 5221
Greenock 5360
Mallala 5502
Wilmington 5485
Seacombe Heights 5047
Lucindale 5272
Hamley Bridge 5401
Boston 5607
Hillier 5116
Crafers West 5152
Gepps Cross 5094
Netherby 5062
Kersbrook 5231
Booleroo Centre 5482
Snowtown 5520
Marion Bay 5575
Semaphore South 5019
Gawler West 5118
Regency Park 5010
Woodforde 5072
Saddleworth 5413
Orroroo 5431
Chiton 5211
Callington 5254
West Richmond 5033
Port Pirie 5540
Fisherman Bay 5522
Mylor 5153
Cape Jervis 5204
Wellington East 5259
Joslin 5070
Tantanoola 5280
Port Germein 5495
Loxton North 5333
Noarlunga Centre 5168
Wirrabara 5481
Dry Creek 5094
Leigh Creek 5731
Karoonda 5307
Echunga 5153
Wudinna 5652
Kalangadoo 5278
Compton 5291
Hawker 5434
Suttontown 5291
Oakbank 5243
Erindale 5066
Hindmarsh Valley 5211
North Moonta 5558
Stonyfell 5066
Penneshaw 5222
Dudley Park 5008
Ovingham 5082
Frewville 5063
Younghusband 5238
Kangarilla 5157
Tintinara 5266
Direk 5110
Medindie 5081
Aldinga 5173
Warooka 5577
Elliston 5670
Mount Torrens 5244
Truro 5356
Hackney 5069
Gumeracha 5233
Sunlands 5322
Glanville 5015
Napperby 5540
Riverglades 5253
Urrbrae 5064
Evanston South 5116
Vista 5091
Clinton 5570
Springton 5235
Upper Sturt 5156
Port Neill 5604
Owen 5460
Blyth 5462
Wasleys 5400
One Tree Hill 5114
Cadell 5321
Gawler Belt 5118
Myponga 5202
Swan Reach 5354
Teringie 5072
Black Point 5571
Loveday 5345
Gillman 5013
Arno Bay 5603
College Park 5069
Glencoe 5291
Melrose 5483
Terowie 5421
Heathfield 5153
Renmark North 5341
Coobowie 5583
Cavan 5094
Yahl 5291
Coonalpyn 5265
Langhorne Creek 5255
Marryatville 5068
Thevenard 5690
Nildottie 5238
Mypolonga 5254
Bute 5560
Kanmantoo 5252
Penfield 5121
Salisbury South 5106
Summertown 5141
Hardwicke Bay 5575
Moorak 5291
Cambrai 5353
Kings Park 5034
Onkaparinga Heights 5163
Second Valley 5204
Nangwarry 5277
Tarpeena 5277
Mundulla 5270
Clarendon 5157
Dublin 5501
Thompson Beach 5501
Bowhill 5238
Curramulka 5580
Walker Flat 5238
Kingston Park 5049
Wallaroo Mines 5554
Padthaway 5271
Sedan 5353
Norton Summit 5136
Chandlers Hill 5159
Smoky Bay 5680
Southend 5280
Farrell Flat 5416
Iron Knob 5611
Balgowan 5573
Uraidla 5142
Minnipa 5654
Allendale East 5291
Currency Creek 5214
Fitzroy 5082
Watervale 5452
Wool Bay 5575
Lipson 5607
Lock 5633
Mile End South 5031
Corny Point 5575
Ob Flat 5291
Island Beach 5222
Tarlee 5411
Spalding 5454
Stanley Flat 5453
Penong 5690
Port Moorowie 5576
Brinkworth 5464
Edinburgh 5111
Kingston On Murray 5331
The Pines 5577
Wirrina Cove 5204
Penrice 5353
Lenswood 5240
Wolseley 5269
White Sands 5253
Cobdogla 5346
Cockatoo Valley 5351
Waitpinga 5211
Robertstown 5381
Nepean Bay 5223
Tungkillo 5236
Edinburgh North 5113
Kudla 5115
Auldana 5072
Georgetown 5472
Hallett 5419
Inman Valley 5211
Lower Inman Valley 5211
Redhill 5521
Charleston 5244
Heathpool 5068
Rowland Flat 5352
Eden Valley 5235
Lyrup 5343
Wangary 5607
Houghton 5131
Narrung 5259
Tickera 5555
Finniss 5255
Rockleigh 5254
Stockwell 5355
Ashton 5137
Golden Heights 5322
Macdonald Park 5121
Wellington 5259
Jerusalem 5554
Paskeville 5552
Tiddy Widdy Beach 5571
Outer Harbor 5018
Sellicks Hill 5174
Koolunga 5464
Mintaro 5415
Jervois 5259
Pinks Beach 5275
Winkie 5343
North Shields 5607
Taylorville 5330
Green Fields 5107
Halbury 5461
Stockport 5410
Harrogate 5244
Flaxman Valley 5235
Keyneton 5353
Mount Burr 5279
Cherry Gardens 5157
Marree 5733
Coonawarra 5263
Glenburnie 5291
Renmark South 5341
Yacka 5470
Coorong 5264
Cooltong 5341
Rosetown 5275
Commissariat Point 5700
Murbko 5320
Rendelsham 5280
Mil-Lel 5291
Adelaide Airport 5950
Tiatukia 5607
Carey Gully 5144
Parham 5501
Springfield 5062
Brownlow Ki 5223
Price 5570
Willunga South 5172
Donovans 5291
Brukunga 5252
Furner 5280
Manoora 5414
Booborowie 5417
Pekina 5431
Cape Jaffa 5275
Point Boston 5607
Hatherleigh 5280
Forreston 5233
Globe Derby Park 5110
Lochaber 5271
Armagh 5453
Vivonne Bay 5223
Port Julia 5580
Alford 5555
Mount Benson 5275
Weeroona Island 5495
Parilla 5303
Montacute 5134
Venus Bay 5607
Greenhill 5140
Paracombe 5132
Farina 5731
Mundoora 5555
Coulta 5607
Emu Bay 5223
Hynam 5262
Baudin Beach 5222
Penfield Gardens 5121
Port Mannum 5238
Fisher 5354
Munno Para Downs 5115
Ashbourne 5157
Appila 5480
Punyelroo 5353
Humbug Scrub 5114
Caltowie 5490
Pine Point 5571
Mount Schank 5291
James Well 5571
Mount Osmond 5064
Cudlee Creek 5232
Lochiel 5510
Wyomi 5275
Carrieton 5432
Kalbeeba 5118
Moonta Mines 5558
Ironbank 5153
Lower Light 5501
Upper Hermitage 5131
Warnertown 5540
Basket Range 5138
Kongorong 5291
Marrabel 5413
Blewitt Springs 5171
Foul Bay 5577
Northern Heights 5253
Chaffey 5341
Joanna 5271
Piccadilly 5151
Carpenter Rocks 5291
Palmer 5237
Pukatja 0872
Moculta 5353
Reid 5118
Cowirra 5238
Light Pass 5355
Mount Bryan 5418
Sandy Creek 5350
Eight Mile Creek 5291
Moorook 5332
Ceduna Waters 5690
Forest Range 5139
Mullaquana 5608
Rhynie 5412
Uleybury 5114
Caloote 5254
Inglewood 5133
Monarto South 5254
Blinman 5730
Whites Valley 5172
Arthurton 5572
Mingbool 5291
Pelican Point 5291
Hoyleton 5453
Korunye 5502
Highland Valley 5255
Coromandel East 5157
Kanyaka 5434
Totness 5250
Hamilton 5373
Monbulla 5277
Wirrulla 5661
Murtho 5340
Sceale Bay 5680
Darke Peak 5642
Moorook South 5332
Rudall 5642
Skye 5072
Wistow 5251
Oodnadatta 5734
Tooperang 5255
Woods Point 5253
Lucky Bay 5602
Warramboo 5650
Willyaroo 5255
Sevenhill 5453
Tarcowie 5431
Cannawigara 5268
Medindie Gardens 5081
Verdun 5245
Haines 5223
Frances 5262
Blakiston 5250
Bolivar 5110
Bookpurnong 5333
Bradbury 5153
Dutton 5356
Peake 5301
Ungarra 5607
Bowmans 5550
Parafield 5106
Yongala 5493
Reedy Creek 5275
Blackfellows Caves 5291
Copley 5732
Delamere 5204
Denial Bay 5690
Nelshaby 5540
Port Kenny 5671
Woodchester 5255
Yatala Vale 5126
Caurnamont 5238
Flinders Ranges 5434
Redbanks 5502
Yaninee 5653
Avenue Range 5273
Back Valley 5211
Eurelia 5431
Kuitpo 5201
Wandilo 5291
Cradock 5432
Gould Creek 5114
St Kilda 5110
Cassini 5223
Kangaroo Flat 5118
Sunnybrae 5422
Whyte Yarcowie 5420
Wisanger 5223
Bugle Ranges 5251
Beltana 5730
Gulnare 5471
Marks Landing 5354
Monarto 5254
Mount Light 5271
Bower 5374
Dawesley 5252
Glenroy 5277
Sultana Point 5583
Cross Roads 5558
Keilira 5275
Mount George 5155
Ramco Heights 5322
Perlubie 5680
Wild Dog Valley 5271
Bibaringa 5118
Long Flat 5253
Cockburn 5440
Kybybolite 5262
Middle Beach 5501
Wangolina 5275
Amata 0872
Maaoupe 5277
Yattalunga 5114
Penwortham 5453
East Moonta 5558
Geranium 5301
Mount Dutton Bay 5607
Conmurra 5272
Mannanarie 5422
Crescent 5341
Ebenezer 5355
Parrakie 5301
Louth Bay 5607
Poochera 5655
Ramco 5322
Ramsay 5575
Windsor 5501
Fowlers Bay 5690
Koppamurra 5271
Mount Mary 5374
Pyap 5333
Wynarka 5306
Holder 5330
Marla 5724
Nene Valley 5291
Point Pass 5374
Poonindie 5607
Stewart Range 5271
Woodlane 5254
Kenton Valley 5233
Nangkita 5210
Paris Creek 5201
Swanport 5253
Hammond 5431
Paisley 5357
Parndana 5220
Scott Creek 5153
Shea-Oak Log 5371
Sherlock 5301
Templers 5371
Alawoona 5311
Burrungule 5291
Edillilie 5630
Sunnyside 5253
Boatswain Point 5275
Butler 5605
Hartley 5255
Tarcoola 5701
Waterloo 5413
Wye 5291
Burdett 5253
Condowie 5464
Sheringa 5607
Tatachilla 5171
Myponga Beach 5202
Rosedale 5350
Whyalla Barson 5601
Wongulla 5238
Yallunda Flat 5607
Yalata 5690
Binnum 5262
Concordia 5118
Mount McIntyre 5279
Alma 5401
Brenda Park 5320
Kyancutta 5651
Rocky Camp 5280
Seppeltsfield 5355
Wandearah East 5523
Ward Belt 5118
Willalooka 5267
Leighton 5417
Brinkley 5253
Mimili 0872
Wanbi 5310
Black Hill 5353
Wild Horse Plains 5501
Bray 5276
Brownlow 5374
Iwantja 0872
Leasingham 5452
Parsons Beach 5575
Pinery 5460
Reeves Plains 5502
Barabba 5460
Kielpa 5642
Kybunga 5453
Moyhall 5271
Seddon 5223
Wattle Range 5280
Bramfield 5670
Coorabie 5690
Koppio 5607
Sandy Grove 5275
Beaufort 5550
Jupiter Creek 5153
Kainton 5552
Miranda 5700
Monteith 5253
Pinkawillinie 5641
Buchfelde 5118
Haslam 5680
Koolywurtie 5575
Rocky Gully 5254
Wauraltee 5573
Western Flat 5268
Cromer 5235
Kaltjiti 0872
Macgillivray 5223
Lynton 5062
Port Rickaby 5575
Telowie 5540
Bethany 5352
Fox 5272
Tulka 5607
Bagot Well 5373
Bethel 5373
Coomandook 5261
Dudley East 5222
Hilltown 5455
Pata 5333
Allendale North 5373
Nantawarra 5550
Agery 5558
Point Souttar 5577
Wanilla 5607
Copeville 5308
Koonibba 5690
Longwood 5153
Matta Flat 5554
Pinkerton Plains 5400
Yunta 5440
Beetaloo Valley 5523
Emu Downs 5381
Mount Bryan East 5419
Mount Crawford 5351
Pages Flat 5172
Pelican Lagoon 5222
Sandilands 5571
Steinfeld 5356
Wunkar 5311
Yeelanna 5632
Sandalwood 5309
Wall Flat 5254
Parawa 5203
Paruna 5311
Point Pearce 5573
Bool Lagoon 5271
Mount Jagged 5211
Port Paterson 5700
Thornlea 5280
Verran 5603
Hindmarsh Tiers 5202
Ucolta 5422
Baroota 5495
Buckleboo 5641
Cockaleechie 5631
Marcollat 5271
Sandergrove 5255
Sunnydale 5353
Altona 5351
Cape Douglas 5291
Meribah 5311
Overland Corner 5330
Taratap 5275
Willowie 5431
Greenways 5272
Minvalara 5422
Sheaoak Flat 5581
Willochra 5433
Belalie North 5491
Belvidere 5255
Buckland Park 5120
Lower Hermitage 5131
Moockra 5432
Prospect Hill 5201
Spring Farm 5453
Belalie East 5491
Bungama 5540
Coles 5272
Wepar 5278
Bull Creek 5157
Davenport 5700
German Flat 5280
Honiton 5576
Keppoch 5271
Marama 5307
Paechtown 5245
Ponde 5238
Senior 5268
Wattle Flat 5203
Black Springs 5413
Boors Plain 5554
Coonamia 5540
Fords 5373
Karatta 5223
Neales Flat 5374
Perponda 5308
Hill River 5453
Pine Hill 5269
Belton 5432
Ettrick 5253
Menzies 5223
Woolumbool 5272
Cooke Plains 5261
Cygnet River 5223
Kulpara 5552
Pipalyatjara 0872
Borrika 5309
Flaxley 5153
Kelly 5641
Sanderston 5237
Taplan 5311
Westall 5680
Magdala 5400
Mindarie 5309
Murray Bridge South 5253
Wokurna 5520
Canowie Belt 5420
Mundulla West 5270
New Residence 5333
Pallamana 5254
Pompoota 5238
Vine Vale 5352
Yarrah 5433
Gurra Gurra 5343
Koorine 5279
Ninnes 5560
Pirie East 5540
St Kitts 5356
Yundi 5172
Bangham 5268
Bluff Beach 5575
Cunliffe 5554
Merriton 5523
North West Bend 5320
Purnong 5238
Sandleton 5356
Sebastopol 5280
Solomon 5641
South Hummocks 5550
Weetulta 5573
Willalo 5419
Hay Flat 5204
Lake Plains 5255
Mount Barker Springs 5251
Narridy 5523
Salter Springs 5401
The Range 5172
Wallaroo Plain 5556
Yatina 5422
Yorke Valley 5573
Gawler River 5118
Hampden 5374
Marananga 5355
Murray Bridge North 5253
Brooker 5607
Hart 5464
Murdinga 5607
Murray Town 5481
Sherwood 5267
Australia Plains 5374
Buchanan 5374
Culburra 5261
Field 5265
Gomersal 5352
Long Plains 5501
Mosquito Hill 5214
Mount Damper 5654
Peebinga 5304
Pewsey Vale 5351
Pygery 5652
Rogues Point 5571
Thorngate 5082
Waterfall Gully 5066
Blackford 5275
Brentwood 5575
Bumbunga 5520
Dudley West 5222
Old Calperum 5341
Tooligie 5607
Angas Plains 5255
Duck Ponds 5607
Emu Flat 5453
Grace Plains 5502
Kepa 5259
Struan 5271
Willamulka 5554
Qualco 5322
Silverton 5204
Waddikee 5640
Whitwarta 5461
Middle River 5223
Nora Creina 5276
Pooginagoric 5268
Avoca Dell 5253
Koongawa 5650
Krondorf 5352
Torrens Vale 5203
Annadale 5356
Colebatch 5266
Coombe 5267
Cungena 5660
Hornsdale 5491
Pike River 5340
Calomba 5501
Cherryville 5134
Cunningham 5571
Eba Anchorage 5680
Mangalo 5602
Stokes Bay 5223
Tilley Swamp 5275
Black Rock 5431
Cadgee 5271
Chandada 5680
Charra 5690
Clay Wells 5280
Coomooroo 5431
Eba 5320
Everard Central 5461
Port Gibbon 5602
Spence 5271
Stone Hut 5480
Sutherlands 5374
Umuwa 0872
Bookabie 5690
Bundaleer North 5491
Clements Gap 5523
McHarg Creek 5157
Melton 5552
Milendella 5237
Miltalie 5602
Port Gawler 5501
South Kilkerran 5573
Spring Gully 5453
D'Estrees Bay 5223
Duncan 5223
Hansborough 5374
Huddleston 5523
Jabuk 5301
Mount Hope 5607
Coomunga 5607
Gosse 5223
Hope Forest 5172
Ki Ki 5261
Mudamuckla 5680
Sampson Flat 5114
Wongyarra 5481
Hanson 5417
Koonunga 5373
Newland 5223
Parnaroo 5422
Towitta 5353
Caltowie West 5490
Daveyston 5355
Deep Creek 5204
Lower Broughton 5540
Minbrie 5602
Mount Barker Summit 5251
Nalyappa 5558
Olympic Dam 5725
Chapel Hill 5153
Elwomple 5260
Karte 5304
Linwood 5410
Magarey 5280
Maggea 5311
Ngapala 5374
Sapphiretown 5222
Stone Well 5352
White Hill 5254
Barunga Gap 5520
Bugle Hut 5311
Comaum 5277
Dismal Swamp 5291
Hawson 5607
Nunjikompita 5680
Western River 5223
Cortlinye 5641
Erith 5461
Gerard 5343
Moppa 5355
Sunnyvale 5552
Urania 5573
Ward Hill 5522
West Range 5275
Willunga Hill 5172
Woodleigh 5311
Leawood Gardens 5150
Moorlands 5301
Caroline 5291
Frankton 5374
German Creek 5291
Mantung 5308
Petersville 5571
Petina 5680
Taldra 5311
Waltowa 5264
White Hut 5575
Bruce 5433
Caveton 5291
Lyndhurst 5731
Middleback Range 5609
Morchard 5431
Mount Magnificent 5210
Pleasant Park 5277
Tothill Creek 5413
Colley 5671
Dawson 5422
Gemmells 5255
Kringin 5304
Poltalloch 5259
Yumali 5261
Bangor 5481
Carew 5270
Gillentown 5453
Halidon 5309
Innamincka 5731
Karkoo 5632
Kellidie Bay 5607
Kingsford 5118
Mount Charles 5267
Mount Templeton 5461
Murninnie Beach 5609
Red Creek 5255
Saltia 5433
Tarnma 5413
Webb Beach 5501
Wigley Flat 5330
Chinaman Wells 5573
Nackara 5440
Thistle Island 5606
Undalya 5451
Walloway 5431
Whites Flat 5607
Bright 5381
Mulgundawa 5255
Point Sturt 5256
Yantanabie 5661
Andrews 5454
Bolto 5238
Caralue 5641
Dowlingville 5571
Galga 5308
Sleaford 5607
Johnburgh 5431
Kingoonya 5719
Laffer 5267
Murrawong 5253
Stanley 5415
Blanche Harbor 5700
Brimbago 5267
Burra Eastern Districts 5417
Moody 5607
Nurom 5523
Warraweena 5730
Worlds End 5381
Zadows Landing 5254
Barossa Goldfields 5351
Bundey 5320
Green Hills Range 5153
Kohinoor 5223
Malpas 5311
Mambray Creek 5495
Mount McKenzie 5353
North Booborowie 5417
Oak Valley 5690
Tothill Belt 5413
Veitch 5311
Washpool 5454
Wattle Range East 5279
Avon 5501
Buckingham 5270
Campoona 5640
Mitchell 5632
Moerlong 5278
Nullarbor 5690
Olary 5440
Point Lowly 5601
Thrington 5552
Green Patch 5607
Hamley 5558
Polish Hill River 5453
Pyap West 5333
Racecourse Bay 5291
Wonna 5419
Baldina 5417
Good Hope Landing 5330
Rapid Bay 5204
Short 5279
Wirrega 5267
Woolshed Flat 5412
Bletchley 5255
Douglas Point 5601
Petwood 5252
Steelton 5413
Angas Valley 5238
Apoinga 5413
Ashville 5259
Biggs Flat 5153
Collinsfield 5555
Dingabledinga 5172
Goyder 5461
Hacklins Corner 5454
Kalanbi 5690
Malinong 5259
Marble Hill 5137
Mitchellville 5602
Muston 5221
Boolgun 5330
Canunda 5280
Couch Beach 5577
De Mole River 5223
Dutton East 5356
McBean Pound 5357
Talia 5670
Wami Kata 5700
Warburto 5556
Boonerdo 5633
Colton 5670
Lowan Vale 5268
Manna Hill 5440
Netherton 5301
Punthari 5238
Wandana 5690
Watarru 0872
Woolpunda 5330
Antechamber Bay 5222
Beaumonts 5320
Gum Creek 5417
Salt Creek 5264
The Gap 5271
Thomas Plain 5554
Wrattonbully 5271
Bald Hills 5203
Caliph 5310
Charlton Gully 5607
Kalka 0872
Kapinnie 5632
Keswick Terminal 5035
Moseley 5641
Nain 5360
Pearlah 5607
Stuart 5320
Tolderol 5256
Wonuarra 5340
Bordertown South 5268
Bowillia 5461
Calca 5671
Kallora 5550
Karcultaby 5654
Stephenston 5433
Watchman 5461
Yinkanie 5332
Barndioota 5434
Brady Creek 5381
Brown Hill Creek 5062
Cavenagh 5422
Chain Of Ponds 5231
Midgee 5602
Mount Clarence Station 5723
Nepabunna 5732
West Bundaleer 5491
Willow Creek 5211
Winulta 5570
Bay Of Shoals 5223
Canowie 5419
Emeroo 5713
Five Miles 5238
Julia 5374
Lowbank 5330
Nectar Brook 5495
Oodla Wirra 5422
Tepko 5254
Ulyerra 5633
Willson River 5222
Winninowie 5700
Woolsheds 5400
Yanyarrie 5432
Big Bend 5238
Little Douglas 5607
Mundic Creek 5340
Parachilna 5730
Petherick 5267
Toora 5253
Willoughby 5222
Woolundunga 5701
Yunyarinyi 0872
Clinton Centre 5570
Hay Valley 5252
Kaldoonera 5655
Kanni 5330
Lake View 5555
Maude 5320
Mount Wedge 5670
Tunkalilla 5203
Chapman Bore 5253
Deepwater 5266
Forster 5238
Glendambo 5719
Inkerman 5550
Lincoln Gap 5715
McCallum 5267
Merghiny 5690
Naturi 5259
Pellaring Flat 5238
Piednippie 5680
Pooginook 5330
St Ives 5252
Warnes 5417
Yalpara 5431
Birchmore 5223
Fischer 5502
Geranium Plains 5381
Peep Hill 5374
Porky Flat 5222
Stockyard Plain 5330
Beatty 5320
Cunyarie 5641
Jericho 5554
Kanpi 0872
Swede Flat 5270
Younghusband Holdings 5238
Barinia 5453
Cocata 5654
Collinsville 5418
Mount Drummond 5607
Nyapari 0872
Pimba 5720
Tyringa 5671
Caltowie North 5490
Cuttlefish Bay 5222
Dorset Vale 5157
Farm Beach 5607
Nurragi 5256
Baird Bay 5671
Cootra 5650
Devlins Pound 5330
Erskine 5422
Fitzgerald Bay 5601
Kyeema 5172
Mercunda 5308
Pimbaacla 5661
Wharminda 5603
Bunbury 5266
Gifford Hill 5253
Kooroona 5558
Mount Cooper 5671
Murlong 5642
Wallala 5661
Yalanda 5641
Yanerbie 5680
Amyton 5431
Bundaleer Gardens 5491
Custon 5269
Greenbanks 5253
Kangaroo Head 5222
Kangaroo Inn 5280
Laura Bay 5680
Mobilong 5253
New Well 5357
Square Mile 5291
Wandearah West 5523
Yelta 5558
Franklyn 5421
Iron Baron 5611
Lake Carlet 5238
Markaranka 5330
Porter Lagoon 5416
Salem 5255
St Johns 5373
Barna 5641
Bungaree 5464
Chilpenunda 5660
Cultana 5700
Euromina 5454
Frayville 5238
Horsnell Gully 5141
Kongal 5270
Morn Hill 5371
Mortana 5671
North Cape 5223
Panitya 5641
Port Davis 5540
Seal Bay 5223
Stockyard Creek 5460
Whites River 5607
Bakara 5354
Ballast Head 5221
Cape Borda 5223
Claypans 5238
Kiana 5607
Meningie East 5264
Morphetts Flat 5320
Paratoo 5422
Yamba 5340
Blackfellows Creek 5201
Boconnoc Park 5453
Chinbingina 5680
Cleland 5152
Giles Corner 5411
Ironstone 5222
Minburra Plain 5431
Paramatta 5558
Cowleds Landing 5609
Holder Siding 5330
Inkster 5680
Makin 5267
Meningie West 5264
Mongolata 5417
Mount Observation 5255
Ngarkat 5302
Pine Creek 5419
Polda 5670
Wappilka 5332
Willow Banks 5253
Burnsfield 5520
Carawa 5680
Kappawanta 5670
Lake Alexandrina 5259
Mayfield 5454
Torrens Island 5015
Inneston 5577
Kuitpo Colony 5172
Naidia 5354
Port Bonython 5601
Riverglen 5253
Schell Well 5311
Stow 5461
Taunton 5235
White Well Corner 5690
Broughton River Valley 5454
Brown Beach 5222
Langs Landing 5353
Mingary 5440
Palkagee 5670
Shaugh 5267
William Creek 5723
Dalkey 5461
False Bay 5601
Frahns 5238
Gawler Ranges 5655
Germein Bay 5495
Hardy 5422
Hope Gap 5555
Hoskin Corner 5461
Lindley 5320
Mundoo Island 5214
Notts Well 5357
Port Arthur 5552
Rocky Plain 5381
Saints 5461
Tootenilla 5607
Watinuma 0872
Apamurra 5237
Benbournie 5453
Castambul 5076
Coolillie 5670
Mount Barker Junction 5251
Stun'sail Boom 5223
Ulooloo 5419
Backy Point 5601
Douglas Point South 5601
Maltee 5690
Millbrook 5231
Murputja 0872
Bakara Well 5354
Carriewerloo 5715
Fountain 5607
Maryvale 5680
Montarra 5172
Pureba 5680
Rochester 5464
Uley 5607
Witera 5671
Wombats Rest 5320
Arcoona 5720
Cadell Lagoon 5321
Hallelujah Hills 5381
Julanka Holdings 5238
Laurie Park 5271
Old Teal Flat 5238
Puntabie 5680
Teal Flat 5238
Flinders Chase 5223
Jamieson 5640
Kootaberra 5713
Point Lowly North 5601
Uworra 5690
Wallerberdina 5713
Carcuma 5301
Chowilla 5341
Gidgealpa 5731
Krongart 5278
Mount Joy 5670
Oulnina 5440
Wilcherry 5641
American Beach 5222
De Rose Hill 0872
Grampus 5440
Gum Creek Station 5730
Koonoona 5417
Mount Falkland 5730
Mutooroo 5440
Spectacle Lake 5345
Stuarts Creek 5720
Waroonee 5422
Watraba 5690
Andamooka Station 5722
Beltana Station 5730
Billiatt 5311
Corunna Station 5611
Lincoln National Park 5607
Oakden Hills 5713
Pernatty 5713
Puttapa 5730
Rocky Point 5238
Wirraminna 5719
Anna Creek 5723
Lake Gilles 5611
Marola 5464
Minburra 5431
Motpena 5730
Proof Range 5550
Upalinna 5434
Waukaringa 5440
Wooltana 5732
Alpana 5730
Anama 5464
Coondambo 5719
Gammon Ranges 5732
Koolgera 5661
Moolooloo 5730
Mount Willoughby 5723
Muloorina 5733
Mulyungarie 5440
Nilpena 5730
North Yelta 5558
Pine Creek Station 5440
Taylorville Station 5330
Welbourn Hill 5724
Wirrealpa 5730
Yellabinna 5690
Billa Kalina 5720
Bockelberg 5655
Bungeroo 5641
Clifton Hills Station 5733
Florina Station 5440
Ingomar 5723
McDouall Peak 5723
Melton Station 5440
Mulka 5733
Mundallio 5700
Mungeranie 5733
Murnpeowie 5731
Myola Station 5611
Nadia 5690
Pandurra 5715
Shaggy Ridge 5434
Wertaloona 5732
Wiawera 5440
Wilgena 5719
Yadlamalka 5713
Yumbarra 5690
Angorigina 5730
Arkaroola Village 5701
Ayers Range South 0872
Baratta 5432
Bollards Lagoon 5731
Commonwealth Hill 5719
Eringa 5734
Etadunna 5733
Farina Station 5731
Hiltaba 5717
Hincks 5603
Kolendo 5717
Kondoolka 5717
Leigh Creek Station 5731
Lindon 5731
Marree Station 5733
Moolawatana 5732
Moonaree 5717
Mount Barry 5723
Mount Eba 5720
Mundowdna 5733
Nalpa 5255
Nonning 5717
Wilkatana Station 5713
Willow Springs 5434
Witchelina 5731
Yardea 5717
Alton Downs Station 5733
Anangu Pitjantjatjara Yankunytjatjara 0872
Angepena 5732
Arckaringa 5723
Bimbowrie 5440
Bon Bon 5719
Bulgunnia 5719
Bulloo Creek 5440
Callanna 5733
Clayton Station 5733
Cooyerdoo 5611
Curnamona 5440
Danggali 5417
Dulkaninna 5733
Erudina 5440
Evelyn Downs 5723
Faraway Hill 5417
Frome Downs 5440
Garden Island 5015
Hambidge 5642
Holowiliena 5432
Holowiliena South 5432
Kalamurina 5733
Kalkaroo 5440
Koonamore 5440
Lake Everard 5717
Lake Gairdner 5717
Lake Torrens Station 5713
Lockes Claypan 5655
Manners Well 5732
Millers Creek 5720
Minburra Station 5431
Mitchidy Moola 5690
Mooleulooloo 5440
Mount Arden 5713
Mount Freeling 5731
Mount Serle 5732
Mount Victor Station 5440
Mulgathing 5719
Myrtle Springs 5731
Narrina 5730
Nilpinna Station 5723
North Moolooloo 5732
Oratunga Station 5730
Pandie Pandie 5733
Parakylia 5720
Pinjarra Station 5680
Plumbago 5440
Pualco Range 5440
Secret Rocks 5611
Siam 5717
Strzelecki Desert 5731
Sturt Vale 5417
Tieyon 0872
Tikalina 5440
Todmorden 5734
Umberatana 5732
Wadnaminga 5440
Wintinna 5723
Witjira 5734
Wompinie 5440
Yankaninna 5732
Abminga Station 5440
Allandale Station 5723
Arkaroola 5732
Balah 5417
Benda 5440
Bibliando 5432
Billeroo West 5440
Bindarrah 5440
Black Hill Station 5434
Boolcoomatta 5440
Bosworth 5720
Bunyung 5417
Burr Well 5732
Calperum Station 5341
Canegrass 5417
Chundaria 5690
Cordillo Downs 5731
Cowarie 5733
Crown Point 5734
Devonborough Downs 5440
Ediacara 5730
Gilles Downs 5611
Gluepot 5417
Hawks Nest Station 5330
Illeroo 5715
Island Lagoon 5713
Kalabity 5440
Katunga Station 5611
Kokatha 5717
Lake Eyre 5733
Lake Frome 5440
Lake Macfarlane 5717
Lake Torrens 5713
Lambina 0872
Mabel Creek 5723
Macumba 5734
Mahanewo 5717
Manunda Station 5440
Martins Well 5440
Merty Merty 5731
Moorillah 5730
Mount Havelock 5434
Mount Ive 5717
Mount Lyndhurst 5731
Mount Sarah 5734
Mount Vivian 5720
Mulga View 5732
Mulgaria 5731
Mundi Mundi 5440
Nanbona 5690
Narlaby 5655
Netley Gap 5440
North Hills 5431
Oakvale Station 5417
Old Koomooloo 5417
Oulnina Park 5440
Outalpa 5440
Parcoola 5417
Pinda Springs 5732
Pine Valley Station 5417
Prelinna 5434
Quinyambie 5440
Quondong 5417
Roxby Downs Station 5725
Simpson Desert 5734
South Gap 5713
Tepco Station 5440
Three Creeks 5432
Thurlga 5717
Uno 5717
Wartaka 5715
Weekeroo 5440
Westons Flat 5320
Wilcowie 5432
Willippa 5432
Winnininnie 5440
Wintabatinyana 5713
Witchitie 5432
Worumba 5434
Yalymboo 5715
Yarramba 5440
Yeltana 5641
Yudnapinna 5715`
