/**
 * Every suburb and locality in Tasmania (TAS) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Devonport 7310
Sandy Bay 7005
Glenorchy 7010
Kingston 7050
Hobart 7000
Howrah 7018
Launceston 7250
Claremont 7011
Ulverstone 7315
Wynyard 7325
New Town 7008
Riverside 7250
Moonah 7009
Blackmans Bay 7052
New Norfolk 7140
West Hobart 7000
Lindisfarne 7015
Newnham 7248
Lenah Valley 7008
South Hobart 7004
Newstead 7250
Prospect Vale 7250
South Launceston 7249
Latrobe 7307
Bellerive 7018
George Town 7253
Rokeby 7019
Kings Meadows 7249
Invermay 7248
Longford 7301
East Devonport 7310
Brighton 7030
Youngtown 7249
Legana 7277
Smithton 7330
Sorell 7172
Trevallyn 7250
West Launceston 7250
Mowbray 7248
Bridgewater 7030
West Ulverstone 7315
Penguin 7316
North Hobart 7000
Somerset 7322
West Moonah 7009
Old Beach 7017
Battery Point 7004
Perth 7300
St Helens 7216
Ravenswood 7250
Deloraine 7304
Huonville 7109
Margate 7054
Geilston Bay 7015
Midway Point 7171
Norwood 7250
Queenstown 7467
Scottsdale 7260
Dodges Ferry 7173
Summerhill 7250
Bridport 7262
Taroona 7053
Mornington 7018
Mount Nelson 7007
Berriedale 7011
Rosetta 7010
Shearwater 7307
Warrane 7018
Westbury 7303
Primrose Sands 7173
Cambridge 7170
Park Grove 7320
Shorewell Park 7320
Lutana 7009
Risdon Vale 7016
Port Sorell 7307
Austins Ferry 7011
Bicheno 7215
Hadspen 7290
St Leonards 7250
Mount Stuart 7000
Montrose 7010
Cygnet 7112
East Launceston 7250
Orford 7190
Burnie 7320
Upper Burnie 7320
Lauderdale 7021
Kingston Beach 7050
Prospect 7250
Spreyton 7310
Tranmere 7018
Swansea 7190
Chigwell 7011
Beaconsfield 7270
Richmond 7025
Sheffield 7306
Oakdowns 7019
Turners Beach 7315
Coles Bay 7215
Sandford 7020
Miandetta 7310
Romaine 7320
Granton 7030
Campbell Town 7210
Acton Park 7170
Beauty Point 7270
Zeehan 7469
Rosebery 7470
Geeveston 7116
Dover 7117
Waverley 7250
Dynnyrne 7005
Carlton 7173
Clarendon Vale 7019
White Beach 7184
Triabunna 7190
Evandale 7212
Scamander 7215
Derwent Park 7009
Rocherlea 7248
Strahan 7468
Ranelagh 7109
Montello 7320
Currie 7256
Gagebrook 7030
Acton 7320
Franklin 7113
St Marys 7215
Bagdad 7030
Seven Mile Beach 7170
Hawley Beach 7307
Mayfield 7248
Miena 7030
Stieglitz 7216
Rose Bay 7015
Cressy 7302
Nubeena 7184
Railton 7305
South Arm 7022
Low Head 7253
Eaglehawk Neck 7179
Hillcrest 7320
Campania 7026
Herdsmans Cove 7030
Goodwood 7010
Snug 7054
Oatlands 7120
Blackstone Heights 7250
Binalong Bay 7216
Parklands 7320
Kettering 7155
Sisters Beach 7321
Greens Beach 7270
Stanley 7331
Forcett 7173
Exeter 7275
Grindelwald 7277
Lewisham 7173
Cooee 7320
Waratah 7321
Port Arthur 7182
Lachlan 7140
Lilydale 7268
Murdunna 7178
Stony Rise 7310
Rosny 7018
Montagu Bay 7018
Forth 7310
Opossum Bay 7023
Carrick 7291
Havenview 7320
Sulphur Creek 7316
Adventure Bay 7150
Ambleside 7310
Hillwood 7252
Fern Tree 7054
Ross 7209
Bothwell 7030
Huntingfield 7055
Glebe 7000
Port Huon 7116
South Burnie 7320
Heybridge 7316
Don 7310
Glen Huon 7109
Dolphin Sands 7190
Dromedary 7030
Fingal 7214
Molesworth 7140
Collinsvale 7012
Howden 7054
Whitemark 7255
Magra 7140
Gravelly Beach 7276
Gawler 7315
Quoiba 7310
Acacia Hills 7306
Mole Creek 7304
Brooklyn 7320
Relbia 7258
Southport 7109
Ridgley 7321
Beaumaris 7215
Woodbridge 7162
Ansons Bay 7264
Pontville 7030
Cremorne 7024
Colebrook 7027
Alonnah 7150
Dunalley 7177
Dilston 7252
Grove 7109
Kempton 7030
Tullah 7321
Lulworth 7252
Punchbowl 7249
Clifton Beach 7020
Wesley Vale 7307
Tolmans Hill 7007
Wivenhoe 7320
Spring Beach 7190
Derby 7264
Otago 7017
Glengarry 7275
Grassy 7256
Western Junction 7212
Forest 7330
Mountain River 7109
Tea Tree 7017
Ringarooma 7263
Lunawanna 7150
Cradoc 7109
Swan Bay 7252
Rosny Park 7018
Bracknell 7302
Branxholm 7261
Lady Barron 7255
North Motton 7315
Judbury 7109
Clarence Point 7270
Orielton 7172
South Spreyton 7310
Penna 7171
Carlton River 7173
Hamilton 7140
Sidmouth 7270
Deviot 7275
Meander 7304
Underwood 7268
Ouse 7140
Leith 7315
Lymington 7109
Lower Snug 7054
Tugrah 7310
Bonnet Hill 7053
Weymouth 7252
Lucaston 7109
Dennes Point 7150
Honeywood 7017
Nunamara 7259
Deep Bay 7112
Mangalore 7030
Nicholls Rivulet 7112
Falmouth 7215
Mooreville 7321
Pipers River 7252
Ellendale 7140
Electrona 7054
Taranna 7180
Tinderbox 7054
Squeaking Point 7307
Saltwater River 7186
Winnaleah 7265
Allens Rivulet 7150
Gardners Bay 7112
Rosevears 7277
Wilmot 7310
Gordon 7150
Yolla 7325
Stowport 7321
Boat Harbour 7321
Elizabeth Town 7304
Lanena 7275
Garden Island Creek 7112
Naracoopa 7256
North Bruny 7150
Karoola 7267
Bridgenorth 7277
Maydena 7140
Oyster Cove 7150
Elliott 7325
Avoca 7213
Hagley 7292
Mount Hicks 7325
Ocean Vista 7320
Coningham 7054
Leslie Vale 7054
Sassafras 7307
Akaroa 7216
Rossarden 7213
Middleton 7163
Verona Sands 7112
Kelso 7270
Boat Harbour Beach 7321
Blackwall 7275
Lake Leake 7210
Tarleton 7310
Devon Hills 7300
Swan Point 7275
Claude Road 7306
Riana 7316
Rocky Cape 7321
Irishtown 7330
South Bruny 7150
Tunnack 7120
Hellyer 7321
Pelverata 7150
Sandfly 7150
Eggs And Bacon Bay 7112
Koonya 7187
Wilburville 7030
Bradys Lake 7140
Crabtree 7109
Little Swanport 7190
Kayena 7270
Beechford 7252
Mathinna 7214
Mount Rumney 7170
Aberdeen 7310
Dysart 7030
Buckland 7190
Golden Valley 7304
Mount Direction 7252
Northdown 7307
Bronte Park 7140
Gormanston 7466
Brandum 7304
Calder 7325
Musselroe Bay 7264
Kindred 7310
Travellers Rest 7250
Downlands 7320
Turners Marsh 7267
Windermere 7252
Flintstone 7030
Flowerdale 7325
Natone 7321
Four Mile Creek 7215
Lower Barrington 7306
Marrawah 7330
Westerway 7140
Gladstone 7264
Scotchtown 7330
Gunns Plains 7315
Poatina 7302
Surveyors Bay 7116
Tunbridge 7120
Gretna 7140
Lower Longley 7109
Risdon 7017
Premaydena 7185
Abels Bay 7112
Lawitta 7140
Wattle Grove 7109
Moriarty 7307
Sloping Main 7186
Bellingham 7254
Camdale 7320
Reedy Marsh 7304
Springfield 7260
Legerwood 7263
Chudleigh 7304
Ridgeway 7054
Castle Forbes Bay 7116
Kaoota 7150
Copping 7174
Frankford 7275
Dulcot 7025
Lebrina 7254
Glenlusk 7012
White Hills 7258
Surges Bay 7116
Broadmarsh 7030
Lefroy 7252
Tomahawk 7262
Nabowla 7260
South Riana 7316
Barrington 7306
Winkleigh 7275
Interlaken 7030
Black Hills 7140
Great Bay 7150
Kellevie 7176
Longley 7150
Nook 7306
Preston 7315
Wattle Hill 7172
Birralee 7303
Neika 7054
Parattah 7120
Pioneer 7264
West Kentish 7306
Boomer Bay 7177
Roches Beach 7170
Emu Heights 7320
Rowella 7270
Elderslie 7030
Levendale 7120
Arthur River 7330
Doctors Point 7304
Loorana 7256
Moorleah 7325
Pegarah 7256
Whitemore 7303
North Scottsdale 7260
Reynolds Neck 7304
Emita 7255
Exton 7303
Jetsonville 7260
Police Point 7116
Loira 7275
Tods Corner 7030
London Lakes 7140
Kimberley 7304
Round Hill 7320
Liffey 7301
Bream Creek 7175
Petcheys Bay 7109
Cornwall 7215
East Cam 7321
Eugenana 7310
Lonnavale 7109
Lymwood 7256
Sisters Creek 7325
Sprent 7315
Upper Natone 7321
Woodsdale 7120
Pyengana 7216
Memana 7255
Bishopsbourne 7301
Blessington 7212
Cuprona 7316
Glenfern 7140
Granville Harbour 7469
Connellys Marsh 7173
Lapoinya 7325
Nile 7212
Strathblane 7109
Redpa 7330
Rhyndaston 7120
Birchs Bay 7162
Bushy Park 7140
Caveside 7304
West Pine 7316
Randalls Bay 7112
Breona 7304
Dunorlan 7304
Nugara 7256
Quamby Brook 7304
Parkham 7304
Table Cape 7325
Weegena 7304
Flowerpot 7163
Nugent 7172
Conara 7211
Henrietta 7325
Killiecrankie 7255
Mengha 7330
Waterhouse 7262
Wayatinah 7140
Crayfish Creek 7321
National Park 7140
Oldina 7325
Bakers Beach 7307
Edith Creek 7330
Highclere 7321
Marion Bay 7175
Paradise 7306
Christmas Hills 7330
Pipers Brook 7254
Lower Wilmot 7310
Patersonia 7259
Pawleena 7172
South Forest 7330
Bangor 7267
Plenty 7140
Togari 7330
Trowutta 7330
Goulds Country 7216
Nietta 7315
Western Creek 7304
Hayes 7140
Mawbanna 7321
Pontypool 7190
Rosevale 7292
Upper Castra 7315
Blackwood Creek 7301
Moltema 7304
Red Hills 7304
Grasstree Hill 7017
Gray 7215
Tunnel 7254
East Ridgley 7321
Goshen 7216
Hastings 7109
Lorinna 7306
Runnymede 7190
Breadalbane 7258
York Town 7270
Apollo Bay 7150
Arthurs Lake 7030
Dowsing Point 7010
Harford 7307
Lalla 7267
Sunnyside 7305
Cramps Bay 7030
Glaziers Bay 7109
Lower Wattle Grove 7109
Mount Seymour 7120
Royal George 7213
Upper Blessington 7212
West Mooreville 7321
Douglas River 7215
Robigana 7275
Roland 7306
Waterloo 7109
West Ridgley 7321
West Scottsdale 7260
Montagu 7330
Edgcumbe Beach 7321
Lileah 7330
Seymour 7215
Preolenna 7325
Tewkesbury 7321
Weldborough 7264
Epping Forest 7211
Mangana 7214
Melrose 7310
Upper Stowport 7321
Woolnorth 7330
Staverton 7306
Charlotte Cove 7112
Deddington 7212
Flowery Gully 7270
Glenora 7140
Holwell 7275
Stonor 7119
Highcroft 7183
Sorell Creek 7140
Thirlstane 7307
Beulah 7306
Cairns Bay 7116
Milabena 7325
Morass Bay 7030
Mount Lloyd 7140
Paloona 7310
Rheban 7190
The Gardens 7216
Trial Harbour 7469
Forthside 7310
Glendevie 7109
Tayene 7259
Abbotsham 7315
Badger Head 7270
Barnes Bay 7150
Cranbrook 7190
Brooks Bay 7116
Doctors Rocks 7325
Fentonbury 7140
Herrick 7264
Moogara 7140
Palana 7255
Simpsons Bay 7150
Jackeys Marsh 7304
Lackrana 7255
North Lilydale 7268
Osmaston 7303
Preservation Bay 7316
Roger River 7330
Selbourne 7292
York Plains 7120
Montumana 7321
Recherche 7109
Cuckoo 7260
Erriba 7310
Melton Mowbray 7030
Raminea 7109
Rosegarland 7140
Tarraleah 7140
Bell Bay 7253
Mella 7330
Moina 7310
Ranga 7255
Chasm Creek 7321
Takone 7325
Upper Scamander 7215
Merseylea 7305
Nabageena 7330
Queens Domain 7000
Talawa 7263
Targa 7259
Gowrie Park 7306
Jericho 7030
Lietinna 7260
West Montagu 7330
Alcomie 7330
Howth 7316
Liena 7304
Westwood 7292
Dairy Plains 7304
Lune River 7109
Myalla 7325
Shannon 7030
Temma 7330
Tyenna 7140
Hampshire 7321
Black River 7321
Lower Beulah 7306
Spalford 7315
Andover 7120
Baden 7120
Boyer 7140
Brittons Swamp 7330
Cape Barren Island 7257
Lottah 7216
Macquarie Plains 7140
Myrtle Bank 7259
Notley Hills 7275
Scopus 7330
Weetah 7304
Barretta 7054
Cleveland 7211
Loongana 7315
Malbina 7140
Upper Woodstock 7150
Whitefoord 7120
Egg Lagoon 7256
Fitzgerald 7140
Rushy Lagoon 7264
Strathgordon 7139
Loccota 7255
Montana 7304
Wyena 7254
Blue Rocks 7255
Castra 7315
Pelham 7030
Lemont 7120
Nowhere Else 7306
Osterley 7140
Stoodley 7306
Yambacoona 7256
Broadmeadows 7330
Dee 7140
Loyetea 7316
Wiltshire 7321
Chain Of Lagoons 7215
Cluan 7303
Leeka 7255
Pawtella 7120
Promised Land 7306
Stonehenge 7120
Upper Esk 7214
Little Pine Lagoon 7140
Karanja 7140
Stormlea 7184
Strickland 7140
Telita 7264
Tooms Lake 7209
Blumont 7260
Cowrie Point 7321
Hollow Tree 7140
South Springfield 7260
Uxbridge 7140
Woodbury 7120
Woodstock 7109
Cradle Mountain 7306
Eddystone 7264
Needles 7304
Nelson Bay 7330
Reekara 7256
Retreat 7254
Apsley 7030
Camena 7316
Golconda 7254
Lower Turners Marsh 7267
Meadowbank 7140
Oaks 7303
Rocky Hills 7190
Toiberry 7301
Lillico 7310
Lower Marshes 7030
Powranna 7300
Tonganah 7260
Yarra Creek 7256
Bungaree 7256
Lughrata 7255
South Mount Cameron 7264
Victoria Valley 7140
West Coast 7321
Couta Rocks 7330
Derwent Bridge 7140
Mayberry 7304
Mount Field 7140
Burns Creek 7212
Killora 7150
South Nietta 7315
Ida Bay 7109
Savage River 7321
Steppes 7030
Alberton 7263
Apslawn 7190
Friendly Beaches 7215
Wickham 7256
Cethana 7306
Detention 7321
Liawenee 7030
Moorina 7264
Pearshape 7256
Quamby Bend 7292
South Preston 7315
Tulendeena 7260
Meunna 7325
Warrentinna 7261
West Takone 7325
Kamona 7260
Swanston 7120
Trenah 7263
Waddamana 7030
Antill Ponds 7120
Cape Portland 7264
Banca 7265
Forester 7260
Freycinet 7215
Middlesex 7306
Oonah 7325
Surprise Bay 7256
Sea Elephant 7256
Wellington Park 7054
Boobyalla 7264
Hermitage 7030
Long Reach 7253
Port Latta 7321
Florentine 7140
Huon Island 7112
Luina 7321
Tiberias 7120
Lake St Clair 7140
Mersey Forest 7304
Wingaroo 7255
Ben Lomond 7212
Central Plateau 7304
Fortescue 7182
Garden Island 7112
Millers Bluff 7030
Mount William 7264
Southwest 7140
Stony Head 7252`
