/**
 * Every suburb and locality in Victoria (VIC) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Melbourne 3000 3004
Southbank 3006
Reservoir 3073
Tarneit 3029
Docklands 3008
Werribee 3030
South Yarra 3141
Pakenham 3810
Carlton 3053
Point Cook 3030
Craigieburn 3064
Frankston 3199
Richmond 3121
Berwick 3806
Preston 3072
St Kilda 3182
Mildura 3500
Sunbury 3429
Warrnambool 3280
Glen Waverley 3150
Truganina 3029
Clyde North 3978
Shepparton 3630
Dandenong 3175
Mount Waverley 3149
Brunswick 3056
North Melbourne 3051
St Albans 3021
Hawthorn 3122
Epping 3076
Hoppers Crossing 3029
Mornington 3931
Cheltenham 3192
Footscray 3011
Traralgon 3844
Noble Park 3174
Croydon 3136
Wollert 3750
Doncaster East 3109
Brighton 3186
Coburg 3058
Port Melbourne 3207
Northcote 3070
Doncaster 3108
Bentleigh East 3165
Ferntree Gully 3156
Rowville 3178
Malvern East 3145
Kew 3101
West Melbourne 3003
Bundoora 3083
Glen Iris 3146
South Melbourne 3205
Boronia 3155
Ocean Grove 3226
Keysborough 3173
Ringwood 3134
Glenroy 3046
Carrum Downs 3201
Springvale 3171
Essendon 3040
Wodonga 3690
Warragul 3820
Camberwell 3124
Mill Park 3082
Narre Warren 3805
Clayton 3168
Thomastown 3074
Box Hill 3128
Wangaratta 3677
Seaford 3198
Torquay 3228
Carnegie 3163
Prahran 3181
Rosebud 3939
Thornbury 3071
Elwood 3184
Lara 3212
Rye 3941
Wyndham Vale 3024
Doreen 3754
Cranbourne 3977
Officer 3809
Langwarrin 3910
South Morang 3752
Mount Martha 3934
Mooroolbark 3138
Greensborough 3088
Moonee Ponds 3039
Mickleham 3064
Hawthorn East 3123
Highton 3216
Caulfield North 3161
Brunswick East 3057
Pascoe Vale 3044
Lilydale 3140
Narre Warren South 3805
Sale 3850
Brunswick West 3055
Wantirna South 3152
Mernda 3754
Lalor 3075
Greenvale 3059
Hampton Park 3976
Fitzroy 3065
Toorak 3142
Dandenong North 3175
Cranbourne East 3977
Bentleigh 3204
Mulgrave 3170
Echuca 3564
Horsham 3400
Morwell 3840
Wheelers Hill 3150
Endeavour Hills 3802
Mitcham 3132
Altona Meadows 3028
Balwyn North 3104
Bayswater 3153
Caroline Springs 3023
Kensington 3031
Armstrong Creek 3217
Sunshine West 3020
Collingwood 3066
Drouin 3818
Eltham 3095
Ascot Vale 3032
Williamstown 3016
Burwood 3125
Fraser Rise 3336
Belmont 3216
Mentone 3194
Ivanhoe 3079
Yarraville 3013
Frankston South 3199
Cowes 3922
Cranbourne North 3977
Cranbourne West 3977
St Kilda East 3183
East Melbourne 3002
Blackburn 3130
Brighton East 3187
Mount Eliza 3930
Clayton South 3169
Fitzroy North 3068
Wallan 3756
Corio 3214
Deer Park 3023
Clyde 3978
Altona North 3025
Abbotsford 3067
Altona 3018
Geelong 3220
Maribyrnong 3032
Roxburgh Park 3064
Keilor East 3033
Highett 3190
Templestowe 3106
Grovedale 3216
Hampton 3188
Balwyn 3103
Armadale 3143
West Wodonga 3690
Benalla 3672
Surrey Hills 3127
Broadmeadows 3047
Elsternwick 3185
Sunshine North 3020
Leopold 3224
Nunawading 3131
West Footscray 3012
Malvern 3144
Portland 3305
Swan Hill 3585
Moe 3825
Wendouree 3355
Hastings 3915
Templestowe Lower 3107
Dromana 3936
Sandringham 3191
Hamilton 3300
Newport 3015
Kangaroo Flat 3555
Campbellfield 3061
Kilsyth 3137
Fawkner 3060
Parkdale 3195
Yarrawonga 3730
Sebastopol 3356
Windsor 3181
Beaumaris 3193
Hillside 3037 3875
Caulfield South 3162
Wantirna 3152
Box Hill North 3129
Melton South 3338
Moorabbin 3189
Tullamarine 3043
Mordialloc 3195
Newtown 3220 3351
Sunshine 3020
Manor Lakes 3024
Taylors Lakes 3038
Braybrook 3019
Burwood East 3151
Bairnsdale 3875
Hallam 3803
Inverloch 3996
Donvale 3111
Somerville 3912
Oakleigh 3166
Colac 3250
Bendigo 3550
Deanside 3336
Alfredton 3350
Norlane 3214
Forest Hill 3131
Donnybrook 3064
Avondale Heights 3034
Meadow Heights 3048
Bulleen 3105
Golden Square 3555
Murrumbeena 3163
Airport West 3042
Diamond Creek 3089
Gisborne 3437
Portarlington 3223
Parkville 3052
Oakleigh South 3167
Coburg North 3058
Chelsea 3196
Maryborough 3465
Maidstone 3012
Ringwood East 3135
Bayswater North 3153
Mount Duneed 3217
Kilmore 3764
Chadstone 3148
Flemington 3031
Macleod 3085
Chirnside Park 3116
Blackburn South 3130
Melton 3337
Safety Beach 3936
St Leonards 3223
Vermont South 3133
Castlemaine 3450
Geelong West 3218
Vermont 3133
Pascoe Vale South 3044
Ballarat Central 3350
Taylors Hill 3037
Harkness 3337
Dingley Village 3172
Ararat 3377
Bacchus Marsh 3340
Dandenong South 3175
Doveton 3177
Mooroopna 3629
Ormond 3204
Springvale South 3172
Montmorency 3094
Kalkallo 3064
Beveridge 3753
Sydenham 3037
Kyneton 3444
Heidelberg 3084
Healesville 3777
Heidelberg West 3081
Hughesdale 3166
Lakes Entrance 3909
Capel Sound 3940
Heathmont 3135
Box Hill South 3128
Seymour 3660
Cobram 3644
Blairgowrie 3942
Kialla 3631
Kyabram 3620
Knoxfield 3180
Kurunjang 3337
Rosanna 3084
Heidelberg Heights 3081
Clifton Springs 3222
Brookfield 3338
Mount Evelyn 3796
Fairfield 3078
Sorrento 3943
Keilor Downs 3038
Anglesea 3230
Wonthaggi 3995
Albert Park 3206
Bonbeach 3196
Balaclava 3183
Ashburton 3147
Point Lonsdale 3225
Mansfield 3722
Aintree 3336
Leongatha 3953
Ringwood North 3134
Strathmore 3041
Golden Beach 3851
Darley 3340
Canterbury 3126
Ashwood 3147
Patterson Lakes 3197
Diggers Rest 3427
Port Fairy 3284
Newborough 3825
Williams Landing 3027
Stawell 3380
Thornhill Park 3335
Alphington 3078
Carlton North 3054
Winter Valley 3358
Strathtulloh 3338
Derrimut 3026
Rockbank 3335
Ballarat East 3350
Oakleigh East 3166
Melton West 3337
Edithvale 3196
Oak Park 3046
Black Rock 3193
Kennington 3550
Aspendale 3195
Clifton Hill 3068
Gladstone Park 3043
Drysdale 3222
Woodend 3442
Irymple 3498
Croydon North 3136
Hadfield 3046
Hamlyn Heights 3215
Westmeadows 3049
Eaglehawk 3556
Weir Views 3338
Delacombe 3356
Cairnlea 3023
Bell Park 3215
Kew East 3102
McKinnon 3204
Charlemont 3217
Glen Huntly 3163
Niddrie 3042
Narre Warren North 3804
Paynesville 3880
Blackburn North 3130
Skye 3977
Delahey 3037
Lorne 3232
Hampton East 3188
Noble Park North 3174
Beaconsfield 3807
Caulfield 3162
Tootgarook 3941
Strathdale 3550
Strathfieldsaye 3551
Clarinda 3169
Lynbrook 3975
Tatura 3616
Botanic Ridge 3977
Lucas 3350
Lyndhurst 3975
Loch Sport 3851
Maddingley 3340
Korumburra 3950
Apollo Bay 3233
Maffra 3860
Daylesford 3460
Seddon 3011
Kings Park 3021
Red Cliffs 3496
Upwey 3158
Whittlesea 3757
Numurkah 3636
Laverton 3028
Newcomb 3219
Scoresby 3179
Montrose 3765
Barwon Heads 3227
Viewbank 3084
Carrum 3197
Dallas 3047
Bannockburn 3331
Albion 3020
Romsey 3434
Frankston North 3200
McCrae 3938
Mont Albert 3127
Keilor 3036
Churchill 3842
Watsonia 3087
Mont Albert North 3129
Burnside 3023
Venus Bay 3956
Aspendale Gardens 3195
Eltham North 3095
Middle Park 3206
Cremorne 3121
Euroa 3666
North Bendigo 3550
North Geelong 3215
Broadford 3658
Epsom 3551
Brown Hill 3350
Kerang 3579
Bell Post Hill 3215
Chelsea Heights 3196
St Albans Park 3219
Warrandyte 3113
Beechworth 3747
Emerald 3782
Bright 3741
Huntly 3551
Lysterfield 3156
Croydon South 3136
California Gully 3556
St Kilda West 3182
Notting Hill 3168
Canadian 3350
Jan Juc 3228
Eynesbury 3338
Metung 3904
Heathcote 3523
Trafalgar 3824
Ballarat North 3350
Camperdown 3260
Mambourin 3024
Essendon North 3041
Flora Hill 3550
Myrtleford 3737
Maiden Gully 3551
Nagambie 3608
East Bendigo 3550
Kingsville 3012
San Remo 3925
Creswick 3363
Whittington 3219
Cobblebank 3338
Bittern 3918
Portsea 3944
Spotswood 3015
Ballan 3342
Rochester 3561
Herne Hill 3218
East Geelong 3219
Curlewis 3222
Ivanhoe East 3079
Riddells Creek 3431
Koo Wee Rup 3981
North Wonthaggi 3995
Moolap 3224
Redan 3350
Albanvale 3021
Brooklyn 3012
Cape Woolamai 3925
Crib Point 3919
White Hills 3550
Long Gully 3550
Bonnie Brook 3335
Aberfeldie 3040
Seabrook 3028
The Basin 3154
Mallacoota 3892
Cranbourne South 3977
Williamstown North 3016
Belgrave 3160
Lower Plenty 3093
Mount Clear 3350
Coolaroo 3048
Tyabb 3913
Sandhurst 3977
Waurn Ponds 3216
Eaglemont 3084
Buninyong 3357
Burnside Heights 3023
Spring Gully 3550
Werribee South 3030
Kingsbury 3083
Indented Head 3223
Alexandra 3714
Cockatoo 3781
Warranwood 3134
Baranduda 3691
Orbost 3888
Braeside 3195
Queenscliff 3225
Winchelsea 3241
Monbulk 3793
Robinvale 3549
Stratford 3862
Park Orchards 3114
Ardeer 3022
Keilor Park 3042
Yarram 3971
Pearcedale 3912
Croydon Hills 3136
Elliminyt 3250
Warracknabeal 3393
Foster 3960
Merbein 3505
Junortoun 3551
Briar Hill 3088
Soldiers Hill 3350
Lake Wendouree 3350
Rutherglen 3685
Miners Rest 3352
Travancore 3032
Hurstbridge 3099
Golden Point 3350 3451 3465
St Arnaud 3478
Warburton 3799
Laverton North 3026
Upper Ferntree Gully 3156
Cohuna 3568
Clunes 3370
Heatherton 3202
Nhill 3418
Lancefield 3435
Yarra Junction 3797
Lang Lang 3984
New Gisborne 3438
Bunyip 3815
Somers 3927
Yarra Glen 3775
Cape Paterson 3995
Wonga Park 3115
Watsonia North 3087
Terang 3264
Maldon 3463
Flinders 3929
Yallambie 3085
Ravenhall 3023
Mirboo North 3871
Wandin North 3139
Aireys Inlet 3231
Eastwood 3875
Quarry Hill 3550
Manifold Heights 3218
Casterton 3311
Ventnor 3922
Kealba 3021
Longwarry 3816
South Kingsville 3015
Attwood 3049
Woori Yallock 3139
South Geelong 3220
Yea 3717
Lovely Banks 3213
Mount Helen 3350
Balnarring 3926
Marshall 3216
Coronet Bay 3984
Barooga 3644
Mount Pleasant 3350
Kilsyth South 3137
Campbells Creek 3451
Eumemmerring 3177
Heyfield 3858
Nathalia 3638
Huntingdale 3166
Koroit 3282
Beaufort 3373
Baxter 3911
Lucknow 3875
Cobden 3266
Junction Village 3977
St Helena 3088
Heywood 3304
Gowanbrae 3043
Seville 3139
Plenty 3090
Dimboola 3414
Deepdene 3103
Black Hill 3350
Yarragon 3823
Princes Hill 3054
Research 3095
Bellfield 3081
Rosedale 3847
Wy Yung 3875
Thomson 3219
North Warrandyte 3113
Fyansford 3218
Trentham 3458
Jacana 3047
Ascot 3551 3364
Smythes Creek 3351
Gembrook 3783
Breakwater 3219
Wandana Heights 3216
Macedon 3440
Traralgon East 3844
Officer South 3809
Paradise Beach 3851
Mortlake 3272
Dennington 3280
Beaconsfield Upper 3808
Olinda 3788
Corinella 3984
Coldstream 3770
Teesdale 3328
Launching Place 3139
Corryong 3707
Coleraine 3315
Ripponlea 3185
Tongala 3621
Flamingo Beach 3851
Tecoma 3160
Donald 3480
Yackandandah 3749
Leneva 3691
Garfield 3814
St Andrews Beach 3941
Jackass Flat 3556
Marong 3515
Neerim South 3831
Seaholme 3018
Newington 3350
Kinglake 3763
Avoca 3467
Shepparton North 3631
Caulfield East 3145
Grantville 3984
Chiltern 3683
Timboon 3268
Allansford 3277
Tooradin 3980
Lake Gardens 3355
Bonshaw 3352
Wallington 3222
Nicholson 3882
Sandy Point 3959
Inverleigh 3321
Ouyen 3490
Charlton 3525
Rushworth 3612
Bonnie Doon 3720
Kalimna 3909
Halls Gap 3381
Shoreham 3916
Millgrove 3799
Mount Buller 3723
Dunolly 3472
East Bairnsdale 3875
Avenel 3664
Tawonga South 3698
Nichols Point 3501
Mount Macedon 3441
Wedderburn 3518
Yallourn North 3825
Essendon West 3040
Red Hill 3937
Eagle Point 3878
Eildon 3713
Invermay Park 3350
Edenhope 3318
Waterways 3195
Nyora 3987
Yarrambat 3091
Glengarry 3854
Surf Beach 3922
Glomar Beach 3851
Longford 3851
Ironbark 3550
Cardigan 3352
Rhyll 3923
Carisbrook 3464
Tallangatta 3700
Briagolong 3860
Koondrook 3580
Selby 3159
Connewarre 3227
Little River 3211
Elmore 3558
Birregurra 3242
Omeo 3898
Gordon 3345
Kallista 3791
Somerton 3062
Dunkeld 3294
Kaniva 3419
Mount Beauty 3699
Devon Meadows 3977
Wattle Glen 3096
Bundalong 3730
Haven 3401
Mount Dandenong 3767
Badger Creek 3777
Kalorama 3766
Wye River 3234
Seaspray 3851
Hazelwood North 3840
Marlo 3888
Harcourt 3453
Lake Boga 3584
Violet Town 3669
Hotham Heights 3741
Gardenvale 3185
Wandong 3758
Bellbrae 3228
Lake Tyers Beach 3909
Nar Nar Goon North 3812
Fish Creek 3959
Ferny Creek 3786
Porepunkah 3740
Wahgunyah 3687
Dalyston 3992
Raymond Island 3880
Belgrave South 3160
Nar Nar Goon 3812
Marysville 3779
Rippleside 3215
Killara 3691 3312
Chewton 3451
Mitchell Park 3355
Port Campbell 3269
Boolarra 3870
Boort 3537
Woodstock 3751
Bangholme 3175
Keilor Lodge 3038
Lethbridge 3332
Eden Park 3757
Murchison 3610
Smiths Beach 3922
Wurruk 3850
Murtoa 3390
Flowerdale 3717
Yinnar 3869
Malmsbury 3446
Kinglake West 3757
Burnley 3121
Toongabbie 3856
Benambra 3900
Newlands Arm 3875
Silverleaves 3922
Batesford 3213
Hopetoun 3396
Strathmerton 3641
Lismore 3324
Toora 3962
Newstead 3462
Bruthen 3885
Inglewood 3517
Fairhaven 3231
Cape Schanck 3939
Penshurst 3289
Swan Reach 3903
Meeniyan 3956
Falls Creek 3699
Fingal 3939
Moorooduc 3933
Silvan 3795
Belgrave Heights 3160
Tangambalanga 3691
North Shore 3214
Smythesdale 3351
East Warburton 3799
Kilcunda 3995
Red Hill South 3937
Dinner Plain 3898
Rainbow 3424
Glenrowan 3675
Glenmaggie 3858
St Andrews 3761
Katunga 3640
Sea Lake 3533
Pyramid Hill 3575
Sassafras 3787
Merrijig 3723 3875
Peterborough 3270
Harkaway 3806
Newhaven 3925
Langwarrin South 3911
Shepparton East 3631
Pyalong 3521
Wycheproof 3527
Mount Cottrell 3024
Birchip 3483
McKenzie Hill 3451
Haddon 3351
Blind Bight 3980
Skenes Creek 3233
Taradale 3447
Kooyong 3144
Tarwin Lower 3956
Tyers 3844
Chum Creek 3777
Ross Creek 3351
Barnawartha 3688
Jamieson 3723
Snake Valley 3351
Stanhope 3623
Don Valley 3139
Kangaroo Ground 3097
Puckapunyal 3662
Wesburn 3799
Axedale 3551
Nerrina 3350
Poowong 3988
Panton Hill 3759
Hepburn 3461
Meredith 3333
Lockington 3563
Nelson 3292
Portland North 3305
Tallarook 3659
Balnarring Beach 3926
Hepburn Springs 3461
Buxton 3711
Pakenham Upper 3810
Marengo 3233
Port Albert 3971
Strathmore Heights 3041
Warrenheip 3352
Lockwood South 3551
Narrawong 3285
Loch 3945
Toolern Vale 3337
The Patch 3792
Jeparit 3423
Anakie 3213
The Honeysuckles 3851
Tolmie 3723
Goughs Bay 3723
Bulla 3428
Gruyere 3770
Nyah West 3595
Minyip 3392
Merrigum 3618
Sailors Gully 3556
Coongulla 3860
Essendon Fields 3041
Talbot 3371
Main Ridge 3928
Skipton 3361
Glenlyon 3461
Beeac 3251
Elphinstone 3448
Sunset Strip 3922
Blackwood 3458
Goornong 3557
Linton 3360
Waldara 3678
Toolamba 3614
Menzies Creek 3159
Eureka 3350
Scarsdale 3351
Dereel 3352
Tungamah 3728
Melbourne Airport 3045
Bolwarra 3305
Invergordon 3636
Tinamba 3859
Leitchville 3567
Tawonga 3697
Heathcote Junction 3758
Natimuk 3409
Cardross 3496
Mount Egerton 3352
Port Welshpool 3965
Willaura 3379
Baringhup 3463
Macarthur 3286
Gunbower 3566
Moorabbin Airport 3194
Rupanyup 3388
Leongatha South 3953
Moriac 3240
Macclesfield 3782
Sarsfield 3875
Wimbledon Heights 3922
Forrest 3236
Arthurs Seat 3936
Lysterfield South 3156
Avonsleigh 3782
Lockwood 3551
Oxley 3678
Swifts Creek 3896
Sunderland Bay 3922
Murrayville 3512
Darnum 3822
Gisborne South 3437
Buchan 3885
Derrinallum 3325
Lake Bunga 3909
Hollands Landing 3862
Walkerville 3956
Invermay 3352
Thorpdale 3835
Bakery Hill 3350
Tottenham 3012
Lindenow 3865
Lindenow South 3875
Nyah 3594
Eppalock 3551
Newmerella 3886
Seville East 3139
Woodside 3874
Beulah 3395
Tylden 3444
Tallygaroopna 3634
Wandiligong 3744
Woodside Beach 3874
Yinnar South 3869
Cannons Creek 3977
Learmonth 3352
Welshpool 3966
Willow Grove 3825
Kennett River 3234
Hoddles Creek 3139
Birdwoodton 3505
Grahamvale 3631
Merricks North 3926
Great Western 3374
Lal Lal 3352
Taggerty 3714
Milawa 3678
Simpson 3266
Lake Bolac 3351
Portland West 3305
South Wharf 3006
Girgarre 3624
Sedgwick 3551
Strathbogie 3666
Greendale 3341
Harrietville 3741
Mandurang 3551
Warneet 3980
Dumbalk 3956
Katamatite 3649
Welshmans Reef 3462
Glenburn 3717
Jindivick 3818
Tooborac 3522
Quambatook 3540
Yarroweyah 3644
Bealiba 3475
Bethanga 3691
Hopetoun Park 3340
Yanakie 3960
Colac East 3250
Drumcondra 3215
South Dudley 3995
Bullengarook 3437
Tynong 3813
Johnsonville 3902
Merricks Beach 3926
Tanjil South 3825
Jeeralang Junction 3840
Katandra West 3634
Pomonal 3381
Cavendish 3314
Moyhu 3732
Branxholme 3302
Cann River 3890
Goroke 3412
Guildford 3451
Marcus Hill 3222
Bass 3991
Gellibrand 3239
West Bendigo 3550
Koonwarra 3954
Redesdale 3444
Cottles Bridge 3099
Breamlea 3227
Undera 3629
Wangaratta South 3678
Barkers Creek 3451
Manangatang 3546
Newham 3442
Congupna 3633
Bridgewater On Loddon 3516
Dookie 3646
Toolangi 3777
Balmoral 3407
Bamawm 3561
Bendoc 3888
Bushfield 3281
Boneo 3939
Toorloo Arm 3909
Glenthompson 3293
Pioneer Bay 3984
Wharparilla 3564
Dartmoor 3304
Kinglake Central 3757
Swan Bay 3225
Koorlong 3501
Traralgon South 3844
Muckleford 3451
Warrandyte South 3134
Cabarita 3505
Ultima 3544
Barmah 3639
Newry 3859
Yellingbo 3139
Enfield 3352
Moe South 3825
Noojee 3833
Rawson 3825
Buffalo 3958
Deans Marsh 3235
Longlea 3551
Underbool 3509
Irrewarra 3249
Bandiana 3691
Barongarook 3249
Christmas Hills 3775
Napoleons 3352
Wunghnu 3635
Woodvale 3556
Alberton 3971
Moyston 3377
Smeaton 3364
Mirboo 3871
Daisy Hill 3465
Golden Gully 3555
Panmure 3265
Ravenswood 3453
Upper Plenty 3756
Cressy 3322
Merton 3715
Stony Creek 3957 3371
Thornton 3712
Walmer 3463
Echuca Village 3564
Langsborough 3971
Gladysdale 3797
Sawmill Settlement 3723
Ardmona 3629
Waaia 3637
Callignee 3844
Myers Flat 3556
Nanneella 3561
Piangil 3597
Erica 3825
Cardigan Village 3352
Taylor Bay 3713
Buln Buln 3821
Stanley 3747
Raywood 3570
Longwood 3665
Merino 3310
Mount Taylor 3875
Woolsthorpe 3276
Apsley 3319
Nungurner 3909
Rokewood 3330
Darraweit Guim 3756
Maryknoll 3812
Orrvale 3631
Wandin East 3139
Landsborough 3384
Mia Mia 3444
Woodford 3281
Kilmore East 3764
Nowa Nowa 3887
Beech Forest 3237
Wheatsheaf 3461
Dixons Creek 3775
Bayles 3981
Cowwarr 3857
Arthurs Creek 3099
Forge Creek 3875
Nilma 3821
Whorouly 3735
Burrumbeet 3352
Eldorado 3746
French Island 3921
Merbein South 3505
Woomelang 3485
Bellbridge 3691
Bena 3946
Myrniong 3341
Baddaginnie 3670
Picola 3639
Tarrawingee 3678
Tuerong 3915
Woorinen South 3588
Freshwater Creek 3217
Kirkstall 3283
Moggs Creek 3231
Cooriemungle 3268
Mailors Flat 3275
Tresco 3583
Clonbinane 3658
Denison 3858
Shelbourne 3515
Winslow 3281
Carlisle River 3239
Moonambel 3478
Neilborough 3570
Hawkesdale 3287
Tambo Upper 3885
Devon North 3971
Gormandale 3873
Yambuk 3285
Ensay 3895
Fryerstown 3451
Lexton 3352
Narbethong 3778
Whiteheads Creek 3660
Cororooke 3254
Gherang 3240
Kiewa 3691
Waubra 3352
Drouin South 3818
McLoughlins Beach 3874
Carlsruhe 3442
Durham Lead 3352
Labertouche 3816
Tarnagulla 3551
Waranga Shores 3612
Yarck 3719
Barwite 3722
North Wangaratta 3678
Tynong North 3813
Coomoora 3461
Huon Creek 3691
Amphitheatre 3468
Bearii 3641
Clarkefield 3430
Colac West 3250
Dales Creek 3341
Grassmere 3281
Trafalgar East 3824
Coimadai 3340
Kialla West 3631
Springhurst 3682
Wilby 3728
Axe Creek 3551
Dargo 3862
Hilldene 3660
Yelta 3505
Argyle 3523
Drouin West 3818
Noorat 3265
Echuca West 3564
Ryanston 3992
Cardinia 3978
Point Leo 3916
Drummond 3461
Macs Cove 3723
Oaklands Junction 3063
The Gurdies 3984
Dooen 3401
Lancaster 3620
Majorca 3465
Strath Creek 3658
Balliang 3340
Barwon Downs 3243
Boisdale 3860
Foster North 3960
Bonegilla 3691
Fernbank 3864
Merricks 3916
Wattle Bank 3995
Avalon 3212
Lyonville 3461
Tarrington 3301
Lake Hume Village 3691
Mitta Mitta 3701
Maindample 3723
Nerrena 3953
Cudgewa 3705
Goorambat 3725
Smiths Gully 3760
Tatong 3673
Eskdale 3701
Killawarra 3678
Yapeen 3451
Big Hill 3555 3231
Colbinabbin 3559
Pheasant Creek 3757
Tenby Point 3984
Wangandary 3678
Warrion 3249
Woolamai 3995
Wooragee 3747
Yandoit 3461
Catani 3981
Hmas Cerberus 3920
Pine Lodge 3631
Shelford 3329
Walwa 3709
Harrow 3317
Killarney 3283
Torrumbarry 3562
Harcourt North 3453
Outtrim 3951
Humevale 3757
Blampied 3364
Mandurang South 3551
Talgarno 3691
Cape Bridgewater 3305
Caramut 3274
Korong Vale 3520
Princetown 3269
Barongarook West 3249
Brim 3391
Quantong 3401
Whitfield 3733
Irrewillipe 3249
Merrimu 3340
Newbridge 3551
Raglan 3373
Drummond North 3446
Narre Warren East 3804
Bowenvale 3465
Bunbartha 3634
Bend Of Islands 3097
Lavers Hill 3238
Sherbrooke 3789
Yan Yean 3755
Bellarine 3223
Clematis 3782
Indigo Valley 3688
Murrabit 3579
Trafalgar South 3824
Walpeup 3507
Buffalo River 3737
Kongwak 3951
Patchewollock 3491
Hernes Oak 3825
Koonoomoo 3644
Koyuga 3622
Mardan 3953
St James 3727
Steels Creek 3775
Toolleen 3551
Colignan 3494
Kawarren 3249
Bemm River 3889
Berriwillock 3531
Emu Creek 3551
Narracan 3824
Sunday Creek 3658
Woodend North 3442
Yannathan 3981
Beverford 3590
Hazelwood South 3840
Waratah Bay 3959
Wyuna 3620
Devenish 3726
Laceby 3678
Miepoll 3666
Purnim 3278
Serpentine 3517
Staghorn Flat 3691
Elmhurst 3469
Gnarwarre 3221
Gooram 3666
Highlands 3660
Larpent 3249
Elaine 3334
Lemnos 3631
Nambrok 3847
Faraday 3451
Illowa 3282
Tallangatta Valley 3701
Metcalfe 3448
Modewarre 3240
Mount Rowan 3352
Powelltown 3797
Bungaree 3352
Dartmouth 3701
Dunnstown 3352
Howqua Inlet 3723
Nilma North 3821
Kyvalley 3621
Walhalla 3825
Watchem 3482
Berringa 3351
Dingee 3571
Jarrahmond 3888
Markwood 3678
Bagshot 3551
Ceres 3221
Glenaroua 3764
Magpie 3352
Separation Creek 3234
McMahons Creek 3799
Arcadia 3631
Calivil 3573
Dhurringile 3610
Eurobin 3739
Fulham 3851
Neerim 3831
Wiseleigh 3885
Woorinen 3589
Werrimull 3496
Iona 3815
Musk 3461
Woorndoo 3272
Port Franklin 3964
Bailieston 3608
Cheshunt 3678
Eganstown 3461
Guys Hill 3807
Meerlieu 3862
Murrindindi 3717
Spring Hill 3444
Wildwood 3429
Cudgee 3265
Nullawarre 3268
Bonang 3888
Ruffy 3666
Scotts Creek 3267
Swan Marsh 3249
Tyrendarra 3285
Willowmavin 3764
Glengarry North 3854
Johanna 3238
Lauriston 3444
Mount Moriac 3240
Ashbourne 3442
Newlyn North 3364
Swanpool 3673
Buchan South 3885
Garvoc 3265
Gorae West 3305
Kingston 3364
Koallah 3260
Mystic Park 3579
Scotsburn 3352
Toora North 3962
Burramine 3730
Killingworth 3717
Pirron Yallock 3249
Porcupine Ridge 3461
Serviceton 3420
Walpa 3875
Acheron 3714
Allendale 3364
Alma 3465
Clifton Creek 3875
Denver 3461
Eddington 3472
Lalbert 3542
Lascelles 3487
Castella 3777
Granite Rock 3875
Ripplebrook 3818
Strathdownie 3312
Sugarloaf Creek 3658
Buckley 3240
Knowsley 3523
Korweinguboora 3461
Moonlight Flat 3465 3450
Pakenham South 3810
Tallangatta South 3701
Tarra Valley 3971
Yalca 3637
Allestree 3305
Binginwarri 3966
Cashmore 3305
Mangalore 3663
Riverside 3401
Goldie 3435
Long Forest 3340
Mudgegonga 3737
Warragul South 3821
Yendon 3352
Harston 3616
Kirwans Bridge 3608
Laanecoorie 3463
Mount Camel 3523
Navigators 3352
Peechelba 3678
Glenorchy 3385
Redbank 3477
Sutton Grange 3448
Yarragon South 3823
Cobains 3851
Creightons Creek 3666
Ladys Pass 3523
Tonimbuk 3815
Broomfield 3364
Cambrian Hill 3352
Coragulac 3249
Kotupna 3638
Sebastian 3556
Trentham East 3458
Barrabool 3221
Bet Bet 3472
Evansford 3371
Hallston 3953
Heathmere 3305
Mannerim 3222
Reedy Creek 3658
Strathewen 3099
Tabilk 3607
Warncoort 3243
Deep Lead 3385
Dreeite 3249
Ellaswood 3875
Lake Charm 3581
Won Wron 3971
Kergunyah 3691
Myrrhee 3732
Neerim East 3831
Ovens 3738
Allans Flat 3691
Ancona 3715
Bridgewater 3516
Culgoa 3530
Ellinbank 3821
Navarre 3384
Crossley 3283
Freeburgh 3741
Gobur 3719
Pound Creek 3996
Seaton 3858
Springfield 3434 3544
Berrys Creek 3953
Boorolite 3723
Dederang 3691
Hesket 3442
Marnoo 3387
Merbein West 3505
Murchison North 3610
Laharum 3401
Woods Point 3723
Benloch 3435
Caniambo 3630
Cobram East 3644
Everton 3678
Monegeetta 3433
Pimpinio 3401
Kalimna West 3909
Leongatha North 3953
Lurg 3673
Mitiamo 3573
Nulla Vale 3435
Corop 3559
Murchison East 3610
Musk Vale 3461
Tol Tol 3549
Trawalla 3373
Wallace 3352
Chesney Vale 3725
Cora Lynn 3814
Hedley 3967
Bunkers Hill 3352
Gundowring 3691
Osbornes Flat 3691
Red Lion 3371
Rokeby 3821
Stradbroke 3851
Huon 3695
Jeetho 3945
Kialla East 3631
Moliagul 3472
Muckatah 3644
Munro 3862
Sandford 3312
Yeodene 3249
Bolinda 3432
Calulu 3875
Hill End 3825
Jumbunna 3951
Three Bridges 3797
Wartook 3401
Waterford Park 3658
Bamawm Extension 3564
Hazelwood 3840
Jancourt East 3266
Newlyn 3364
Noorinbee 3890
Parwan 3340
Ecklin South 3265
Gerangamete 3249
Valencia Creek 3860
Bells Beach 3228
Buckland 3740
Derrinal 3523
Winchelsea South 3241
Yabba North 3646
Dalmore 3981
Gorae 3305
Pennyroyal 3235
Sulky 3352
Tyntynder 3586
Balmattum 3666
Bambra 3241
Byrneside 3617
Kardella 3951
Maude 3331
Northwood 3660
Nullawil 3529
Whanregarwen 3714
Club Terrace 3889
Drouin East 3818
Lower Norton 3401
Strzelecki 3950
Barnawartha North 3691
Caldermeade 3984
Glen Alvie 3979
Tyntynder South 3586
Alvie 3249
Barjarg 3723
Bundalaguah 3851
Garfield North 3814
Kilmany 3851
Ondit 3249
Towong 3707
Vectis 3401
Wangoom 3279
Arawata 3951
Bete Bolong 3888
Limestone 3717
Longwood East 3666
Paraparap 3240
Ruby 3953
Shady Creek 3821
Yering 3770
Boundary Bend 3599
Cobungra 3898
Jung 3401
Streatham 3351
Wongungarra 3862
Buangor 3375
Harmers Haven 3995
Heath Hill 3981
Kaarimba 3635
Poowong North 3988
Sandy Creek 3695
Seaview 3821
Black Range 3381
Carngham 3351
Condah 3303
Neerim Junction 3832
Wairewa 3887
Yuulong 3237
Gapsted 3737
Happy Valley 3360 3549
Krowera 3945
Lima East 3673
Millbrook 3352
Vinifera 3591
Baromi 3871
Flynn 3844
Jam Jerrup 3984
Kevington 3723
Longwarry North 3816
Murroon 3243
Waterloo 3373
Wellsford 3551
Mossiface 3885
Mount Eccles 3953
Netherby 3418
Pipers Creek 3444
Reefton 3799
Tongio 3896
Yallourn 3825
Youanmite 3646
Cape Clear 3351
Carpendeit 3260
Goon Nure 3875
Maintongoon 3714
Warrenbayne 3670
Bookaar 3260
Buln Buln East 3821
Corindhap 3352
Gelantipy 3885
Hansonville 3675
Katandra 3634
Molesworth 3718
Morrisons 3334
Mumbannar 3304
Robertsons Beach 3971
Rowsley 3340
Bessiebelle 3304
Curdievale 3268
Manns Beach 3971
Mount Glasgow 3371
Ombersley 3241
Tempy 3489
Yaapeet 3424
Bengworden 3875
Beremboke 3342
Boho South 3669
Mooroopna North 3629
Springmount 3364
Wareek 3465
Ellerslie 3265
Everton Upper 3678
Nangiloc 3494
Thoona 3726
Bridge Creek 3723
Bullarto 3461
Byaduk 3301
Darlington 3271
Digby 3309
Hexham 3273
Kernot 3979
Merriang 3737
Mount Burnett 3781
Wongarra 3234
Amherst 3371
Brodribb River 3888
Budgeree 3870
Cloverlea 3822
Crossover 3821
Dean 3363
Kimbolton 3551
Kolora 3265
Marungi 3634
Molyullah 3673
Naring 3636
Stuart Mill 3477
Boolarra South 3870
Byawatha 3678
Drung 3401
Ensay North 3895
Kardella South 3950
Modella 3816
Drumborg 3304
Fawcett 3714
Girgarre East 3616
Goulburn Weir 3608
Graytown 3608
Nariel Valley 3707
Tennyson 3572
Westbury 3825
Bindi 3896
Boorhaman 3678
Costerfield 3523
Garibaldi 3352
Greta West 3675
Iraak 3494
Lake Rowan 3727
Patho 3564
Athlone 3818
Barfold 3444
Framlingham 3265
Granya 3701
Lillimur 3420
Pental Island 3586
Timor 3465
Wickliffe 3379
Winton 3673
Wooreen 3953
Barkly 3384
Bylands 3762
Clarendon 3352
Corunnun 3249
Jack River 3971
Kamarooka 3570
Lalalty 3644
Locksley 3665
Wensleydale 3241
Boorcan 3265
Castle Donnington 3585
Concongella 3384
Eastern View 3231
Keilor North 3036
Shepherds Flat 3461
Yeo 3249
Yuroke 3063
Baw Baw Village 3833
Ghin Ghin 3717
Glen Forbes 3990
Londrigan 3678
Moranding 3764
Mount Wallace 3342
Sandon 3462
Chetwynd 3312
Combienbar 3889
Plumpton 3335
Riverslea 3860
Carrajung 3844
Childers 3824
Glenhope 3444
Langkoop 3318
McKenzie Creek 3401
Pentland Hills 3341
Redcastle 3523
Tarraville 3971
Wurdiboluc 3241
Cabbage Tree Creek 3889
Carrajung Lower 3844
Grangefields 3335
South Purrumbete 3260
Wahring 3608
Willung South 3847
Wuk Wuk 3875
Zeerust 3634
Airly 3851
Greta South 3675
Korumburra South 3950
Meringur 3496
Moorabool 3213
Mount Toolebewong 3777
Reedy Flat 3895
Rosebrook 3285
Rosewhite 3737
Stewarton 3725
Strangways 3461
Upper Gundowring 3691
Waggarandall 3646
Yielima 3638
Coomboona 3629
Genoa 3891
Irrewillipe East 3249
Kerrisdale 3660
Middle Tarwin 3956
Sailors Falls 3461
Tresco West 3584
Woodleigh 3945
Yulecart 3301
Boosey 3730
Clydesdale 3461
Dunach 3371
Koorooman 3953
Lardner 3821
Macorna 3579
Mollongghip 3352
Mundoona 3635
Natte Yallock 3465
Tatyoon 3378
Vaughan 3451
Walkerville North 3956
Cosgrove 3631
Dunluce 3472
Edi Upper 3678
Lillicur 3371
Lima South 3673
Little Hampton 3458
Orford 3284
The Sisters 3265
Wannon 3301
Caveat 3660
Forbes 3764
Glenormiston South 3265
Leichardt 3516
Mountain View 3988
Poowong East 3988
Tatura East 3616
Crowlands 3377
Gheringhap 3331
Glenfyne 3266
High Camp 3764
Moolort 3465
Mountain Bay 3723
Myall 3579 3533
Norong 3682
She Oaks 3331
Speed 3488
Timmering 3561
Weering 3251
Woodfield 3715
Berrybank 3323
Byaduk North 3300
Campbelltown 3364
Chinkapook 3546
Dewhurst 3808
Glenaire 3238
Hallora 3818
Mooralla 3314
Tallandoon 3701
Wemen 3549
Wyelangta 3237
Ballendella 3561
Baynton 3444
Betley 3472
Carboor 3678
Cornishtown 3683
Dollar 3871
Mount Doran 3334
Nintingbool 3351
Wando Vale 3312
Wonwondah 3401
Chewton Bushlands 3451
Driffield 3840
Homewood 3717
King Valley 3678
Kithbrook 3666
Laang 3265
Mount Franklin 3461
Nareen 3315
Naringal 3277
Rocklyn 3364
Tragowel 3579
Bald Hills 3364
Balliang East 3340
Carwarp 3494
Docker 3678
Greta 3675
Howqua 3723
Kotta 3565
Mead 3568
Minimay 3413
Taminick 3675
Terip Terip 3719
Wallacedale 3303
Yangery 3283
Agnes 3962
Arcadia South 3631
Clydebank 3851
Dumbalk North 3956
Ebden 3691
Fern Hill 3458
Henty 3312
Kyneton South 3444
Nutfield 3099
Strathallan 3622
Trawool 3660
Weerite 3260
Yanac 3418
Bobinawarrah 3678
Brimpaen 3401
Delegate River 3888
Glengarry West 3854
Hordern Vale 3238
Horfield 3567
Lance Creek 3995
McMillans 3568
Newbury 3458
Toolamba West 3614
Victoria Valley 3294
Winnindoo 3858
Brucknell 3268
Franklinford 3461
Glen Park 3352
Green Gully 3462
Springbank 3352
Tintaldra 3708
Toolondo 3401
Upper Lurg 3673
Cooma 3616
Dingwall 3579
Exford 3338
Mount Best 3960
Murmungee 3747
Nandaly 3533
Perry Bridge 3862
Staffordshire Reef 3351
Woorarra West 3960
Adelaide Lead 3465
Bowmans Forest 3735
Bullarook 3352
Bung Bong 3465
Eurack 3251
Gerang Gerung 3418
Havelock 3465
Kerrie 3434
Kiata 3418
Ranceby 3951
St Arnaud East 3477
Staughton Vale 3340
Stonyford 3260
West Creek 3992
Whroo 3612
Windermere 3352
Bungador 3260
Cullulleraine 3496
Earlston 3669
Kanumbra 3719
Longerenong 3401
Meadow Creek 3678
Moutajup 3294
Murraydale 3586
Noradjuha 3409
Teal Point 3579
Thowgla Valley 3707
Toolong 3285
W Tree 3885
Werneth 3352
Barwidgee 3737
Bungalally 3401
Chintin 3756
Cosgrove South 3631
Konongwootong 3315
Marionvale 3634
Myrtlebank 3851
Neerim North 3832
Piries 3723
Ravenswood South 3453
Rheola 3517
Wattle Flat 3352
Yarrawalla 3575
Browns Plains 3685
Dixie 3265
Edi 3678
Ercildoune 3352
Grenville 3352
Naringal East 3277
Southern Cross 3283
Tarrengower 3463
Trida 3953
Wonga 3960
Balintore 3249
Cathcart 3377
Chapple Vale 3239
Flagstaff 3465
Glenaladale 3864
Glenormiston North 3265
Howes Creek 3723
Lower Moira 3639
Mitchellstown 3608
Mount Mercer 3352
Whorouly East 3735
Wood Wood 3596
Blowhard 3352
Boho 3669
Cowangie 3506
Flaggy Creek 3875
Goomalibee 3673
Hillcrest 3351
Koriella 3714
Marraweeney 3669
Murrawee 3586
Turtons Creek 3960
Youarang 3728
Banksia Peninsula 3875
Bumberrah 3902
Iguana Creek 3875
Karramomus 3631
Lang Lang East 3984
Pearsondale 3851
Woorinen North 3589
Adams Estate 3984
Allambee South 3871
Bangerang 3393
Bathumi 3730
Bromley 3472
Coral Bank 3691
Glen Valley 3898
Heathcote South 3523
Maroona 3377
Sutherlands Creek 3331
Tarnook 3670
Alberton West 3971
Armstrong 3377
Borung 3518
Bulart 3314
Chiltern Valley 3683
Fosterville 3557
Murgheboluc 3218
Rubicon 3712
Steiglitz 3331
Tanjil Bren 3833
Cobrico 3266
Edgecombe 3444
Gannawarra 3568
Glenrowan West 3675
Kingower 3517
Maffra West Upper 3859
Myrtle Creek 3551
Nalangil 3249
Sailors Hill 3461
Werona 3364
Wyuna East 3620
Broadwater 3301
Bullioh 3700
Bunyip North 3815
Burramine South 3730
Cassilis 3898
Deddick Valley 3888
Dundonnell 3271
Dunrobin 3312
Hensley Park 3301
Jeeralang 3840
Kancoona 3691
Licola 3858
Nirranda South 3268
Patyah 3318
Rochford 3442
Simson 3465
Tetoora Road 3821
Tyaak 3658
Barramunga 3249
Big Pats Creek 3799
Brandy Creek 3821
Dadswells Bridge 3385
Darlimurla 3871
Fairy Dell 3561 3875
Leonards Hill 3461
Moorngag 3673
Naroghid 3266
Nayook 3832
Panitya 3512
Pomborneit 3260
Tarrone 3283
Tremont 3785
Wandella 3579
Antwerp 3414
Bona Vista 3820
Devils River 3714
Emu 3475
Ferndale 3821
Gipsy Point 3891
Minhamite 3287
Monomeith 3984
Myamyn 3304
Strathkellar 3301
Tarrawarra 3775
Vesper 3833
Warrak 3377
Yambuna 3621
Bullumwaal 3875
Dergholm 3312
Durham Ox 3576
Gnotuk 3260
Kelvin View 3666
Koornalla 3844
Lamplough 3352
Langley 3444
Lilliput 3682
Mepunga West 3277
North Blackwood 3458
Percydale 3478
Scotchmans Lead 3352
St Germains 3620
Addington 3352
Archies Creek 3995
Barraport 3537
Bruarong 3749
Carapooee 3477
Diggora 3561
Kewell 3390
Lake Mundi 3312
Mooroopna North West 3616
Pastoria 3444
Seacombe 3851
Tarwin 3956
Tesbury 3260
Warrong 3283
Westmere 3351
Yundool 3727
Almurta 3979
Bahgallah 3312
Bostocks Creek 3260
Carlyle 3685
Coghills Creek 3364
Douglas 3409
Dutton Way 3305
Elingamite North 3266
Gaffneys Creek 3723
Giffard 3851
Koroop 3579
Lima 3673
Pootilla 3352
Samaria 3673
Strathlea 3364
Walkerville South 3956
Yabba South 3646
Bears Lagoon 3517
Benjeroop 3579
Boweya North 3675
Clear Lake 3409
Daltons Bridge 3568
Goongerah 3888
Kooroocheang 3364
Lillico 3820
Logan 3475
McIntyre 3472
Milltown 3304
Mininera 3351
Moormbool West 3523
Nirranda 3268
Rocklands 3401
Willung 3847
Bochara 3301
Cobaw 3442
Glenlee 3418
Hazel Park 3966
Ingliston 3342
Kurting 3517
Mannibadar 3360
Tarcombe 3666
Telford 3730
Timor West 3465
Woorarra East 3962
Bogong 3699
Boorool 3953
Callawadda 3387
Cape Otway 3233
Chocolyn 3260
Dookie College 3647
Gateway Island 3691
Gilderoy 3797
Goldsborough 3472
Greens Creek 3387
Hotspur 3303
Mincha 3575
Peechelba East 3678
Runnymede 3558
Smoko 3741
Staceys Bridge 3971
Stonehaven 3218
Allambee Reserve 3871
Ballangeich 3279
Carapook 3312
Croxton East 3301
Drumanure 3636
Gonn Crossing 3579
Jarvis Creek 3700
Katamatite East 3649
Leslie Manor 3260
Muckleford South 3462
Poolaijelo 3312
Skibo 3260
Telangatuk East 3401
Tower Hill 3283
Barrys Reef 3458
Biggara 3707
Bullarto South 3461
Corringle 3888
Creswick North 3363
Fumina South 3825
Giffard West 3851
Greenhill 3444
Icy Creek 3833
Illawarra 3381
Kalkee 3401
Kyabram South 3620
Mirranatwa 3294
Moorilim 3610
Old Tallangatta 3701
Stockdale 3862
Wehla 3518
Woodglen 3875
Yandoit Hills 3461
Yarpturk 3283
Arnold 3551
Bagshot North 3551
Blakeville 3342
Boralma 3682
Buckrabanyule 3525
Bundalong South 3730
Carag Carag 3623
Clarkes Hill 3352
Delburn 3871
Glenpatrick 3469
Greenwald 3304
Gymbowen 3401
Lubeck 3385
Mitre 3409
Mologa 3575
Natya 3597
Newfield 3268
Nuggetty 3463
Pelluebla 3727
Quandong 3030
Tubbut 3888
Anglers Rest 3898
Avonmore 3559
Bannerton 3549
Bradvale 3361
Cherokee 3434
Glengower 3370
Kergunyah South 3691
Kooloonong 3597
Moondarra 3825
Mount Richmond 3305
Peronne 3413
Pomborneit North 3260
Russells Bridge 3331
Skenes Creek North 3233
Tamleugh 3669
Telopea Downs 3420
Vervale 3814
Waitchie 3544
Yando 3537
Benayeo 3319
Berringama 3691
Brookville 3896
Burnbank 3371
Chepstowe 3351
Dreeite South 3249
Ferguson 3237
Georges Creek 3700
Kariah 3260
Kenley 3597
Korobeit 3341
Merrinee 3496
Minjah 3276
Piedmont 3833
Pine Grove 3573
Sheep Hills 3392
Stockyard Hill 3373
Tanybryn 3249
Ullina 3370
Willatook 3283
Wilsons Hill 3515
Wool Wool 3249
Archdale 3475
Colac Colac 3707
Dockers Plains 3678
East Wangaratta 3678
Elingamite 3266
Glenhope East 3522
Gooramadda 3685
Llanelly 3551
Melville Forest 3315
Molka 3666
Mount Lonarch 3468
Muskerry 3557
Narraport 3483
Upotipotpon 3669
Whitlands 3678
Wonyip 3962
Breakaway Creek 3303
Bungal 3334
Castle Creek 3691
Chatsworth 3379
Drik Drik 3304
Gainsborough 3822
Kennedys Creek 3239
Linga 3509
Main Lead 3373
Nareeb 3293
Pompapiel 3571
Prairie 3572
St Arnaud North 3477
Tahara 3301
Turriff 3488
Wallup 3401
Watsons Creek 3097
Wild Dog Valley 3953
Boweya 3675
Brimin 3685
Broughton 3418
Capels Crossing 3579
Charleroi 3695
Craigie 3465
Dawson 3858
Mount Bruno 3675
Mount Bute 3324
Murrabit West 3579
Neuarpurr 3413
Nurcoung 3401
Nurrabiel 3401
Stoneleigh 3373
Tambo Crossing 3893
Annuello 3549
Baringhup West 3463
Barunah Park 3329
Beenak 3139
Bunding 3342
Coalville 3825
Cope Cope 3480
Creek Junction 3669
Dutson 3851
Glenluce 3451
Gower 3463
Hilgay 3315
Kanyapella 3564
Montgomery 3851
Murrindal 3885
Rose River 3678
Slaty Creek 3477
St Helens Plains 3401
Torrita 3490
Vasey 3407
Wail 3401
Weatherboard 3352
Whorouly South 3735
Wilkur 3393
Wingeel 3321
Wulgulmerang 3885
Wulgulmerang East 3885
Allambee 3823
Ballyrogan 3375
Blackwarry 3844
Boorhaman North 3685
Bringenbrong 3707
Bushy Park 3860
Campbells Forest 3556
Charam 3318
East Sale 3852
Gazette 3289
Gellibrand Lower 3237
Grassdale 3302
Howqua Hills 3723
Joyces Creek 3364
Mepunga East 3277
Miram 3415
Mount Hooghly 3472
Moyarra 3951
Murra Warra 3401
Paradise 3477
Salisbury West 3517
Tamboon 3890
Timboon West 3268
Tinamba West 3859
Ullswater 3318
Wychitella 3525
Bolwarrah 3352
Brewster 3352
Bridgewater North 3516
Burramboot 3559
Cornella 3551
Dry Diggings 3461
Fairbank 3951
Fyans Creek 3381
Gillieston 3616
Heytesbury Lower 3268
Keely 3568
Leigh Creek 3352
Lucyvale 3691
Major Plains 3725
Metcalfe East 3444
Milloo 3572
Moglonemby 3666
Mount Prospect 3364
Nerrin Nerrin 3351
Noorinbee North 3890
Nullawarre North 3268
Pastoria East 3444
Rhymney 3377
Rokewood Junction 3351
Sheans Creek 3666
Simpsons Creek 3888
Vite Vite 3325
Vite Vite North 3325
Wombelano 3409
Yeungroon 3525
Bellellen 3381
Bennison 3960
Cannum 3393
Carranballac 3361
Chandlers Creek 3890
Cotswold 3465
Elevated Plains 3461
Gobarup 3559
Gringegalgona 3315
Gritjurk 3315
Homebush 3465
Hunter 3558
Lah 3393
Leaghur 3537
Lyons 3304
Merriang South 3737
Mount Alfred 3709
Nug Nug 3737
Oxley Flats 3678
Rich Avon West 3480
Tandarra 3571
Tarranyurk 3414
Upper Ryans Creek 3673
Wee Wee Rup 3568
Weeaproinah 3237
Codrington 3285
Glenmore 3340
Goschen 3585
Gowangardie 3669
Huntly North 3551
Jumbuk 3869
Karnak 3401
Lake Goldsmith 3373
Lake Lonsdale 3381
Lake Powell 3597
Ledcourt 3385
Pigeon Ponds 3407
Powlett Plains 3517
Tallangatta East 3700
Tamleugh North 3669
Tarrayoukyan 3315
Waanyarra 3551
Watchupga 3485
Whoorel 3243
Beauchamp 3579
Benwerrin 3235
Boomahnoomoonah 3728
Burrowye 3709
Butchers Ridge 3885
Carina 3512
Cathkin 3714
Coonooer Bridge 3477
Glenisla 3314
Kadnook 3318
Lake Meran 3579
Mongans Bridge 3691
Nalinga 3646
Paschendale 3315
Picola West 3639
Wargan 3505
Warrock 3312
Woodhouse 3294
Areegra 3480
Barkstead 3364
Burnewang 3558
Dorodong 3312
Fentons Creek 3518
Fieldstone 3024
Glendaruel 3363
Hinnomunjie 3898
Homerton 3304
Kanagulk 3401
Landsborough West 3384
Litchfield 3480
Maryvale 3840
Mysia 3518
Omeo Valley 3898
St Helens 3285
Wallinduc 3351
Wombat Creek 3888
Yarrawonga South 3730
Almonds 3727
Appin South 3579
Bonn 3561
Boonah 3235
Coojar 3315
Corndale 3311
Cundare North 3251
Drummartin 3570
Foxhow 3323
Gerrigerrup 3289
Kerang East 3579
Lake Marmal 3525
Roslynmead 3564
Smokeytown 3364
St Clair 3995
Tarrenlea 3315
Tutye 3490
Upton Hill 3664
Anderson 3995
Buckley Swamp 3301
Cobbannah 3862
Colbrook 3342
Cowleys Creek 3268
Cullen 3568
Glen Creek 3691
Glenbrae 3352
Gowar East 3477
Jarklin 3517
Karabeal 3294
Kellalac 3393
Llowalong 3862
Mount Bolton 3352
Normanville 3579
Pomborneit East 3249
Pranjip 3666
Pura Pura 3271
Running Creek 3691
Traynors Lagoon 3477
Wal Wal 3385
Watchem West 3482
Willenabrina 3393
Wingan River 3891
Banyena 3388
Buldah 3890
Bungeet 3726
Bungeet West 3726
Cadello 3442
Campbells Bridge 3387
Cargerie 3334
Culla 3315
Doctors Flat 3895
Gelliondale 3971
Glenlofty 3469
Grass Flat 3409
Illabarook 3351
Koetong 3704
Koo Wee Rup North 3981
Kunat 3585
Langdons Hill 3363
Lawrence 3364
Lyal 3444
Macks Creek 3971
Mena Park 3373
Mockinya 3401
Murphys Creek 3551
Norval 3377
Spargo Creek 3461
Tabor 3289
The Heart 3851
Wangarabell 3891
Warrayure 3301
Wooroonook 3525
Wootong Vale 3315
Koonda 3669
Miga Lake 3409
Mingay 3324
Nangana 3781
Narrapumelap South 3293
Nowhere Creek 3469
Paaratte 3268
Pine Mountain 3709
Reedy Lake 3579
Rossbridge 3377
Shelley 3701
Tahara Bridge 3315
Thorpdale South 3824
Tostaree 3888
Towan 3596
Wando Bridge 3312
Warrabkook 3286
Archdale Junction 3475
Ayrford 3268
Berrimal 3518
Boolarong 3960
Brenanah 3517
Caringal 3825
Claretown 3352
Crymelon 3393
Duchembegarra 3409
Dumosa 3527
Duverney 3323
Fumina 3825
Glenlogie 3469
Gre Gre South 3477
Hattah 3501
Kulwin 3490
Liparoo 3549
Maramingo Creek 3891
Middle Creek 3375
Mincha West 3568
Mittyack 3490
Morgiana 3301
Mywee 3641
Rythdale 3810
Bamganie 3333
Beazleys Bridge 3477
Brit Brit 3315
Chute 3373
Derby 3516
Dropmore 3660
Esmond 3730
Gatum 3407
Glen Wills 3898
Hiamdale 3847
Jacob Creek 3825
Joel Joel 3384
Kinnabulla 3483
Lake Fyans 3381
Matlock 3723
Riggs Creek 3666
Speewa 3585
Springdallah 3351
Tanwood 3478
Torwood 3821
Warragul West 3821
Willangie 3485
Arnold West 3551
Boolite 3392
Bornes Hill 3379
Burkes Flat 3475
Cundare 3251
Fish Point 3585
Flynns Creek 3844
Kooreh 3477
Larralea 3325
Lindsay Point 3496
Loddon Vale 3575
Madalya 3971
Mount Cameron 3370
Muntham 3315
Ozenkadnook 3413
Rathscar West 3465
Stavely 3379
Suggan Buggan 3885
Sutherland 3477
Tahara West 3310
Tarilta 3451
Tourello 3363
Towong Upper 3707
Warrenmang 3478
Willaura North 3379
Woodstock West 3463
Yatchaw 3301
Aberfeldy 3825
Basalt 3460
Bowser 3678
Broken Creek 3673
Bunguluke 3527
Burkes Bridge 3568
Calrossie 3971
Carapooee West 3477
Connewirricoo 3318
Corack East 3480
Dooboobetic 3478
Eastville 3463
Hiawatha 3971
Hunterston 3971
Jancourt 3266
Jeffcott 3480
Mafeking 3379
Nowie 3585
Purnim West 3278
Reedy Dam 3395
Sugarloaf 3234
Tandarook 3260
Wanalta 3612
Waygara 3888
Whirily 3483
Whitelaw 3950
Winnap 3304
Bete Bolong North 3888
Boxwood 3725
Bringalbert 3319
Bulgana 3377
Canary Island 3537
Clover Flat 3315
Creek View 3551
Curyo 3483
Dobie 3377
Dunneworthy 3377
Fiery Flat 3518
Havilah 3737
Kalpienung 3529
Macorna North 3568
Mepunga 3277
Moora 3612
Moyreisk 3477
Myola 3551
Narrung 3597
Rich Avon 3480
Terrappee 3525
Thologolong 3691
Tidal River 3960
Tooan 3409
Waterholes 3875
Wattle Creek 3384
Arapiles 3409
Boinka 3490
Catumnal 3537
Curdies River 3268
Enochs Point 3723
Fernihurst 3518
Framlingham East 3265
Grey River 3234
Guys Forest 3709
Hesse 3321
Jeffcott North 3480
Joel South 3384
Knebsworth 3286
Langi Kal Kal 3352
Lawloit 3418
Melwood 3875
Mount Emu 3351
Nangeela 3312
Nareewillock 3525
Neereman 3463
Nine Mile 3518
Skinners Flat 3518
Thalloo 3825
Ulupna 3641
Whipstick 3556
Winnambool 3546
Yeungroon East 3525
Appin 3579
Balook 3971
Carrajung South 3844
Chillingollah 3585
Cochranes Creek 3475
Cross Roads 3373
Darriman 3851
Denicull Creek 3377
Eaglehawk North 3556
Frenchmans 3384
Gerahmin 3546
Germantown 3741
Glenalbyn 3517
Laen 3480
Marnoo West 3387
Milnes Bridge 3579
Moolerr 3477
Mount Major 3646
Murnungin 3544
Nyerimilang 3909
Nyrraby 3585
Pittong 3360
Rathscar 3465
Sidonia 3444
Taroon 3265
Teddywaddy 3527
Teddywaddy West 3527
Banyan 3485
Broadlands 3875
Cabbage Tree 3364
Gladfield 3575
Jil Jil 3483
Kenmare 3395
Meering West 3579
Pira 3585
Point Wilson 3212
Wallaloo East 3387
Wedderburn Junction 3518
Woodstock On Loddon 3551
Aubrey 3393
Bingo Munjie 3898
Bolton 3546
Bradford 3463
Bravington 3821
Callignee North 3844
Cannie 3540
Caralulup 3371
Corack 3480
Englefield 3407
Glenloth East 3527
Grand Ridge 3870
Karyrie 3483
Lawler 3480
Licola North 3858
Massey 3482
Meatian 3585
Noorat East 3265
Painswick 3551
Terrick Terrick East 3573
Tonghi Creek 3890
Victoria Point 3294
Waarre 3269
Wallagaraugh 3891
Warmur 3482
Yarraberb 3516
Barnadown 3557
Bayindeen 3375
Blackheath 3401
Bo Peep 3351
Boole Poole 3880
Boorhaman East 3678
Bullaharre 3266
Carron 3480
Germania 3387
Gil Gil 3480
Gooroc 3477
Irishtown 3451
Laen North 3480
Lake Tyers 3887
Langi Logan 3377
Loy Yang 3844
Mount Beckworth 3363
Purdeet 3289
Sandhill Lake 3579
Shays Flat 3377
Swanwater 3477
The Cove 3268
Tyrrell 3533
Willowvale 3360
Wycheproof South 3527
Archerton 3723
Ballapur 3483
Baynton East 3444
Cape Conran 3888
Crooked River 3862
Fairley 3579
Fiskville 3342
Glenloth 3527
Gong Gong 3352
Gowanford 3544
Minmindie 3537
Mount Cole 3377
Piggoreet 3351
Pitfield 3351
Rosebery 3395
Rostron 3477
Terrick Terrick 3575
Tyrendarra East 3285
Tyrrell Downs 3533
Wallaloo 3387
Winton North 3673
Woodside North 3874
Auchmore 3570
Avon Plains 3477
Barraport West 3537
Boigbeat 3531
Calder Park 3037
Callignee South 3844
Coonooer West 3477
Gre Gre 3477
Inkerman 3472
Kinypanial 3520
Morton Plains 3482
Mount Cole Creek 3377
Mount Napier 3301
Nirranda East 3268
Nurran 3888
Nyarrin 3533
Pier Milan 3533
Powers Creek 3312
Rich Avon East 3480
Richmond Plains 3518
Towaninny 3527
Wangie 3530
Waranga 3616
Warne 3530
Westby 3579
Woosang 3518
Wychitella North 3525
Abbeyard 3737
Barunah Plains 3329
Bimbourie 3533
Chinangin 3544
Chirrip 3525
Delatite 3723
Durdidwarrah 3342
Dutson Downs 3851
Eversley 3377
Gre Gre North 3477
Gredgwin 3537
Lorquon 3418
Mount Dryden 3381
Murray-Sunset 3490
Nerring 3373
Ninyeunook 3527
Oakvale 3540
Petticoat Creek 3233
Polisbet 3585
Roses Gap 3385
Swan Hill West 3585
Swan Island 3225
Swanwater West 3480
Sylvaterre 3575
Thalia 3527
Tulkara 3384
Wattle Hill 3237
Wilsons Promontory 3960
Woolenook 3860
Yalla-Y-Poora 3378
Bael Bael 3579
Barrakee 3525
Birchip West 3483
Brimboal 3312
Dalyenong 3477
Jeruk 3527
Jilpanger 3409
Kamarooka North 3571
Kurraca 3518
Kurraca West 3518
Lake Condah 3303
Lake Eildon 3713
Manorina 3889
Marlbed 3483
Marnoo East 3477
Mount Sabine 3236
Summerlands 3922
Tabberabbera 3875
Tittybong 3542
Turoar 3546
Ultima East 3544
Winlaton 3585
Wroxham 3891
Zumsteins 3401
Bungil 3691
Cocamba 3546
Knockwood 3723
Laen East 3480
Mokepilly 3381
Moornapa 3862
Mount Eccles South 3953
Neds Corner 3496
Ninda 3533
Turriff East 3488
Winjallok 3477
Amor 3825
Big Desert 3490
Budgerum East 3579
Bulga 3586
Cocoroc 3030
Condah Swamp 3286
Dandongadale 3737
Double Bridges 3893
Gunyah 3960
Hawkhurst 3862
Kanya 3387
Lake Wongan 3373
Lindsay 3312
Pine View 3579
Stanhope South 3623
Sutton 3530
Tantaraboo 3764
Towaninny South 3527
Wandown 3549
Woolshed Flat 3518
Wulgulmerang West 3885
Yalmy 3885
Bellbird Creek 3889
Cokum 3542
Glendonald 3364
Glenfalloch 3858
Morrl Morrl 3387
Queensferry 3984
Riachella 3385
Rocky Point 3377
Shannonvale 3898
Tylden South 3444
Yawong Hills 3478
Cambarville 3779
Churchill Island 3925
Coopers Creek 3825
Elizabeth Island 3921
Granite Flat 3525
Koorool 3860
Little Desert 3418
Miowera 3862
Miralie 3596
Nunniong 3896
Ryans 3875
Straten 3533
Tottington 3477
Tyenna 3533
Wentworth 3875
Wirrate 3608
Bolangum 3387
Boola 3825
Cherrypool 3401
Cheshunt South 3678
Cobberas 3900
Cowa 3862
Deptford 3875
Errinundra 3889
Grays Bridge 3477
Jungaburra 3575
Lake Eppalock 3551
Lake Tyrrell 3533
Lerderderg 3458
Loch Valley 3833
Mirimbah 3722
Ocean Grange 3880
Stirling 3893
Tom Groggin 3707
Toombon 3825`
