/**
 * Every suburb and locality in Western Australia (WA) with the
 * postcodes its street addresses use, the most used first; localities with
 * the most addresses first. One per line: "<name> <postcode>…". Read by the
 * offline address checks in src/lib/addressVerify.ts.
 *
 * GENERATED by scripts/build-localities.mjs on 2026-09-24. Do not edit: run
 * the script again.
 *
 * Source: https://github.com/joelkoen/postcodes-au (MIT), data/localities-au.csv,
 * commit ccbc808, 2024-05-02.
 * Contains G-NAF data © Geoscape Australia, licensed by the Commonwealth of
 * Australia under the Open G-NAF End User Licence Agreement.
 */
export default `Perth 6000
Baldivis 6171
Canning Vale 6155
Scarborough 6019
Dianella 6059
Rockingham 6168
Morley 6062
East Perth 6004
South Perth 6151
Maylands 6051
Mandurah 6210
Como 6152
Ellenbrook 6069
Gosnells 6110
Bayswater 6053
Thornlie 6108
West Perth 6005
Subiaco 6008
Fremantle 6160
Rivervale 6103
Byford 6122
Armadale 6112
Willetton 6155
Yokine 6060
Halls Head 6210
Victoria Park 6100
Mount Lawley 6050
Wembley 6014
Balcatta 6021
Australind 6233
Bentley 6102
Balga 6061
Nollamara 6061
Ballajura 6066
Maddington 6109
Hamilton Hill 6163
East Victoria Park 6101
Forrestfield 6058
Osborne Park 6017
South Hedland 6722
Duncraig 6023
Clarkson 6030
Claremont 6010
Bassendean 6054
Wellard 6170
Landsdale 6065
Margaret River 6285
Piara Waters 6112
Greenfields 6210
Wanneroo 6065
Joondalup 6027
Innaloo 6018
Kelmscott 6111
Midland 6056
Spearwood 6163
Alkimos 6038
Port Kennedy 6172
Nedlands 6009
Aveley 6069
North Perth 6006
Yanchep 6035
High Wycombe 6057
West Busselton 6280
Dunsborough 6281
Kingsley 6026
South Bunbury 6230
Butler 6036
Cannington 6107
Mosman Park 6012
Waikiki 6169
Southern River 6110
Tuart Hill 6060
Success 6164
Belmont 6104
Cloverdale 6105
Palmyra 6157
Hillarys 6025
Doubleview 6018
Brabham 6055
Applecross 6153
Northam 6401
Banksia Grove 6031
Karrinyup 6018
Cottesloe 6011
Dawesville 6211
Warnbro 6169
Beckenham 6107
Kardinya 6163
Stirling 6021
Collie 6225
Secret Harbour 6173
Bibra Lake 6163
Carlisle 6101
Kewdale 6105
Greenwood 6024
Dalyellup 6230
Bunbury 6230
Falcon 6210
Leeming 6149
Harrisdale 6112
Mount Pleasant 6153
East Fremantle 6158
Girrawheen 6064
Seville Grove 6112
Eaton 6232
Mount Hawthorn 6016
Dudley Park 6210
Meadow Springs 6210
Kalamunda 6076
Marangaroo 6064
Woodvale 6026
Bicton 6157
Beechboro 6063
Swan View 6056
Padbury 6025
Newman 6753
Safety Bay 6169
Malaga 6090
Westminster 6061
Yangebup 6164
Beeliar 6164
Quinns Rocks 6030
Joondanna 6060
Queens Park 6107
Broome 6725
Bull Creek 6149
Noranda 6062
Kalgoorlie 6430
Booragoon 6154
Hammond Park 6164
Floreat 6014
Cable Beach 6726
Inglewood 6052
Wilson 6107
Coolbellup 6163
Tapping 6065
West Leederville 6007
Kununurra 6743
Geraldton 6530
Sorrento 6020
Mindarie 6030
North Fremantle 6159
Huntingdale 6110
Lesmurdie 6076
Atwell 6164
Erskine 6210
Mirrabooka 6061
Attadale 6156
Caversham 6055
Carey Park 6230
Port Hedland 6721
Bullsbrook 6084
Wangara 6065
Lakelands 6180
East Cannington 6107
Willagee 6156
Ocean Reef 6027
Narrogin 6312
Craigie 6025
St James 6102
Heathridge 6027
Bedford 6052
Shoalwater 6169
Melville 6156
Cooloongup 6168
Madeley 6065
Pinjarra 6208
Leederville 6007
Manjimup 6258
Beaconsfield 6162
Eglinton 6034
Alexander Heights 6064
Roleystone 6111
Golden Bay 6174
East Bunbury 6230
Currambine 6028
Parmelia 6167
Burswood 6100
Boulder 6432
Parkwood 6147
Broadwater 6280
Kenwick 6107
Wembley Downs 6019
Coodanup 6210
Dayton 6055
City Beach 6015
Wannanup 6210
Treeby 6164
Riverton 6148
Shenton Park 6008
Redcliffe 6104
Carine 6020
Derby 6728
Hocking 6065
Kinross 6028
Carramar 6031
Coogee 6166
Darch 6065
South Lake 6164
Welshpool 6106
Geographe 6280
Jurien Bay 6516
Busselton 6280
Aubin Grove 6164
South Yunderup 6208
North Coogee 6163
Mullaloo 6027
Ardross 6153
Bridgetown 6255
Langford 6147
Hilbert 6112
Merriwa 6030
Two Rocks 6037
South Kalgoorlie 6430
Wattle Grove 6107
Katanning 6317
Bennett Springs 6063
Shelley 6148
Madora Bay 6210
Vasse 6280
Jindalee 6036
Orelia 6167
Exmouth 6707
Woodlands 6018
York 6302
Denmark 6333
Kallaroo 6025
South Fremantle 6162
Castletown 6450
Manning 6152
Winthrop 6150
Ferndale 6148
Kalbarri 6536
Nickol 6714
The Vines 6069
Hamersley 6022
Bertram 6167
Hilton 6163
Spencer Park 6330
Midvale 6056
Merredin 6415
Crawley 6009
Lake Coogee 6166
Mount Claremont 6010
South Guildford 6055
Warwick 6024
Glendalough 6016
Iluka 6028
Helena Valley 6056
Esperance 6450
North Beach 6020
Mount Barker 6324
Gwelup 6018
O'Connor 6163
Edgewater 6027
Ascot 6104
Harvey 6220
Lathlain 6100
Kensington 6151
Wandina 6530
Camillo 6111
Swanbourne 6010
Highgate 6003
Albany 6330
Ridgewood 6030
Waroona 6215
Donnybrook 6239
Maida Vale 6057
Baynton 6714
Somerville 6430
Cockburn Central 6164
Wandi 6167
Dalkeith 6009
Yakamia 6330
Pearsall 6065
Northbridge 6003
Mundaring 6073
Churchlands 6018
Embleton 6062
Withers 6230
Singleton 6175
McKail 6330
Beldon 6027
Bayonet Head 6330
Lynwood 6147
Myaree 6154
Ashby 6065
Jandakot 6164
Rossmoyne 6148
White Gum Valley 6162
Koondoola 6064
Forrestdale 6112
Burns Beach 6028
Eden Hill 6054
Augusta 6290
Tom Price 6751
Bulgarra 6714
Murdoch 6150
Lockridge 6054
Menora 6050
Darlington 6070
Henley Brook 6055
Mount Tarcoola 6530
Ravenswood 6208
Mira Mar 6330
Cowaramup 6284
Djugun 6725
Glen Iris 6230
Gooseberry Hill 6076
Wagin 6315
Bateman 6150
Gidgegannup 6083
Connolly 6027
Quindalup 6281
Pegs Creek 6714
Middle Swan 6056
Wickham 6720
Capel 6271
Jane Brook 6056
Piccadilly 6430
Sinagra 6065
Port Denison 6525
Mount Helena 6082
Medina 6167
Haynes 6112
Alfred Cove 6154
Paraburdoo 6754
Jolimont 6014
Stratton 6056
Yallingup 6282
Salter Point 6152
Mount Nasura 6112
Wonthella 6530
Centennial Park 6330
Bellevue 6056
Moora 6510
Serpentine 6125
Glen Forrest 6071
Trigg 6029
Greenmount 6056
Lancelin 6044
Yalyalup 6280
Orana 6330
Leda 6170
Hopetoun 6348
Beresford 6530
Dongara 6525
Waggrakine 6530
Toodyay 6566
Gnangara 6077
Norseman 6443
Brentwood 6153
Bedfordale 6112
Leschenault 6233
Hannans 6430
Beverley 6304
Spalding 6530
South Boulder 6432
Guildford 6055
Rangeway 6530
Brookdale 6112
Champion Lakes 6111
Christmas Island 6798
Millbridge 6232
Kendenup 6323
Karawara 6152
Waterford 6152
Oakford 6121
Calista 6167
Kambalda West 6442
Stoneville 6081
Leonora 6438
Parkerville 6081
Karnup 6176
Mount Richon 6112
Marmion 6020
Millars Well 6714
Beachlands 6530
Kojonup 6395
Usher 6230
West Beach 6450
Wundowie 6560
Williams 6391
Lower Chittering 6084
Lower King 6330
Silver Sands 6210
Drummond Cove 6532
Lamington 6430
Binningup 6233
Gelorup 6230
Chidlow 6556
Bluff Point 6530
Denham 6537
Sunset Beach 6530
Pemberton 6260
Boddington 6390
Davenport 6230
Wyndham 6740
Utakarra 6530
Northampton 6535
Samson 6163
Southern Cross 6426
Boyanup 6237
Pingelly 6308
Bilingurr 6725
Daglish 6008
Wongan Hills 6603
Halls Creek 6770
Peppermint Grove 6011
Bruce Rock 6418
Onslow 6710
Mount Melville 6330
Martin 6110
Boyup Brook 6244
Kiara 6054
Brookton 6306
Nannup 6275
Woodbridge 6056
Watermans Bay 6020
Cunderdin 6407
Little Grove 6330
Lockyer 6330
Meekatharra 6642
Hillman 6168
Coolbinia 6050
Roebourne 6718
Bindoon 6502
Viveash 6056
Darling Downs 6122
Kellerberrin 6410
Witchcliffe 6286
Herne Hill 6056
Brockman 6701
Cervantes 6511
Furnissdale 6209
Menzies 6436
Abbey 6280
Corrigin 6375
Coolgardie 6429
Bremer Bay 6338
Bakers Hill 6562
Glenfield 6532
Hazelmere 6055
Brunswick 6224
Wiluna 6646
West Lamington 6430
Sinclair 6450
Ashfield 6054
Webberton 6530
Mandogalup 6167
Upper Swan 6069
Ocean Beach 6333
Wattleup 6166
Tarcoola Beach 6530
Chittering 6084
Middleton Beach 6330
Bushmead 6055
Gledhow 6330
Nulsen 6450
Mullewa 6630
Ravensthorpe 6346
Bouvard 6211
South Carnarvon 6701
Dalwallinu 6609
Jarrahdale 6124
Pink Lake 6450
Gingin 6503
Milpara 6330
Goomalling 6460
Quairading 6383
Barragup 6209
North Dandalup 6207
Dampier 6713
Cranbrook 6321
Gnowangerup 6335
Mundijong 6123
Walpole 6398
Woorree 6530
Walliston 6076
Ledge Point 6043
Shadforth 6333
Preston Beach 6215
Mount Magnet 6638
Mahomets Flats 6530
San Remo 6210
Morawa 6623
Perth Airport 6105
College Grove 6230
East Carnarvon 6701
Koongamia 6056
Muchea 6501
Yarloop 6218
Balingup 6253
Green Head 6514
Mount Clarence 6330
Fitzroy Crossing 6765
Morgantown 6701
Pelican Point 6230
Karratha Industrial Estate 6714
North Lake 6163
Kambalda East 6442
Leeman 6514
North Yunderup 6208
Dowerin 6461
Guilderton 6041
Whitby 6123
Peppermint Grove Beach 6271
Cardup 6122
Laverton 6440
Broomehill Village 6318
Wedgefield 6721
Victory Heights 6432
Kulin 6365
West End 6530
Kalgan 6330
Brigadoon 6069
Meckering 6405
Sawyers Valley 6074
Cuballing 6311
Darkan 6392
Deepdale 6532
Roelands 6226
Gnarabup 6285
Strathalbyn 6530
Carnamah 6517
Neerabup 6031
Kwinana Town Centre 6167
Lake Clifton 6215
Banjup 6164
Broadwood 6430
Chadwick 6450
Moresby 6530
Frankland River 6396
Dwellingup 6213
Lake Grace 6353
East Rockingham 6168
Wooroloo 6558
Coondle 6566
Mingenew 6522
Morangup 6083
Wyalkatchem 6485
Sandstone 6639
Gabbadah 6041
Orange Grove 6109
Westonia 6423
Henderson 6166
Dumbleyung 6350
Myalup 6220
Kondinin 6367
Eneabba 6518
Three Springs 6519
Hay 6333
Robinson 6330
Narembeen 6369
Mariginiup 6078
Burekup 6227
Wickepin 6370
Mahogany Creek 6072
Naval Base 6165
West Toodyay 6566
Warrenup 6330
Karratha 6714
Tambellup 6320
Pannawonica 6716
Greenbushes 6254
Anketell 6167
Koorda 6475
Woodanilling 6316
Marble Bar 6760
Collingwood Heights 6330
Stratham 6237
Tenterden 6322
Karridale 6288
Leinster 6437
Seabird 6042
Bullfinch 6484
Myrup 6450
Dardanup 6236
Mukinbudin 6479
Scotsdale 6333
Cape Burney 6532
Narrikup 6326
Eagle Bay 6281
Jerramungup 6337
Woodridge 6041
Casuarina 6167
Dardanup West 6236
Kangaroo Gully 6255
Cookernup 6219
Boya 6056
Minyirr 6725
Lange 6330
Bickley 6076
Hyden 6359
Peaceful Bay 6333
West Kalgoorlie 6430
Rottnest Island 6161
Bencubbin 6477
Hovea 6071
Carmel 6076
Herron 6211
Pickering Brook 6076
Carnarvon 6701
Allanson 6225
Salmon Gums 6445
Molloy Island 6290
Willyung 6330
Naturaliste 6281
Nyabing 6341
Perenjori 6620
Quedjinup 6281
Gibson 6448
Carabooda 6033
Wandering 6308
West Swan 6055
Cue 6640
Karloo 6530
Julimar 6567
Wilyabrup 6280
Parklands 6180
White Peak 6532
Monjingup 6450
Northcliffe 6262
Mardella 6125
Marvel Loch 6426
Deanmill 6258
Gracetown 6284
Goode Beach 6330
Home Island 6799
Windy Harbour 6262
Yallingup Siding 6282
Horrocks 6535
Pingrup 6343
Argyle 6239
Coolup 6214
Condingup 6450
Badgingarra 6521
Popanyinning 6309
Dandaragan 6507
Greenough 6532
Millendon 6056
Porongurup 6324
Lagrange 6725
Coorow 6515
Mullingar 6430
Baskerville 6056
Cossack 6720
Marbelup 6330
Karlkurla 6430
Roebuck 6725
Tammin 6409
Trayning 6488
Emu Point 6330
Nungarin 6490
Ambergate 6280
Calingiri 6569
Yalgoo 6635
Jigalong 6753
Karragullen 6111
Bolgart 6568
West Pinjarra 6208
Nilgen 6044
Burnside 6285
Munglinup 6450
Bovell 6280
Moonyoonooka 6532
Beacon 6472
Collingwood Park 6330
Nunile 6566
Karakin 6044
Bandy Creek 6450
Clackline 6564
Narngulu 6532
Jandabup 6077
Uduc 6220
Elleker 6330
Dumbarton 6566
Youngs Siding 6330
Newdegate 6355
Kronkup 6330
Stake Hill 6181
Torbay 6330
Forest Grove 6286
Kwinana Beach 6167
Kalannie 6468
Oldbury 6121
Kirup 6251
Grass Patch 6446
Napier 6330
North Plantations 6701
Williamstown 6430
Hopeland 6125
Dinninup 6244
Hope Valley 6165
Picton 6229
Metricup 6280
Prevelly 6285
Quinninup 6258
Crooked Brook 6236
Dale 6304
Rocky Gully 6397
Hamel 6215
Keysbrook 6126
Marybrook 6280
Mayanup 6244
Point Samson 6720
Rosa Brook 6285
Kukerin 6352
Boodarie 6722
Camballin 6728
Karlgarin 6358
Bejoording 6566
Pithara 6608
Middlesex 6258
Ballidu 6606
Highbury 6313
Shackleton 6386
Walkaway 6528
North Boyanup 6237
Picton East 6229
Jalbarragup 6275
Ferguson 6236
East Pingelly 6308
North West Cape 6707
Wokalup 6221
Wungong 6112
Nowergup 6032
Yealering 6372
Dingup 6258
Kulikup 6244
Springfield 6525
Kununoppin 6489
Meelon 6208
Mooliabeenee 6504
Mokine 6401
Redmond 6327
Muluckine 6401
Brookhampton 6239
Boorara Brook 6262
Dalyup 6450
Mullalyup 6252
Nambeelup 6207
Watheroo 6513
Kingsford 6701
Koolyanobbing 6427
Wonnerup 6280
Broomehill West 6318
Belhus 6069
Nornalup 6333
Minnivale 6462
Crowea 6262
Neergabby 6503
Scaddan 6447
Grass Valley 6403
Miling 6575
Bullaring 6373
Wanerie 6503
Crossman 6390
Jelcobine 6306
King River 6330
Burracoppin 6421
Dampier Peninsula 6725
Gap Ridge 6714
Ongerup 6336
Coral Bay 6701
Kudardup 6290
Coonabidgee 6503
Muckenburra 6503
North Greenbushes 6254
St George Ranges 6728
Wannamal 6505
Jardee 6258
Manypeaks 6328
Nullagine 6758
Bonniefield 6525
Kalumburu 6740
Doodlakine 6411
Meerup 6262
Nabawa 6532
Ranford 6390
Reinscourt 6280
Rosa Glen 6285
Seppings 6330
Wubin 6612
Benger 6223
Catterick 6255
Coomalbidgup 6450
Lennard Brook 6503
Nanson 6532
Talbot 6302
Upper Capel 6239
West Island 6799
Jerdacuttup 6346
Winnejup 6255
Cascade 6450
Rudds Gully 6532
Lake King 6356
Millbrook 6330
Port Albany 6330
Stove Hill 6714
Kordabup 6333
Benjinup 6255
Kentdale 6333
Manmanning 6465
Mount Hardey 6302
Arthur River 6315
Hoddys Well 6566
Walgoolan 6422
Buller 6532
Lowlands 6330
Pinjar 6078
Redgate 6286
Osmington 6285
Paradise 6236
Siesta Park 6280
Bodallin 6424
Buntine 6613
Yanmah 6258
West Coolup 6214
Yeagarup 6260
Dumberning 6312
Jingalup 6395
Ludlow 6280
Moorine Rock 6425
Waterloo 6228
Wilga 6243
Latham 6616
Perup 6258
Piesse Brook 6076
Wittenoom 6751
Broomehill East 6318
Lowden 6240
West Pingelly 6308
Neridup 6450
Yerecoin 6571
Arrino 6519
Bookara 6525
Dudinin 6363
Duranillin 6393
Ardath 6419
Babakin 6428
Channybearup 6260
Takalarup 6324
Thomson Brook 6239
Capel River 6271
Chapman Hill 6280
Mount Elphinstone 6330
Muradup 6394
Palgarup 6258
Yabberup 6239
Dangin 6383
Karrakup 6122
Spencers Brook 6401
Wadderin 6369
Wellstead 6328
Aldersyde 6306
Balbarrup 6258
Gabbin 6476
Bowelling 6225
Henty 6236
Howatharra 6532
Carbunup River 6280
Wellington Mill 6236
William Bay 6333
Gairdner 6337
North Tammin 6409
Big Grove 6330
Bow Bridge 6333
Carlotta 6275
Kwolyin 6385
Beelerup 6239
East Augusta 6290
Eastbrook 6260
Greys Plain 6701
Kundat Djaru 6770
Treeton 6284
Glenlynn 6256
Hester Brook 6255
Stirling Estate 6271
Warawarrup 6220
Wialki 6473
Cadoux 6466
Denbarker 6324
Munster 6166
Noggerup 6225
South Tammin 6409
Tanami 6770
Beechina 6556
Cold Harbour 6302
Coomberdale 6512
Cuthbert 6330
North Walpole 6398
South Greenough 6528
Hines Hill 6413
Muntadgin 6420
Piawaning 6572
South Kumminin 6368
Useless Loop 6537
Elgin 6237
Kokeby 6304
Varley 6355
Hazelvale 6333
South Plantations 6701
Beermullah 6503
Bornholm 6330
Cardiff 6225
Gascoyne Junction 6705
Harrismith 6361
Meru 6530
Southampton 6253
Forest Hill 6324
Gregory 6535
Kaloorup 6280
Lumeah 6395
Pingaring 6357
Brown Range 6701
East Beverley 6304
Hamelin Bay 6288
Mount Palmer 6426
Wedgecarrup 6315
Kookynie 6431
Lort River 6447
Bowes 6535
Hester 6255
Howick 6450
Jackitup 6335
Merivale 6450
Mogumber 6506
Nangeenan 6414
Newlands 6251
Preston Settlement 6225
Birchmont 6214
Borden 6338
Daliak 6302
Gwambygine 6302
Needilup 6336
Woogenellup 6324
Binnu 6532
Bramley 6285
East Munglinup 6450
Pindar 6631
Waterbank 6725
Wellesley 6233
Bannister 6390
Cundinup 6275
Dewars Pool 6567
Kauring 6302
Warralakin 6421
Yelverton 6280
Copley 6562
East Nannup 6275
Hill River 6521
West River 6346
Glenoran 6258
Kadathinni 6519
Marradong 6390
Narrogin Valley 6312
Pallinup 6335
Pinwernying 6317
Wagerup 6215
Boxwood Hill 6338
Cowalla 6503
Eucla 6443
Isseka 6535
Reedy 6640
Westdale 6304
Windabout 6450
Yallabatharra 6535
Yathroo 6507
Moulyinning 6351
Red Hill 6056
Acton Park 6280
Mount Walker 6369
Alma 6535
Warradarge 6518
Balladong 6302
Ginginup 6503
Ringbark 6258
Beaumont 6450
Bilbarin 6375
Irishtown 6401
Kulin West 6365
Mobrup 6395
Konnongorring 6603
Moojebing 6317
St Ronans 6302
Tincurrin 6361
Wattening 6568
Cherry Tree Pool 6395
Dudawa 6519
Mokup 6394
Sunnyside 6256
Vittoria 6230
Bunjil 6620
Korrelocking 6485
Kulja 6470
Maranup 6256
Mocardy 6603
Qualeup 6394
Redmond West 6327
Donnelly River 6258
Mumberkine 6401
Parryville 6333
Sandy Gully 6535
Tutunup 6280
Boscabel 6394
Karranadgin 6460
McAlinden 6225
Scotts Brook 6244
Torndirrup 6330
Womarden 6519
Ajana 6532
Jitarning 6365
Merkanooka 6625
Piesseville 6315
Minigin 6312
Tingledale 6333
Yoongarillup 6280
Arrowsmith East 6519
Canning Mills 6111
Collins 6260
Deepdene 6290
Irwin 6525
Jennapullin 6401
Throssell 6401
Bindi Bindi 6574
Caljie 6302
Cramphorne 6420
Eganu 6515
Narra Tarra 6532
Tardun 6628
Wandillup 6256
Bally Bally 6304
Blythewood 6208
Bonnie Rock 6479
Bowgada 6623
Burakin 6467
Changerup 6394
Lake Toolbrunup 6320
Mumballup 6225
Paulls Valley 6076
Walsall 6280
Burrup 6714
Georgina 6532
Green Range 6328
Mount Hardman 6765
North Jindong 6280
Walmsley 6330
Yornup 6256
Amelup 6338
Bambun 6503
Bulyee 6306
Gilgering 6302
Harris River 6225
Hastings 6308
Koomberkine 6461
Mindarabin 6336
Scott River East 6275
Toolibin 6312
Upper Warren 6258
Waddy Forest 6515
Bailup 6082
Canna 6627
Carrabin 6423
Herdsman 6017
Kalgup 6280
Parkfield 6233
Perillup 6324
West Popanyinning 6309
Worsley 6225
Chowerup 6244
Darradup 6275
Greenhills 6302
Gutha 6623
Jacup 6337
Jilakin 6365
Nullaki 6330
Ruabon 6280
Ucarty 6462
Yardarino 6525
Dulbelling 6383
Fairbridge 6208
Hillside 6312
Mount Hampton 6426
Mount Sheridan 6355
New Norcia 6509
Abba River 6280
Anniebrook 6280
Cullacabardee 6067
Jindong 6280
Kondut 6605
Redbank 6721
South Quairading 6383
Southern Brook 6401
Wansbrough 6320
Woottating 6562
Babbage Island 6701
Bokal 6392
Katrine 6401
Nillup 6288
Old Plains 6569
Orchid Valley 6394
Palmer 6225
Pantapin 6384
Red Gully 6503
South Trayning 6488
Tenindewa 6632
Brazier 6251
Collie Burn 6225
Dixvale 6258
Hithergreen 6280
Lake Argyle 6743
Welbungin 6477
Widgiemooltha 6443
Boallia 6280
Bobalong 6320
Boothendarra 6521
Charley Creek 6239
Codjatotine 6308
Durack 6743
Holt Rock 6355
Korbel 6415
Kuender 6353
Lake Biddy 6355
Malabaine 6401
Moodiarrup 6393
North Kukerin 6352
Paynedale 6239
South Stirling 6324
The Plains 6237
Boundain 6312
Buckland 6401
Hindmarsh 6462
Maya 6614
McBeath 6770
Nirimba 6208
Pippingarra 6722
Warner Glen 6288
West Ballidu 6606
Wongoondy 6630
Drome 6330
East Ballidu 6606
Mallee Hill 6353
Marchagee 6515
Queenwood 6239
Quindanning 6391
South Doodlakine 6411
South Lake Grace 6353
Wogolin 6370
Yornaning 6311
Beaufort River 6394
Goodlands 6468
Gwindinup 6237
Hoffman 6220
Moonies Hill 6320
Narraloggan 6302
Sabina River 6280
Walebing 6510
Wilberforce 6302
Courtenay 6288
East Wickepin 6370
Gnowellen 6328
Jibberding 6612
North Bodallin 6424
North Burngup 6353
Ryansbrook 6395
Waeel 6407
Warrachuppin 6423
West Casuarinas 6630
Carani 6569
East Bowes 6535
East Chapman 6532
Granville 6503
Green Valley 6330
Jennacubbine 6401
Kunjin 6375
Linfarne 6258
Mills Lake 6336
Mindarra 6503
Mornington 6221
North Baandee 6412
Smith Brook 6258
South Newdegate 6355
Trigwell 6244
Walyormouring 6460
Warding East 6405
Burlong 6401
Cowalellup 6336
Cullalla 6503
Jarlmadangah Burru 6728
Malebelling 6302
Namban 6512
Ogilvie 6535
The Lakes 6556
Badgebup 6317
Boyatup 6450
Cartmeticup 6316
Coblinine 6317
West Fitzgerald 6337
Youndegin 6407
Beela 6224
Carrolup 6317
East Yuna 6532
Glentromie 6509
Koojan 6510
Mettler 6328
Newcarlbeon 6475
North Lake Grace 6353
Parkeston 6434
South Burracoppin 6421
South Yelbeni 6487
Watercarrin 6407
Wongamine 6401
Yandanooka 6522
Beenong 6353
Berkshire Valley 6510
Gillingarra 6510
Lake Margarette 6475
Moondyne 6567
Morbinning 6304
Mount Madden 6356
Nukarni 6480
Orange Springs 6503
South Bodallin 6424
Tampu 6472
Wijilawarrim 6743
Yetna 6532
Yilliminning 6312
Dongolocking 6315
Doodenanning 6383
Kings Park 6005
Kojaneerup South 6328
Minding 6315
Nalyerlup 6338
Nomans Lake 6312
Palmdale 6328
Walyurin 6363
Wamenusking 6383
Wellington Forest 6236
Whiteman 6068
Adamsvale 6375
Boonanarring 6503
Borderdale 6320
Breera 6503
Culham 6566
Daadenning Creek 6410
Lexia 6079
Mollerin 6475
Nokaning 6415
Ora Banda 6431
Pintharuka 6623
Woolocutty 6369
Yarawindah 6509
Cancanning 6315
Devils Creek 6630
Dukin 6475
Eighty Mile Beach 6725
Glen Mervyn 6239
Lower Hotham 6390
Mount Hill 6528
Nambung 6521
Nunierra 6630
Quelagetting 6405
Regans Ford 6507
Scott River 6288
Wardering 6311
Yarragadee 6522
Balkuling 6383
Benjaberring 6463
Booralaming 6475
Bootenal 6532
Caraban 6041
Dartnall 6320
Forrest Beach 6271
Ikewa 6522
Kebaringup 6335
Kurrenkutten 6375
Lake Hinds 6603
Nanarup 6330
Nangetty 6522
Quellington 6302
South Yilgarn 6426
Tarin Rock 6353
Teesdale 6213
Tonebridge 6244
Toompup 6336
Boilup 6394
Boyerine 6316
East Popanyinning 6309
Ewlyamartup 6317
Gillimanning 6370
Gorge Rock 6375
Mungalup 6225
Murchison 6630
South Kununoppin 6489
Wittenoom Hills 6447
Wyening 6568
Yuna 6532
Allanooka 6525
Barrabup 6275
Dwarda 6308
Gunyidi 6513
Inkpen 6302
Jaloran 6315
Lake Ninan 6603
Little Italy 6359
Magitup 6338
Naraling 6532
Neendaling 6353
North Kellerberrin 6410
North Trayning 6488
Talgomine 6490
Wilgoyne 6479
Corinthia 6426
Cubbine 6383
Karalundi 6642
Kojarena 6532
Lake Camm 6355
Magenta 6355
Malyalling 6370
Minnenooka 6532
Ucarty West 6460
Arrowsmith 6525
Ballaying 6315
Buniche 6353
Cleary 6472
Dulyalbin 6425
Elabbin 6490
Kirk Rock 6372
North Yelbeni 6487
Talbot West 6302
Beedelup 6260
Datatine 6317
East Newdegate 6355
Glencoe 6316
Hulongine 6460
Jarrahwood 6275
Kealy 6280
Koolanooka 6623
Marracoonda 6317
Monjebup 6338
Mount Stirling 6383
Nolba 6532
Paynes Find 6612
Badgin 6302
Coyrecup 6317
Dardadine 6392
Greenwoods Valley 6405
Hacketts Gully 6076
Inggarda 6701
Inglehope 6213
Kenmare 6316
Lake Brown 6479
Meenaar 6401
Merilup 6352
North Kununoppin 6489
Nugadong 6609
Tandegin 6415
The Spectacles 6167
Westwood 6316
Badgerin Rock 6475
Bringo 6532
Cataby 6507
Dandanning 6479
Grey 6521
Holyoake 6213
Mordalup 6258
Mount Horner 6525
North Stirlings 6338
Postans 6167
West Holleton 6369
Wyola West 6407
Alexandra Bridge 6288
Ambania 6632
Broke 6398
Buckingham 6225
Cheynes 6328
Diamond Tree 6258
Karrakatta 6010
Moondah 6503
Murdong 6317
Nairibin 6350
Norpa 6415
North Moulyinning 6351
Peron 6168
Petrudor 6468
Pumphreys Bridge 6308
Wandana 6532
Xantippe 6609
Avon Valley National Park 6084
Burges 6302
Commodine 6311
Cooljarloo 6507
Ellendale 6532
Karloning 6479
Lake Muir 6258
Milo 6525
Mimegarra 6507
Mount Adams 6525
Muja 6225
Wattoning 6479
Barbalin 6479
Callcup 6260
Contine 6311
Cowcowing 6485
Ghooli 6426
Holmwood 6522
Kanowna 6431
Mooriary 6522
Mount Budd 6522
Nippering 6350
Ord River 6770
Rossmore 6401
South Kukerin 6352
West Binnu 6532
Wilga West 6243
Goomarin 6415
Kingston 6256
Lake Jasper 6260
Mount Erin 6532
Mount Ney 6447
Peerabeelup 6260
Shannon 6262
South Glencoe 6317
South Yuna 6532
Wilgarrup 6258
Biddelia 6260
Collanilling 6315
Cunjardine 6401
Dindiloa 6532
Dunn Rock 6355
Gundaring 6315
Lime Lake 6315
Lol Gray 6311
Lyalls Mill 6225
Lyndon 6701
Meda 6728
Waddington 6509
Yoganup 6275
Yoting 6383
Barberton 6510
Binduli 6430
Bullabulling 6429
Durawah 6532
Elachbutting 6479
Hamelin Pool 6532
Kweda 6306
Lockier 6522
Miamoon 6612
Mount Caroline 6410
Mulataga 6714
Northern Gully 6532
Wilbinga 6041
Burran Rock 6490
Cooya Pooya 6714
Dartmoor 6532
Eradu South 6532
Holleton 6426
Massey Bay 6701
Meeking 6392
Millstream 6716
Nembudding 6485
North Cascade 6445
Skeleton Rock 6426
South Datatine 6317
Yelbeni 6487
Baandee 6412
Badjaling 6383
Breton Bay 6043
Bullock Hills 6317
Chandler 6490
East Damboring 6606
Gabalong 6574
Learmonth 6707
Macleod 6701
Melaleuca 6079
Townsendale 6311
Turkey Hill 6426
Whim Creek 6718
Wicherina South 6532
Bandya 6440
Boodarockin 6423
Bundanoon 6522
Burma Road 6532
East Nabawa 6532
Eradu 6532
Kwelkan 6490
Marrinup 6213
Meadow 6532
Mueller Ranges 6770
Muresk 6401
Ngaanyatjarra-Giles 0872
North Wialki 6473
Stratherne 6309
Whittaker 6207
Wicherina 6532
Francois Peron National Park 6537
Londonderry 6429
Minilya 6701
Nalkain 6485
Nanutarra 6751
North Eradu 6532
Tamala Park 6030
Upper Murray 6390
Wooramel 6701
Yeal 6503
Boorabbin 6429
De Grey 6722
Fraser Range 6443
King Leopold Ranges 6728
Mardie 6714
Marne 6608
Monkey Mia 6537
Nanga 6537
Nanga Brook 6215
Springs 6308
Tibradden 6532
Warmun 6743
Yannarie 6710
Yilkari 6430
Boranup 6286
Capricorn 6642
Fimiston 6432
Fitzgerald River National Park 6346
Fortescue 6716
Kurnalpi 6431
Marrah 6532
Myara 6207
Oakajee 6532
Ularring 6436
Valentine 6532
Willare 6728
Yourdamung Lake 6225
Ashendon 6111
Brown Hill 6431
Bulong 6431
Doobarda 6112
Dryandra 6311
East Lyons River 6705
Ennuin 6484
Indee 6721
Leeuwin 6290
Mount Burges 6429
Mount Holland 6426
Mount Jackson 6426
Mount Observation 6302
Rockwell 6532
Sandsprings 6532
Shotts 6225
Strelley 6721
Walyunga National Park 6084
Wedge Island 6044
Cape Arid 6452
Cocklebiddy 6443
Cooladar Hill 6638
Coolcalalaya 6532
Dundas 6443
Emu Flat 6431
Flynn 6302
Gibb 6743
Gnoorea 6714
Hickety 6532
Karramindie 6429
Keralup 6182
Lake Austin 6640
Lakewood 6431
Madura 6443
Mount Anketell 6714
Mulga Downs 6751
Mundrabilla 6443
Peedamulla 6710
Rawlinna 6434
Rothsay 6620
Stirling Range National Park 6338
Sturt Creek 6770
Talisker 6701
Tjirrkarli 0872
Toolonga 6532
Vancouver Peninsula 6330
Yellowdine 6426
Balla Balla 6714
Beadell 6440
Buraminya 6452
Cane 6710
Cape Le Grand 6450
Carrarang 6532
Cosmo Newbery 6440
Daggar Hills 6638
Drysdale River 6740
Eurardy 6532
Exmouth Gulf 6707
Feysville 6431
Fitzgerald 6337
Flint 6302
Forrest 6434
Forrestania 6359
Frenchman Bay 6330
Gascoyne River 6705
Gibson Desert South 0872
Higginsville 6443
Karijini 6751
Kumarina 6642
Lake Darlot 6438
Maitland 6714
Mount Lindesay 6333
Mount Sheila 6751
Mouroubra 6472
Mundabullangana 6721
North Bannister 6390
Oakley 6208
Parker Range 6426
Point Grey 6208
Reservoir 6076
Rocklea 6751
Tamala 6532
Trent 6333
Warburton 6431
Woodleigh 6701
Woolgorong 6630
Wuraming 6390
Yalardy 6701
Yandoo Creek 6701
Yebble 6285`
