/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessSlugRouteRouteImport } from './routes/$businessSlug/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BusinessSlugAnalyticsRouteImport } from './routes/$businessSlug/analytics'
import { Route as BusinessSlugNotesRouteImport } from './routes/$businessSlug/notes'
import { Route as BusinessSlugScheduleRouteImport } from './routes/$businessSlug/schedule'
import { Route as BusinessSlugSettingsRouteImport } from './routes/$businessSlug/settings'
import { Route as BusinessSlugClientsIndexRouteImport } from './routes/$businessSlug/clients/index'
import { Route as BusinessSlugReportsIndexRouteImport } from './routes/$businessSlug/reports/index'
import { Route as BusinessSlugReportsReportIdRouteImport } from './routes/$businessSlug/reports/$reportId'
import { Route as BusinessSlugReportsNewRouteImport } from './routes/$businessSlug/reports/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BusinessSlugReportsTemplatesIndexRouteImport } from './routes/$businessSlug/reports/templates/index'
import { Route as BusinessSlugReportsTemplatesTemplateIdRouteImport } from './routes/$businessSlug/reports/templates/$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRouteRoute = BusinessSlugRouteRouteImport.update({
  id: '/$businessSlug',
  path: '/$businessSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugAnalyticsRoute = BusinessSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugNotesRoute = BusinessSlugNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugScheduleRoute = BusinessSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugSettingsRoute = BusinessSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugClientsIndexRoute =
  BusinessSlugClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsIndexRoute =
  BusinessSlugReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsReportIdRoute =
  BusinessSlugReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsNewRoute = BusinessSlugReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugReportsTemplatesIndexRoute =
  BusinessSlugReportsTemplatesIndexRouteImport.update({
    id: '/reports/templates/',
    path: '/reports/templates/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsTemplatesTemplateIdRoute =
  BusinessSlugReportsTemplatesTemplateIdRouteImport.update({
    id: '/reports/templates/$templateId',
    path: '/reports/templates/$templateId',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$businessSlug/analytics': typeof BusinessSlugAnalyticsRoute
  '/$businessSlug/notes': typeof BusinessSlugNotesRoute
  '/$businessSlug/schedule': typeof BusinessSlugScheduleRoute
  '/$businessSlug/settings': typeof BusinessSlugSettingsRoute
  '/$businessSlug/reports/$reportId': typeof BusinessSlugReportsReportIdRoute
  '/$businessSlug/reports/new': typeof BusinessSlugReportsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$businessSlug/clients/': typeof BusinessSlugClientsIndexRoute
  '/$businessSlug/reports/': typeof BusinessSlugReportsIndexRoute
  '/$businessSlug/reports/templates/$templateId': typeof BusinessSlugReportsTemplatesTemplateIdRoute
  '/$businessSlug/reports/templates/': typeof BusinessSlugReportsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$businessSlug/analytics': typeof BusinessSlugAnalyticsRoute
  '/$businessSlug/notes': typeof BusinessSlugNotesRoute
  '/$businessSlug/schedule': typeof BusinessSlugScheduleRoute
  '/$businessSlug/settings': typeof BusinessSlugSettingsRoute
  '/$businessSlug/reports/$reportId': typeof BusinessSlugReportsReportIdRoute
  '/$businessSlug/reports/new': typeof BusinessSlugReportsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$businessSlug/clients': typeof BusinessSlugClientsIndexRoute
  '/$businessSlug/reports': typeof BusinessSlugReportsIndexRoute
  '/$businessSlug/reports/templates/$templateId': typeof BusinessSlugReportsTemplatesTemplateIdRoute
  '/$businessSlug/reports/templates': typeof BusinessSlugReportsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$businessSlug/analytics': typeof BusinessSlugAnalyticsRoute
  '/$businessSlug/notes': typeof BusinessSlugNotesRoute
  '/$businessSlug/schedule': typeof BusinessSlugScheduleRoute
  '/$businessSlug/settings': typeof BusinessSlugSettingsRoute
  '/$businessSlug/reports/$reportId': typeof BusinessSlugReportsReportIdRoute
  '/$businessSlug/reports/new': typeof BusinessSlugReportsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$businessSlug/clients/': typeof BusinessSlugClientsIndexRoute
  '/$businessSlug/reports/': typeof BusinessSlugReportsIndexRoute
  '/$businessSlug/reports/templates/$templateId': typeof BusinessSlugReportsTemplatesTemplateIdRoute
  '/$businessSlug/reports/templates/': typeof BusinessSlugReportsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$businessSlug'
    | '/login'
    | '/onboarding'
    | '/$businessSlug/analytics'
    | '/$businessSlug/notes'
    | '/$businessSlug/schedule'
    | '/$businessSlug/settings'
    | '/$businessSlug/reports/$reportId'
    | '/$businessSlug/reports/new'
    | '/api/auth/$'
    | '/$businessSlug/clients/'
    | '/$businessSlug/reports/'
    | '/$businessSlug/reports/templates/$templateId'
    | '/$businessSlug/reports/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$businessSlug'
    | '/login'
    | '/onboarding'
    | '/$businessSlug/analytics'
    | '/$businessSlug/notes'
    | '/$businessSlug/schedule'
    | '/$businessSlug/settings'
    | '/$businessSlug/reports/$reportId'
    | '/$businessSlug/reports/new'
    | '/api/auth/$'
    | '/$businessSlug/clients'
    | '/$businessSlug/reports'
    | '/$businessSlug/reports/templates/$templateId'
    | '/$businessSlug/reports/templates'
  id:
    | '__root__'
    | '/'
    | '/$businessSlug'
    | '/login'
    | '/onboarding'
    | '/$businessSlug/analytics'
    | '/$businessSlug/notes'
    | '/$businessSlug/schedule'
    | '/$businessSlug/settings'
    | '/$businessSlug/reports/$reportId'
    | '/$businessSlug/reports/new'
    | '/api/auth/$'
    | '/$businessSlug/clients/'
    | '/$businessSlug/reports/'
    | '/$businessSlug/reports/templates/$templateId'
    | '/$businessSlug/reports/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessSlugRouteRoute: typeof BusinessSlugRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug': {
      id: '/$businessSlug'
      path: '/$businessSlug'
      fullPath: '/$businessSlug'
      preLoaderRoute: typeof BusinessSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/analytics': {
      id: '/$businessSlug/analytics'
      path: '/analytics'
      fullPath: '/$businessSlug/analytics'
      preLoaderRoute: typeof BusinessSlugAnalyticsRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/notes': {
      id: '/$businessSlug/notes'
      path: '/notes'
      fullPath: '/$businessSlug/notes'
      preLoaderRoute: typeof BusinessSlugNotesRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/schedule': {
      id: '/$businessSlug/schedule'
      path: '/schedule'
      fullPath: '/$businessSlug/schedule'
      preLoaderRoute: typeof BusinessSlugScheduleRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings': {
      id: '/$businessSlug/settings'
      path: '/settings'
      fullPath: '/$businessSlug/settings'
      preLoaderRoute: typeof BusinessSlugSettingsRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/clients/': {
      id: '/$businessSlug/clients/'
      path: '/clients'
      fullPath: '/$businessSlug/clients/'
      preLoaderRoute: typeof BusinessSlugClientsIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/': {
      id: '/$businessSlug/reports/'
      path: '/reports'
      fullPath: '/$businessSlug/reports/'
      preLoaderRoute: typeof BusinessSlugReportsIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/$reportId': {
      id: '/$businessSlug/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/$businessSlug/reports/$reportId'
      preLoaderRoute: typeof BusinessSlugReportsReportIdRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/new': {
      id: '/$businessSlug/reports/new'
      path: '/reports/new'
      fullPath: '/$businessSlug/reports/new'
      preLoaderRoute: typeof BusinessSlugReportsNewRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/reports/templates/': {
      id: '/$businessSlug/reports/templates/'
      path: '/reports/templates'
      fullPath: '/$businessSlug/reports/templates/'
      preLoaderRoute: typeof BusinessSlugReportsTemplatesIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/templates/$templateId': {
      id: '/$businessSlug/reports/templates/$templateId'
      path: '/reports/templates/$templateId'
      fullPath: '/$businessSlug/reports/templates/$templateId'
      preLoaderRoute: typeof BusinessSlugReportsTemplatesTemplateIdRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
  }
}

interface BusinessSlugRouteRouteChildren {
  BusinessSlugAnalyticsRoute: typeof BusinessSlugAnalyticsRoute
  BusinessSlugNotesRoute: typeof BusinessSlugNotesRoute
  BusinessSlugScheduleRoute: typeof BusinessSlugScheduleRoute
  BusinessSlugSettingsRoute: typeof BusinessSlugSettingsRoute
  BusinessSlugReportsReportIdRoute: typeof BusinessSlugReportsReportIdRoute
  BusinessSlugReportsNewRoute: typeof BusinessSlugReportsNewRoute
  BusinessSlugClientsIndexRoute: typeof BusinessSlugClientsIndexRoute
  BusinessSlugReportsIndexRoute: typeof BusinessSlugReportsIndexRoute
  BusinessSlugReportsTemplatesTemplateIdRoute: typeof BusinessSlugReportsTemplatesTemplateIdRoute
  BusinessSlugReportsTemplatesIndexRoute: typeof BusinessSlugReportsTemplatesIndexRoute
}

const BusinessSlugRouteRouteChildren: BusinessSlugRouteRouteChildren = {
  BusinessSlugAnalyticsRoute: BusinessSlugAnalyticsRoute,
  BusinessSlugNotesRoute: BusinessSlugNotesRoute,
  BusinessSlugScheduleRoute: BusinessSlugScheduleRoute,
  BusinessSlugSettingsRoute: BusinessSlugSettingsRoute,
  BusinessSlugReportsReportIdRoute: BusinessSlugReportsReportIdRoute,
  BusinessSlugReportsNewRoute: BusinessSlugReportsNewRoute,
  BusinessSlugClientsIndexRoute: BusinessSlugClientsIndexRoute,
  BusinessSlugReportsIndexRoute: BusinessSlugReportsIndexRoute,
  BusinessSlugReportsTemplatesTemplateIdRoute:
    BusinessSlugReportsTemplatesTemplateIdRoute,
  BusinessSlugReportsTemplatesIndexRoute:
    BusinessSlugReportsTemplatesIndexRoute,
}

const BusinessSlugRouteRouteWithChildren =
  BusinessSlugRouteRoute._addFileChildren(BusinessSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessSlugRouteRoute: BusinessSlugRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
