/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessSlugRouteRouteImport } from './routes/$businessSlug/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TwoStepRouteImport } from './routes/two-step'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BusinessSlugAnalyticsRouteImport } from './routes/$businessSlug/analytics'
import { Route as BusinessSlugJobRouteRouteImport } from './routes/$businessSlug/job/route'
import { Route as BusinessSlugLeadsRouteImport } from './routes/$businessSlug/leads'
import { Route as BusinessSlugNotesRouteImport } from './routes/$businessSlug/notes'
import { Route as BusinessSlugProductsRouteImport } from './routes/$businessSlug/products'
import { Route as BusinessSlugScheduleRouteImport } from './routes/$businessSlug/schedule'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as StartTokenRouteImport } from './routes/start.$token'
import { Route as BusinessSlugClientsIndexRouteImport } from './routes/$businessSlug/clients/index'
import { Route as BusinessSlugJobIndexRouteImport } from './routes/$businessSlug/job/index'
import { Route as BusinessSlugJobRecurringRouteImport } from './routes/$businessSlug/job/recurring'
import { Route as BusinessSlugReportsIndexRouteImport } from './routes/$businessSlug/reports/index'
import { Route as BusinessSlugReportsReportIdRouteImport } from './routes/$businessSlug/reports/$reportId'
import { Route as BusinessSlugReportsNewRouteImport } from './routes/$businessSlug/reports/new'
import { Route as BusinessSlugSettingsIndexRouteImport } from './routes/$businessSlug/settings/index'
import { Route as BusinessSlugSettingsAboutRouteImport } from './routes/$businessSlug/settings/about'
import { Route as BusinessSlugSettingsAppearanceRouteImport } from './routes/$businessSlug/settings/appearance'
import { Route as BusinessSlugSettingsBusinessRouteImport } from './routes/$businessSlug/settings/business'
import { Route as BusinessSlugSettingsDetailsRouteImport } from './routes/$businessSlug/settings/details'
import { Route as BusinessSlugSettingsSignInRouteImport } from './routes/$businessSlug/settings/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BusinessSlugReportsTemplatesIndexRouteImport } from './routes/$businessSlug/reports/templates/index'
import { Route as BusinessSlugReportsTemplatesTemplateIdRouteImport } from './routes/$businessSlug/reports/templates/$templateId'
import { Route as BusinessSlugSettingsLicenceIndexRouteImport } from './routes/$businessSlug/settings/licence/index'
import { Route as BusinessSlugSettingsLicenceLicenceIdRouteImport } from './routes/$businessSlug/settings/licence/$licenceId'
import { Route as BusinessSlugSettingsLicenceNewRouteImport } from './routes/$businessSlug/settings/licence/new'
import { Route as BusinessSlugSettingsReportsIndexRouteImport } from './routes/$businessSlug/settings/reports/index'
import { Route as BusinessSlugSettingsReportsAnswersRouteImport } from './routes/$businessSlug/settings/reports/answers'
import { Route as BusinessSlugSettingsTeamIndexRouteImport } from './routes/$businessSlug/settings/team/index'
import { Route as BusinessSlugSettingsTeamMemberIdRouteImport } from './routes/$businessSlug/settings/team/$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRouteRoute = BusinessSlugRouteRouteImport.update({
  id: '/$businessSlug',
  path: '/$businessSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoStepRoute = TwoStepRouteImport.update({
  id: '/two-step',
  path: '/two-step',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugAnalyticsRoute = BusinessSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugJobRouteRoute = BusinessSlugJobRouteRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugLeadsRoute = BusinessSlugLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugNotesRoute = BusinessSlugNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugProductsRoute = BusinessSlugProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugScheduleRoute = BusinessSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StartTokenRoute = StartTokenRouteImport.update({
  id: '/start/$token',
  path: '/start/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugClientsIndexRoute =
  BusinessSlugClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugJobIndexRoute = BusinessSlugJobIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessSlugJobRouteRoute,
} as any)
const BusinessSlugJobRecurringRoute =
  BusinessSlugJobRecurringRouteImport.update({
    id: '/recurring',
    path: '/recurring',
    getParentRoute: () => BusinessSlugJobRouteRoute,
  } as any)
const BusinessSlugReportsIndexRoute =
  BusinessSlugReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsReportIdRoute =
  BusinessSlugReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsNewRoute = BusinessSlugReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => BusinessSlugRouteRoute,
} as any)
const BusinessSlugSettingsIndexRoute =
  BusinessSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsAboutRoute =
  BusinessSlugSettingsAboutRouteImport.update({
    id: '/settings/about',
    path: '/settings/about',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsAppearanceRoute =
  BusinessSlugSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsBusinessRoute =
  BusinessSlugSettingsBusinessRouteImport.update({
    id: '/settings/business',
    path: '/settings/business',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsDetailsRoute =
  BusinessSlugSettingsDetailsRouteImport.update({
    id: '/settings/details',
    path: '/settings/details',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsSignInRoute =
  BusinessSlugSettingsSignInRouteImport.update({
    id: '/settings/sign-in',
    path: '/settings/sign-in',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugReportsTemplatesIndexRoute =
  BusinessSlugReportsTemplatesIndexRouteImport.update({
    id: '/reports/templates/',
    path: '/reports/templates/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugReportsTemplatesTemplateIdRoute =
  BusinessSlugReportsTemplatesTemplateIdRouteImport.update({
    id: '/reports/templates/$templateId',
    path: '/reports/templates/$templateId',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsLicenceIndexRoute =
  BusinessSlugSettingsLicenceIndexRouteImport.update({
    id: '/settings/licence/',
    path: '/settings/licence/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsLicenceLicenceIdRoute =
  BusinessSlugSettingsLicenceLicenceIdRouteImport.update({
    id: '/settings/licence/$licenceId',
    path: '/settings/licence/$licenceId',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsLicenceNewRoute =
  BusinessSlugSettingsLicenceNewRouteImport.update({
    id: '/settings/licence/new',
    path: '/settings/licence/new',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsReportsIndexRoute =
  BusinessSlugSettingsReportsIndexRouteImport.update({
    id: '/settings/reports/',
    path: '/settings/reports/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsReportsAnswersRoute =
  BusinessSlugSettingsReportsAnswersRouteImport.update({
    id: '/settings/reports/answers',
    path: '/settings/reports/answers',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsTeamIndexRoute =
  BusinessSlugSettingsTeamIndexRouteImport.update({
    id: '/settings/team/',
    path: '/settings/team/',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)
const BusinessSlugSettingsTeamMemberIdRoute =
  BusinessSlugSettingsTeamMemberIdRouteImport.update({
    id: '/settings/team/$memberId',
    path: '/settings/team/$memberId',
    getParentRoute: () => BusinessSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/two-step': typeof TwoStepRoute
  '/welcome': typeof WelcomeRoute
  '/$businessSlug/job': typeof BusinessSlugJobRouteRouteWithChildren
  '/$businessSlug/analytics': typeof BusinessSlugAnalyticsRoute
  '/$businessSlug/leads': typeof BusinessSlugLeadsRoute
  '/$businessSlug/notes': typeof BusinessSlugNotesRoute
  '/$businessSlug/products': typeof BusinessSlugProductsRoute
  '/$businessSlug/schedule': typeof BusinessSlugScheduleRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/$token': typeof StartTokenRoute
  '/$businessSlug/job/recurring': typeof BusinessSlugJobRecurringRoute
  '/$businessSlug/reports/$reportId': typeof BusinessSlugReportsReportIdRoute
  '/$businessSlug/reports/new': typeof BusinessSlugReportsNewRoute
  '/$businessSlug/settings/about': typeof BusinessSlugSettingsAboutRoute
  '/$businessSlug/settings/appearance': typeof BusinessSlugSettingsAppearanceRoute
  '/$businessSlug/settings/business': typeof BusinessSlugSettingsBusinessRoute
  '/$businessSlug/settings/details': typeof BusinessSlugSettingsDetailsRoute
  '/$businessSlug/settings/sign-in': typeof BusinessSlugSettingsSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$businessSlug/clients/': typeof BusinessSlugClientsIndexRoute
  '/$businessSlug/job/': typeof BusinessSlugJobIndexRoute
  '/$businessSlug/reports/': typeof BusinessSlugReportsIndexRoute
  '/$businessSlug/settings/': typeof BusinessSlugSettingsIndexRoute
  '/$businessSlug/reports/templates/$templateId': typeof BusinessSlugReportsTemplatesTemplateIdRoute
  '/$businessSlug/settings/licence/$licenceId': typeof BusinessSlugSettingsLicenceLicenceIdRoute
  '/$businessSlug/settings/licence/new': typeof BusinessSlugSettingsLicenceNewRoute
  '/$businessSlug/settings/reports/answers': typeof BusinessSlugSettingsReportsAnswersRoute
  '/$businessSlug/settings/team/$memberId': typeof BusinessSlugSettingsTeamMemberIdRoute
  '/$businessSlug/reports/templates/': typeof BusinessSlugReportsTemplatesIndexRoute
  '/$businessSlug/settings/licence/': typeof BusinessSlugSettingsLicenceIndexRoute
  '/$businessSlug/settings/reports/': typeof BusinessSlugSettingsReportsIndexRoute
  '/$businessSlug/settings/team/': typeof BusinessSlugSettingsTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/two-step': typeof TwoStepRoute
  '/welcome': typeof WelcomeRoute
  '/$businessSlug/analytics': typeof BusinessSlugAnalyticsRoute
  '/$businessSlug/leads': typeof BusinessSlugLeadsRoute
  '/$businessSlug/notes': typeof BusinessSlugNotesRoute
  '/$businessSlug/products': typeof BusinessSlugProductsRoute
  '/$businessSlug/schedule': typeof BusinessSlugScheduleRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/$token': typeof StartTokenRoute
  '/$businessSlug/job/recurring': typeof BusinessSlugJobRecurringRoute
  '/$businessSlug/reports/$reportId': typeof BusinessSlugReportsReportIdRoute
  '/$businessSlug/reports/new': typeof BusinessSlugReportsNewRoute
  '/$businessSlug/settings/about': typeof BusinessSlugSettingsAboutRoute
  '/$businessSlug/settings/appearance': typeof BusinessSlugSettingsAppearanceRoute
  '/$businessSlug/settings/business': typeof BusinessSlugSettingsBusinessRoute
  '/$businessSlug/settings/details': typeof BusinessSlugSettingsDetailsRoute
  '/$businessSlug/settings/sign-in': typeof BusinessSlugSettingsSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$businessSlug/clients': typeof BusinessSlugClientsIndexRoute
  '/$businessSlug/job': typeof BusinessSlugJobIndexRoute
  '/$businessSlug/reports': typeof BusinessSlugReportsIndexRoute
  '/$businessSlug/settings': typeof BusinessSlugSettingsIndexRoute
  '/$businessSlug/reports/templates/$templateId': typeof BusinessSlugReportsTemplatesTemplateIdRoute
  '/$businessSlug/settings/licence/$licenceId': typeof BusinessSlugSettingsLicenceLicenceIdRoute
  '/$businessSlug/settings/licence/new': typeof BusinessSlugSettingsLicenceNewRoute
  '/$businessSlug/settings/reports/answers': typeof BusinessSlugSettingsReportsAnswersRoute
  '/$businessSlug/settings/team/$memberId': typeof BusinessSlugSettingsTeamMemberIdRoute
  '/$businessSlug/reports/templates': typeof BusinessSlugReportsTemplatesIndexRoute
  '/$businessSlug/settings/licence': typeof BusinessSlugSettingsLicenceIndexRoute
  '/$businessSlug/settings/reports': typeof BusinessSlugSettingsReportsIndexRoute
  '/$businessSlug/settings/team': typeof BusinessSlugSettingsTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$businessSlug': typeof BusinessSlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/two-step': typeof TwoStepRoute
  '/welcome': typeof WelcomeRoute
  '/$businessSlug/job': typeof BusinessSlugJobRouteRouteWithChildren
  '/$businessSlug/analytics': typeof BusinessSlugAnalyticsRoute
  '/$businessSlug/leads': typeof BusinessSlugLeadsRoute
  '/$businessSlug/notes': typeof BusinessSlugNotesRoute
  '/$businessSlug/products': typeof BusinessSlugProductsRoute
  '/$businessSlug/schedule': typeof BusinessSlugScheduleRoute
  '/join/$token': typeof JoinTokenRoute
  '/start/$token': typeof StartTokenRoute
  '/$businessSlug/job/recurring': typeof BusinessSlugJobRecurringRoute
  '/$businessSlug/reports/$reportId': typeof BusinessSlugReportsReportIdRoute
  '/$businessSlug/reports/new': typeof BusinessSlugReportsNewRoute
  '/$businessSlug/settings/about': typeof BusinessSlugSettingsAboutRoute
  '/$businessSlug/settings/appearance': typeof BusinessSlugSettingsAppearanceRoute
  '/$businessSlug/settings/business': typeof BusinessSlugSettingsBusinessRoute
  '/$businessSlug/settings/details': typeof BusinessSlugSettingsDetailsRoute
  '/$businessSlug/settings/sign-in': typeof BusinessSlugSettingsSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$businessSlug/clients/': typeof BusinessSlugClientsIndexRoute
  '/$businessSlug/job/': typeof BusinessSlugJobIndexRoute
  '/$businessSlug/reports/': typeof BusinessSlugReportsIndexRoute
  '/$businessSlug/settings/': typeof BusinessSlugSettingsIndexRoute
  '/$businessSlug/reports/templates/$templateId': typeof BusinessSlugReportsTemplatesTemplateIdRoute
  '/$businessSlug/settings/licence/$licenceId': typeof BusinessSlugSettingsLicenceLicenceIdRoute
  '/$businessSlug/settings/licence/new': typeof BusinessSlugSettingsLicenceNewRoute
  '/$businessSlug/settings/reports/answers': typeof BusinessSlugSettingsReportsAnswersRoute
  '/$businessSlug/settings/team/$memberId': typeof BusinessSlugSettingsTeamMemberIdRoute
  '/$businessSlug/reports/templates/': typeof BusinessSlugReportsTemplatesIndexRoute
  '/$businessSlug/settings/licence/': typeof BusinessSlugSettingsLicenceIndexRoute
  '/$businessSlug/settings/reports/': typeof BusinessSlugSettingsReportsIndexRoute
  '/$businessSlug/settings/team/': typeof BusinessSlugSettingsTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$businessSlug'
    | '/login'
    | '/onboarding'
    | '/two-step'
    | '/welcome'
    | '/$businessSlug/job'
    | '/$businessSlug/analytics'
    | '/$businessSlug/leads'
    | '/$businessSlug/notes'
    | '/$businessSlug/products'
    | '/$businessSlug/schedule'
    | '/join/$token'
    | '/start/$token'
    | '/$businessSlug/job/recurring'
    | '/$businessSlug/reports/$reportId'
    | '/$businessSlug/reports/new'
    | '/$businessSlug/settings/about'
    | '/$businessSlug/settings/appearance'
    | '/$businessSlug/settings/business'
    | '/$businessSlug/settings/details'
    | '/$businessSlug/settings/sign-in'
    | '/api/auth/$'
    | '/$businessSlug/clients/'
    | '/$businessSlug/job/'
    | '/$businessSlug/reports/'
    | '/$businessSlug/settings/'
    | '/$businessSlug/reports/templates/$templateId'
    | '/$businessSlug/settings/licence/$licenceId'
    | '/$businessSlug/settings/licence/new'
    | '/$businessSlug/settings/reports/answers'
    | '/$businessSlug/settings/team/$memberId'
    | '/$businessSlug/reports/templates/'
    | '/$businessSlug/settings/licence/'
    | '/$businessSlug/settings/reports/'
    | '/$businessSlug/settings/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$businessSlug'
    | '/login'
    | '/onboarding'
    | '/two-step'
    | '/welcome'
    | '/$businessSlug/analytics'
    | '/$businessSlug/leads'
    | '/$businessSlug/notes'
    | '/$businessSlug/products'
    | '/$businessSlug/schedule'
    | '/join/$token'
    | '/start/$token'
    | '/$businessSlug/job/recurring'
    | '/$businessSlug/reports/$reportId'
    | '/$businessSlug/reports/new'
    | '/$businessSlug/settings/about'
    | '/$businessSlug/settings/appearance'
    | '/$businessSlug/settings/business'
    | '/$businessSlug/settings/details'
    | '/$businessSlug/settings/sign-in'
    | '/api/auth/$'
    | '/$businessSlug/clients'
    | '/$businessSlug/job'
    | '/$businessSlug/reports'
    | '/$businessSlug/settings'
    | '/$businessSlug/reports/templates/$templateId'
    | '/$businessSlug/settings/licence/$licenceId'
    | '/$businessSlug/settings/licence/new'
    | '/$businessSlug/settings/reports/answers'
    | '/$businessSlug/settings/team/$memberId'
    | '/$businessSlug/reports/templates'
    | '/$businessSlug/settings/licence'
    | '/$businessSlug/settings/reports'
    | '/$businessSlug/settings/team'
  id:
    | '__root__'
    | '/'
    | '/$businessSlug'
    | '/login'
    | '/onboarding'
    | '/two-step'
    | '/welcome'
    | '/$businessSlug/job'
    | '/$businessSlug/analytics'
    | '/$businessSlug/leads'
    | '/$businessSlug/notes'
    | '/$businessSlug/products'
    | '/$businessSlug/schedule'
    | '/join/$token'
    | '/start/$token'
    | '/$businessSlug/job/recurring'
    | '/$businessSlug/reports/$reportId'
    | '/$businessSlug/reports/new'
    | '/$businessSlug/settings/about'
    | '/$businessSlug/settings/appearance'
    | '/$businessSlug/settings/business'
    | '/$businessSlug/settings/details'
    | '/$businessSlug/settings/sign-in'
    | '/api/auth/$'
    | '/$businessSlug/clients/'
    | '/$businessSlug/job/'
    | '/$businessSlug/reports/'
    | '/$businessSlug/settings/'
    | '/$businessSlug/reports/templates/$templateId'
    | '/$businessSlug/settings/licence/$licenceId'
    | '/$businessSlug/settings/licence/new'
    | '/$businessSlug/settings/reports/answers'
    | '/$businessSlug/settings/team/$memberId'
    | '/$businessSlug/reports/templates/'
    | '/$businessSlug/settings/licence/'
    | '/$businessSlug/settings/reports/'
    | '/$businessSlug/settings/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessSlugRouteRoute: typeof BusinessSlugRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  TwoStepRoute: typeof TwoStepRoute
  WelcomeRoute: typeof WelcomeRoute
  JoinTokenRoute: typeof JoinTokenRoute
  StartTokenRoute: typeof StartTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug': {
      id: '/$businessSlug'
      path: '/$businessSlug'
      fullPath: '/$businessSlug'
      preLoaderRoute: typeof BusinessSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-step': {
      id: '/two-step'
      path: '/two-step'
      fullPath: '/two-step'
      preLoaderRoute: typeof TwoStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/analytics': {
      id: '/$businessSlug/analytics'
      path: '/analytics'
      fullPath: '/$businessSlug/analytics'
      preLoaderRoute: typeof BusinessSlugAnalyticsRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/job': {
      id: '/$businessSlug/job'
      path: '/job'
      fullPath: '/$businessSlug/job'
      preLoaderRoute: typeof BusinessSlugJobRouteRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/leads': {
      id: '/$businessSlug/leads'
      path: '/leads'
      fullPath: '/$businessSlug/leads'
      preLoaderRoute: typeof BusinessSlugLeadsRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/notes': {
      id: '/$businessSlug/notes'
      path: '/notes'
      fullPath: '/$businessSlug/notes'
      preLoaderRoute: typeof BusinessSlugNotesRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/products': {
      id: '/$businessSlug/products'
      path: '/products'
      fullPath: '/$businessSlug/products'
      preLoaderRoute: typeof BusinessSlugProductsRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/schedule': {
      id: '/$businessSlug/schedule'
      path: '/schedule'
      fullPath: '/$businessSlug/schedule'
      preLoaderRoute: typeof BusinessSlugScheduleRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/$token': {
      id: '/start/$token'
      path: '/start/$token'
      fullPath: '/start/$token'
      preLoaderRoute: typeof StartTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/clients/': {
      id: '/$businessSlug/clients/'
      path: '/clients'
      fullPath: '/$businessSlug/clients/'
      preLoaderRoute: typeof BusinessSlugClientsIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/job/': {
      id: '/$businessSlug/job/'
      path: '/'
      fullPath: '/$businessSlug/job/'
      preLoaderRoute: typeof BusinessSlugJobIndexRouteImport
      parentRoute: typeof BusinessSlugJobRouteRoute
    }
    '/$businessSlug/job/recurring': {
      id: '/$businessSlug/job/recurring'
      path: '/recurring'
      fullPath: '/$businessSlug/job/recurring'
      preLoaderRoute: typeof BusinessSlugJobRecurringRouteImport
      parentRoute: typeof BusinessSlugJobRouteRoute
    }
    '/$businessSlug/reports/': {
      id: '/$businessSlug/reports/'
      path: '/reports'
      fullPath: '/$businessSlug/reports/'
      preLoaderRoute: typeof BusinessSlugReportsIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/$reportId': {
      id: '/$businessSlug/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/$businessSlug/reports/$reportId'
      preLoaderRoute: typeof BusinessSlugReportsReportIdRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/new': {
      id: '/$businessSlug/reports/new'
      path: '/reports/new'
      fullPath: '/$businessSlug/reports/new'
      preLoaderRoute: typeof BusinessSlugReportsNewRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/': {
      id: '/$businessSlug/settings/'
      path: '/settings'
      fullPath: '/$businessSlug/settings/'
      preLoaderRoute: typeof BusinessSlugSettingsIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/about': {
      id: '/$businessSlug/settings/about'
      path: '/settings/about'
      fullPath: '/$businessSlug/settings/about'
      preLoaderRoute: typeof BusinessSlugSettingsAboutRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/appearance': {
      id: '/$businessSlug/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/$businessSlug/settings/appearance'
      preLoaderRoute: typeof BusinessSlugSettingsAppearanceRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/business': {
      id: '/$businessSlug/settings/business'
      path: '/settings/business'
      fullPath: '/$businessSlug/settings/business'
      preLoaderRoute: typeof BusinessSlugSettingsBusinessRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/details': {
      id: '/$businessSlug/settings/details'
      path: '/settings/details'
      fullPath: '/$businessSlug/settings/details'
      preLoaderRoute: typeof BusinessSlugSettingsDetailsRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/sign-in': {
      id: '/$businessSlug/settings/sign-in'
      path: '/settings/sign-in'
      fullPath: '/$businessSlug/settings/sign-in'
      preLoaderRoute: typeof BusinessSlugSettingsSignInRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/reports/templates/': {
      id: '/$businessSlug/reports/templates/'
      path: '/reports/templates'
      fullPath: '/$businessSlug/reports/templates/'
      preLoaderRoute: typeof BusinessSlugReportsTemplatesIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/reports/templates/$templateId': {
      id: '/$businessSlug/reports/templates/$templateId'
      path: '/reports/templates/$templateId'
      fullPath: '/$businessSlug/reports/templates/$templateId'
      preLoaderRoute: typeof BusinessSlugReportsTemplatesTemplateIdRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/licence/': {
      id: '/$businessSlug/settings/licence/'
      path: '/settings/licence'
      fullPath: '/$businessSlug/settings/licence/'
      preLoaderRoute: typeof BusinessSlugSettingsLicenceIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/licence/$licenceId': {
      id: '/$businessSlug/settings/licence/$licenceId'
      path: '/settings/licence/$licenceId'
      fullPath: '/$businessSlug/settings/licence/$licenceId'
      preLoaderRoute: typeof BusinessSlugSettingsLicenceLicenceIdRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/licence/new': {
      id: '/$businessSlug/settings/licence/new'
      path: '/settings/licence/new'
      fullPath: '/$businessSlug/settings/licence/new'
      preLoaderRoute: typeof BusinessSlugSettingsLicenceNewRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/reports/': {
      id: '/$businessSlug/settings/reports/'
      path: '/settings/reports'
      fullPath: '/$businessSlug/settings/reports/'
      preLoaderRoute: typeof BusinessSlugSettingsReportsIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/reports/answers': {
      id: '/$businessSlug/settings/reports/answers'
      path: '/settings/reports/answers'
      fullPath: '/$businessSlug/settings/reports/answers'
      preLoaderRoute: typeof BusinessSlugSettingsReportsAnswersRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/team/': {
      id: '/$businessSlug/settings/team/'
      path: '/settings/team'
      fullPath: '/$businessSlug/settings/team/'
      preLoaderRoute: typeof BusinessSlugSettingsTeamIndexRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
    '/$businessSlug/settings/team/$memberId': {
      id: '/$businessSlug/settings/team/$memberId'
      path: '/settings/team/$memberId'
      fullPath: '/$businessSlug/settings/team/$memberId'
      preLoaderRoute: typeof BusinessSlugSettingsTeamMemberIdRouteImport
      parentRoute: typeof BusinessSlugRouteRoute
    }
  }
}

interface BusinessSlugJobRouteRouteChildren {
  BusinessSlugJobRecurringRoute: typeof BusinessSlugJobRecurringRoute
  BusinessSlugJobIndexRoute: typeof BusinessSlugJobIndexRoute
}

const BusinessSlugJobRouteRouteChildren: BusinessSlugJobRouteRouteChildren = {
  BusinessSlugJobRecurringRoute: BusinessSlugJobRecurringRoute,
  BusinessSlugJobIndexRoute: BusinessSlugJobIndexRoute,
}

const BusinessSlugJobRouteRouteWithChildren =
  BusinessSlugJobRouteRoute._addFileChildren(BusinessSlugJobRouteRouteChildren)

interface BusinessSlugRouteRouteChildren {
  BusinessSlugJobRouteRoute: typeof BusinessSlugJobRouteRouteWithChildren
  BusinessSlugAnalyticsRoute: typeof BusinessSlugAnalyticsRoute
  BusinessSlugLeadsRoute: typeof BusinessSlugLeadsRoute
  BusinessSlugNotesRoute: typeof BusinessSlugNotesRoute
  BusinessSlugProductsRoute: typeof BusinessSlugProductsRoute
  BusinessSlugScheduleRoute: typeof BusinessSlugScheduleRoute
  BusinessSlugReportsReportIdRoute: typeof BusinessSlugReportsReportIdRoute
  BusinessSlugReportsNewRoute: typeof BusinessSlugReportsNewRoute
  BusinessSlugSettingsAboutRoute: typeof BusinessSlugSettingsAboutRoute
  BusinessSlugSettingsAppearanceRoute: typeof BusinessSlugSettingsAppearanceRoute
  BusinessSlugSettingsBusinessRoute: typeof BusinessSlugSettingsBusinessRoute
  BusinessSlugSettingsDetailsRoute: typeof BusinessSlugSettingsDetailsRoute
  BusinessSlugSettingsSignInRoute: typeof BusinessSlugSettingsSignInRoute
  BusinessSlugClientsIndexRoute: typeof BusinessSlugClientsIndexRoute
  BusinessSlugReportsIndexRoute: typeof BusinessSlugReportsIndexRoute
  BusinessSlugSettingsIndexRoute: typeof BusinessSlugSettingsIndexRoute
  BusinessSlugReportsTemplatesTemplateIdRoute: typeof BusinessSlugReportsTemplatesTemplateIdRoute
  BusinessSlugSettingsLicenceLicenceIdRoute: typeof BusinessSlugSettingsLicenceLicenceIdRoute
  BusinessSlugSettingsLicenceNewRoute: typeof BusinessSlugSettingsLicenceNewRoute
  BusinessSlugSettingsReportsAnswersRoute: typeof BusinessSlugSettingsReportsAnswersRoute
  BusinessSlugSettingsTeamMemberIdRoute: typeof BusinessSlugSettingsTeamMemberIdRoute
  BusinessSlugReportsTemplatesIndexRoute: typeof BusinessSlugReportsTemplatesIndexRoute
  BusinessSlugSettingsLicenceIndexRoute: typeof BusinessSlugSettingsLicenceIndexRoute
  BusinessSlugSettingsReportsIndexRoute: typeof BusinessSlugSettingsReportsIndexRoute
  BusinessSlugSettingsTeamIndexRoute: typeof BusinessSlugSettingsTeamIndexRoute
}

const BusinessSlugRouteRouteChildren: BusinessSlugRouteRouteChildren = {
  BusinessSlugJobRouteRoute: BusinessSlugJobRouteRouteWithChildren,
  BusinessSlugAnalyticsRoute: BusinessSlugAnalyticsRoute,
  BusinessSlugLeadsRoute: BusinessSlugLeadsRoute,
  BusinessSlugNotesRoute: BusinessSlugNotesRoute,
  BusinessSlugProductsRoute: BusinessSlugProductsRoute,
  BusinessSlugScheduleRoute: BusinessSlugScheduleRoute,
  BusinessSlugReportsReportIdRoute: BusinessSlugReportsReportIdRoute,
  BusinessSlugReportsNewRoute: BusinessSlugReportsNewRoute,
  BusinessSlugSettingsAboutRoute: BusinessSlugSettingsAboutRoute,
  BusinessSlugSettingsAppearanceRoute: BusinessSlugSettingsAppearanceRoute,
  BusinessSlugSettingsBusinessRoute: BusinessSlugSettingsBusinessRoute,
  BusinessSlugSettingsDetailsRoute: BusinessSlugSettingsDetailsRoute,
  BusinessSlugSettingsSignInRoute: BusinessSlugSettingsSignInRoute,
  BusinessSlugClientsIndexRoute: BusinessSlugClientsIndexRoute,
  BusinessSlugReportsIndexRoute: BusinessSlugReportsIndexRoute,
  BusinessSlugSettingsIndexRoute: BusinessSlugSettingsIndexRoute,
  BusinessSlugReportsTemplatesTemplateIdRoute:
    BusinessSlugReportsTemplatesTemplateIdRoute,
  BusinessSlugSettingsLicenceLicenceIdRoute:
    BusinessSlugSettingsLicenceLicenceIdRoute,
  BusinessSlugSettingsLicenceNewRoute: BusinessSlugSettingsLicenceNewRoute,
  BusinessSlugSettingsReportsAnswersRoute:
    BusinessSlugSettingsReportsAnswersRoute,
  BusinessSlugSettingsTeamMemberIdRoute: BusinessSlugSettingsTeamMemberIdRoute,
  BusinessSlugReportsTemplatesIndexRoute:
    BusinessSlugReportsTemplatesIndexRoute,
  BusinessSlugSettingsLicenceIndexRoute: BusinessSlugSettingsLicenceIndexRoute,
  BusinessSlugSettingsReportsIndexRoute: BusinessSlugSettingsReportsIndexRoute,
  BusinessSlugSettingsTeamIndexRoute: BusinessSlugSettingsTeamIndexRoute,
}

const BusinessSlugRouteRouteWithChildren =
  BusinessSlugRouteRoute._addFileChildren(BusinessSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessSlugRouteRoute: BusinessSlugRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  TwoStepRoute: TwoStepRoute,
  WelcomeRoute: WelcomeRoute,
  JoinTokenRoute: JoinTokenRoute,
  StartTokenRoute: StartTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
